<?php

return [
    'default_plan' => 'free',

    'plans' => [
        'free' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => [],
                'whatsapp.settings' => [],
                'whatsapp.chats'    => [],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
                'games.math'        => [],
                'games.vocabulary'  => [],
            ],
            'limits' => [
                'team.members.max'             => 1,
                'team.roles.custom.max'        => 0,
                'team.invitations.pending.max' => 0,
                'finance.monthly_tx.max'       => 100,
                'finance.accounts.max'         => 2,
                'finance.budgets.active.max'   => 2,
                'finance.custom_cat.max'       => 10,
                'master.categories.max'        => 10,
                'master.currencies.max'        => 2,
                'master.uom.max'               => 8,
                'finance.pockets.max'          => 0,
                'finance.goals.max'            => 3,
                'finance.wishes.max'           => 5,
                'master.tags.max'              => 10,
            ],
        ],
        'pro' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => ['view', 'create', 'update'],
                'whatsapp.settings' => ['view', 'update'],
                'whatsapp.chats'    => ['view', 'update'],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
                'games.math'        => ['view', 'create', 'update'],
                'games.vocabulary'  => ['view', 'create', 'update'],
            ],
            'limits' => [
                'team.members.max'             => 3,
                'team.roles.custom.max'        => 3,
                'team.invitations.pending.max' => 5,
                'finance.monthly_tx.max'       => 500,
                'finance.accounts.max'         => 5,
                'finance.budgets.active.max'   => 5,
                'finance.custom_cat.max'       => 25,
                'master.categories.max'        => 25,
                'master.currencies.max'        => 4,
                'master.uom.max'               => 15,
                'finance.pockets.max'          => 5,
                'finance.goals.max'            => 10,
                'finance.wishes.max'           => 15,
                'master.tags.max'              => 20,
            ],
        ],
        'business' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => ['view', 'create', 'update'],
                'whatsapp.settings' => ['view', 'update'],
                'whatsapp.chats'    => ['view', 'update'],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
                'games.math'        => ['view', 'create', 'update'],
                'games.vocabulary'  => ['view', 'create', 'update'],
            ],
            'limits' => [
                'team.members.max'             => 10,
                'team.roles.custom.max'        => 10,
                'team.invitations.pending.max' => 15,
                'finance.monthly_tx.max'       => 2000,
                'finance.accounts.max'         => 12,
                'finance.budgets.active.max'   => 12,
                'finance.custom_cat.max'       => 60,
                'master.categories.max'        => 60,
                'master.currencies.max'        => 8,
                'master.uom.max'               => 30,
                'finance.pockets.max'          => 20,
                'finance.goals.max'            => 30,
                'finance.wishes.max'           => 50,
                'master.tags.max'              => 50,
            ],
        ],
        'enterprise' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => ['view', 'create', 'update'],
                'whatsapp.settings' => ['view', 'update'],
                'whatsapp.chats'    => ['view', 'update'],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
                'games.math'        => ['view', 'create', 'update'],
                'games.vocabulary'  => ['view', 'create', 'update'],
            ],
            'limits' => [
                'team.members.max'             => -1,
                'team.roles.custom.max'        => -1,
                'team.invitations.pending.max' => -1,
                'finance.monthly_tx.max'       => -1,
                'finance.accounts.max'         => -1,
                'finance.budgets.active.max'   => -1,
                'finance.custom_cat.max'       => -1,
                'master.categories.max'        => -1,
                'master.currencies.max'        => -1,
                'master.uom.max'               => -1,
                'finance.pockets.max'          => -1,
                'finance.goals.max'            => -1,
                'finance.wishes.max'           => -1,
                'master.tags.max'              => -1,
            ],
        ],
    ],

    'module_labels' => [
        'dashboard'         => 'Dashboard',
        'team.members'      => 'Team / Anggota',
        'team.roles'        => 'Team / Peran',
        'team.invitations'  => 'Team / Undangan',
        'whatsapp.settings' => 'WhatsApp / Pengaturan',
        'whatsapp.chats'    => 'WhatsApp / Percakapan',
        'finance'           => 'Keuangan Keluarga',
        'master.categories' => 'Master Data / Kategori',
        'master.tags'       => 'Master Data / Tag',
        'master.currencies' => 'Master Data / Mata Uang',
        'master.uom'        => 'Master Data / Satuan',
        'games.math'        => 'Games / Matematika',
        'games.vocabulary'  => 'Games / Kosakata',
    ],

    'limit_labels' => [
        'team.members.max'             => 'Maks. Anggota',
        'team.roles.custom.max'        => 'Maks. Peran Kustom',
        'team.invitations.pending.max' => 'Maks. Undangan Tertunda',
        'finance.monthly_tx.max'       => 'Maks. Transaksi per Bulan',
        'finance.accounts.max'         => 'Maks. Akun',
        'finance.budgets.active.max'   => 'Maks. Budget Aktif',
        'finance.custom_cat.max'       => 'Maks. Kategori Kustom',
        'master.categories.max'        => 'Maks. Kategori Master',
        'master.currencies.max'        => 'Maks. Mata Uang',
        'master.uom.max'               => 'Maks. Satuan',
        'finance.pockets.max'          => 'Maks. Pocket / Wallet Tambahan',
        'finance.goals.max'            => 'Maks. Savings Goal',
        'finance.wishes.max'           => 'Maks. Wishes',
        'master.tags.max'              => 'Maks. Tag',
    ],
];
