<?php

return [
    'default_plan' => 'free',

    'plans' => [
        'free' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => [],
                'whatsapp.settings' => [],
                'whatsapp.chats'    => [],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
            ],
            'limits' => [
                'team.members.max'             => 5,
                'team.roles.custom.max'        => 2,
                'team.invitations.pending.max' => 3,
                'finance.monthly_tx.max'       => 200,
                'finance.custom_cat.max'       => 5,
                'master.tags.max'              => 20,
            ],
        ],
        'pro' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => ['view', 'create', 'update'],
                'whatsapp.settings' => ['view', 'update'],
                'whatsapp.chats'    => ['view', 'update'],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
            ],
            'limits' => [
                'team.members.max'             => 50,
                'team.roles.custom.max'        => 25,
                'team.invitations.pending.max' => 100,
                'finance.monthly_tx.max'       => -1,
                'finance.custom_cat.max'       => -1,
                'master.tags.max'              => -1,
            ],
        ],
        'business' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => ['view', 'create', 'update'],
                'whatsapp.settings' => ['view', 'update'],
                'whatsapp.chats'    => ['view', 'update'],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
            ],
            'limits' => [
                'team.members.max'             => 50,
                'team.roles.custom.max'        => 25,
                'team.invitations.pending.max' => 100,
                'finance.monthly_tx.max'       => -1,
                'finance.custom_cat.max'       => -1,
                'master.tags.max'              => -1,
            ],
        ],
        'enterprise' => [
            'features' => [
                'dashboard'         => ['view'],
                'team.members'      => ['view', 'create', 'update', 'delete'],
                'team.roles'        => ['view', 'create', 'update', 'delete', 'assign'],
                'team.invitations'  => ['view', 'create', 'update'],
                'whatsapp.settings' => ['view', 'update'],
                'whatsapp.chats'    => ['view', 'update'],
                'finance'           => ['view', 'create', 'update', 'delete'],
                'master.categories' => ['view', 'create', 'update', 'delete'],
                'master.tags'       => ['view', 'create', 'update', 'delete'],
                'master.currencies' => ['view', 'create', 'update', 'delete'],
                'master.uom'        => ['view', 'create', 'update', 'delete'],
            ],
            'limits' => [
                'team.members.max'             => -1,
                'team.roles.custom.max'        => -1,
                'team.invitations.pending.max' => -1,
                'finance.monthly_tx.max'       => -1,
                'finance.custom_cat.max'       => -1,
                'master.tags.max'              => -1,
            ],
        ],
    ],

    'module_labels' => [
        'dashboard'         => 'Dashboard',
        'team.members'      => 'Team / Anggota',
        'team.roles'        => 'Team / Peran',
        'team.invitations'  => 'Team / Undangan',
        'whatsapp.settings' => 'WhatsApp / Pengaturan',
        'whatsapp.chats'    => 'WhatsApp / Percakapan',
        'finance'           => 'Keuangan / Transaksi',
        'master.categories' => 'Master Data / Kategori',
        'master.tags'       => 'Master Data / Tag',
        'master.currencies' => 'Master Data / Mata Uang',
        'master.uom'        => 'Master Data / Satuan',
    ],

    'limit_labels' => [
        'team.members.max'             => 'Maks. Anggota',
        'team.roles.custom.max'        => 'Maks. Peran Kustom',
        'team.invitations.pending.max' => 'Maks. Undangan Tertunda',
        'finance.monthly_tx.max'       => 'Maks. Transaksi per Bulan',
        'finance.custom_cat.max'       => 'Maks. Kategori Kustom',
        'master.tags.max'              => 'Maks. Tag',
    ],
];
