<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Alam
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Bintang',
          'bahasa_inggris' => 'Star',
          'fonetik' => 'star',
          'bahasa_arab' => 'نَجْمَةٌ',
          'fonetik_arab' => 'Najmatun',
          'bahasa_mandarin' => '星星',
          'fonetik_mandarin' => 'Xīngxīng',
          'kategori' => 'Alam',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Matahari',
          'bahasa_inggris' => 'Sun',
          'fonetik' => 'san',
          'bahasa_arab' => 'شَمْسٌ',
          'fonetik_arab' => 'Syamsun',
          'bahasa_mandarin' => '太阳',
          'fonetik_mandarin' => 'Tàiyáng',
          'kategori' => 'Alam',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Bulan',
          'bahasa_inggris' => 'Moon',
          'fonetik' => 'mun',
          'bahasa_arab' => 'قَمَرٌ',
          'fonetik_arab' => 'Qamarun',
          'bahasa_mandarin' => '月亮',
          'fonetik_mandarin' => 'Yuèliàng',
          'kategori' => 'Alam',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Hujan',
          'bahasa_inggris' => 'Rain',
          'fonetik' => 'rein',
          'bahasa_arab' => 'مَطَرٌ',
          'fonetik_arab' => 'Matharun',
          'bahasa_mandarin' => '雨',
          'fonetik_mandarin' => 'Yǔ',
          'kategori' => 'Alam',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Salju',
          'bahasa_inggris' => 'Snow',
          'fonetik' => 'snou',
          'bahasa_arab' => 'ثَلْجٌ',
          'fonetik_arab' => 'Tsaljun',
          'bahasa_mandarin' => '雪',
          'fonetik_mandarin' => 'Xuě',
          'kategori' => 'Alam',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Angin',
          'bahasa_inggris' => 'Wind',
          'fonetik' => 'wind',
          'bahasa_arab' => 'رِيْحٌ',
          'fonetik_arab' => 'Riihun',
          'bahasa_mandarin' => '风',
          'fonetik_mandarin' => 'Fēng',
          'kategori' => 'Alam',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Awan',
          'bahasa_inggris' => 'Cloud',
          'fonetik' => 'klaud',
          'bahasa_arab' => 'سَحَابٌ',
          'fonetik_arab' => 'Sahaabun',
          'bahasa_mandarin' => '云',
          'fonetik_mandarin' => 'Yún',
          'kategori' => 'Alam',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Pelangi',
          'bahasa_inggris' => 'Rainbow',
          'fonetik' => 'rein-bou',
          'bahasa_arab' => 'قَوْسُ قُزَحٍ',
          'fonetik_arab' => 'Qawsu Quzaḥin',
          'bahasa_mandarin' => '彩虹',
          'fonetik_mandarin' => 'Cǎihóng',
          'kategori' => 'Alam',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Petir',
          'bahasa_inggris' => 'Lightning',
          'fonetik' => 'lait-ning',
          'bahasa_arab' => 'بَرْقٌ',
          'fonetik_arab' => 'Barqun',
          'bahasa_mandarin' => '闪电',
          'fonetik_mandarin' => 'Shǎndiàn',
          'kategori' => 'Alam',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Badai',
          'bahasa_inggris' => 'Storm',
          'fonetik' => 'storm',
          'bahasa_arab' => 'عَاصِفَةٌ',
          'fonetik_arab' => 'ʿĀṣifatun',
          'bahasa_mandarin' => '风暴',
          'fonetik_mandarin' => 'Fēngbào',
          'kategori' => 'Alam',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Langit',
          'bahasa_inggris' => 'Sky',
          'fonetik' => 'skai',
          'bahasa_arab' => 'سَمَاءٌ',
          'fonetik_arab' => 'Samāʾun',
          'bahasa_mandarin' => '天空',
          'fonetik_mandarin' => 'Tiānkōng',
          'kategori' => 'Alam',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Bumi',
          'bahasa_inggris' => 'Earth',
          'fonetik' => 'erth',
          'bahasa_arab' => 'أَرْضٌ',
          'fonetik_arab' => 'Arḍun',
          'bahasa_mandarin' => '地球',
          'fonetik_mandarin' => 'Dìqiú',
          'kategori' => 'Alam',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Gunung',
          'bahasa_inggris' => 'Mountain',
          'fonetik' => 'maun-ten',
          'bahasa_arab' => 'جَبَلٌ',
          'fonetik_arab' => 'Jabalun',
          'bahasa_mandarin' => '山',
          'fonetik_mandarin' => 'Shān',
          'kategori' => 'Alam',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Laut',
          'bahasa_inggris' => 'Sea',
          'fonetik' => 'si',
          'bahasa_arab' => 'بَحْرٌ',
          'fonetik_arab' => 'Baḥrun',
          'bahasa_mandarin' => '海',
          'fonetik_mandarin' => 'Hǎi',
          'kategori' => 'Alam',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Pantai',
          'bahasa_inggris' => 'Beach',
          'fonetik' => 'bic',
          'bahasa_arab' => 'شَاطِئٌ',
          'fonetik_arab' => 'Shāṭiʾun',
          'bahasa_mandarin' => '海滩',
          'fonetik_mandarin' => 'Hǎitān',
          'kategori' => 'Alam',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Hutan',
          'bahasa_inggris' => 'Forest',
          'fonetik' => 'fo-rest',
          'bahasa_arab' => 'غَابَةٌ',
          'fonetik_arab' => 'Ghābatun',
          'bahasa_mandarin' => '森林',
          'fonetik_mandarin' => 'Sēnlín',
          'kategori' => 'Alam',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Sungai',
          'bahasa_inggris' => 'River',
          'fonetik' => 'ri-ver',
          'bahasa_arab' => 'نَهْرٌ',
          'fonetik_arab' => 'Nahrun',
          'bahasa_mandarin' => '河流',
          'fonetik_mandarin' => 'Héliú',
          'kategori' => 'Alam',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Danau',
          'bahasa_inggris' => 'Lake',
          'fonetik' => 'leyk',
          'bahasa_arab' => 'بُحَيْرَةٌ',
          'fonetik_arab' => 'Buḥayratun',
          'bahasa_mandarin' => '湖泊',
          'fonetik_mandarin' => 'Húpō',
          'kategori' => 'Alam',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Pohon',
          'bahasa_inggris' => 'Tree',
          'fonetik' => 'tri',
          'bahasa_arab' => 'شَجَرَةٌ',
          'fonetik_arab' => 'Shajaratun',
          'bahasa_mandarin' => '树',
          'fonetik_mandarin' => 'Shù',
          'kategori' => 'Alam',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Bunga',
          'bahasa_inggris' => 'Flower',
          'fonetik' => 'flau-wer',
          'bahasa_arab' => 'زَهْرَةٌ',
          'fonetik_arab' => 'Zahratun',
          'bahasa_mandarin' => '花',
          'fonetik_mandarin' => 'Huā',
          'kategori' => 'Alam',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Rumput',
          'bahasa_inggris' => 'Grass',
          'fonetik' => 'gres',
          'bahasa_arab' => 'عُشْبٌ',
          'fonetik_arab' => 'ʿUshbun',
          'bahasa_mandarin' => '草',
          'fonetik_mandarin' => 'Cǎo',
          'kategori' => 'Alam',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Batu',
          'bahasa_inggris' => 'Stone',
          'fonetik' => 'stoun',
          'bahasa_arab' => 'حَجَرٌ',
          'fonetik_arab' => 'Ḥajarun',
          'bahasa_mandarin' => '石头',
          'fonetik_mandarin' => 'Shítou',
          'kategori' => 'Alam',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Pasir',
          'bahasa_inggris' => 'Sand',
          'fonetik' => 'send',
          'bahasa_arab' => 'رَمْلٌ',
          'fonetik_arab' => 'Ramlun',
          'bahasa_mandarin' => '沙子',
          'fonetik_mandarin' => 'Shāzi',
          'kategori' => 'Alam',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Tanah',
          'bahasa_inggris' => 'Soil',
          'fonetik' => 'soil',
          'bahasa_arab' => 'تُرَابٌ',
          'fonetik_arab' => 'Turābun',
          'bahasa_mandarin' => '土壤',
          'fonetik_mandarin' => 'Tǔrǎng',
          'kategori' => 'Alam',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Api',
          'bahasa_inggris' => 'Fire',
          'fonetik' => 'fa-yer',
          'bahasa_arab' => 'نَارٌ',
          'fonetik_arab' => 'Nārun',
          'bahasa_mandarin' => '火',
          'fonetik_mandarin' => 'Huǒ',
          'kategori' => 'Alam',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Air',
          'bahasa_inggris' => 'Water',
          'fonetik' => 'wo-ter',
          'bahasa_arab' => 'مَاءٌ',
          'fonetik_arab' => 'Māʾun',
          'bahasa_mandarin' => '水',
          'fonetik_mandarin' => 'Shuǐ',
          'kategori' => 'Alam',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Udara',
          'bahasa_inggris' => 'Air',
          'fonetik' => 'er',
          'bahasa_arab' => 'هَوَاءٌ',
          'fonetik_arab' => 'Hawāʾun',
          'bahasa_mandarin' => '空气',
          'fonetik_mandarin' => 'Kōngqì',
          'kategori' => 'Alam',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Cahaya',
          'bahasa_inggris' => 'Light',
          'fonetik' => 'lait',
          'bahasa_arab' => 'ضَوْءٌ',
          'fonetik_arab' => 'Ḍawʾun',
          'bahasa_mandarin' => '光',
          'fonetik_mandarin' => 'Guāng',
          'kategori' => 'Alam',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Kabut',
          'bahasa_inggris' => 'Fog',
          'fonetik' => 'fog',
          'bahasa_arab' => 'ضَبَابٌ',
          'fonetik_arab' => 'Ḍabābun',
          'bahasa_mandarin' => '雾',
          'fonetik_mandarin' => 'Wù',
          'kategori' => 'Alam',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Embun',
          'bahasa_inggris' => 'Dew',
          'fonetik' => 'dyu',
          'bahasa_arab' => 'نَدًى',
          'fonetik_arab' => 'Nadan',
          'bahasa_mandarin' => '露水',
          'fonetik_mandarin' => 'Lùshuǐ',
          'kategori' => 'Alam',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Lembah',
          'bahasa_inggris' => 'Valley',
          'fonetik' => 'va-li',
          'bahasa_arab' => 'وَادٍ',
          'fonetik_arab' => 'Wādin',
          'bahasa_mandarin' => '山谷',
          'fonetik_mandarin' => 'Shāngǔ',
          'kategori' => 'Alam',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Gurun',
          'bahasa_inggris' => 'Desert',
          'fonetik' => 'de-zert',
          'bahasa_arab' => 'صَحْرَاءُ',
          'fonetik_arab' => 'Ṣaḥrāʾu',
          'bahasa_mandarin' => '沙漠',
          'fonetik_mandarin' => 'Shāmò',
          'kategori' => 'Alam',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Gua',
          'bahasa_inggris' => 'Cave',
          'fonetik' => 'keiv',
          'bahasa_arab' => 'كَهْفٌ',
          'fonetik_arab' => 'Kahfun',
          'bahasa_mandarin' => '洞穴',
          'fonetik_mandarin' => 'Dòngxué',
          'kategori' => 'Alam',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Pulau',
          'bahasa_inggris' => 'Island',
          'fonetik' => 'ai-lend',
          'bahasa_arab' => 'جَزِيْرَةٌ',
          'fonetik_arab' => 'Jazīratun',
          'bahasa_mandarin' => '岛屿',
          'fonetik_mandarin' => 'Dǎoyǔ',
          'kategori' => 'Alam',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Samudra',
          'bahasa_inggris' => 'Ocean',
          'fonetik' => 'o-syen',
          'bahasa_arab' => 'مُحِيْطٌ',
          'fonetik_arab' => 'Muḥīṭun',
          'bahasa_mandarin' => '海洋',
          'fonetik_mandarin' => 'Hǎiyáng',
          'kategori' => 'Alam',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Bukit',
          'bahasa_inggris' => 'Hill',
          'fonetik' => 'hil',
          'bahasa_arab' => 'تَلٌّ',
          'fonetik_arab' => 'Tallun',
          'bahasa_mandarin' => '小山',
          'fonetik_mandarin' => 'Xiǎoshān',
          'kategori' => 'Alam',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Merkurius',
          'bahasa_inggris' => 'Mercury',
          'fonetik' => 'mer-kyu-ri',
          'bahasa_arab' => 'عُطَارِدُ',
          'fonetik_arab' => 'ʿUṭāridu',
          'bahasa_mandarin' => '水星',
          'fonetik_mandarin' => 'Shuǐxīng',
          'kategori' => 'Alam',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Venus',
          'bahasa_inggris' => 'Venus',
          'fonetik' => 'vi-nes',
          'bahasa_arab' => 'الزُّهَرَةُ',
          'fonetik_arab' => 'Az-Zuharatu',
          'bahasa_mandarin' => '金星',
          'fonetik_mandarin' => 'Jīnxīng',
          'kategori' => 'Alam',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Mars',
          'bahasa_inggris' => 'Mars',
          'fonetik' => 'mars',
          'bahasa_arab' => 'الْمَرِّيْخُ',
          'fonetik_arab' => 'Al-Marrīkhu',
          'bahasa_mandarin' => '火星',
          'fonetik_mandarin' => 'Huǒxīng',
          'kategori' => 'Alam',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Yupiter',
          'bahasa_inggris' => 'Jupiter',
          'fonetik' => 'yu-pi-ter',
          'bahasa_arab' => 'الْمُشْتَرِي',
          'fonetik_arab' => 'Al-Musytarī',
          'bahasa_mandarin' => '木星',
          'fonetik_mandarin' => 'Mùxīng',
          'kategori' => 'Alam',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Saturnus',
          'bahasa_inggris' => 'Saturn',
          'fonetik' => 'sa-tern',
          'bahasa_arab' => 'زُحَلُ',
          'fonetik_arab' => 'Zuḥalu',
          'bahasa_mandarin' => '土星',
          'fonetik_mandarin' => 'Tǔxīng',
          'kategori' => 'Alam',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Neptunus',
          'bahasa_inggris' => 'Neptune',
          'fonetik' => 'nep-tyun',
          'bahasa_arab' => 'نِبْتُون',
          'fonetik_arab' => 'Nibtūn',
          'bahasa_mandarin' => '海王星',
          'fonetik_mandarin' => 'Hǎiwángxīng',
          'kategori' => 'Alam',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Galaksi',
          'bahasa_inggris' => 'Galaxy',
          'fonetik' => 'ga-lak-si',
          'bahasa_arab' => 'مَجَرَّةٌ',
          'fonetik_arab' => 'Majarratun',
          'bahasa_mandarin' => '星系',
          'fonetik_mandarin' => 'Xīngxì',
          'kategori' => 'Alam',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Komet',
          'bahasa_inggris' => 'Comet',
          'fonetik' => 'ko-met',
          'bahasa_arab' => 'مُذَنَّبٌ',
          'fonetik_arab' => 'Mudhannabun',
          'bahasa_mandarin' => '彗星',
          'fonetik_mandarin' => 'Huìxīng',
          'kategori' => 'Alam',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Asteroid',
          'bahasa_inggris' => 'Asteroid',
          'fonetik' => 'as-te-roid',
          'bahasa_arab' => 'كُوَيْكِبٌ',
          'fonetik_arab' => 'Kuwaykibun',
          'bahasa_mandarin' => '小行星',
          'fonetik_mandarin' => 'Xiǎohángxīng',
          'kategori' => 'Alam',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Meteor',
          'bahasa_inggris' => 'Meteor',
          'fonetik' => 'mi-ti-or',
          'bahasa_arab' => 'نَيْزَكٌ',
          'fonetik_arab' => 'Nayzakun',
          'bahasa_mandarin' => '流星',
          'fonetik_mandarin' => 'Liúxīng',
          'kategori' => 'Alam',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Lubang Hitam',
          'bahasa_inggris' => 'Black Hole',
          'fonetik' => 'blek houl',
          'bahasa_arab' => 'ثُقْبٌ أَسْوَدُ',
          'fonetik_arab' => 'Thuqbun Aswadu',
          'bahasa_mandarin' => '黑洞',
          'fonetik_mandarin' => 'Hēidòng',
          'kategori' => 'Alam',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Alam Semesta',
          'bahasa_inggris' => 'Universe',
          'fonetik' => 'yu-ni-vers',
          'bahasa_arab' => 'الْكَوْنُ',
          'fonetik_arab' => 'Al-Kownu',
          'bahasa_mandarin' => '宇宙',
          'fonetik_mandarin' => 'Yǔzhòu',
          'kategori' => 'Alam',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Benua',
          'bahasa_inggris' => 'Continent',
          'fonetik' => 'kon-ti-nent',
          'bahasa_arab' => 'قَارَّةٌ',
          'fonetik_arab' => 'Qārratun',
          'bahasa_mandarin' => '大陆',
          'fonetik_mandarin' => 'Dàlù',
          'kategori' => 'Alam',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Rawa',
          'bahasa_inggris' => 'Swamp',
          'fonetik' => 'swomp',
          'bahasa_arab' => 'مُسْتَنْقَعٌ',
          'fonetik_arab' => 'Mustanqaʿun',
          'bahasa_mandarin' => '沼泽',
          'fonetik_mandarin' => 'Zhǎozé',
          'kategori' => 'Alam',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Air Terjun',
          'bahasa_inggris' => 'Waterfall',
          'fonetik' => 'wo-ter-fol',
          'bahasa_arab' => 'شَلَّالٌ',
          'fonetik_arab' => 'Syallālun',
          'bahasa_mandarin' => '瀑布',
          'fonetik_mandarin' => 'Pùbù',
          'kategori' => 'Alam',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Tebing',
          'bahasa_inggris' => 'Cliff',
          'fonetik' => 'klif',
          'bahasa_arab' => 'جُرُفٌ',
          'fonetik_arab' => 'Jurufun',
          'bahasa_mandarin' => '悬崖',
          'fonetik_mandarin' => 'Xuányá',
          'kategori' => 'Alam',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Tanjung',
          'bahasa_inggris' => 'Cape',
          'fonetik' => 'keip',
          'bahasa_arab' => 'رَأْسٌ',
          'fonetik_arab' => 'Raʾsun',
          'bahasa_mandarin' => '海角',
          'fonetik_mandarin' => 'Hǎijiǎo',
          'kategori' => 'Alam',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Teluk',
          'bahasa_inggris' => 'Bay',
          'fonetik' => 'bei',
          'bahasa_arab' => 'خَلِيْجٌ',
          'fonetik_arab' => 'Khalījun',
          'bahasa_mandarin' => '海湾',
          'fonetik_mandarin' => 'Hǎiwān',
          'kategori' => 'Alam',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Kawah',
          'bahasa_inggris' => 'Crater',
          'fonetik' => 'krei-ter',
          'bahasa_arab' => 'فُوَّهَةٌ',
          'fonetik_arab' => 'Fuwwahatun',
          'bahasa_mandarin' => '火山口',
          'fonetik_mandarin' => 'Huǒshānkǒu',
          'kategori' => 'Alam',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Gunung Berapi',
          'bahasa_inggris' => 'Volcano',
          'fonetik' => 'vol-kei-no',
          'bahasa_arab' => 'بُرْكَانٌ',
          'fonetik_arab' => 'Burkānun',
          'bahasa_mandarin' => '火山',
          'fonetik_mandarin' => 'Huǒshān',
          'kategori' => 'Alam',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Gempa Bumi',
          'bahasa_inggris' => 'Earthquake',
          'fonetik' => 'erth-kweik',
          'bahasa_arab' => 'زِلْزَالٌ',
          'fonetik_arab' => 'Zilzālun',
          'bahasa_mandarin' => '地震',
          'fonetik_mandarin' => 'Dìzhèn',
          'kategori' => 'Alam',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Tsunami',
          'bahasa_inggris' => 'Tsunami',
          'fonetik' => 'tsu-na-mi',
          'bahasa_arab' => 'تْسُونَامِي',
          'fonetik_arab' => 'Tsūnāmī',
          'bahasa_mandarin' => '海啸',
          'fonetik_mandarin' => 'Hǎixiào',
          'kategori' => 'Alam',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Longsor',
          'bahasa_inggris' => 'Landslide',
          'fonetik' => 'lend-slaid',
          'bahasa_arab' => 'اِنْهِيَارٌ أَرْضِيٌّ',
          'fonetik_arab' => 'Inhiyārun Arḍiyyun',
          'bahasa_mandarin' => '泥石流',
          'fonetik_mandarin' => 'Níshíliú',
          'kategori' => 'Alam',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Banjir',
          'bahasa_inggris' => 'Flood',
          'fonetik' => 'flad',
          'bahasa_arab' => 'فَيْضَانٌ',
          'fonetik_arab' => 'Fayḍānun',
          'bahasa_mandarin' => '洪水',
          'fonetik_mandarin' => 'Hóngshuǐ',
          'kategori' => 'Alam',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Emas',
          'bahasa_inggris' => 'Gold',
          'fonetik' => 'gould',
          'bahasa_arab' => 'ذَهَبٌ',
          'fonetik_arab' => 'Dhahabun',
          'bahasa_mandarin' => '黄金',
          'fonetik_mandarin' => 'Huángjīn',
          'kategori' => 'Alam',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Perak',
          'bahasa_inggris' => 'Silver',
          'fonetik' => 'sil-ver',
          'bahasa_arab' => 'فِضَّةٌ',
          'fonetik_arab' => 'Fiḍḍatun',
          'bahasa_mandarin' => '白银',
          'fonetik_mandarin' => 'Báiyín',
          'kategori' => 'Alam',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Batu Bara',
          'bahasa_inggris' => 'Coal',
          'fonetik' => 'koul',
          'bahasa_arab' => 'فَحْمٌ',
          'fonetik_arab' => 'Faḥmun',
          'bahasa_mandarin' => '煤炭',
          'fonetik_mandarin' => 'Méitàn',
          'kategori' => 'Alam',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Minyak Bumi',
          'bahasa_inggris' => 'Petroleum',
          'fonetik' => 'pe-tro-li-um',
          'bahasa_arab' => 'نَفْطٌ',
          'fonetik_arab' => 'Nafṭun',
          'bahasa_mandarin' => '石油',
          'fonetik_mandarin' => 'Shíyóu',
          'kategori' => 'Alam',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Besi',
          'bahasa_inggris' => 'Iron',
          'fonetik' => 'ai-yen',
          'bahasa_arab' => 'حَدِيدٌ',
          'fonetik_arab' => 'Ḥadīdun',
          'bahasa_mandarin' => '铁',
          'fonetik_mandarin' => 'Tiě',
          'kategori' => 'Alam',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Tembaga',
          'bahasa_inggris' => 'Copper',
          'fonetik' => 'ko-per',
          'bahasa_arab' => 'نُحَاسٌ',
          'fonetik_arab' => 'Nuḥāsun',
          'bahasa_mandarin' => '铜',
          'fonetik_mandarin' => 'Tóng',
          'kategori' => 'Alam',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Atmosfer',
          'bahasa_inggris' => 'Atmosphere',
          'fonetik' => 'at-mos-fir',
          'bahasa_arab' => 'غِلَافٌ جَوِيٌّ',
          'fonetik_arab' => 'Ghilāfun Jawiyyun',
          'bahasa_mandarin' => '大气层',
          'fonetik_mandarin' => 'Dàqìcéng',
          'kategori' => 'Alam',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Oksigen',
          'bahasa_inggris' => 'Oxygen',
          'fonetik' => 'ok-si-jen',
          'bahasa_arab' => 'أُوكْسِجِين',
          'fonetik_arab' => 'Ūksijīn',
          'bahasa_mandarin' => '氧气',
          'fonetik_mandarin' => 'Yǎngqì',
          'kategori' => 'Alam',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Karbon Dioksida',
          'bahasa_inggris' => 'Carbon Dioxide',
          'fonetik' => 'kar-bon dai-ok-said',
          'bahasa_arab' => 'ثَانِي أُكْسِيدِ الْكَرْبُونِ',
          'fonetik_arab' => 'Thānī Uksīdil Karbūni',
          'bahasa_mandarin' => '二氧化碳',
          'fonetik_mandarin' => 'Èryǎnghuàtàn',
          'kategori' => 'Alam',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Lapisan Ozon',
          'bahasa_inggris' => 'Ozone Layer',
          'fonetik' => 'o-zon lei-er',
          'bahasa_arab' => 'طَبَقَةُ الْأُوزُونِ',
          'fonetik_arab' => 'Ṭabaqatul Uzūni',
          'bahasa_mandarin' => '臭氧层',
          'fonetik_mandarin' => 'Chòuyǎngcéng',
          'kategori' => 'Alam',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Orbit',
          'bahasa_inggris' => 'Orbit',
          'fonetik' => 'or-bit',
          'bahasa_arab' => 'مَدَارٌ',
          'fonetik_arab' => 'Madārun',
          'bahasa_mandarin' => '轨道',
          'fonetik_mandarin' => 'Guǐdào',
          'kategori' => 'Alam',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Gravitasi',
          'bahasa_inggris' => 'Gravity',
          'fonetik' => 'gra-vi-ta-si',
          'bahasa_arab' => 'جَاذِبِيَّةٌ',
          'fonetik_arab' => 'Jādhibiyyatun',
          'bahasa_mandarin' => '重力',
          'fonetik_mandarin' => 'Zhònglì',
          'kategori' => 'Alam',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Ekosistem',
          'bahasa_inggris' => 'Ecosystem',
          'fonetik' => 'e-ko-sis-tem',
          'bahasa_arab' => 'نِظَامٌ بِيْئِيٌّ',
          'fonetik_arab' => 'Niẓāmun Bīʾiyyun',
          'bahasa_mandarin' => '生态系统',
          'fonetik_mandarin' => 'Shēngtài xìtǒng',
          'kategori' => 'Alam',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Iklim',
          'bahasa_inggris' => 'Climate',
          'fonetik' => 'klai-met',
          'bahasa_arab' => 'مُنَاخٌ',
          'fonetik_arab' => 'Munākhun',
          'bahasa_mandarin' => '气候',
          'fonetik_mandarin' => 'Qìhòu',
          'kategori' => 'Alam',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Musim',
          'bahasa_inggris' => 'Season',
          'fonetik' => 'si-zen',
          'bahasa_arab' => 'فَصْلٌ',
          'fonetik_arab' => 'Faṣlun',
          'bahasa_mandarin' => '季节',
          'fonetik_mandarin' => 'Jìjié',
          'kategori' => 'Alam',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Fajar',
          'bahasa_inggris' => 'Dawn',
          'fonetik' => 'don',
          'bahasa_arab' => 'فَجْرٌ',
          'fonetik_arab' => 'Fajrun',
          'bahasa_mandarin' => '黎明',
          'fonetik_mandarin' => 'Límíng',
          'kategori' => 'Alam',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Senja',
          'bahasa_inggris' => 'Dusk',
          'fonetik' => 'dask',
          'bahasa_arab' => 'غُرُوْبٌ',
          'fonetik_arab' => 'Ghurūbun',
          'bahasa_mandarin' => '黄昏',
          'fonetik_mandarin' => 'Huánghūn',
          'kategori' => 'Alam',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Tengah Malam',
          'bahasa_inggris' => 'Midnight',
          'fonetik' => 'mid-nait',
          'bahasa_arab' => 'مُنْتَصَفُ اللَّيْلِ',
          'fonetik_arab' => 'Muntaṣaful Layli',
          'bahasa_mandarin' => '午夜',
          'fonetik_mandarin' => 'Wǔyè',
          'kategori' => 'Alam',
          'hari' => 13,
        ),
    );
  }
}