<?php

namespace Database\Seeders\Support\Game\Blueprints;

class AnggotaTubuh
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Kepala',
          'bahasa_inggris' => 'Head',
          'fonetik' => 'hed',
          'bahasa_arab' => 'رَأْسٌ',
          'fonetik_arab' => 'Raʾsun',
          'bahasa_mandarin' => '头',
          'fonetik_mandarin' => 'Tóu',
          'kategori' => 'Anggota Tubuh',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Mata',
          'bahasa_inggris' => 'Eye',
          'fonetik' => 'ai',
          'bahasa_arab' => 'عَيْنٌ',
          'fonetik_arab' => 'ʿAynun',
          'bahasa_mandarin' => '眼睛',
          'fonetik_mandarin' => 'Yǎnjīng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Hidung',
          'bahasa_inggris' => 'Nose',
          'fonetik' => 'nouz',
          'bahasa_arab' => 'أَنْفٌ',
          'fonetik_arab' => 'Anfun',
          'bahasa_mandarin' => '鼻子',
          'fonetik_mandarin' => 'Bízi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Mulut',
          'bahasa_inggris' => 'Mouth',
          'fonetik' => 'mauth',
          'bahasa_arab' => 'فَمٌ',
          'fonetik_arab' => 'Famun',
          'bahasa_mandarin' => '嘴巴',
          'fonetik_mandarin' => 'Zuǐbā',
          'kategori' => 'Anggota Tubuh',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Tangan',
          'bahasa_inggris' => 'Hand',
          'fonetik' => 'hend',
          'bahasa_arab' => 'يَدٌ',
          'fonetik_arab' => 'Yadun',
          'bahasa_mandarin' => '手',
          'fonetik_mandarin' => 'Shǒu',
          'kategori' => 'Anggota Tubuh',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Kaki',
          'bahasa_inggris' => 'Foot',
          'fonetik' => 'fut',
          'bahasa_arab' => 'قَدَمٌ',
          'fonetik_arab' => 'Qadamun',
          'bahasa_mandarin' => '脚',
          'fonetik_mandarin' => 'Jiǎo',
          'kategori' => 'Anggota Tubuh',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Rambut',
          'bahasa_inggris' => 'Hair',
          'fonetik' => 'her',
          'bahasa_arab' => 'شَعْرٌ',
          'fonetik_arab' => 'Shaʿrun',
          'bahasa_mandarin' => '头发',
          'fonetik_mandarin' => 'Tóufǎ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Telinga',
          'bahasa_inggris' => 'Ear',
          'fonetik' => 'ir',
          'bahasa_arab' => 'أُذُنٌ',
          'fonetik_arab' => 'Udhnun',
          'bahasa_mandarin' => '耳朵',
          'fonetik_mandarin' => 'Ěrduǒ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Jari',
          'bahasa_inggris' => 'Finger',
          'fonetik' => 'fing-ger',
          'bahasa_arab' => 'إِصْبَعٌ',
          'fonetik_arab' => 'Iṣbaʿun',
          'bahasa_mandarin' => '手指',
          'fonetik_mandarin' => 'Shǒuzhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Lengan',
          'bahasa_inggris' => 'Arm',
          'fonetik' => 'arm',
          'bahasa_arab' => 'ذِرَاعٌ',
          'fonetik_arab' => 'Dhirāʿun',
          'bahasa_mandarin' => '手臂',
          'fonetik_mandarin' => 'Shǒubì',
          'kategori' => 'Anggota Tubuh',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Kaki (tungkai)',
          'bahasa_inggris' => 'Leg',
          'fonetik' => 'leg',
          'bahasa_arab' => 'سَاقٌ',
          'fonetik_arab' => 'Sāqun',
          'bahasa_mandarin' => '腿',
          'fonetik_mandarin' => 'Tuǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Gigi',
          'bahasa_inggris' => 'Tooth',
          'fonetik' => 'tuth',
          'bahasa_arab' => 'سِنٌّ',
          'fonetik_arab' => 'Sinnun',
          'bahasa_mandarin' => '牙齿',
          'fonetik_mandarin' => 'Yáchǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Wajah',
          'bahasa_inggris' => 'Face',
          'fonetik' => 'feys',
          'bahasa_arab' => 'وَجْهٌ',
          'fonetik_arab' => 'Wajhun',
          'bahasa_mandarin' => '脸',
          'fonetik_mandarin' => 'Liǎn',
          'kategori' => 'Anggota Tubuh',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Leher',
          'bahasa_inggris' => 'Neck',
          'fonetik' => 'nek',
          'bahasa_arab' => 'رَقَبَةٌ',
          'fonetik_arab' => 'Raqabatun',
          'bahasa_mandarin' => '脖子',
          'fonetik_mandarin' => 'Bózi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Bahu',
          'bahasa_inggris' => 'Shoulder',
          'fonetik' => 'syol-der',
          'bahasa_arab' => 'كَتِفٌ',
          'fonetik_arab' => 'Katifun',
          'bahasa_mandarin' => '肩膀',
          'fonetik_mandarin' => 'Jiānbǎng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Punggung',
          'bahasa_inggris' => 'Back',
          'fonetik' => 'bek',
          'bahasa_arab' => 'ظَهْرٌ',
          'fonetik_arab' => 'Ẓahrun',
          'bahasa_mandarin' => '背',
          'fonetik_mandarin' => 'Bèi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Perut',
          'bahasa_inggris' => 'Belly',
          'fonetik' => 'be-li',
          'bahasa_arab' => 'بَطْنٌ',
          'fonetik_arab' => 'Baṭnun',
          'bahasa_mandarin' => '肚子',
          'fonetik_mandarin' => 'Dùzi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Lutut',
          'bahasa_inggris' => 'Knee',
          'fonetik' => 'ni',
          'bahasa_arab' => 'رُكْبَةٌ',
          'fonetik_arab' => 'Rukbatun',
          'bahasa_mandarin' => '膝盖',
          'fonetik_mandarin' => 'Xīgài',
          'kategori' => 'Anggota Tubuh',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Lidah',
          'bahasa_inggris' => 'Tongue',
          'fonetik' => 'tang',
          'bahasa_arab' => 'لِسَانٌ',
          'fonetik_arab' => 'Lisānun',
          'bahasa_mandarin' => '舌头',
          'fonetik_mandarin' => 'Shétou',
          'kategori' => 'Anggota Tubuh',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Bibir',
          'bahasa_inggris' => 'Lip',
          'fonetik' => 'lip',
          'bahasa_arab' => 'شَفَةٌ',
          'fonetik_arab' => 'Shafatun',
          'bahasa_mandarin' => '嘴唇',
          'fonetik_mandarin' => 'Zuǐchún',
          'kategori' => 'Anggota Tubuh',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Pipi',
          'bahasa_inggris' => 'Cheek',
          'fonetik' => 'cik',
          'bahasa_arab' => 'خَدٌّ',
          'fonetik_arab' => 'Khaddun',
          'bahasa_mandarin' => '脸颊',
          'fonetik_mandarin' => 'Liǎnjiá',
          'kategori' => 'Anggota Tubuh',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Dagu',
          'bahasa_inggris' => 'Chin',
          'fonetik' => 'cin',
          'bahasa_arab' => 'ذَقْنٌ',
          'fonetik_arab' => 'Dhaqnún',
          'bahasa_mandarin' => '下巴',
          'fonetik_mandarin' => 'Xiàba',
          'kategori' => 'Anggota Tubuh',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Alis',
          'bahasa_inggris' => 'Eyebrow',
          'fonetik' => 'ai-brau',
          'bahasa_arab' => 'حَاجِبٌ',
          'fonetik_arab' => 'Ḥājibun',
          'bahasa_mandarin' => '眉毛',
          'fonetik_mandarin' => 'Méimao',
          'kategori' => 'Anggota Tubuh',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Jari kaki',
          'bahasa_inggris' => 'Toe',
          'fonetik' => 'tou',
          'bahasa_arab' => 'إِصْبَعُ الْقَدَمِ',
          'fonetik_arab' => 'Iṣbaʿ al-Qadam',
          'bahasa_mandarin' => '脚趾',
          'fonetik_mandarin' => 'Jiǎozhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Dada',
          'bahasa_inggris' => 'Chest',
          'fonetik' => 'cest',
          'bahasa_arab' => 'صَدْرٌ',
          'fonetik_arab' => 'Ṣadrun',
          'bahasa_mandarin' => '胸部',
          'fonetik_mandarin' => 'Xiōngbù',
          'kategori' => 'Anggota Tubuh',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Siku',
          'bahasa_inggris' => 'Elbow',
          'fonetik' => 'el-bou',
          'bahasa_arab' => 'مِرْفَقٌ',
          'fonetik_arab' => 'Mirfaqun',
          'bahasa_mandarin' => '肘',
          'fonetik_mandarin' => 'Zhǒu',
          'kategori' => 'Anggota Tubuh',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Kuku',
          'bahasa_inggris' => 'Nail',
          'fonetik' => 'neil',
          'bahasa_arab' => 'ظُفْرٌ',
          'fonetik_arab' => 'Ẓufrun',
          'bahasa_mandarin' => '指甲',
          'fonetik_mandarin' => 'Zhǐjia',
          'kategori' => 'Anggota Tubuh',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Kulit',
          'bahasa_inggris' => 'Skin',
          'fonetik' => 'skin',
          'bahasa_arab' => 'جِلْدٌ',
          'fonetik_arab' => 'Jildun',
          'bahasa_mandarin' => '皮肤',
          'fonetik_mandarin' => 'Pífū',
          'kategori' => 'Anggota Tubuh',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Tulang',
          'bahasa_inggris' => 'Bone',
          'fonetik' => 'boun',
          'bahasa_arab' => 'عَظْمٌ',
          'fonetik_arab' => 'ʿAẓmun',
          'bahasa_mandarin' => '骨头',
          'fonetik_mandarin' => 'Gǔtou',
          'kategori' => 'Anggota Tubuh',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Darah',
          'bahasa_inggris' => 'Blood',
          'fonetik' => 'blad',
          'bahasa_arab' => 'دَمٌ',
          'fonetik_arab' => 'Damun',
          'bahasa_mandarin' => '血',
          'fonetik_mandarin' => 'Xuè',
          'kategori' => 'Anggota Tubuh',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Jantung',
          'bahasa_inggris' => 'Heart',
          'fonetik' => 'hart',
          'bahasa_arab' => 'قَلْبٌ',
          'fonetik_arab' => 'Qalbún',
          'bahasa_mandarin' => '心脏',
          'fonetik_mandarin' => 'Xīnzàng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Otak',
          'bahasa_inggris' => 'Brain',
          'fonetik' => 'brein',
          'bahasa_arab' => 'دِمَاغٌ',
          'fonetik_arab' => 'Dimāghun',
          'bahasa_mandarin' => '大脑',
          'fonetik_mandarin' => 'Dànǎo',
          'kategori' => 'Anggota Tubuh',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Otot',
          'bahasa_inggris' => 'Muscle',
          'fonetik' => 'ma-sel',
          'bahasa_arab' => 'عَضَلَةٌ',
          'fonetik_arab' => 'ʿAḍalatun',
          'bahasa_mandarin' => '肌肉',
          'fonetik_mandarin' => 'Jīròu',
          'kategori' => 'Anggota Tubuh',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Pinggang',
          'bahasa_inggris' => 'Waist',
          'fonetik' => 'weist',
          'bahasa_arab' => 'خَصْرٌ',
          'fonetik_arab' => 'Khaṣrun',
          'bahasa_mandarin' => '腰',
          'fonetik_mandarin' => 'Yāo',
          'kategori' => 'Anggota Tubuh',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Tumit',
          'bahasa_inggris' => 'Heel',
          'fonetik' => 'hil',
          'bahasa_arab' => 'كَعْبٌ',
          'fonetik_arab' => 'Kaʿbun',
          'bahasa_mandarin' => '脚跟',
          'fonetik_mandarin' => 'Jiǎogēn',
          'kategori' => 'Anggota Tubuh',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Pergelangan Kaki',
          'bahasa_inggris' => 'Ankle',
          'fonetik' => 'eng-kel',
          'bahasa_arab' => 'كَاحِلٌ',
          'fonetik_arab' => 'Kāḥilun',
          'bahasa_mandarin' => '脚踝',
          'fonetik_mandarin' => 'Jiǎohuái',
          'kategori' => 'Anggota Tubuh',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Pergelangan Tangan',
          'bahasa_inggris' => 'Wrist',
          'fonetik' => 'rist',
          'bahasa_arab' => 'مِعْصَمٌ',
          'fonetik_arab' => 'Miʿṣamun',
          'bahasa_mandarin' => '手腕',
          'fonetik_mandarin' => 'Shǒuwàn',
          'kategori' => 'Anggota Tubuh',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Telapak Tangan',
          'bahasa_inggris' => 'Palm',
          'fonetik' => 'paam',
          'bahasa_arab' => 'كَفٌّ',
          'fonetik_arab' => 'Kaffun',
          'bahasa_mandarin' => '手掌',
          'fonetik_mandarin' => 'Shǒuzhǎng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Ibu Jari',
          'bahasa_inggris' => 'Thumb',
          'fonetik' => 'tham',
          'bahasa_arab' => 'إِبْهَامٌ',
          'fonetik_arab' => 'Ibhāmun',
          'bahasa_mandarin' => '拇指',
          'fonetik_mandarin' => 'Mǔzhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Jari Telunjuk',
          'bahasa_inggris' => 'Index Finger',
          'fonetik' => 'in-deks fing-ger',
          'bahasa_arab' => 'سَبَّابَةٌ',
          'fonetik_arab' => 'Sabbābatun',
          'bahasa_mandarin' => '食指',
          'fonetik_mandarin' => 'Shízhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Jari Tengah',
          'bahasa_inggris' => 'Middle Finger',
          'fonetik' => 'mi-del fing-ger',
          'bahasa_arab' => 'وُسْطَى',
          'fonetik_arab' => 'Wusṭā',
          'bahasa_mandarin' => '中指',
          'fonetik_mandarin' => 'Zhōngzhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Jari Manis',
          'bahasa_inggris' => 'Ring Finger',
          'fonetik' => 'ring fing-ger',
          'bahasa_arab' => 'بِنْصِرٌ',
          'fonetik_arab' => 'Binṣirun',
          'bahasa_mandarin' => '无名指',
          'fonetik_mandarin' => 'Wúmíngzhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Jari Kelingking',
          'bahasa_inggris' => 'Pinky Finger',
          'fonetik' => 'ping-ki fing-ger',
          'bahasa_arab' => 'خِنْصِرٌ',
          'fonetik_arab' => 'Khinṣirun',
          'bahasa_mandarin' => '小指',
          'fonetik_mandarin' => 'Xiǎozhǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Paha',
          'bahasa_inggris' => 'Thigh',
          'fonetik' => 'thai',
          'bahasa_arab' => 'فَخِذٌ',
          'fonetik_arab' => 'Fakhidhun',
          'bahasa_mandarin' => '大腿',
          'fonetik_mandarin' => 'Dàtuǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Betis',
          'bahasa_inggris' => 'Calf',
          'fonetik' => 'kaf',
          'bahasa_arab' => 'عَضَلَةُ السَّاقِ',
          'fonetik_arab' => 'ʿAḍalat as-Sāq',
          'bahasa_mandarin' => '小腿',
          'fonetik_mandarin' => 'Xiǎotuǐ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Telapak Kaki',
          'bahasa_inggris' => 'Sole',
          'fonetik' => 'soul',
          'bahasa_arab' => 'أَخْمَصُ الْقَدَمِ',
          'fonetik_arab' => 'Akhmaṣ al-Qadam',
          'bahasa_mandarin' => '脚掌',
          'fonetik_mandarin' => 'Jiǎozhǎng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Punggung Kaki',
          'bahasa_inggris' => 'Instep',
          'fonetik' => 'in-step',
          'bahasa_arab' => 'ظَهْرُ الْقَدَمِ',
          'fonetik_arab' => 'Ẓahr al-Qadam',
          'bahasa_mandarin' => '脚背',
          'fonetik_mandarin' => 'Jiǎobèi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Pinggul',
          'bahasa_inggris' => 'Hip',
          'fonetik' => 'hip',
          'bahasa_arab' => 'وَرِكٌ',
          'fonetik_arab' => 'Warikun',
          'bahasa_mandarin' => '胯',
          'fonetik_mandarin' => 'Kuà',
          'kategori' => 'Anggota Tubuh',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Dahi',
          'bahasa_inggris' => 'Forehead',
          'fonetik' => 'for-hed',
          'bahasa_arab' => 'جَبْهَةٌ',
          'fonetik_arab' => 'Jabhahun',
          'bahasa_mandarin' => '前额',
          'fonetik_mandarin' => 'Qián\'é',
          'kategori' => 'Anggota Tubuh',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Bulu Mata',
          'bahasa_inggris' => 'Eyelashes',
          'fonetik' => 'ai-la-syez',
          'bahasa_arab' => 'رِمْشٌ',
          'fonetik_arab' => 'Rimshun',
          'bahasa_mandarin' => '睫毛',
          'fonetik_mandarin' => 'Jiémáo',
          'kategori' => 'Anggota Tubuh',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Kelopak Mata',
          'bahasa_inggris' => 'Eyelid',
          'fonetik' => 'ai-lid',
          'bahasa_arab' => 'جَفْنٌ',
          'fonetik_arab' => 'Jafnun',
          'bahasa_mandarin' => '眼睑',
          'fonetik_mandarin' => 'Yǎnjiǎn',
          'kategori' => 'Anggota Tubuh',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Lubang Hidung',
          'bahasa_inggris' => 'Nostril',
          'fonetik' => 'nos-tril',
          'bahasa_arab' => 'مِنْخَرٌ',
          'fonetik_arab' => 'Minkharun',
          'bahasa_mandarin' => '鼻孔',
          'fonetik_mandarin' => 'Bíkǒng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Gusi',
          'bahasa_inggris' => 'Gum',
          'fonetik' => 'gam',
          'bahasa_arab' => 'لِثَةٌ',
          'fonetik_arab' => 'Lithatun',
          'bahasa_mandarin' => '牙龈',
          'fonetik_mandarin' => 'Yáyín',
          'kategori' => 'Anggota Tubuh',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Langit-langit Mulut',
          'bahasa_inggris' => 'Palate',
          'fonetik' => 'pa-let',
          'bahasa_arab' => 'حَنَكٌ',
          'fonetik_arab' => 'Ḥanakun',
          'bahasa_mandarin' => '腭',
          'fonetik_mandarin' => 'È',
          'kategori' => 'Anggota Tubuh',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Paru-paru',
          'bahasa_inggris' => 'Lungs',
          'fonetik' => 'langs',
          'bahasa_arab' => 'رِئَةٌ',
          'fonetik_arab' => 'Riʾatun',
          'bahasa_mandarin' => '肺',
          'fonetik_mandarin' => 'Fèi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Hati',
          'bahasa_inggris' => 'Liver',
          'fonetik' => 'li-ver',
          'bahasa_arab' => 'كَبِدٌ',
          'fonetik_arab' => 'Kabidun',
          'bahasa_mandarin' => '肝脏',
          'fonetik_mandarin' => 'Gānzàng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Ginjal',
          'bahasa_inggris' => 'Kidney',
          'fonetik' => 'kid-ni',
          'bahasa_arab' => 'كُلْيَةٌ',
          'fonetik_arab' => 'Kulyatun',
          'bahasa_mandarin' => '肾脏',
          'fonetik_mandarin' => 'Shènzàng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Usus',
          'bahasa_inggris' => 'Intestine',
          'fonetik' => 'in-tes-tin',
          'bahasa_arab' => 'أَمْعَاءٌ',
          'fonetik_arab' => 'Amʿāʾun',
          'bahasa_mandarin' => '肠',
          'fonetik_mandarin' => 'Cháng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Lambung',
          'bahasa_inggris' => 'Stomach',
          'fonetik' => 'sta-mek',
          'bahasa_arab' => 'مَعِدَةٌ',
          'fonetik_arab' => 'Maʿidatun',
          'bahasa_mandarin' => '胃',
          'fonetik_mandarin' => 'Wèi',
          'kategori' => 'Anggota Tubuh',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Empedu',
          'bahasa_inggris' => 'Gallbladder',
          'fonetik' => 'gol-bla-der',
          'bahasa_arab' => 'مَرَارَةٌ',
          'fonetik_arab' => 'Marāratun',
          'bahasa_mandarin' => '胆囊',
          'fonetik_mandarin' => 'Dǎnnáng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Tenggorokan',
          'bahasa_inggris' => 'Throat',
          'fonetik' => 'throut',
          'bahasa_arab' => 'حَلْقٌ',
          'fonetik_arab' => 'Ḥalqun',
          'bahasa_mandarin' => '喉咙',
          'fonetik_mandarin' => 'Hóulóng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Jakun',
          'bahasa_inggris' => 'Adam\'s Apple',
          'fonetik' => 'a-dam-z e-pel',
          'bahasa_arab' => 'تُفَّاحَةُ آدَمَ',
          'fonetik_arab' => 'Tuffāḥat Ādam',
          'bahasa_mandarin' => '喉结',
          'fonetik_mandarin' => 'Hóujié',
          'kategori' => 'Anggota Tubuh',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Ubun-ubun',
          'bahasa_inggris' => 'Crown',
          'fonetik' => 'kraun',
          'bahasa_arab' => 'يَا فُوخٌ',
          'fonetik_arab' => 'Yāfūkhun',
          'bahasa_mandarin' => '头顶',
          'fonetik_mandarin' => 'Tóudǐng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Pelipis',
          'bahasa_inggris' => 'Temple',
          'fonetik' => 'tem-pel',
          'bahasa_arab' => 'صُدْغٌ',
          'fonetik_arab' => 'Ṣudghun',
          'bahasa_mandarin' => '太阳穴',
          'fonetik_mandarin' => 'Tàiyángxué',
          'kategori' => 'Anggota Tubuh',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Rahang',
          'bahasa_inggris' => 'Jaw',
          'fonetik' => 'jo',
          'bahasa_arab' => 'فَكٌّ',
          'fonetik_arab' => 'Fakkun',
          'bahasa_mandarin' => '下颚',
          'fonetik_mandarin' => 'Xià\'è',
          'kategori' => 'Anggota Tubuh',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Anak Tekak',
          'bahasa_inggris' => 'Uvula',
          'fonetik' => 'yu-vyu-la',
          'bahasa_arab' => 'لَهَاةٌ',
          'fonetik_arab' => 'Lahātun',
          'bahasa_mandarin' => '小舌',
          'fonetik_mandarin' => 'Xiǎoshé',
          'kategori' => 'Anggota Tubuh',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Tengkorak',
          'bahasa_inggris' => 'Skull',
          'fonetik' => 'skal',
          'bahasa_arab' => 'جُمْجُمَةٌ',
          'fonetik_arab' => 'Jumjumatun',
          'bahasa_mandarin' => '头骨',
          'fonetik_mandarin' => 'Tóugǔ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Tulang Rusuk',
          'bahasa_inggris' => 'Rib',
          'fonetik' => 'rib',
          'bahasa_arab' => 'ضِلْعٌ',
          'fonetik_arab' => 'Ḍilʿun',
          'bahasa_mandarin' => '肋骨',
          'fonetik_mandarin' => 'Lèigǔ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Tulang Belakang',
          'bahasa_inggris' => 'Spine',
          'fonetik' => 'spain',
          'bahasa_arab' => 'عَمُودٌ فِقْرِيٌّ',
          'fonetik_arab' => 'ʿAmūd Fiqrī',
          'bahasa_mandarin' => '脊柱',
          'fonetik_mandarin' => 'Jǐzhù',
          'kategori' => 'Anggota Tubuh',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Sendi',
          'bahasa_inggris' => 'Joint',
          'fonetik' => 'join',
          'bahasa_arab' => 'مَفْصِلٌ',
          'fonetik_arab' => 'Mafṣilun',
          'bahasa_mandarin' => '关节',
          'fonetik_mandarin' => 'Guānjié',
          'kategori' => 'Anggota Tubuh',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Urat',
          'bahasa_inggris' => 'Vein',
          'fonetik' => 'vein',
          'bahasa_arab' => 'وَرِيدٌ',
          'fonetik_arab' => 'Warīdun',
          'bahasa_mandarin' => '静脉',
          'fonetik_mandarin' => 'Jìngmài',
          'kategori' => 'Anggota Tubuh',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Saraf',
          'bahasa_inggris' => 'Nerve',
          'fonetik' => 'nerv',
          'bahasa_arab' => 'عَصَبٌ',
          'fonetik_arab' => 'ʿAṣabun',
          'bahasa_mandarin' => '神经',
          'fonetik_mandarin' => 'Shénjīng',
          'kategori' => 'Anggota Tubuh',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Ketiak',
          'bahasa_inggris' => 'Armpit',
          'fonetik' => 'arm-pit',
          'bahasa_arab' => 'إِبْطٌ',
          'fonetik_arab' => 'Ibṭun',
          'bahasa_mandarin' => '腋下',
          'fonetik_mandarin' => 'Yèxià',
          'kategori' => 'Anggota Tubuh',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Pusar',
          'bahasa_inggris' => 'Navel',
          'fonetik' => 'nei-vel',
          'bahasa_arab' => 'سُرَّةٌ',
          'fonetik_arab' => 'Surratun',
          'bahasa_mandarin' => '肚脐',
          'fonetik_mandarin' => 'Dùqí',
          'kategori' => 'Anggota Tubuh',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Lengan Atas',
          'bahasa_inggris' => 'Upper Arm',
          'fonetik' => 'a-per arm',
          'bahasa_arab' => 'عَضُدٌ',
          'fonetik_arab' => 'ʿAḍudun',
          'bahasa_mandarin' => '上臂',
          'fonetik_mandarin' => 'Shàngbì',
          'kategori' => 'Anggota Tubuh',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Lengan Bawah',
          'bahasa_inggris' => 'Forearm',
          'fonetik' => 'for-arm',
          'bahasa_arab' => 'سَاعِدٌ',
          'fonetik_arab' => 'Sāʿidun',
          'bahasa_mandarin' => '前臂',
          'fonetik_mandarin' => 'Qiánbì',
          'kategori' => 'Anggota Tubuh',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Pantat',
          'bahasa_inggris' => 'Buttocks',
          'fonetik' => 'ba-toks',
          'bahasa_arab' => 'أَلْيَةٌ',
          'fonetik_arab' => 'Alyatun',
          'bahasa_mandarin' => '臀部',
          'fonetik_mandarin' => 'Túnbù',
          'kategori' => 'Anggota Tubuh',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Mata Kaki',
          'bahasa_inggris' => 'Ankle Bone',
          'fonetik' => 'eng-kel boun',
          'bahasa_arab' => 'كَعْبٌ',
          'fonetik_arab' => 'Kaʿbun',
          'bahasa_mandarin' => '踝骨',
          'fonetik_mandarin' => 'Huáigǔ',
          'kategori' => 'Anggota Tubuh',
          'hari' => 13,
        ),
    );
  }
}