<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Angka
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Satu',
          'bahasa_inggris' => 'One',
          'fonetik' => 'wan',
          'bahasa_arab' => 'وَاحِدٌ',
          'fonetik_arab' => 'Wāḥidun',
          'bahasa_mandarin' => '一',
          'fonetik_mandarin' => 'Yī',
          'kategori' => 'Angka',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Dua',
          'bahasa_inggris' => 'Two',
          'fonetik' => 'tu',
          'bahasa_arab' => 'اثْنَانِ',
          'fonetik_arab' => 'Ithnāni',
          'bahasa_mandarin' => '二',
          'fonetik_mandarin' => 'Èr',
          'kategori' => 'Angka',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Tiga',
          'bahasa_inggris' => 'Three',
          'fonetik' => 'thri',
          'bahasa_arab' => 'ثَلَاثَةٌ',
          'fonetik_arab' => 'Thalāthatun',
          'bahasa_mandarin' => '三',
          'fonetik_mandarin' => 'Sān',
          'kategori' => 'Angka',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Empat',
          'bahasa_inggris' => 'Four',
          'fonetik' => 'for',
          'bahasa_arab' => 'أَرْبَعَةٌ',
          'fonetik_arab' => 'Arbaʿatun',
          'bahasa_mandarin' => '四',
          'fonetik_mandarin' => 'Sì',
          'kategori' => 'Angka',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Lima',
          'bahasa_inggris' => 'Five',
          'fonetik' => 'faiv',
          'bahasa_arab' => 'خَمْسَةٌ',
          'fonetik_arab' => 'Khamsatun',
          'bahasa_mandarin' => '五',
          'fonetik_mandarin' => 'Wǔ',
          'kategori' => 'Angka',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Nol',
          'bahasa_inggris' => 'Zero',
          'fonetik' => 'zi-ro',
          'bahasa_arab' => 'صِفْرٌ',
          'fonetik_arab' => 'Shifrun',
          'bahasa_mandarin' => '零',
          'fonetik_mandarin' => 'Líng',
          'kategori' => 'Angka',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Enam',
          'bahasa_inggris' => 'Six',
          'fonetik' => 'siks',
          'bahasa_arab' => 'سِتَّةٌ',
          'fonetik_arab' => 'Sittatun',
          'bahasa_mandarin' => '六',
          'fonetik_mandarin' => 'Liù',
          'kategori' => 'Angka',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Tujuh',
          'bahasa_inggris' => 'Seven',
          'fonetik' => 'se-ven',
          'bahasa_arab' => 'سَبْعَةٌ',
          'fonetik_arab' => 'Sabʿatun',
          'bahasa_mandarin' => '七',
          'fonetik_mandarin' => 'Qī',
          'kategori' => 'Angka',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Delapan',
          'bahasa_inggris' => 'Eight',
          'fonetik' => 'eyt',
          'bahasa_arab' => 'ثَمَانِيَةٌ',
          'fonetik_arab' => 'Thamāniyatun',
          'bahasa_mandarin' => '八',
          'fonetik_mandarin' => 'Bā',
          'kategori' => 'Angka',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Sembilan',
          'bahasa_inggris' => 'Nine',
          'fonetik' => 'nain',
          'bahasa_arab' => 'تِسْعَةٌ',
          'fonetik_arab' => 'Tisʿatun',
          'bahasa_mandarin' => '九',
          'fonetik_mandarin' => 'Jiǔ',
          'kategori' => 'Angka',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Sepuluh',
          'bahasa_inggris' => 'Ten',
          'fonetik' => 'ten',
          'bahasa_arab' => 'عَشَرَةٌ',
          'fonetik_arab' => 'ʿAsharatun',
          'bahasa_mandarin' => '十',
          'fonetik_mandarin' => 'Shí',
          'kategori' => 'Angka',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Dua Puluh Satu',
          'bahasa_inggris' => 'Twenty one',
          'fonetik' => 'twen-ti wan',
          'bahasa_arab' => 'وَاحِدٌ وَعِشْرُونَ',
          'fonetik_arab' => 'Wāḥidun wa-ʿIshrūna',
          'bahasa_mandarin' => '二十一',
          'fonetik_mandarin' => 'Èrshíyī',
          'kategori' => 'Angka',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Sebelas',
          'bahasa_inggris' => 'Eleven',
          'fonetik' => 'i-le-ven',
          'bahasa_arab' => 'أَحَدَ عَشَرَ',
          'fonetik_arab' => 'Aḥada ʿAshara',
          'bahasa_mandarin' => '十一',
          'fonetik_mandarin' => 'Shíyī',
          'kategori' => 'Angka',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Dua Belas',
          'bahasa_inggris' => 'Twelve',
          'fonetik' => 'twelv',
          'bahasa_arab' => 'اثْنَا عَشَرَ',
          'fonetik_arab' => 'Ithnā ʿAshara',
          'bahasa_mandarin' => '十二',
          'fonetik_mandarin' => 'Shí\'èr',
          'kategori' => 'Angka',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Tiga Belas',
          'bahasa_inggris' => 'Thirteen',
          'fonetik' => 'ther-tin',
          'bahasa_arab' => 'ثَلَاثَةَ عَشَرَ',
          'fonetik_arab' => 'Thalāthata ʿAshara',
          'bahasa_mandarin' => '十三',
          'fonetik_mandarin' => 'Shísān',
          'kategori' => 'Angka',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Empat Belas',
          'bahasa_inggris' => 'Fourteen',
          'fonetik' => 'for-tin',
          'bahasa_arab' => 'أَرْبَعَةَ عَشَرَ',
          'fonetik_arab' => 'Arbaʿata ʿAshara',
          'bahasa_mandarin' => '十四',
          'fonetik_mandarin' => 'Shísì',
          'kategori' => 'Angka',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Lima Belas',
          'bahasa_inggris' => 'Fifteen',
          'fonetik' => 'fif-tin',
          'bahasa_arab' => 'خَمْسَةَ عَشَرَ',
          'fonetik_arab' => 'Khamsata ʿAshara',
          'bahasa_mandarin' => '十五',
          'fonetik_mandarin' => 'Shíwǔ',
          'kategori' => 'Angka',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Dua Puluh Dua',
          'bahasa_inggris' => 'Twenty two',
          'fonetik' => 'twen-ti tu',
          'bahasa_arab' => 'اثْنَانِ وَعِشْرُونَ',
          'fonetik_arab' => 'Ithnāni wa-ʿIshrūna',
          'bahasa_mandarin' => '二十二',
          'fonetik_mandarin' => 'Èrshí\'èr',
          'kategori' => 'Angka',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Enam Belas',
          'bahasa_inggris' => 'Sixteen',
          'fonetik' => 'siks-tin',
          'bahasa_arab' => 'سِتَّةَ عَشَرَ',
          'fonetik_arab' => 'Sittata ʿAshara',
          'bahasa_mandarin' => '十六',
          'fonetik_mandarin' => 'Shíliù',
          'kategori' => 'Angka',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Tujuh Belas',
          'bahasa_inggris' => 'Seventeen',
          'fonetik' => 'se-ven-tin',
          'bahasa_arab' => 'سَبْعَةَ عَشَرَ',
          'fonetik_arab' => 'Sabʿata ʿAshara',
          'bahasa_mandarin' => '十七',
          'fonetik_mandarin' => 'Shíqī',
          'kategori' => 'Angka',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Delapan Belas',
          'bahasa_inggris' => 'Eighteen',
          'fonetik' => 'ey-tin',
          'bahasa_arab' => 'ثَمَانِيَةَ عَشَرَ',
          'fonetik_arab' => 'Thamāniyata ʿAshara',
          'bahasa_mandarin' => '十八',
          'fonetik_mandarin' => 'Shíbā',
          'kategori' => 'Angka',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Sembilan Belas',
          'bahasa_inggris' => 'Nineteen',
          'fonetik' => 'nain-tin',
          'bahasa_arab' => 'تِسْعَةَ عَشَرَ',
          'fonetik_arab' => 'Tisʿata ʿAshara',
          'bahasa_mandarin' => '十九',
          'fonetik_mandarin' => 'Shíjiǔ',
          'kategori' => 'Angka',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Dua Puluh',
          'bahasa_inggris' => 'Twenty',
          'fonetik' => 'twen-ti',
          'bahasa_arab' => 'عِشْرُونَ',
          'fonetik_arab' => 'ʿIshruna',
          'bahasa_mandarin' => '二十',
          'fonetik_mandarin' => 'Èrshí',
          'kategori' => 'Angka',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Dua Puluh Tiga',
          'bahasa_inggris' => 'Twenty three',
          'fonetik' => 'twen-ti thri',
          'bahasa_arab' => 'ثَلَاثَةٌ وَعِشْرُونَ',
          'fonetik_arab' => 'Thalāthatun wa-ʿIshrūna',
          'bahasa_mandarin' => '二十三',
          'fonetik_mandarin' => 'Èrshísān',
          'kategori' => 'Angka',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Tiga Puluh',
          'bahasa_inggris' => 'Thirty',
          'fonetik' => 'ther-ti',
          'bahasa_arab' => 'ثَلَاثُونَ',
          'fonetik_arab' => 'Thalāthuna',
          'bahasa_mandarin' => '三十',
          'fonetik_mandarin' => 'Sānshí',
          'kategori' => 'Angka',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Empat Puluh',
          'bahasa_inggris' => 'Forty',
          'fonetik' => 'for-ti',
          'bahasa_arab' => 'أَرْبَعُونَ',
          'fonetik_arab' => 'Arbaʿuna',
          'bahasa_mandarin' => '四十',
          'fonetik_mandarin' => 'Sìshí',
          'kategori' => 'Angka',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Lima Puluh',
          'bahasa_inggris' => 'Fifty',
          'fonetik' => 'fif-ti',
          'bahasa_arab' => 'خَمْسُونَ',
          'fonetik_arab' => 'Khamsuna',
          'bahasa_mandarin' => '五十',
          'fonetik_mandarin' => 'Wǔshí',
          'kategori' => 'Angka',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Enam Puluh',
          'bahasa_inggris' => 'Sixty',
          'fonetik' => 'siks-ti',
          'bahasa_arab' => 'سِتُّونَ',
          'fonetik_arab' => 'Sittuna',
          'bahasa_mandarin' => '六十',
          'fonetik_mandarin' => 'Liùshí',
          'kategori' => 'Angka',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Tujuh Puluh',
          'bahasa_inggris' => 'Seventy',
          'fonetik' => 'sev-en-ti',
          'bahasa_arab' => 'سَبْعُونَ',
          'fonetik_arab' => 'Sabʿuna',
          'bahasa_mandarin' => '七十',
          'fonetik_mandarin' => 'Qīshí',
          'kategori' => 'Angka',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Delapan Puluh',
          'bahasa_inggris' => 'Eighty',
          'fonetik' => 'ey-ti',
          'bahasa_arab' => 'ثَمَانُونَ',
          'fonetik_arab' => 'Thamānuna',
          'bahasa_mandarin' => '八十',
          'fonetik_mandarin' => 'Bāshí',
          'kategori' => 'Angka',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Sembilan Puluh',
          'bahasa_inggris' => 'Ninety',
          'fonetik' => 'nain-ti',
          'bahasa_arab' => 'تِسْعُونَ',
          'fonetik_arab' => 'Tisʿuna',
          'bahasa_mandarin' => '九十',
          'fonetik_mandarin' => 'Jiǔshí',
          'kategori' => 'Angka',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Seratus',
          'bahasa_inggris' => 'One hundred',
          'fonetik' => 'wan han-dred',
          'bahasa_arab' => 'مِائَةٌ',
          'fonetik_arab' => 'Miʾatun',
          'bahasa_mandarin' => '一百',
          'fonetik_mandarin' => 'Yībǎi',
          'kategori' => 'Angka',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Dua Ratus',
          'bahasa_inggris' => 'Two hundred',
          'fonetik' => 'tu han-dred',
          'bahasa_arab' => 'مِائَتَانِ',
          'fonetik_arab' => 'Miʾatāni',
          'bahasa_mandarin' => '两百',
          'fonetik_mandarin' => 'Liǎngbǎi',
          'kategori' => 'Angka',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Seribu',
          'bahasa_inggris' => 'One thousand',
          'fonetik' => 'wan thau-zend',
          'bahasa_arab' => 'أَلْفٌ',
          'fonetik_arab' => 'Alfun',
          'bahasa_mandarin' => '一千',
          'fonetik_mandarin' => 'Yīqiān',
          'kategori' => 'Angka',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Seratus Ribu',
          'bahasa_inggris' => 'One hundred thousand',
          'fonetik' => 'wan han-dred thau-zend',
          'bahasa_arab' => 'مِائَةُ أَلْفٍ',
          'fonetik_arab' => 'Miʾatu Alfin',
          'bahasa_mandarin' => '十万',
          'fonetik_mandarin' => 'Shíwàn',
          'kategori' => 'Angka',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Satu Juta',
          'bahasa_inggris' => 'One million',
          'fonetik' => 'wan mil-yen',
          'bahasa_arab' => 'مَلْيُونٌ',
          'fonetik_arab' => 'Malyūnún',
          'bahasa_mandarin' => '一百万',
          'fonetik_mandarin' => 'Yībǎiwàn',
          'kategori' => 'Angka',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Satu Miliar',
          'bahasa_inggris' => 'One billion',
          'fonetik' => 'wan mil-yerd',
          'bahasa_arab' => 'مِلْيَارٌ',
          'fonetik_arab' => 'Milyārun',
          'bahasa_mandarin' => '十亿',
          'fonetik_mandarin' => 'Shíyì',
          'kategori' => 'Angka',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Satu Triliun',
          'bahasa_inggris' => 'One trillion',
          'fonetik' => 'wan tril-yen',
          'bahasa_arab' => 'تِرِيليُونٌ',
          'fonetik_arab' => 'Trilyūnun',
          'bahasa_mandarin' => '一万亿',
          'fonetik_mandarin' => 'Yīwànyì',
          'kategori' => 'Angka',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Satu Kuadriliun',
          'bahasa_inggris' => 'One quadrillion',
          'fonetik' => 'wan kwod-ril-yen',
          'bahasa_arab' => 'كُوَادْرِيلِيُونٌ',
          'fonetik_arab' => 'Kūwādrilyūnun',
          'bahasa_mandarin' => '一千万亿',
          'fonetik_mandarin' => 'Yīqiānwànyì',
          'kategori' => 'Angka',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Satu Kuintiliun',
          'bahasa_inggris' => 'One quintillion',
          'fonetik' => 'wan kwin-til-yen',
          'bahasa_arab' => 'كُوِينْتِيلِيُونٌ',
          'fonetik_arab' => 'Kwīntilyūnun',
          'bahasa_mandarin' => '百京',
          'fonetik_mandarin' => 'Bǎijīng',
          'kategori' => 'Angka',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Setengah Miliar',
          'bahasa_inggris' => 'Half a billion',
          'fonetik' => 'haf e mil-yerd',
          'bahasa_arab' => 'نِصْفُ مِلْيَارٍ',
          'fonetik_arab' => 'Niṣfu Milyārin',
          'bahasa_mandarin' => '五亿',
          'fonetik_mandarin' => 'Wǔyì',
          'kategori' => 'Angka',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Sepuluh Ribu',
          'bahasa_inggris' => 'Ten thousand',
          'fonetik' => 'ten thau-zend',
          'bahasa_arab' => 'عَشَرَةُ آلَافٍ',
          'fonetik_arab' => 'ʿAsharatu Ālāfin',
          'bahasa_mandarin' => '一万',
          'fonetik_mandarin' => 'Yīwàn',
          'kategori' => 'Angka',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Setengah',
          'bahasa_inggris' => 'Half',
          'fonetik' => 'haf',
          'bahasa_arab' => 'نِصْفٌ',
          'fonetik_arab' => 'Niṣfun',
          'bahasa_mandarin' => '一半',
          'fonetik_mandarin' => 'Yībàn',
          'kategori' => 'Angka',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Sepertiga',
          'bahasa_inggris' => 'One third',
          'fonetik' => 'wan therd',
          'bahasa_arab' => 'ثُلُثٌ',
          'fonetik_arab' => 'Thuluthun',
          'bahasa_mandarin' => '三分之一',
          'fonetik_mandarin' => 'Sān fēn zhī yī',
          'kategori' => 'Angka',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Seperempat',
          'bahasa_inggris' => 'One quarter',
          'fonetik' => 'wan kwor-ter',
          'bahasa_arab' => 'رُبْعٌ',
          'fonetik_arab' => 'Rubʿun',
          'bahasa_mandarin' => '四分之一',
          'fonetik_mandarin' => 'Sì fēn zhī yī',
          'kategori' => 'Angka',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Seperlima',
          'bahasa_inggris' => 'One fifth',
          'fonetik' => 'wan fifth',
          'bahasa_arab' => 'خُمْسٌ',
          'fonetik_arab' => 'Khumsun',
          'bahasa_mandarin' => '五分之一',
          'fonetik_mandarin' => 'Wǔ fēn zhī yī',
          'kategori' => 'Angka',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Seperenam',
          'bahasa_inggris' => 'One sixth',
          'fonetik' => 'wan siksth',
          'bahasa_arab' => 'سُدُسٌ',
          'fonetik_arab' => 'Sudusun',
          'bahasa_mandarin' => '六分之一',
          'fonetik_mandarin' => 'Liù fēn zhī yī',
          'kategori' => 'Angka',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Sepersepuluh',
          'bahasa_inggris' => 'One tenth',
          'fonetik' => 'wan tenth',
          'bahasa_arab' => 'عُشْرٌ',
          'fonetik_arab' => 'ʿUshrun',
          'bahasa_mandarin' => '十分之一',
          'fonetik_mandarin' => 'Shí fēn zhī yī',
          'kategori' => 'Angka',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Dua Pertiga',
          'bahasa_inggris' => 'Two thirds',
          'fonetik' => 'tu therds',
          'bahasa_arab' => 'ثُلُثَانِ',
          'fonetik_arab' => 'Thuluthāni',
          'bahasa_mandarin' => '三分之二',
          'fonetik_mandarin' => 'Sān fēn zhī èr',
          'kategori' => 'Angka',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Tiga Perempat',
          'bahasa_inggris' => 'Three quarters',
          'fonetik' => 'thri kwor-terz',
          'bahasa_arab' => 'ثَلَاثَةُ أَرْبَاعٍ',
          'fonetik_arab' => 'Thalāthatu Arbāʿin',
          'bahasa_mandarin' => '四分之三',
          'fonetik_mandarin' => 'Sì fēn zhī sān',
          'kategori' => 'Angka',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Dua Perlima',
          'bahasa_inggris' => 'Two fifths',
          'fonetik' => 'tu fifths',
          'bahasa_arab' => 'خَمْسَانِ',
          'fonetik_arab' => 'Khumsāni',
          'bahasa_mandarin' => '五分之二',
          'fonetik_mandarin' => 'Wǔ fēn zhī èr',
          'kategori' => 'Angka',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Tiga Perlima',
          'bahasa_inggris' => 'Three fifths',
          'fonetik' => 'thri fifths',
          'bahasa_arab' => 'ثَلَاثَةُ أَخْمَاسٍ',
          'fonetik_arab' => 'Thalāthatu Akhmāsin',
          'bahasa_mandarin' => '五分之三',
          'fonetik_mandarin' => 'Wǔ fēn zhī sān',
          'kategori' => 'Angka',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Lima Perenam',
          'bahasa_inggris' => 'Five sixths',
          'fonetik' => 'faiv siksths',
          'bahasa_arab' => 'خَمْسَةُ أَسْدَاسٍ',
          'fonetik_arab' => 'Khamsatu Asdāsin',
          'bahasa_mandarin' => '六分之五',
          'fonetik_mandarin' => 'Liù fēn zhī wǔ',
          'kategori' => 'Angka',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Tujuh Persepuluh',
          'bahasa_inggris' => 'Seven tenths',
          'fonetik' => 'se-ven tenths',
          'bahasa_arab' => 'سَبْعَةُ أَعْشَارٍ',
          'fonetik_arab' => 'Sabʿatu Aʿshārin',
          'bahasa_mandarin' => '十分之七',
          'fonetik_mandarin' => 'Shí fēn zhī qī',
          'kategori' => 'Angka',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Tambah',
          'bahasa_inggris' => 'Plus',
          'fonetik' => 'plas',
          'bahasa_arab' => 'زَائِد',
          'fonetik_arab' => 'Zāʾid',
          'bahasa_mandarin' => '加',
          'fonetik_mandarin' => 'Jiā',
          'kategori' => 'Angka',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Kurang',
          'bahasa_inggris' => 'Minus',
          'fonetik' => 'mai-nes',
          'bahasa_arab' => 'نَاقِص',
          'fonetik_arab' => 'Nāqiṣ',
          'bahasa_mandarin' => '减',
          'fonetik_mandarin' => 'Jiǎn',
          'kategori' => 'Angka',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Kali',
          'bahasa_inggris' => 'Times',
          'fonetik' => 'taimz',
          'bahasa_arab' => 'فِى',
          'fonetik_arab' => 'Fī',
          'bahasa_mandarin' => '乘',
          'fonetik_mandarin' => 'Chéng',
          'kategori' => 'Angka',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Bagi',
          'bahasa_inggris' => 'Divided by',
          'fonetik' => 'di-vai-ded bai',
          'bahasa_arab' => 'عَلَى',
          'fonetik_arab' => 'ʿAlā',
          'bahasa_mandarin' => '除以',
          'fonetik_mandarin' => 'Chú yǐ',
          'kategori' => 'Angka',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Persen',
          'bahasa_inggris' => 'Percent',
          'fonetik' => 'per-sent',
          'bahasa_arab' => 'بِالْمِائَة',
          'fonetik_arab' => 'Bil-miʾah',
          'bahasa_mandarin' => '百分之',
          'fonetik_mandarin' => 'Bǎifēnzhī',
          'kategori' => 'Angka',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Sama Dengan',
          'bahasa_inggris' => 'Equals',
          'fonetik' => 'i-kwelz',
          'bahasa_arab' => 'يُسَاوِي',
          'fonetik_arab' => 'Yusāwī',
          'bahasa_mandarin' => '等于',
          'fonetik_mandarin' => 'Děngyú',
          'kategori' => 'Angka',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Pertama',
          'bahasa_inggris' => 'First',
          'fonetik' => 'ferst',
          'bahasa_arab' => 'أَوَّل',
          'fonetik_arab' => 'Awwal',
          'bahasa_mandarin' => '第一',
          'fonetik_mandarin' => 'Dì yī',
          'kategori' => 'Angka',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Kedua',
          'bahasa_inggris' => 'Second',
          'fonetik' => 'se-kend',
          'bahasa_arab' => 'ثَانِي',
          'fonetik_arab' => 'Thānī',
          'bahasa_mandarin' => '第二',
          'fonetik_mandarin' => 'Dì èr',
          'kategori' => 'Angka',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Ketiga',
          'bahasa_inggris' => 'Third',
          'fonetik' => 'therd',
          'bahasa_arab' => 'ثَالِث',
          'fonetik_arab' => 'Thālith',
          'bahasa_mandarin' => '第三',
          'fonetik_mandarin' => 'Dì sān',
          'kategori' => 'Angka',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Keempat',
          'bahasa_inggris' => 'Fourth',
          'fonetik' => 'forth',
          'bahasa_arab' => 'رَابِع',
          'fonetik_arab' => 'Rābiʿ',
          'bahasa_mandarin' => '第四',
          'fonetik_mandarin' => 'Dì sì',
          'kategori' => 'Angka',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Kelima',
          'bahasa_inggris' => 'Fifth',
          'fonetik' => 'fifth',
          'bahasa_arab' => 'خَامِس',
          'fonetik_arab' => 'Khāmis',
          'bahasa_mandarin' => '第五',
          'fonetik_mandarin' => 'Dì wǔ',
          'kategori' => 'Angka',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Keenam',
          'bahasa_inggris' => 'Sixth',
          'fonetik' => 'siksth',
          'bahasa_arab' => 'سَا دِس',
          'fonetik_arab' => 'Sādis',
          'bahasa_mandarin' => '第六',
          'fonetik_mandarin' => 'Dì liù',
          'kategori' => 'Angka',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Ketujuh',
          'bahasa_inggris' => 'Seventh',
          'fonetik' => 'se-venth',
          'bahasa_arab' => 'سَابِع',
          'fonetik_arab' => 'Sābiʿ',
          'bahasa_mandarin' => '第七',
          'fonetik_mandarin' => 'Dì qī',
          'kategori' => 'Angka',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Kedelapan',
          'bahasa_inggris' => 'Eighth',
          'fonetik' => 'eyth',
          'bahasa_arab' => 'ثَامِن',
          'fonetik_arab' => 'Thāmin',
          'bahasa_mandarin' => '第八',
          'fonetik_mandarin' => 'Bā',
          'kategori' => 'Angka',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Kesembilan',
          'bahasa_inggris' => 'Ninth',
          'fonetik' => 'nainth',
          'bahasa_arab' => 'تَاسِع',
          'fonetik_arab' => 'Tāsiʿ',
          'bahasa_mandarin' => '第九',
          'fonetik_mandarin' => 'Jiǔ',
          'kategori' => 'Angka',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Kesepuluh',
          'bahasa_inggris' => 'Tenth',
          'fonetik' => 'tenth',
          'bahasa_arab' => 'عَاشِر',
          'fonetik_arab' => 'ʿĀshir',
          'bahasa_mandarin' => '第十',
          'fonetik_mandarin' => 'Shí',
          'kategori' => 'Angka',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Ganda',
          'bahasa_inggris' => 'Double',
          'fonetik' => 'da-bel',
          'bahasa_arab' => 'مُضَاعَف',
          'fonetik_arab' => 'Muḍāʿaf',
          'bahasa_mandarin' => '双倍',
          'fonetik_mandarin' => 'Shuāngbèi',
          'kategori' => 'Angka',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Tiga Kali Lipat',
          'bahasa_inggris' => 'Triple',
          'fonetik' => 'tri-pel',
          'bahasa_arab' => 'ثَلَاثَةُ أَضْعَافٍ',
          'fonetik_arab' => 'Thalāthatu Aḍʿāfin',
          'bahasa_mandarin' => '三倍',
          'fonetik_mandarin' => 'Sānbèi',
          'kategori' => 'Angka',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Koma',
          'bahasa_inggris' => 'Point',
          'fonetik' => 'point',
          'bahasa_arab' => 'فَاصِلَة',
          'fonetik_arab' => 'Fāṣilah',
          'bahasa_mandarin' => '点',
          'fonetik_mandarin' => 'Diǎn',
          'kategori' => 'Angka',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Satu Setengah',
          'bahasa_inggris' => 'One and a half',
          'fonetik' => 'wan end e haf',
          'bahasa_arab' => 'وَاحِد وَنِصْف',
          'fonetik_arab' => 'Wāḥid wa Niṣf',
          'bahasa_mandarin' => '一又二分之一',
          'fonetik_mandarin' => 'Yī yòu èr fēn zhī yī',
          'kategori' => 'Angka',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Sepasang',
          'bahasa_inggris' => 'A pair',
          'fonetik' => 'e per',
          'bahasa_arab' => 'زَوْج',
          'fonetik_arab' => 'Zawj',
          'bahasa_mandarin' => '一双',
          'fonetik_mandarin' => 'Yī shuāng',
          'kategori' => 'Angka',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Selusin',
          'bahasa_inggris' => 'A dozen',
          'fonetik' => 'e da-zen',
          'bahasa_arab' => 'دَرْزَن',
          'fonetik_arab' => 'Darzan',
          'bahasa_mandarin' => '一打',
          'fonetik_mandarin' => 'Yī dá',
          'kategori' => 'Angka',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Sekali',
          'bahasa_inggris' => 'Once',
          'fonetik' => 'wans',
          'bahasa_arab' => 'مَرَّةً وَاحِدَةً',
          'fonetik_arab' => 'Marratan Wāḥidatan',
          'bahasa_mandarin' => '一次',
          'fonetik_mandarin' => 'Yī cì',
          'kategori' => 'Angka',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Dua Kali',
          'bahasa_inggris' => 'Twice',
          'fonetik' => 'twais',
          'bahasa_arab' => 'مَرَّتَيْنِ',
          'fonetik_arab' => 'Marratayani',
          'bahasa_mandarin' => '两次',
          'fonetik_mandarin' => 'Liǎng cì',
          'kategori' => 'Angka',
          'hari' => 13,
        ),
    );
  }
}