<?php

namespace Database\Seeders\Support\Game\Blueprints;

class BendadiRumah
{
    public static function defaultWords(): array
    {
        return [
          0 => 
          [
            'bahasa_indonesia' => 'Rumah',
            'bahasa_inggris' => 'House',
            'fonetik' => 'haus',
            'bahasa_arab' => 'بَيْتٌ',
            'fonetik_arab' => 'Baytun',
            'bahasa_mandarin' => '房子',
            'fonetik_mandarin' => 'Fángzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 1,
          ],
          1 => 
          [
            'bahasa_indonesia' => 'Pintu',
            'bahasa_inggris' => 'Door',
            'fonetik' => 'dor',
            'bahasa_arab' => 'بَابٌ',
            'fonetik_arab' => 'Bābún',
            'bahasa_mandarin' => '门',
            'fonetik_mandarin' => 'Mén',
            'kategori' => 'Benda di Rumah',
            'hari' => 1,
          ],
          2 => 
          [
            'bahasa_indonesia' => 'Jendela',
            'bahasa_inggris' => 'Window',
            'fonetik' => 'win-dou',
            'bahasa_arab' => 'نَافِذَةٌ',
            'fonetik_arab' => 'Nāfithatun',
            'bahasa_mandarin' => '窗户',
            'fonetik_mandarin' => 'Chuānghu',
            'kategori' => 'Benda di Rumah',
            'hari' => 1,
          ],
          3 => 
          [
            'bahasa_indonesia' => 'Kursi',
            'bahasa_inggris' => 'Chair',
            'fonetik' => 'cher',
            'bahasa_arab' => 'كُرْسِيٌ',
            'fonetik_arab' => 'Kursiyyun',
            'bahasa_mandarin' => '椅子',
            'fonetik_mandarin' => 'Yǐzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 1,
          ],
          4 => 
          [
            'bahasa_indonesia' => 'Meja',
            'bahasa_inggris' => 'Table',
            'fonetik' => 'tey-bel',
            'bahasa_arab' => 'طَاوِلَةٌ',
            'fonetik_arab' => 'Ṭāwīlatun',
            'bahasa_mandarin' => '桌子',
            'fonetik_mandarin' => 'Zhuōzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 1,
          ],
          5 => 
          [
            'bahasa_indonesia' => 'Tempat Tidur',
            'bahasa_inggris' => 'Bed',
            'fonetik' => 'bed',
            'bahasa_arab' => 'سَرِيرٌ',
            'fonetik_arab' => 'Sarīrun',
            'bahasa_mandarin' => '床',
            'fonetik_mandarin' => 'Chuáng',
            'kategori' => 'Benda di Rumah',
            'hari' => 1,
          ],
          6 => 
          [
            'bahasa_indonesia' => 'Lampu',
            'bahasa_inggris' => 'Lamp',
            'fonetik' => 'lemp',
            'bahasa_arab' => 'مِصْبَاحٌ',
            'fonetik_arab' => 'Miṣbāḥun',
            'bahasa_mandarin' => '灯',
            'fonetik_mandarin' => 'Dēng',
            'kategori' => 'Benda di Rumah',
            'hari' => 2,
          ],
          7 => 
          [
            'bahasa_indonesia' => 'Sofa',
            'bahasa_inggris' => 'Sofa',
            'fonetik' => 'sou-fa',
            'bahasa_arab' => 'أَرِيكَةٌ',
            'fonetik_arab' => 'Arīkatun',
            'bahasa_mandarin' => '沙发',
            'fonetik_mandarin' => 'Shāfā',
            'kategori' => 'Benda di Rumah',
            'hari' => 2,
          ],
          8 => 
          [
            'bahasa_indonesia' => 'Buku',
            'bahasa_inggris' => 'Book',
            'fonetik' => 'buk',
            'bahasa_arab' => 'كِتَابٌ',
            'fonetik_arab' => 'Kitābún',
            'bahasa_mandarin' => '书',
            'fonetik_mandarin' => 'Shū',
            'kategori' => 'Benda di Rumah',
            'hari' => 2,
          ],
          9 => 
          [
            'bahasa_indonesia' => 'Kunci',
            'bahasa_inggris' => 'Key',
            'fonetik' => 'ki',
            'bahasa_arab' => 'مِفْتَاحٌ',
            'fonetik_arab' => 'Miftāḥun',
            'bahasa_mandarin' => '钥匙',
            'fonetik_mandarin' => 'Yàoshi',
            'kategori' => 'Benda di Rumah',
            'hari' => 2,
          ],
          10 => 
          [
            'bahasa_indonesia' => 'Jam',
            'bahasa_inggris' => 'Clock',
            'fonetik' => 'klok',
            'bahasa_arab' => 'سَاعَةٌ',
            'fonetik_arab' => 'Sāʿatun',
            'bahasa_mandarin' => '钟',
            'fonetik_mandarin' => 'Zhōng',
            'kategori' => 'Benda di Rumah',
            'hari' => 2,
          ],
          11 => 
          [
            'bahasa_indonesia' => 'Telepon',
            'bahasa_inggris' => 'Phone',
            'fonetik' => 'foun',
            'bahasa_arab' => 'هَاتِفٌ',
            'fonetik_arab' => 'Hātifun',
            'bahasa_mandarin' => '电话',
            'fonetik_mandarin' => 'Diànhuà',
            'kategori' => 'Benda di Rumah',
            'hari' => 2,
          ],
          12 => 
          [
            'bahasa_indonesia' => 'Dapur',
            'bahasa_inggris' => 'Kitchen',
            'fonetik' => 'ki-cen',
            'bahasa_arab' => 'مَطْبَخٌ',
            'fonetik_arab' => 'Maṭbakhun',
            'bahasa_mandarin' => '厨房',
            'fonetik_mandarin' => 'Chúfáng',
            'kategori' => 'Benda di Rumah',
            'hari' => 3,
          ],
          13 => 
          [
            'bahasa_indonesia' => 'Kamar Mandi',
            'bahasa_inggris' => 'Bathroom',
            'fonetik' => 'bath-rum',
            'bahasa_arab' => 'حَمَّامٌ',
            'fonetik_arab' => 'Ḥammāmun',
            'bahasa_mandarin' => '浴室',
            'fonetik_mandarin' => 'Yùshì',
            'kategori' => 'Benda di Rumah',
            'hari' => 3,
          ],
          14 => 
          [
            'bahasa_indonesia' => 'Kamar Tidur',
            'bahasa_inggris' => 'Bedroom',
            'fonetik' => 'bed-rum',
            'bahasa_arab' => 'غُرْفَةُ نَوْمٍ',
            'fonetik_arab' => 'Ghurfatun Nawm',
            'bahasa_mandarin' => '卧室',
            'fonetik_mandarin' => 'Wòshì',
            'kategori' => 'Benda di Rumah',
            'hari' => 3,
          ],
          15 => 
          [
            'bahasa_indonesia' => 'Taman',
            'bahasa_inggris' => 'Garden',
            'fonetik' => 'gar-den',
            'bahasa_arab' => 'حَدِيقَةٌ',
            'fonetik_arab' => 'Ḥadīqatun',
            'bahasa_mandarin' => '花园',
            'fonetik_mandarin' => 'Huāyuán',
            'kategori' => 'Benda di Rumah',
            'hari' => 3,
          ],
          16 => 
          [
            'bahasa_indonesia' => 'Atap',
            'bahasa_inggris' => 'Roof',
            'fonetik' => 'ruf',
            'bahasa_arab' => 'سَقْفٌ',
            'fonetik_arab' => 'Saqfun',
            'bahasa_mandarin' => '屋顶',
            'fonetik_mandarin' => 'Wūdǐng',
            'kategori' => 'Benda di Rumah',
            'hari' => 3,
          ],
          17 => 
          [
            'bahasa_indonesia' => 'Lantai',
            'bahasa_inggris' => 'Floor',
            'fonetik' => 'flor',
            'bahasa_arab' => 'أَرْضِيَّةٌ',
            'fonetik_arab' => 'Arḍiyyah',
            'bahasa_mandarin' => '地板',
            'fonetik_mandarin' => 'Dìbǎn',
            'kategori' => 'Benda di Rumah',
            'hari' => 3,
          ],
          18 => 
          [
            'bahasa_indonesia' => 'Piring',
            'bahasa_inggris' => 'Plate',
            'fonetik' => 'pleyt',
            'bahasa_arab' => 'صَحْنٌ',
            'fonetik_arab' => 'Ṣaḥnun',
            'bahasa_mandarin' => '盘子',
            'fonetik_mandarin' => 'Pánzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 4,
          ],
          19 => 
          [
            'bahasa_indonesia' => 'Gelas',
            'bahasa_inggris' => 'Glass',
            'fonetik' => 'gles',
            'bahasa_arab' => 'كَأْسٌ',
            'fonetik_arab' => 'Kaʾsun',
            'bahasa_mandarin' => '玻璃杯',
            'fonetik_mandarin' => 'Bōlibēi',
            'kategori' => 'Benda di Rumah',
            'hari' => 4,
          ],
          20 => 
          [
            'bahasa_indonesia' => 'Garpu',
            'bahasa_inggris' => 'Fork',
            'fonetik' => 'fork',
            'bahasa_arab' => 'شَوْكَةٌ',
            'fonetik_arab' => 'Shawkatun',
            'bahasa_mandarin' => '叉子',
            'fonetik_mandarin' => 'Chāzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 4,
          ],
          21 => 
          [
            'bahasa_indonesia' => 'Sendok',
            'bahasa_inggris' => 'Spoon',
            'fonetik' => 'spun',
            'bahasa_arab' => 'مِلْعَقَةٌ',
            'fonetik_arab' => 'Milʿaqatun',
            'bahasa_mandarin' => '勺子',
            'fonetik_mandarin' => 'Sháozi',
            'kategori' => 'Benda di Rumah',
            'hari' => 4,
          ],
          22 => 
          [
            'bahasa_indonesia' => 'Pisau',
            'bahasa_inggris' => 'Knife',
            'fonetik' => 'naif',
            'bahasa_arab' => 'سِكِّينٌ',
            'fonetik_arab' => 'Sīkkīnun',
            'bahasa_mandarin' => '刀',
            'fonetik_mandarin' => 'Dāo',
            'kategori' => 'Benda di Rumah',
            'hari' => 4,
          ],
          23 => 
          [
            'bahasa_indonesia' => 'Mangkuk',
            'bahasa_inggris' => 'Bowl',
            'fonetik' => 'boul',
            'bahasa_arab' => 'وِعَاءٌ',
            'fonetik_arab' => 'Wiʿāʾun',
            'bahasa_mandarin' => '碗',
            'fonetik_mandarin' => 'Wǎn',
            'kategori' => 'Benda di Rumah',
            'hari' => 4,
          ],
          24 => 
          [
            'bahasa_indonesia' => 'Lemari',
            'bahasa_inggris' => 'Cabinet',
            'fonetik' => 'ka-bi-net',
            'bahasa_arab' => 'خِزَانَةٌ',
            'fonetik_arab' => 'Khizānatun',
            'bahasa_mandarin' => '柜子',
            'fonetik_mandarin' => 'Guìzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 5,
          ],
          25 => 
          [
            'bahasa_indonesia' => 'Bantal',
            'bahasa_inggris' => 'Pillow',
            'fonetik' => 'pi-lou',
            'bahasa_arab' => 'وِسَادَةٌ',
            'fonetik_arab' => 'Wisādatun',
            'bahasa_mandarin' => '枕头',
            'fonetik_mandarin' => 'Zhěntou',
            'kategori' => 'Benda di Rumah',
            'hari' => 5,
          ],
          26 => 
          [
            'bahasa_indonesia' => 'Cermin',
            'bahasa_inggris' => 'Mirror',
            'fonetik' => 'mi-rer',
            'bahasa_arab' => 'مِرْآةٌ',
            'fonetik_arab' => 'Mirʾātun',
            'bahasa_mandarin' => '镜子',
            'fonetik_mandarin' => 'Jìngzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 5,
          ],
          27 => 
          [
            'bahasa_indonesia' => 'Handuk',
            'bahasa_inggris' => 'Towel',
            'fonetik' => 'tau-wel',
            'bahasa_arab' => 'مَنْشَفَةٌ',
            'fonetik_arab' => 'Manshafatun',
            'bahasa_mandarin' => '毛巾',
            'fonetik_mandarin' => 'Máojīn',
            'kategori' => 'Benda di Rumah',
            'hari' => 5,
          ],
          28 => 
          [
            'bahasa_indonesia' => 'Sapu',
            'bahasa_inggris' => 'Broom',
            'fonetik' => 'brum',
            'bahasa_arab' => 'مِكْنَسَةٌ',
            'fonetik_arab' => 'Miknasatun',
            'bahasa_mandarin' => '扫帚',
            'fonetik_mandarin' => 'Sàozhou',
            'kategori' => 'Benda di Rumah',
            'hari' => 5,
          ],
          29 => 
          [
            'bahasa_indonesia' => 'Ember',
            'bahasa_inggris' => 'Bucket',
            'fonetik' => 'ba-ket',
            'bahasa_arab' => 'دَلْوٌ',
            'fonetik_arab' => 'Dalwun',
            'bahasa_mandarin' => '水桶',
            'fonetik_mandarin' => 'Shuǐtǒng',
            'kategori' => 'Benda di Rumah',
            'hari' => 5,
          ],
          30 => 
          [
            'bahasa_indonesia' => 'Televisi',
            'bahasa_inggris' => 'Television',
            'fonetik' => 'te-le-vi-syen',
            'bahasa_arab' => 'تِلْفَازٌ',
            'fonetik_arab' => 'Tilfāzún',
            'bahasa_mandarin' => '电视',
            'fonetik_mandarin' => 'Diànshì',
            'kategori' => 'Benda di Rumah',
            'hari' => 6,
          ],
          31 => 
          [
            'bahasa_indonesia' => 'Komputer',
            'bahasa_inggris' => 'Computer',
            'fonetik' => 'kem-pyu-ter',
            'bahasa_arab' => 'حَاسُوبٌ',
            'fonetik_arab' => 'Ḥāsūbun',
            'bahasa_mandarin' => '电脑',
            'fonetik_mandarin' => 'Diànnǎo',
            'kategori' => 'Benda di Rumah',
            'hari' => 6,
          ],
          32 => 
          [
            'bahasa_indonesia' => 'Radio',
            'bahasa_inggris' => 'Radio',
            'fonetik' => 'rey-di-o',
            'bahasa_arab' => 'رَادْيُو',
            'fonetik_arab' => 'Rādiyū',
            'bahasa_mandarin' => '收音机',
            'fonetik_mandarin' => 'Shōuyīnjī',
            'kategori' => 'Benda di Rumah',
            'hari' => 6,
          ],
          33 => 
          [
            'bahasa_indonesia' => 'Kamera',
            'bahasa_inggris' => 'Camera',
            'fonetik' => 'ke-me-ra',
            'bahasa_arab' => 'كَامِيرَا',
            'fonetik_arab' => 'Kāmīrā',
            'bahasa_mandarin' => '相机',
            'fonetik_mandarin' => 'Xiàngjī',
            'kategori' => 'Benda di Rumah',
            'hari' => 6,
          ],
          34 => 
          [
            'bahasa_indonesia' => 'Gambar',
            'bahasa_inggris' => 'Picture',
            'fonetik' => 'pik-cer',
            'bahasa_arab' => 'صُورَةٌ',
            'fonetik_arab' => 'Ṣūratun',
            'bahasa_mandarin' => '图片',
            'fonetik_mandarin' => 'Túpiàn',
            'kategori' => 'Benda di Rumah',
            'hari' => 6,
          ],
          35 => 
          [
            'bahasa_indonesia' => 'Vas',
            'bahasa_inggris' => 'Vase',
            'fonetik' => 'veys',
            'bahasa_arab' => 'مَزْهَرِيَّةٌ',
            'fonetik_arab' => 'Mazhariyyah',
            'bahasa_mandarin' => '花瓶',
            'fonetik_mandarin' => 'Huāpíng',
            'kategori' => 'Benda di Rumah',
            'hari' => 6,
          ],
          36 => 
          [
            'bahasa_indonesia' => 'Tangga',
            'bahasa_inggris' => 'Stairs',
            'fonetik' => 'sters',
            'bahasa_arab' => 'دَرَجٌ',
            'fonetik_arab' => 'Darajun',
            'bahasa_mandarin' => '楼梯',
            'fonetik_mandarin' => 'Lóutī',
            'kategori' => 'Benda di Rumah',
            'hari' => 7,
          ],
          37 => 
          [
            'bahasa_indonesia' => 'Dinding',
            'bahasa_inggris' => 'Wall',
            'fonetik' => 'wol',
            'bahasa_arab' => 'جِدَارٌ',
            'fonetik_arab' => 'Jidārun',
            'bahasa_mandarin' => '墙',
            'fonetik_mandarin' => 'Qiáng',
            'kategori' => 'Benda di Rumah',
            'hari' => 7,
          ],
          38 => 
          [
            'bahasa_indonesia' => 'Karpet',
            'bahasa_inggris' => 'Carpet',
            'fonetik' => 'kar-pet',
            'bahasa_arab' => 'سَجَّادَةٌ',
            'fonetik_arab' => 'Sajjādatun',
            'bahasa_mandarin' => '地毯',
            'fonetik_mandarin' => 'Dìtǎn',
            'kategori' => 'Benda di Rumah',
            'hari' => 7,
          ],
          39 => 
          [
            'bahasa_indonesia' => 'Gorden',
            'bahasa_inggris' => 'Curtain',
            'fonetik' => 'ker-ten',
            'bahasa_arab' => 'سِتَارَةٌ',
            'fonetik_arab' => 'Sitāratun',
            'bahasa_mandarin' => '窗帘',
            'fonetik_mandarin' => 'Chuānglián',
            'kategori' => 'Benda di Rumah',
            'hari' => 7,
          ],
          40 => 
          [
            'bahasa_indonesia' => 'Sabun',
            'bahasa_inggris' => 'Soap',
            'fonetik' => 'soup',
            'bahasa_arab' => 'صَابُونٌ',
            'fonetik_arab' => 'Ṣābūnún',
            'bahasa_mandarin' => '肥皂',
            'fonetik_mandarin' => 'Féizào',
            'kategori' => 'Benda di Rumah',
            'hari' => 7,
          ],
          41 => 
          [
            'bahasa_indonesia' => 'Sikat Gigi',
            'bahasa_inggris' => 'Toothbrush',
            'fonetik' => 'tuth-brash',
            'bahasa_arab' => 'فُرْشَاةُ أَسْنَانٍ',
            'fonetik_arab' => 'Furshātu Asnān',
            'bahasa_mandarin' => '牙刷',
            'fonetik_mandarin' => 'Yáshuā',
            'kategori' => 'Benda di Rumah',
            'hari' => 7,
          ],
          42 => 
          [
            'bahasa_indonesia' => 'Kulkas',
            'bahasa_inggris' => 'Refrigerator',
            'fonetik' => 're-fri-je-rey-ter',
            'bahasa_arab' => 'ثَلَّاجَةٌ',
            'fonetik_arab' => 'Thallājatun',
            'bahasa_mandarin' => '冰箱',
            'fonetik_mandarin' => 'Bīngxiāng',
            'kategori' => 'Benda di Rumah',
            'hari' => 8,
          ],
          43 => 
          [
            'bahasa_indonesia' => 'Mesin Cuci',
            'bahasa_inggris' => 'Washing machine',
            'fonetik' => 'wo-shing me-syin',
            'bahasa_arab' => 'غَسَّالَةٌ',
            'fonetik_arab' => 'Ghassālatun',
            'bahasa_mandarin' => '洗衣机',
            'fonetik_mandarin' => 'Xǐyījī',
            'kategori' => 'Benda di Rumah',
            'hari' => 8,
          ],
          44 => 
          [
            'bahasa_indonesia' => 'Kipas Angin',
            'bahasa_inggris' => 'Fan',
            'fonetik' => 'fen',
            'bahasa_arab' => 'مِرْوَحَةٌ',
            'fonetik_arab' => 'Mirwaḥatun',
            'bahasa_mandarin' => '风扇',
            'fonetik_mandarin' => 'Fēngshàn',
            'kategori' => 'Benda di Rumah',
            'hari' => 8,
          ],
          45 => 
          [
            'bahasa_indonesia' => 'Pendingin Ruangan',
            'bahasa_inggris' => 'Air conditioner',
            'fonetik' => 'er kon-di-syen-er',
            'bahasa_arab' => 'مُكَيِّفٌ',
            'fonetik_arab' => 'Mukayyifun',
            'bahasa_mandarin' => '空调',
            'fonetik_mandarin' => 'Kōngtiáo',
            'kategori' => 'Benda di Rumah',
            'hari' => 8,
          ],
          46 => 
          [
            'bahasa_indonesia' => 'Setrika',
            'bahasa_inggris' => 'Iron',
            'fonetik' => 'ai-yen',
            'bahasa_arab' => 'مِكْوَاةٌ',
            'fonetik_arab' => 'Mikwātun',
            'bahasa_mandarin' => '熨斗',
            'fonetik_mandarin' => 'Yùndǒu',
            'kategori' => 'Benda di Rumah',
            'hari' => 8,
          ],
          47 => 
          [
            'bahasa_indonesia' => 'Penyedot Debu',
            'bahasa_inggris' => 'Vacuum cleaner',
            'fonetik' => 'va-kyum kli-ner',
            'bahasa_arab' => 'مِكْنَسَةٌ كَهْرَبَائِيَّةٌ',
            'fonetik_arab' => 'Miknasatun Kahrabāʾiyyah',
            'bahasa_mandarin' => '吸尘器',
            'fonetik_mandarin' => 'Xīchénqì',
            'kategori' => 'Benda di Rumah',
            'hari' => 8,
          ],
          48 => 
          [
            'bahasa_indonesia' => 'Teko',
            'bahasa_inggris' => 'Kettle',
            'fonetik' => 'ke-tel',
            'bahasa_arab' => 'غَلَّايَةٌ',
            'fonetik_arab' => 'Ghallāyatun',
            'bahasa_mandarin' => '水壶',
            'fonetik_mandarin' => 'Shuǐhú',
            'kategori' => 'Benda di Rumah',
            'hari' => 9,
          ],
          49 => 
          [
            'bahasa_indonesia' => 'Kompor',
            'bahasa_inggris' => 'Stove',
            'fonetik' => 'stouv',
            'bahasa_arab' => 'مَوْقِدٌ',
            'fonetik_arab' => 'Mawqidun',
            'bahasa_mandarin' => '炉灶',
            'fonetik_mandarin' => 'Lúzào',
            'kategori' => 'Benda di Rumah',
            'hari' => 9,
          ],
          50 => 
          [
            'bahasa_indonesia' => 'Oven',
            'bahasa_inggris' => 'Oven',
            'fonetik' => 'o-ven',
            'bahasa_arab' => 'فُرْنٌ',
            'fonetik_arab' => 'Furnun',
            'bahasa_mandarin' => '烤箱',
            'fonetik_mandarin' => 'Kǎoxiāng',
            'kategori' => 'Benda di Rumah',
            'hari' => 9,
          ],
          51 => 
          [
            'bahasa_indonesia' => 'Microwave',
            'bahasa_inggris' => 'Microwave',
            'fonetik' => 'mai-kro-weyv',
            'bahasa_arab' => 'مَيكرُووِيف',
            'fonetik_arab' => 'Māykrūwīf',
            'bahasa_mandarin' => '微波炉',
            'fonetik_mandarin' => 'Wēibōlú',
            'kategori' => 'Benda di Rumah',
            'hari' => 9,
          ],
          52 => 
          [
            'bahasa_indonesia' => 'Pemanggang Roti',
            'bahasa_inggris' => 'Toaster',
            'fonetik' => 'tous-ter',
            'bahasa_arab' => 'مُحَمِّصَةُ خُبْزٍ',
            'fonetik_arab' => 'Muḥammiṣatu Khubz',
            'bahasa_mandarin' => '烤面包机',
            'fonetik_mandarin' => 'Kǎomiànbāojī',
            'kategori' => 'Benda di Rumah',
            'hari' => 9,
          ],
          53 => 
          [
            'bahasa_indonesia' => 'Blender',
            'bahasa_inggris' => 'Blender',
            'fonetik' => 'blen-der',
            'bahasa_arab' => 'خَلَّاطٌ',
            'fonetik_arab' => 'Khallāṭun',
            'bahasa_mandarin' => '搅拌机',
            'fonetik_mandarin' => 'Jiǎobànjī',
            'kategori' => 'Benda di Rumah',
            'hari' => 9,
          ],
          54 => 
          [
            'bahasa_indonesia' => 'Pasta Gigi',
            'bahasa_inggris' => 'Toothpaste',
            'fonetik' => 'tuth-peyst',
            'bahasa_arab' => 'مَعْجُونُ أَسْنَانٍ',
            'fonetik_arab' => 'Maʿjūnu Asnān',
            'bahasa_mandarin' => '牙膏',
            'fonetik_mandarin' => 'Yágāo',
            'kategori' => 'Benda di Rumah',
            'hari' => 10,
          ],
          55 => 
          [
            'bahasa_indonesia' => 'Sampo',
            'bahasa_inggris' => 'Shampoo',
            'fonetik' => 'syem-pu',
            'bahasa_arab' => 'شَامْبُو',
            'fonetik_arab' => 'Shāmbū',
            'bahasa_mandarin' => '洗发水',
            'fonetik_mandarin' => 'Xǐfàshuǐ',
            'kategori' => 'Benda di Rumah',
            'hari' => 10,
          ],
          56 => 
          [
            'bahasa_indonesia' => 'Pancuran',
            'bahasa_inggris' => 'Shower',
            'fonetik' => 'syau-wer',
            'bahasa_arab' => 'دُشٌّ',
            'fonetik_arab' => 'Dushshun',
            'bahasa_mandarin' => '淋浴',
            'fonetik_mandarin' => 'Línyù',
            'kategori' => 'Benda di Rumah',
            'hari' => 10,
          ],
          57 => 
          [
            'bahasa_indonesia' => 'Bak Mandi',
            'bahasa_inggris' => 'Bathtub',
            'fonetik' => 'bath-tab',
            'bahasa_arab' => 'حَوْضُ اسْتِحْمَامٍ',
            'fonetik_arab' => 'Ḥawḍu Istiḥmām',
            'bahasa_mandarin' => '浴缸',
            'fonetik_mandarin' => 'Yùgāng',
            'kategori' => 'Benda di Rumah',
            'hari' => 10,
          ],
          58 => 
          [
            'bahasa_indonesia' => 'Keran',
            'bahasa_inggris' => 'Faucet',
            'fonetik' => 'fo-set',
            'bahasa_arab' => 'حَنَفِيَّةٌ',
            'fonetik_arab' => 'Ḥanafiyyatun',
            'bahasa_mandarin' => '水龙头',
            'fonetik_mandarin' => 'Shuǐlóngtóu',
            'kategori' => 'Benda di Rumah',
            'hari' => 10,
          ],
          59 => 
          [
            'bahasa_indonesia' => 'Keset',
            'bahasa_inggris' => 'Doormat',
            'fonetik' => 'dor-met',
            'bahasa_arab' => 'مِمْسَحَةُ أَرْجُلٍ',
            'fonetik_arab' => 'Mimsāḥatu Arjul',
            'bahasa_mandarin' => '门垫',
            'fonetik_mandarin' => 'Méndiàn',
            'kategori' => 'Benda di Rumah',
            'hari' => 10,
          ],
          60 => 
          [
            'bahasa_indonesia' => 'Lemari Pakaian',
            'bahasa_inggris' => 'Wardrobe',
            'fonetik' => 'wor-droub',
            'bahasa_arab' => 'خِزَانَةُ مَلَابِسَ',
            'fonetik_arab' => 'Khizānatu Malābis',
            'bahasa_mandarin' => '衣柜',
            'fonetik_mandarin' => 'Yīguì',
            'kategori' => 'Benda di Rumah',
            'hari' => 11,
          ],
          61 => 
          [
            'bahasa_indonesia' => 'Gantungan Baju',
            'bahasa_inggris' => 'Hanger',
            'fonetik' => 'heng-er',
            'bahasa_arab' => 'عَلَّاقَةُ مَلَابِسَ',
            'fonetik_arab' => 'ʿAllāqatu Malābis',
            'bahasa_mandarin' => '衣架',
            'fonetik_mandarin' => 'Yījià',
            'kategori' => 'Benda di Rumah',
            'hari' => 11,
          ],
          62 => 
          [
            'bahasa_indonesia' => 'Selimut',
            'bahasa_inggris' => 'Blanket',
            'fonetik' => 'bleng-ket',
            'bahasa_arab' => 'بَطَّانِيَّةٌ',
            'fonetik_arab' => 'Baṭṭāniyyatun',
            'bahasa_mandarin' => '毯子',
            'fonetik_mandarin' => 'Tǎnzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 11,
          ],
          63 => 
          [
            'bahasa_indonesia' => 'Sprei',
            'bahasa_inggris' => 'Bed sheet',
            'fonetik' => 'bed syit',
            'bahasa_arab' => 'شَرْشَفٌ',
            'fonetik_arab' => 'Sharshafun',
            'bahasa_mandarin' => '床单',
            'fonetik_mandarin' => 'Chuángdān',
            'kategori' => 'Benda di Rumah',
            'hari' => 11,
          ],
          64 => 
          [
            'bahasa_indonesia' => 'Sisir',
            'bahasa_inggris' => 'Comb',
            'fonetik' => 'koum',
            'bahasa_arab' => 'مُشْطٌ',
            'fonetik_arab' => 'Mushṭun',
            'bahasa_mandarin' => '梳子',
            'fonetik_mandarin' => 'Shūzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 11,
          ],
          65 => 
          [
            'bahasa_indonesia' => 'Pengering Rambut',
            'bahasa_inggris' => 'Hairdryer',
            'fonetik' => 'her-drai-er',
            'bahasa_arab' => 'مُجَفِّفُ شَعْرٍ',
            'fonetik_arab' => 'Mujaffifu Shaʿr',
            'bahasa_mandarin' => '吹风机',
            'fonetik_mandarin' => 'Chuīfēngjī',
            'kategori' => 'Benda di Rumah',
            'hari' => 11,
          ],
          66 => 
          [
            'bahasa_indonesia' => 'Gunting',
            'bahasa_inggris' => 'Scissors',
            'fonetik' => 'si-zerz',
            'bahasa_arab' => 'مِقَصٌّ',
            'fonetik_arab' => 'Miqaṣṣun',
            'bahasa_mandarin' => '剪刀',
            'fonetik_mandarin' => 'Jiǎndāo',
            'kategori' => 'Benda di Rumah',
            'hari' => 12,
          ],
          67 => 
          [
            'bahasa_indonesia' => 'Palu',
            'bahasa_inggris' => 'Hammer',
            'fonetik' => 'he-mer',
            'bahasa_arab' => 'مِطْرَقَةٌ',
            'fonetik_arab' => 'Miṭraqatun',
            'bahasa_mandarin' => '锤子',
            'fonetik_mandarin' => 'Chuízi',
            'kategori' => 'Benda di Rumah',
            'hari' => 12,
          ],
          68 => 
          [
            'bahasa_indonesia' => 'Obeng',
            'bahasa_inggris' => 'Screwdriver',
            'fonetik' => 'skru-drai-ver',
            'bahasa_arab' => 'مِفَكُّ بَرَاغِي',
            'fonetik_arab' => 'Mifakku Barāghī',
            'bahasa_mandarin' => '螺丝刀',
            'fonetik_mandarin' => 'Luósīdāo',
            'kategori' => 'Benda di Rumah',
            'hari' => 12,
          ],
          69 => 
          [
            'bahasa_indonesia' => 'Tang',
            'bahasa_inggris' => 'Pliers',
            'fonetik' => 'plai-erz',
            'bahasa_arab' => 'زَرَدِيَّةٌ',
            'fonetik_arab' => 'Zaradiyyatun',
            'bahasa_mandarin' => '老虎钳',
            'fonetik_mandarin' => 'Lǎohǔqián',
            'kategori' => 'Benda di Rumah',
            'hari' => 12,
          ],
          70 => 
          [
            'bahasa_indonesia' => 'Meteran',
            'bahasa_inggris' => 'Tape measure',
            'fonetik' => 'teyp me-syer',
            'bahasa_arab' => 'شَرِيطُ قِيَاسٍ',
            'fonetik_arab' => 'Sharīṭu Qiyās',
            'bahasa_mandarin' => '卷尺',
            'fonetik_mandarin' => 'Juǎnchǐ',
            'kategori' => 'Benda di Rumah',
            'hari' => 12,
          ],
          71 => 
          [
            'bahasa_indonesia' => 'Tangga Lipat',
            'bahasa_inggris' => 'Ladder',
            'fonetik' => 'le-der',
            'bahasa_arab' => 'سُلَّمٌ',
            'fonetik_arab' => 'Sullamun',
            'bahasa_mandarin' => '梯子',
            'fonetik_mandarin' => 'Tīzi',
            'kategori' => 'Benda di Rumah',
            'hari' => 12,
          ],
          72 => 
          [
            'bahasa_indonesia' => 'Tas',
            'bahasa_inggris' => 'Bag',
            'fonetik' => 'beg',
            'bahasa_arab' => 'حَقِيبَةٌ',
            'fonetik_arab' => 'Ḥaqībatun',
            'bahasa_mandarin' => '包',
            'fonetik_mandarin' => 'Bāo',
            'kategori' => 'Benda di Rumah',
            'hari' => 13,
          ],
          73 => 
          [
            'bahasa_indonesia' => 'Dompet',
            'bahasa_inggris' => 'Wallet',
            'fonetik' => 'wo-let',
            'bahasa_arab' => 'مِحْفَظَةٌ',
            'fonetik_arab' => 'Miḥfaẓatun',
            'bahasa_mandarin' => '钱包',
            'fonetik_mandarin' => 'Qiánbāo',
            'kategori' => 'Benda di Rumah',
            'hari' => 13,
          ],
          74 => 
          [
            'bahasa_indonesia' => 'Payung',
            'bahasa_inggris' => 'Umbrella',
            'fonetik' => 'am-bre-la',
            'bahasa_arab' => 'مِظَلَّةٌ',
            'fonetik_arab' => 'Miẓallatun',
            'bahasa_mandarin' => '雨伞',
            'fonetik_mandarin' => 'Yǔsǎn',
            'kategori' => 'Benda di Rumah',
            'hari' => 13,
          ],
          75 => 
          [
            'bahasa_indonesia' => 'Kacamata',
            'bahasa_inggris' => 'Glasses',
            'fonetik' => 'gla-sez',
            'bahasa_arab' => 'نَظَّارَةٌ',
            'fonetik_arab' => 'Naẓẓāratun',
            'bahasa_mandarin' => '眼镜',
            'fonetik_mandarin' => 'Yǎnjìng',
            'kategori' => 'Benda di Rumah',
            'hari' => 13,
          ],
          76 => 
          [
            'bahasa_indonesia' => 'Jam Tangan',
            'bahasa_inggris' => 'Watch',
            'fonetik' => 'woc',
            'bahasa_arab' => 'سَاعَةُ يَدٍ',
            'fonetik_arab' => 'Sāʿatu Yad',
            'bahasa_mandarin' => '手表',
            'fonetik_mandarin' => 'Shǒubiǎo',
            'kategori' => 'Benda di Rumah',
            'hari' => 13,
          ],
          77 => 
          [
            'bahasa_indonesia' => 'Korek Api',
            'bahasa_inggris' => 'Lighter',
            'fonetik' => 'lai-ter',
            'bahasa_arab' => 'وَلَّاعَةٌ',
            'fonetik_arab' => 'Wallāʿatun',
            'bahasa_mandarin' => '打火机',
            'fonetik_mandarin' => 'Dǎhuǒjī',
            'kategori' => 'Benda di Rumah',
            'hari' => 13,
          ],
        ];
    }
}
