<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Bentuk
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Lingkaran',
          'bahasa_inggris' => 'Circle',
          'fonetik' => 'ser-kel',
          'bahasa_arab' => 'دَائِرَةٌ',
          'fonetik_arab' => 'Dāʾiratun',
          'bahasa_mandarin' => '圆形',
          'fonetik_mandarin' => 'Yuánxíng',
          'kategori' => 'Bentuk',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Persegi',
          'bahasa_inggris' => 'Square',
          'fonetik' => 'skwer',
          'bahasa_arab' => 'مُرَبَّعٌ',
          'fonetik_arab' => 'Murabbaʿun',
          'bahasa_mandarin' => '正方形',
          'fonetik_mandarin' => 'Zhèngfāngxíng',
          'kategori' => 'Bentuk',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Segitiga',
          'bahasa_inggris' => 'Triangle',
          'fonetik' => 'trai-eng-gel',
          'bahasa_arab' => 'مُثَلَّثٌ',
          'fonetik_arab' => 'Muthallathun',
          'bahasa_mandarin' => '三角形',
          'fonetik_mandarin' => 'Sānjiǎoxíng',
          'kategori' => 'Bentuk',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Hati',
          'bahasa_inggris' => 'Heart',
          'fonetik' => 'hart',
          'bahasa_arab' => 'قَلْبٌ',
          'fonetik_arab' => 'Qalbún',
          'bahasa_mandarin' => '心形',
          'fonetik_mandarin' => 'Xīnxíng',
          'kategori' => 'Bentuk',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Persegi Panjang',
          'bahasa_inggris' => 'Rectangle',
          'fonetik' => 'rek-teng-gel',
          'bahasa_arab' => 'مُسْتَطِيلٌ',
          'fonetik_arab' => 'Mustaṭīlun',
          'bahasa_mandarin' => '长方形',
          'fonetik_mandarin' => 'Chángfāngxíng',
          'kategori' => 'Bentuk',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Garis',
          'bahasa_inggris' => 'Line',
          'fonetik' => 'lain',
          'bahasa_arab' => 'خَطٌّ',
          'fonetik_arab' => 'Khaṭṭun',
          'bahasa_mandarin' => '线条',
          'fonetik_mandarin' => 'Xiàntiáo',
          'kategori' => 'Bentuk',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Oval',
          'bahasa_inggris' => 'Oval',
          'fonetik' => 'o-val',
          'bahasa_arab' => 'بَيْضَاوِيٌّ',
          'fonetik_arab' => 'Bayḍāwīyun',
          'bahasa_mandarin' => '椭圆形',
          'fonetik_mandarin' => 'Tuǒyuánxíng',
          'kategori' => 'Bentuk',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Berlian',
          'bahasa_inggris' => 'Diamond',
          'fonetik' => 'dai-mend',
          'bahasa_arab' => 'مُعَيَّنٌ',
          'fonetik_arab' => 'Muʿayyanun',
          'bahasa_mandarin' => '菱形',
          'fonetik_mandarin' => 'Língxíng',
          'kategori' => 'Bentuk',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Panah',
          'bahasa_inggris' => 'Arrow',
          'fonetik' => 'e-rou',
          'bahasa_arab' => 'سَهْمٌ',
          'fonetik_arab' => 'Sahmun',
          'bahasa_mandarin' => '箭头',
          'fonetik_mandarin' => 'Jiàntóu',
          'kategori' => 'Bentuk',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Bulan Sabit',
          'bahasa_inggris' => 'Crescent',
          'fonetik' => 'kre-sent',
          'bahasa_arab' => 'هِلَالٌ',
          'fonetik_arab' => 'Hilālun',
          'bahasa_mandarin' => '新月形',
          'fonetik_mandarin' => 'Xīnyuèxíng',
          'kategori' => 'Bentuk',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Kubus',
          'bahasa_inggris' => 'Cube',
          'fonetik' => 'kyub',
          'bahasa_arab' => 'مُكَعَّبٌ',
          'fonetik_arab' => 'Mukaʿʿabun',
          'bahasa_mandarin' => '立方体',
          'fonetik_mandarin' => 'Lìfāngtǐ',
          'kategori' => 'Bentuk',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Silinder',
          'bahasa_inggris' => 'Cylinder',
          'fonetik' => 'si-lin-der',
          'bahasa_arab' => 'أُسْطُوَانَةٌ',
          'fonetik_arab' => 'Usṭuwānatun',
          'bahasa_mandarin' => '圆柱体',
          'fonetik_mandarin' => 'Yuánzhùtǐ',
          'kategori' => 'Bentuk',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Kerucut',
          'bahasa_inggris' => 'Cone',
          'fonetik' => 'koun',
          'bahasa_arab' => 'مَخْرُوطٌ',
          'fonetik_arab' => 'Makhrūṭun',
          'bahasa_mandarin' => '圆锥体',
          'fonetik_mandarin' => 'Yuánzhuītǐ',
          'kategori' => 'Bentuk',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Bola',
          'bahasa_inggris' => 'Sphere',
          'fonetik' => 'sfir',
          'bahasa_arab' => 'كُرَةٌ',
          'fonetik_arab' => 'Kuratun',
          'bahasa_mandarin' => '球体',
          'fonetik_mandarin' => 'Qiútǐ',
          'kategori' => 'Bentuk',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Piramida',
          'bahasa_inggris' => 'Pyramid',
          'fonetik' => 'pi-ra-mid',
          'bahasa_arab' => 'هَرَمٌ',
          'fonetik_arab' => 'Haramun',
          'bahasa_mandarin' => '金字塔形',
          'fonetik_mandarin' => 'Jīnzìtǎxíng',
          'kategori' => 'Bentuk',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Segi Lima',
          'bahasa_inggris' => 'Pentagon',
          'fonetik' => 'pen-ta-gon',
          'bahasa_arab' => 'مُخَمَّسٌ',
          'fonetik_arab' => 'Mukhammasun',
          'bahasa_mandarin' => '五边形',
          'fonetik_mandarin' => 'Wǔbiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Segi Enam',
          'bahasa_inggris' => 'Hexagon',
          'fonetik' => 'hek-sa-gon',
          'bahasa_arab' => 'مُسَدَّسٌ',
          'fonetik_arab' => 'Musaddasún',
          'bahasa_mandarin' => '六边形',
          'fonetik_mandarin' => 'Liùbiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Salib',
          'bahasa_inggris' => 'Cross',
          'fonetik' => 'kros',
          'bahasa_arab' => 'صَلِيبٌ',
          'fonetik_arab' => 'Ṣalībún',
          'bahasa_mandarin' => '十字形',
          'fonetik_mandarin' => 'Shízìxíng',
          'kategori' => 'Bentuk',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Trapesium',
          'bahasa_inggris' => 'Trapezoid',
          'fonetik' => 'tre-pe-zoid',
          'bahasa_arab' => 'شِبْهُ مُنْحَرِفٍ',
          'fonetik_arab' => 'Shibhu Munḥarifin',
          'bahasa_mandarin' => '梯形',
          'fonetik_mandarin' => 'Tīxíng',
          'kategori' => 'Bentuk',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Jajar Genjang',
          'bahasa_inggris' => 'Parallelogram',
          'fonetik' => 'pe-ra-le-lo-grem',
          'bahasa_arab' => 'مُتَوَازِي أَضْلَاعٍ',
          'fonetik_arab' => 'Mutawāzī Aḍlāʿin',
          'bahasa_mandarin' => '平行四边形',
          'fonetik_mandarin' => 'Píngxíng sìbiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Belah Ketupat',
          'bahasa_inggris' => 'Rhombus',
          'fonetik' => 'rom-bes',
          'bahasa_arab' => 'مُعَيَّنٌ',
          'fonetik_arab' => 'Muʿayyanun',
          'bahasa_mandarin' => '菱形',
          'fonetik_mandarin' => 'Língxíng',
          'kategori' => 'Bentuk',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Elips',
          'bahasa_inggris' => 'Ellipse',
          'fonetik' => 'i-lips',
          'bahasa_arab' => 'شَكْلٌ بَيْضَاوِيٌّ',
          'fonetik_arab' => 'Shaklun Bayḍāwīyun',
          'bahasa_mandarin' => '椭圆形',
          'fonetik_mandarin' => 'Tuǒyuánxíng',
          'kategori' => 'Bentuk',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Setengah Lingkaran',
          'bahasa_inggris' => 'Semicircle',
          'fonetik' => 'se-mi-ser-kel',
          'bahasa_arab' => 'نِصْفُ دَائِرَةٍ',
          'fonetik_arab' => 'Niṣfu Dāʾiratin',
          'bahasa_mandarin' => '半圆形',
          'fonetik_mandarin' => 'Bányuánxíng',
          'kategori' => 'Bentuk',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Juring',
          'bahasa_inggris' => 'Sector',
          'fonetik' => 'sek-ter',
          'bahasa_arab' => 'قِطَاعٌ دَائِرِيٌّ',
          'fonetik_arab' => 'Qiṭāʿun Dāʾirīyun',
          'bahasa_mandarin' => '扇形',
          'fonetik_mandarin' => 'Shànxíng',
          'kategori' => 'Bentuk',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Prisma',
          'bahasa_inggris' => 'Prism',
          'fonetik' => 'pri-zem',
          'bahasa_arab' => 'مَنْشُورٌ',
          'fonetik_arab' => 'Manshūrun',
          'bahasa_mandarin' => '棱柱',
          'fonetik_mandarin' => 'Léngzhù',
          'kategori' => 'Bentuk',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Tetrahedron',
          'bahasa_inggris' => 'Tetrahedron',
          'fonetik' => 'tet-ra-hi-dron',
          'bahasa_arab' => 'رَبَاعِيُّ الأَوْجُهِي',
          'fonetik_arab' => 'Rabāʿī al-Awjuhi',
          'bahasa_mandarin' => '四面体',
          'fonetik_mandarin' => 'Sìmiàntǐ',
          'kategori' => 'Bentuk',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Octahedron',
          'bahasa_inggris' => 'Octahedron',
          'fonetik' => 'ok-ta-hi-dron',
          'bahasa_arab' => 'ثَمَانِيُّ الأَوْجُهِي',
          'fonetik_arab' => 'Thamānī al-Awjuhi',
          'bahasa_mandarin' => '八面体',
          'fonetik_mandarin' => 'Bāmiàntǐ',
          'kategori' => 'Bentuk',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Dodecahedron',
          'bahasa_inggris' => 'Dodecahedron',
          'fonetik' => 'dou-dek-a-hi-dron',
          'bahasa_arab' => 'اثْنَا عَشَرِيُّ الأَوْجُهِي',
          'fonetik_arab' => 'Ithnā ʿAsharī al-Awjuhi',
          'bahasa_mandarin' => '十二面体',
          'fonetik_mandarin' => 'Shí\'èr miàntǐ',
          'kategori' => 'Bentuk',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Icosahedron',
          'bahasa_inggris' => 'Icosahedron',
          'fonetik' => 'ai-ko-sa-hi-dron',
          'bahasa_arab' => 'عِشْرُونِيُّ الأَوْجُهِي',
          'fonetik_arab' => 'ʿIshrūnī al-Awjuhi',
          'bahasa_mandarin' => '二十面体',
          'fonetik_mandarin' => 'Èrshí miàntǐ',
          'kategori' => 'Bentuk',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Torus',
          'bahasa_inggris' => 'Torus',
          'fonetik' => 'to-res',
          'bahasa_arab' => 'حَلَقَةٌ',
          'fonetik_arab' => 'Ḥalaqatun',
          'bahasa_mandarin' => '圆环体',
          'fonetik_mandarin' => 'Yuánhuántǐ',
          'kategori' => 'Bentuk',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Segi Tujuh',
          'bahasa_inggris' => 'Heptagon',
          'fonetik' => 'hep-ta-gon',
          'bahasa_arab' => 'مُسَبَّعٌ',
          'fonetik_arab' => 'Musabbaʿun',
          'bahasa_mandarin' => '七边形',
          'fonetik_mandarin' => 'Qībiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Segi Delapan',
          'bahasa_inggris' => 'Octagon',
          'fonetik' => 'ok-ta-gon',
          'bahasa_arab' => 'مُثَمَّنٌ',
          'fonetik_arab' => 'Muthammanun',
          'bahasa_mandarin' => '八边形',
          'fonetik_mandarin' => 'Bābiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Segi Sembilan',
          'bahasa_inggris' => 'Nonagon',
          'fonetik' => 'no-na-gon',
          'bahasa_arab' => 'تُسَاعِيُّ الأَضْلَاعِ',
          'fonetik_arab' => 'Tusāʿī al-Aḍlāʿi',
          'bahasa_mandarin' => '九边形',
          'fonetik_mandarin' => 'Jiǔbiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Segi Sepuluh',
          'bahasa_inggris' => 'Decagon',
          'fonetik' => 'de-ka-gon',
          'bahasa_arab' => 'عُشَارِيُّ الأَضْلَاعِ',
          'fonetik_arab' => 'ʿUshārī al-Aḍlāʿi',
          'bahasa_mandarin' => '十边形',
          'fonetik_mandarin' => 'Shíbiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Segi Sebelas',
          'bahasa_inggris' => 'Hendecagon',
          'fonetik' => 'hen-de-ka-gon',
          'bahasa_arab' => 'أَحَدَ عَشَرِيُّ الأَضْلَاعِ',
          'fonetik_arab' => 'Aḥada ʿAsharī al-Aḍlāʿi',
          'bahasa_mandarin' => '十一边形',
          'fonetik_mandarin' => 'Shíyībiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Segi Dua Belas',
          'bahasa_inggris' => 'Dodecagon',
          'fonetik' => 'dou-de-ka-gon',
          'bahasa_arab' => 'اثْنَا عَشَرِيُّ الأَضْلَاعِ',
          'fonetik_arab' => 'Ithnā ʿAsharī al-Aḍlāʿi',
          'bahasa_mandarin' => '十二边形',
          'fonetik_mandarin' => 'Shí\'èrbiānxíng',
          'kategori' => 'Bentuk',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Garis Mendatar',
          'bahasa_inggris' => 'Horizontal line',
          'fonetik' => 'ho-ri-zon-tel lain',
          'bahasa_arab' => 'خَطٌّ أُفُقِيٌّ',
          'fonetik_arab' => 'Khaṭṭun Ufuqīyun',
          'bahasa_mandarin' => '水平线',
          'fonetik_mandarin' => 'Shuǐpíngxiàn',
          'kategori' => 'Bentuk',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Garis Tegak',
          'bahasa_inggris' => 'Vertical line',
          'fonetik' => 'ver-ti-kel lain',
          'bahasa_arab' => 'خَطٌّ عَمُودِيٌّ',
          'fonetik_arab' => 'Khaṭṭun ʿAmūdīyun',
          'bahasa_mandarin' => '垂直线',
          'fonetik_mandarin' => 'Chuízhíxiàn',
          'kategori' => 'Bentuk',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Garis Miring',
          'bahasa_inggris' => 'Diagonal line',
          'fonetik' => 'dai-a-go-nel lain',
          'bahasa_arab' => 'خَطٌّ قُطْرِيٌّ',
          'fonetik_arab' => 'Khaṭṭun Quṭrīyun',
          'bahasa_mandarin' => '斜线',
          'fonetik_mandarin' => 'Xiéxiàn',
          'kategori' => 'Bentuk',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Garis Sejajar',
          'bahasa_inggris' => 'Parallel lines',
          'fonetik' => 'pe-ra-lel lainz',
          'bahasa_arab' => 'خُطُوطٌ مُتَوَازِيَةٌ',
          'fonetik_arab' => 'Khuṭūṭun Mutawāziyatun',
          'bahasa_mandarin' => '平行线',
          'fonetik_mandarin' => 'Píngxíngxiàn',
          'kategori' => 'Bentuk',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Garis Tegak Lurus',
          'bahasa_inggris' => 'Perpendicular line',
          'fonetik' => 'per-pen-dik-yu-ler lain',
          'bahasa_arab' => 'خَطٌّ مُتَعَامِدٌ',
          'fonetik_arab' => 'Khaṭṭun Mutaʿāmidun',
          'bahasa_mandarin' => '垂直线',
          'fonetik_mandarin' => 'Chuízhíxiàn',
          'kategori' => 'Bentuk',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Garis Lengkung',
          'bahasa_inggris' => 'Curved line',
          'fonetik' => 'kervd lain',
          'bahasa_arab' => 'خَطٌّ مُنْحَنٍ',
          'fonetik_arab' => 'Khaṭṭun Munḥanin',
          'bahasa_mandarin' => '曲线',
          'fonetik_mandarin' => 'Qūxiàn',
          'kategori' => 'Bentuk',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Titik',
          'bahasa_inggris' => 'Point',
          'fonetik' => 'point',
          'bahasa_arab' => 'نُقْطَةٌ',
          'fonetik_arab' => 'Nuqṭatun',
          'bahasa_mandarin' => '点',
          'fonetik_mandarin' => 'Diǎn',
          'kategori' => 'Bentuk',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Sudut',
          'bahasa_inggris' => 'Angle',
          'fonetik' => 'eng-gel',
          'bahasa_arab' => 'زَاوِيَةٌ',
          'fonetik_arab' => 'Zāwiyatun',
          'bahasa_mandarin' => '角度',
          'fonetik_mandarin' => 'Jiǎodù',
          'kategori' => 'Bentuk',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Sisi',
          'bahasa_inggris' => 'Side',
          'fonetik' => 'said',
          'bahasa_arab' => 'ضِلْعٌ',
          'fonetik_arab' => 'Ḍilʿun',
          'bahasa_mandarin' => '边缘',
          'fonetik_mandarin' => 'Biānyuán',
          'kategori' => 'Bentuk',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Sudut Siku-siku',
          'bahasa_inggris' => 'Right angle',
          'fonetik' => 'rait eng-gel',
          'bahasa_arab' => 'زَاوِيَةٌ قَائِمَةٌ',
          'fonetik_arab' => 'Zāwiyatun Qāʾimatun',
          'bahasa_mandarin' => '直角',
          'fonetik_mandarin' => 'Zhíjiǎo',
          'kategori' => 'Bentuk',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Bintang',
          'bahasa_inggris' => 'Star',
          'fonetik' => 'star',
          'bahasa_arab' => 'نَجْمَةٌ',
          'fonetik_arab' => 'Najmatun',
          'bahasa_mandarin' => '星形',
          'fonetik_mandarin' => 'Xīngxíng',
          'kategori' => 'Bentuk',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Cincin',
          'bahasa_inggris' => 'Ring',
          'fonetik' => 'ring',
          'bahasa_arab' => 'حَلَقَةٌ',
          'fonetik_arab' => 'Ḥalaqatun',
          'bahasa_mandarin' => '环形',
          'fonetik_mandarin' => 'Huánxíng',
          'kategori' => 'Bentuk',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Segitiga Sama Sisi',
          'bahasa_inggris' => 'Equilateral triangle',
          'fonetik' => 'i-kwi-la-te-ral trai-eng-gel',
          'bahasa_arab' => 'مُثَلَّثٌ مُتَسَاوِي الأَضْلَاعِ',
          'fonetik_arab' => 'Muthallathun Mutasāwī al-Aḍlāʿi',
          'bahasa_mandarin' => '等边三角形',
          'fonetik_mandarin' => 'Děngbiān sānjiǎoxíng',
          'kategori' => 'Bentuk',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Segitiga Sama Kaki',
          'bahasa_inggris' => 'Isosceles triangle',
          'fonetik' => 'ai-sos-e-liz trai-eng-gel',
          'bahasa_arab' => 'مُثَلَّثٌ مُتَسَاوِي السَّاقَيْنِ',
          'fonetik_arab' => 'Muthallathun Mutasāwī as-Sāqayni',
          'bahasa_mandarin' => '等腰三角形',
          'fonetik_mandarin' => 'Děngyāo sānjiǎoxíng',
          'kategori' => 'Bentuk',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Segitiga Siku-siku',
          'bahasa_inggris' => 'Right triangle',
          'fonetik' => 'rait trai-eng-gel',
          'bahasa_arab' => 'مُثَلَّثٌ قَائِمُ الزَّاوِيَةِ',
          'fonetik_arab' => 'Muthallathun Qāʾimu az-Zāwiyati',
          'bahasa_mandarin' => '直角三角形',
          'fonetik_mandarin' => 'Zhíjiǎo sānjiǎoxíng',
          'kategori' => 'Bentuk',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Jaring-jaring',
          'bahasa_inggris' => 'Net',
          'fonetik' => 'net',
          'bahasa_arab' => 'شَبَكَةٌ',
          'fonetik_arab' => 'Shabakatun',
          'bahasa_mandarin' => '展开图',
          'fonetik_mandarin' => 'Zhǎnkāitú',
          'kategori' => 'Bentuk',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Penampang',
          'bahasa_inggris' => 'Cross-section',
          'fonetik' => 'kros sek-syen',
          'bahasa_arab' => 'مَقْطَعٌ عَرْضِيٌّ',
          'fonetik_arab' => 'Maqṭaʿun ʿArḍīyun',
          'bahasa_mandarin' => '横截面',
          'fonetik_mandarin' => 'Héngjiémiàn',
          'kategori' => 'Bentuk',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Proyeksi',
          'bahasa_inggris' => 'Projection',
          'fonetik' => 'pro-jek-syen',
          'bahasa_arab' => 'إِسْقَاطٌ',
          'fonetik_arab' => 'Isqāṭun',
          'bahasa_mandarin' => '投影',
          'fonetik_mandarin' => 'Tóuyǐng',
          'kategori' => 'Bentuk',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Simetri',
          'bahasa_inggris' => 'Symmetry',
          'fonetik' => 'si-me-tri',
          'bahasa_arab' => 'تَمَاثُلٌ',
          'fonetik_arab' => 'Tamāthulun',
          'bahasa_mandarin' => '对称',
          'fonetik_mandarin' => 'Duìchèn',
          'kategori' => 'Bentuk',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Asimetri',
          'bahasa_inggris' => 'Asymmetry',
          'fonetik' => 'ei-si-me-tri',
          'bahasa_arab' => 'عَدَمُ التَّمَاثُلِ',
          'fonetik_arab' => 'ʿAdamu at-Tamāthuli',
          'bahasa_mandarin' => '不对称',
          'fonetik_mandarin' => 'Bùduìchèn',
          'kategori' => 'Bentuk',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Cembung',
          'bahasa_inggris' => 'Convex',
          'fonetik' => 'kon-veks',
          'bahasa_arab' => 'مُحَدَّبٌ',
          'fonetik_arab' => 'Muḥaddabun',
          'bahasa_mandarin' => '凸面',
          'fonetik_mandarin' => 'Tūmiàn',
          'kategori' => 'Bentuk',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Cekung',
          'bahasa_inggris' => 'Concave',
          'fonetik' => 'kon-keyv',
          'bahasa_arab' => 'مُقَعَّرٌ',
          'fonetik_arab' => 'Muqaʿʿarun',
          'bahasa_mandarin' => '凹面',
          'fonetik_mandarin' => 'Āomiàn',
          'kategori' => 'Bentuk',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Padat',
          'bahasa_inggris' => 'Solid',
          'fonetik' => 'so-lid',
          'bahasa_arab' => 'جَامِدٌ',
          'fonetik_arab' => 'Jāmidun',
          'bahasa_mandarin' => '固体',
          'fonetik_mandarin' => 'Gùtǐ',
          'kategori' => 'Bentuk',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Berlubang',
          'bahasa_inggris' => 'Hollow',
          'fonetik' => 'ho-lou',
          'bahasa_arab' => 'مُجَوَّفٌ',
          'fonetik_arab' => 'Mujawwafun',
          'bahasa_mandarin' => '中空',
          'fonetik_mandarin' => 'Zhōngkōng',
          'kategori' => 'Bentuk',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Diameter',
          'bahasa_inggris' => 'Diameter',
          'fonetik' => 'dai-a-me-ter',
          'bahasa_arab' => 'قُطْرٌ',
          'fonetik_arab' => 'Quṭrun',
          'bahasa_mandarin' => '直径',
          'fonetik_mandarin' => 'Zhíjìng',
          'kategori' => 'Bentuk',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Jari-jari',
          'bahasa_inggris' => 'Radius',
          'fonetik' => 'rey-di-us',
          'bahasa_arab' => 'نِصْفُ الْقُطْرِ',
          'fonetik_arab' => 'Niṣfu al-Quṭri',
          'bahasa_mandarin' => '半径',
          'fonetik_mandarin' => 'Bànjìng',
          'kategori' => 'Bentuk',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Keliling',
          'bahasa_inggris' => 'Circumference',
          'fonetik' => 'ser-kam-fe-rens',
          'bahasa_arab' => 'مُحِيطٌ',
          'fonetik_arab' => 'Muḥīṭun',
          'bahasa_mandarin' => '周长',
          'fonetik_mandarin' => 'Zhōucháng',
          'kategori' => 'Bentuk',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Luas',
          'bahasa_inggris' => 'Area',
          'fonetik' => 'e-riya',
          'bahasa_arab' => 'مِسَاحَةٌ',
          'fonetik_arab' => 'Misāḥatun',
          'bahasa_mandarin' => '面积',
          'fonetik_mandarin' => 'Miànjī',
          'kategori' => 'Bentuk',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Pusat',
          'bahasa_inggris' => 'Center',
          'fonetik' => 'sen-ter',
          'bahasa_arab' => 'مَرْكَزٌ',
          'fonetik_arab' => 'Markazun',
          'bahasa_mandarin' => '中心',
          'fonetik_mandarin' => 'Zhōngxīn',
          'kategori' => 'Bentuk',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Tali Busur',
          'bahasa_inggris' => 'Chord',
          'fonetik' => 'kord',
          'bahasa_arab' => 'وَتَرٌ',
          'fonetik_arab' => 'Watarun',
          'bahasa_mandarin' => '弦',
          'fonetik_mandarin' => 'Xián',
          'kategori' => 'Bentuk',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Titik-titik',
          'bahasa_inggris' => 'Dotted',
          'fonetik' => 'do-ted',
          'bahasa_arab' => 'مُنَقَّطٌ',
          'fonetik_arab' => 'Munaqqaṭun',
          'bahasa_mandarin' => '虚线',
          'fonetik_mandarin' => 'Xūxiàn',
          'kategori' => 'Bentuk',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Bergaris',
          'bahasa_inggris' => 'Striped',
          'fonetik' => 'straipt',
          'bahasa_arab' => 'مُخَطَّطٌ',
          'fonetik_arab' => 'Mukhaṭṭaṭun',
          'bahasa_mandarin' => '条纹',
          'fonetik_mandarin' => 'Tiáowén',
          'kategori' => 'Bentuk',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Kotak-kotak',
          'bahasa_inggris' => 'Checkered',
          'fonetik' => 'ce-kerd',
          'bahasa_arab' => 'مُرَبَّعَاتٌ',
          'fonetik_arab' => 'Murabbaʿātun',
          'bahasa_mandarin' => '格子',
          'fonetik_mandarin' => 'Gézi',
          'kategori' => 'Bentuk',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Zig-zag',
          'bahasa_inggris' => 'Zig-zag',
          'fonetik' => 'zig-zeg',
          'bahasa_arab' => 'مُتَعَرِّجٌ',
          'fonetik_arab' => 'Mutaʿarrijun',
          'bahasa_mandarin' => '锯齿形',
          'fonetik_mandarin' => 'Jùchǐxíng',
          'kategori' => 'Bentuk',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Spiral',
          'bahasa_inggris' => 'Spiral',
          'fonetik' => 'spai-rel',
          'bahasa_arab' => 'حَلَزُونِيٌّ',
          'fonetik_arab' => 'Ḥalazūnīyun',
          'bahasa_mandarin' => '螺旋形',
          'fonetik_mandarin' => 'Luóxuánxíng',
          'kategori' => 'Bentuk',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Gelombang',
          'bahasa_inggris' => 'Wavy',
          'fonetik' => 'wey-vi',
          'bahasa_arab' => 'تَمَوُّجِيٌّ',
          'fonetik_arab' => 'Tamawwujīyun',
          'bahasa_mandarin' => '波浪形',
          'fonetik_mandarin' => 'Bōlàngxíng',
          'kategori' => 'Bentuk',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Pola',
          'bahasa_inggris' => 'Pattern',
          'fonetik' => 'pe-tern',
          'bahasa_arab' => 'نَمَطٌ',
          'fonetik_arab' => 'Namaṭun',
          'bahasa_mandarin' => '图案',
          'fonetik_mandarin' => 'Tú\'àn',
          'kategori' => 'Bentuk',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Tekstur',
          'bahasa_inggris' => 'Texture',
          'fonetik' => 'teks-tyer',
          'bahasa_arab' => 'قِوَامٌ',
          'fonetik_arab' => 'Qiwāmun',
          'bahasa_mandarin' => '质地',
          'fonetik_mandarin' => 'Zhìdì',
          'kategori' => 'Bentuk',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Bingkai',
          'bahasa_inggris' => 'Frame',
          'fonetik' => 'freym',
          'bahasa_arab' => 'إِطَارٌ',
          'fonetik_arab' => 'Iṭārun',
          'bahasa_mandarin' => '框架',
          'fonetik_mandarin' => 'Kuàngjià',
          'kategori' => 'Bentuk',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Kisi-kisi',
          'bahasa_inggris' => 'Grid',
          'fonetik' => 'grid',
          'bahasa_arab' => 'شَبَكَةٌ',
          'fonetik_arab' => 'Shabakatun',
          'bahasa_mandarin' => '网格',
          'fonetik_mandarin' => 'Wǎnggé',
          'kategori' => 'Bentuk',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Latar Belakang',
          'bahasa_inggris' => 'Background',
          'fonetik' => 'bek-graund',
          'bahasa_arab' => 'خَلْفِيَّةٌ',
          'fonetik_arab' => 'Khalfiyyatun',
          'bahasa_mandarin' => '背景',
          'fonetik_mandarin' => 'Bèijǐng',
          'kategori' => 'Bentuk',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Bagian Depan',
          'bahasa_inggris' => 'Foreground',
          'fonetik' => 'for-graund',
          'bahasa_arab' => 'مُقَدِّمَةٌ',
          'fonetik_arab' => 'Muqaddimatun',
          'bahasa_mandarin' => '前景',
          'fonetik_mandarin' => 'Qiánjǐng',
          'kategori' => 'Bentuk',
          'hari' => 13,
        ),
    );
  }
}