<?php

namespace Database\Seeders\Support\Game\Blueprints;

class BuahBuahan
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Apel',
          'bahasa_inggris' => 'Apple',
          'fonetik' => 'e-pel',
          'bahasa_arab' => 'تُفَّاحَةٌ',
          'fonetik_arab' => 'Tuffāḥatun',
          'bahasa_mandarin' => '苹果',
          'fonetik_mandarin' => 'Píngguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Pisang',
          'bahasa_inggris' => 'Banana',
          'fonetik' => 'be-na-na',
          'bahasa_arab' => 'مَوْزٌ',
          'fonetik_arab' => 'Mawzún',
          'bahasa_mandarin' => '香蕉',
          'fonetik_mandarin' => 'Xiāngjiāo',
          'kategori' => 'Buah-buahan',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Jeruk',
          'bahasa_inggris' => 'Orange',
          'fonetik' => 'o-renj',
          'bahasa_arab' => 'بُرْتُقَالٌ',
          'fonetik_arab' => 'Burtuqālun',
          'bahasa_mandarin' => '橙子',
          'fonetik_mandarin' => 'Chéngzi',
          'kategori' => 'Buah-buahan',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Anggur',
          'bahasa_inggris' => 'Grape',
          'fonetik' => 'greyp',
          'bahasa_arab' => 'عِنَبٌ',
          'fonetik_arab' => 'ʿInabun',
          'bahasa_mandarin' => '葡萄',
          'fonetik_mandarin' => 'Pútáo',
          'kategori' => 'Buah-buahan',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Mangga',
          'bahasa_inggris' => 'Mango',
          'fonetik' => 'meng-go',
          'bahasa_arab' => 'مَانْجُو',
          'fonetik_arab' => 'Mānjū',
          'bahasa_mandarin' => '芒果',
          'fonetik_mandarin' => 'Mángguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Stroberi',
          'bahasa_inggris' => 'Strawberry',
          'fonetik' => 'stro-be-ri',
          'bahasa_arab' => 'فَرَاوْلَةٌ',
          'fonetik_arab' => 'Farāwlatun',
          'bahasa_mandarin' => '草莓',
          'fonetik_mandarin' => 'Cǎoméi',
          'kategori' => 'Buah-buahan',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Nanas',
          'bahasa_inggris' => 'Pineapple',
          'fonetik' => 'pain-e-pel',
          'bahasa_arab' => 'أَنَانَاسٌ',
          'fonetik_arab' => 'Anānāsún',
          'bahasa_mandarin' => '菠萝',
          'fonetik_mandarin' => 'Bōluó',
          'kategori' => 'Buah-buahan',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Semangka',
          'bahasa_inggris' => 'Watermelon',
          'fonetik' => 'wo-ter-me-len',
          'bahasa_arab' => 'بِطِّيخٌ',
          'fonetik_arab' => 'Biṭṭīkhun',
          'bahasa_mandarin' => '西瓜',
          'fonetik_mandarin' => 'Xīguā',
          'kategori' => 'Buah-buahan',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Melon',
          'bahasa_inggris' => 'Melon',
          'fonetik' => 'me-len',
          'bahasa_arab' => 'شَمَّامٌ',
          'fonetik_arab' => 'Shammāmun',
          'bahasa_mandarin' => '甜瓜',
          'fonetik_mandarin' => 'Tiánguā',
          'kategori' => 'Buah-buahan',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Pepaya',
          'bahasa_inggris' => 'Papaya',
          'fonetik' => 'pa-pai-ya',
          'bahasa_arab' => 'بَابَايَا',
          'fonetik_arab' => 'Bābāyā',
          'bahasa_mandarin' => '木瓜',
          'fonetik_mandarin' => 'Mùguā',
          'kategori' => 'Buah-buahan',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Jambu Biji',
          'bahasa_inggris' => 'Guava',
          'fonetik' => 'gwa-va',
          'bahasa_arab' => 'جَوَافَةٌ',
          'fonetik_arab' => 'Jawwāfatun',
          'bahasa_mandarin' => '番石榴',
          'fonetik_mandarin' => 'Fānshíliú',
          'kategori' => 'Buah-buahan',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Ceri',
          'bahasa_inggris' => 'Cherry',
          'fonetik' => 'ce-ri',
          'bahasa_arab' => 'كَرَزٌ',
          'fonetik_arab' => 'Karazún',
          'bahasa_mandarin' => '樱桃',
          'fonetik_mandarin' => 'Yīngtáo',
          'kategori' => 'Buah-buahan',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Lemon',
          'bahasa_inggris' => 'Lemon',
          'fonetik' => 'le-men',
          'bahasa_arab' => 'لَيْمُونٌ',
          'fonetik_arab' => 'Laymūnún',
          'bahasa_mandarin' => '柠檬',
          'fonetik_mandarin' => 'Níngméng',
          'kategori' => 'Buah-buahan',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Kelapa',
          'bahasa_inggris' => 'Coconut',
          'fonetik' => 'ko-ko-nat',
          'bahasa_arab' => 'جَوْزُ الْهِنْدِ',
          'fonetik_arab' => 'Jawz al-Hind',
          'bahasa_mandarin' => '椰子',
          'fonetik_mandarin' => 'Yēzi',
          'kategori' => 'Buah-buahan',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Alpukat',
          'bahasa_inggris' => 'Avocado',
          'fonetik' => 'a-vo-ka-do',
          'bahasa_arab' => 'أَفُوكَادُو',
          'fonetik_arab' => 'Afūkādū',
          'bahasa_mandarin' => '牛油果',
          'fonetik_mandarin' => 'Niúyóuguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Kiwi',
          'bahasa_inggris' => 'Kiwi',
          'fonetik' => 'ki-wi',
          'bahasa_arab' => 'كِيوِي',
          'fonetik_arab' => 'Kīwī',
          'bahasa_mandarin' => '猕猴桃',
          'fonetik_mandarin' => 'Míhóutáo',
          'kategori' => 'Buah-buahan',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Pir',
          'bahasa_inggris' => 'Pear',
          'fonetik' => 'per',
          'bahasa_arab' => 'كُمَّثْرَى',
          'fonetik_arab' => 'Kummathrā',
          'bahasa_mandarin' => '梨',
          'fonetik_mandarin' => 'Lí',
          'kategori' => 'Buah-buahan',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Persik',
          'bahasa_inggris' => 'Peach',
          'fonetik' => 'pic',
          'bahasa_arab' => 'خَوْخٌ',
          'fonetik_arab' => 'Khawkhun',
          'bahasa_mandarin' => '桃子',
          'fonetik_mandarin' => 'Táozi',
          'kategori' => 'Buah-buahan',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Leci',
          'bahasa_inggris' => 'Lychee',
          'fonetik' => 'lai-ci',
          'bahasa_arab' => 'لِيتْشِي',
          'fonetik_arab' => 'Lītshī',
          'bahasa_mandarin' => '荔枝',
          'fonetik_mandarin' => 'Lìzhī',
          'kategori' => 'Buah-buahan',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Rambutan',
          'bahasa_inggris' => 'Rambutan',
          'fonetik' => 'ram-bu-tan',
          'bahasa_arab' => 'رَامْبُوتَان',
          'fonetik_arab' => 'Rāmbutān',
          'bahasa_mandarin' => '红毛丹',
          'fonetik_mandarin' => 'Hóngmáodān',
          'kategori' => 'Buah-buahan',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Manggis',
          'bahasa_inggris' => 'Mangosteen',
          'fonetik' => 'meng-go-stin',
          'bahasa_arab' => 'مَانْجُوسْتِين',
          'fonetik_arab' => 'Mānjūstīn',
          'bahasa_mandarin' => '山竹',
          'fonetik_mandarin' => 'Shānzhú',
          'kategori' => 'Buah-buahan',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Durian',
          'bahasa_inggris' => 'Durian',
          'fonetik' => 'du-ri-an',
          'bahasa_arab' => 'دُورْيَان',
          'fonetik_arab' => 'Dūryān',
          'bahasa_mandarin' => '榴莲',
          'fonetik_mandarin' => 'Liúlián',
          'kategori' => 'Buah-buahan',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Buah Naga',
          'bahasa_inggris' => 'Dragon fruit',
          'fonetik' => 'dre-gen frut',
          'bahasa_arab' => 'فَاكِهَةُ التِّنِّينِ',
          'fonetik_arab' => 'Fākihah at-Tinnīn',
          'bahasa_mandarin' => '火龙果',
          'fonetik_mandarin' => 'Huǒlóngguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Belimbing',
          'bahasa_inggris' => 'Star fruit',
          'fonetik' => 'star frut',
          'bahasa_arab' => 'فَاكِهَةُ النَّجْمَةِ',
          'fonetik_arab' => 'Fākihah an-Najmah',
          'bahasa_mandarin' => '杨桃',
          'fonetik_mandarin' => 'Yángtáo',
          'kategori' => 'Buah-buahan',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Nangka',
          'bahasa_inggris' => 'Jackfruit',
          'fonetik' => 'jek-frut',
          'bahasa_arab' => 'جَاكِيَةٌ',
          'fonetik_arab' => 'Jākiyatun',
          'bahasa_mandarin' => '菠萝蜜',
          'fonetik_mandarin' => 'Bōluómì',
          'kategori' => 'Buah-buahan',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Salak',
          'bahasa_inggris' => 'Snake fruit',
          'fonetik' => 'sneyk frut',
          'bahasa_arab' => 'فَاكِهَةُ الثُّعْبَانِ',
          'fonetik_arab' => 'Fākihatu ath-Thuʿbāni',
          'bahasa_mandarin' => '蛇皮果',
          'fonetik_mandarin' => 'Shépíguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Sirsak',
          'bahasa_inggris' => 'Soursop',
          'fonetik' => 'sau-er-sop',
          'bahasa_arab' => 'قِشْطَةٌ شَائكَةٌ',
          'fonetik_arab' => 'Qishṭatun Shāʾikah',
          'bahasa_mandarin' => '刺果番荔枝',
          'fonetik_mandarin' => 'Cìguǒ fānlìzhī',
          'kategori' => 'Buah-buahan',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Srikaya',
          'bahasa_inggris' => 'Custard apple',
          'fonetik' => 'kas-terd e-pel',
          'bahasa_arab' => 'قِشْطَةٌ',
          'fonetik_arab' => 'Qishṭatun',
          'bahasa_mandarin' => '番荔枝',
          'fonetik_mandarin' => 'Fānlìzhī',
          'kategori' => 'Buah-buahan',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Delima',
          'bahasa_inggris' => 'Pomegranate',
          'fonetik' => 'po-me-gre-net',
          'bahasa_arab' => 'رُمَّانٌ',
          'fonetik_arab' => 'Rummānun',
          'bahasa_mandarin' => '石榴',
          'fonetik_mandarin' => 'Shíliú',
          'kategori' => 'Buah-buahan',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Kesemek',
          'bahasa_inggris' => 'Persimmon',
          'fonetik' => 'per-si-men',
          'bahasa_arab' => 'كَـاكِي',
          'fonetik_arab' => 'Kākī',
          'bahasa_mandarin' => '柿子',
          'fonetik_mandarin' => 'Shìzi',
          'kategori' => 'Buah-buahan',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Markisa',
          'bahasa_inggris' => 'Passion fruit',
          'fonetik' => 'pe-syen frut',
          'bahasa_arab' => 'فَاكِهَةُ الْآلَامِ',
          'fonetik_arab' => 'Fākihatu al-Ālām',
          'bahasa_mandarin' => '百香果',
          'fonetik_mandarin' => 'Bǎixiāngguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Sukun',
          'bahasa_inggris' => 'Breadfruit',
          'fonetik' => 'bred-frut',
          'bahasa_arab' => 'ثَمَرَةُ الْخُبْزِ',
          'fonetik_arab' => 'Thamāratu al-Khubzi',
          'bahasa_mandarin' => '面包果',
          'fonetik_mandarin' => 'Miànbāoguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Lengkeng',
          'bahasa_inggris' => 'Longan',
          'fonetik' => 'long-gan',
          'bahasa_arab' => 'عَيْنُ الْقِطِّ',
          'fonetik_arab' => 'ʿAynu al-Qiṭṭi',
          'bahasa_mandarin' => '龙眼',
          'fonetik_mandarin' => 'Lóngyǎn',
          'kategori' => 'Buah-buahan',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Duku',
          'bahasa_inggris' => 'Duku',
          'fonetik' => 'du-ku',
          'bahasa_arab' => 'دُوكُو',
          'fonetik_arab' => 'Dūkū',
          'bahasa_mandarin' => '度古',
          'fonetik_mandarin' => 'Dùgǔ',
          'kategori' => 'Buah-buahan',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Langsat',
          'bahasa_inggris' => 'Langsat',
          'fonetik' => 'lang-sat',
          'bahasa_arab' => 'لَانْجِسَات',
          'fonetik_arab' => 'Lānjisāt',
          'bahasa_mandarin' => '榔色果',
          'fonetik_mandarin' => 'Lángsèguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Asam Jawa',
          'bahasa_inggris' => 'Tamarind',
          'fonetik' => 'te-me-rind',
          'bahasa_arab' => 'تَمْرٌ هِنْدِيٌّ',
          'fonetik_arab' => 'Tamrun Hindiyyun',
          'bahasa_mandarin' => '罗望子',
          'fonetik_mandarin' => 'Luówàngzǐ',
          'kategori' => 'Buah-buahan',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Blueberry',
          'bahasa_inggris' => 'Blueberry',
          'fonetik' => 'blu-be-ri',
          'bahasa_arab' => 'تُوتٌ أَزْرَقُ',
          'fonetik_arab' => 'Tūtun Azraqu',
          'bahasa_mandarin' => '蓝莓',
          'fonetik_mandarin' => 'Lánméi',
          'kategori' => 'Buah-buahan',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Raspberry',
          'bahasa_inggris' => 'Raspberry',
          'fonetik' => 'raz-be-ri',
          'bahasa_arab' => 'تُوتُ الْعُلَّيْقِ',
          'fonetik_arab' => 'Tūtu al-ʿUllayqi',
          'bahasa_mandarin' => '树莓',
          'fonetik_mandarin' => 'Shùméi',
          'kategori' => 'Buah-buahan',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Blackberry',
          'bahasa_inggris' => 'Blackberry',
          'fonetik' => 'blek-be-ri',
          'bahasa_arab' => 'تُوتٌ أَسْوَدُ',
          'fonetik_arab' => 'Tūtun Aswadu',
          'bahasa_mandarin' => '黑莓',
          'fonetik_mandarin' => 'Hēiméi',
          'kategori' => 'Buah-buahan',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Mulberry',
          'bahasa_inggris' => 'Mulberry',
          'fonetik' => 'mal-be-ri',
          'bahasa_arab' => 'تُوتٌ',
          'fonetik_arab' => 'Tūtun',
          'bahasa_mandarin' => '桑葚',
          'fonetik_mandarin' => 'Sāngshèn',
          'kategori' => 'Buah-buahan',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Cranberry',
          'bahasa_inggris' => 'Cranberry',
          'fonetik' => 'kren-be-ri',
          'bahasa_arab' => 'تُوتُ الرَّافِدَةِ',
          'fonetik_arab' => 'Tūtu ar-Rāfidati',
          'bahasa_mandarin' => '蔓越橘',
          'fonetik_mandarin' => 'Mànyuèjú',
          'kategori' => 'Buah-buahan',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Gooseberry',
          'bahasa_inggris' => 'Gooseberry',
          'fonetik' => 'gus-be-ri',
          'bahasa_arab' => 'عِنَبُ الثَّعْلَبِ',
          'fonetik_arab' => 'ʿInabu ath-Thaʿlabi',
          'bahasa_mandarin' => '鹅莓',
          'fonetik_mandarin' => 'Éméi',
          'kategori' => 'Buah-buahan',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Ara',
          'bahasa_inggris' => 'Fig',
          'fonetik' => 'fig',
          'bahasa_arab' => 'تِينٌ',
          'fonetik_arab' => 'Tīnun',
          'bahasa_mandarin' => '无花果',
          'fonetik_mandarin' => 'Wúhuāguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Kurma',
          'bahasa_inggris' => 'Date',
          'fonetik' => 'deyt',
          'bahasa_arab' => 'تَمْرٌ',
          'fonetik_arab' => 'Tamrun',
          'bahasa_mandarin' => '枣',
          'fonetik_mandarin' => 'Zǎo',
          'kategori' => 'Buah-buahan',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Kismis',
          'bahasa_inggris' => 'Raisin',
          'fonetik' => 'rey-zen',
          'bahasa_arab' => 'زَبِيبٌ',
          'fonetik_arab' => 'Zabībun',
          'bahasa_mandarin' => '葡萄干',
          'fonetik_mandarin' => 'Pútáogān',
          'kategori' => 'Buah-buahan',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Aprikot',
          'bahasa_inggris' => 'Apricot',
          'fonetik' => 'ey-pri-kot',
          'bahasa_arab' => 'مِشْمِشٌ',
          'fonetik_arab' => 'Mishmishun',
          'bahasa_mandarin' => '杏子',
          'fonetik_mandarin' => 'Xìngzi',
          'kategori' => 'Buah-buahan',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Plum',
          'bahasa_inggris' => 'Plum',
          'fonetik' => 'plam',
          'bahasa_arab' => 'بَرْقُوقٌ',
          'fonetik_arab' => 'Barqūqun',
          'bahasa_mandarin' => '李子',
          'fonetik_mandarin' => 'Lǐzi',
          'kategori' => 'Buah-buahan',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Zaitun',
          'bahasa_inggris' => 'Olive',
          'fonetik' => 'o-liv',
          'bahasa_arab' => 'زَيْتُونٌ',
          'fonetik_arab' => 'Zaytūnun',
          'bahasa_mandarin' => '橄榄',
          'fonetik_mandarin' => 'Gǎnlǎn',
          'kategori' => 'Buah-buahan',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Jeruk Nipis',
          'bahasa_inggris' => 'Lime',
          'fonetik' => 'laim',
          'bahasa_arab' => 'لَيْمُونٌ حَامِضٌ',
          'fonetik_arab' => 'Laymūnun Ḥāmiḍun',
          'bahasa_mandarin' => '青柠',
          'fonetik_mandarin' => 'Qīngníng',
          'kategori' => 'Buah-buahan',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Jeruk Bali',
          'bahasa_inggris' => 'Pomelo',
          'fonetik' => 'po-me-lou',
          'bahasa_arab' => 'لَيْمُونٌ هِنْدِيٌّ',
          'fonetik_arab' => 'Laymūnun Hindiyyun',
          'bahasa_mandarin' => '柚子',
          'fonetik_mandarin' => 'Yòuzi',
          'kategori' => 'Buah-buahan',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Jeruk Keprok',
          'bahasa_inggris' => 'Tangerine',
          'fonetik' => 'ten-je-rin',
          'bahasa_arab' => 'يُوسُفِيّ',
          'fonetik_arab' => 'Yūsufī',
          'bahasa_mandarin' => '橘子',
          'fonetik_mandarin' => 'Júzi',
          'kategori' => 'Buah-buahan',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Clementine',
          'bahasa_inggris' => 'Clementine',
          'fonetik' => 'kle-men-tin',
          'bahasa_arab' => 'كَلْمَنْتِين',
          'fonetik_arab' => 'Kalmantīn',
          'bahasa_mandarin' => '小柑橘',
          'fonetik_mandarin' => 'Xiǎo gānjú',
          'kategori' => 'Buah-buahan',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Kumquat',
          'bahasa_inggris' => 'Kumquat',
          'fonetik' => 'kam-kwat',
          'bahasa_arab' => 'كُمكُوات',
          'fonetik_arab' => 'Kumkuwāt',
          'bahasa_mandarin' => '金橘',
          'fonetik_mandarin' => 'Jīnjú',
          'kategori' => 'Buah-buahan',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Jeruk Darah',
          'bahasa_inggris' => 'Blood orange',
          'fonetik' => 'blad o-renj',
          'bahasa_arab' => 'بُرْتُقَالٌ دَمَوِيٌّ',
          'fonetik_arab' => 'Burtuqālun Damawīyun',
          'bahasa_mandarin' => '血橙',
          'fonetik_mandarin' => 'Xuèchéng',
          'kategori' => 'Buah-buahan',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Kedondong',
          'bahasa_inggris' => 'Ambarella',
          'fonetik' => 'em-be-re-la',
          'bahasa_arab' => 'كِدُونْدُونج',
          'fonetik_arab' => 'Kidūndūng',
          'bahasa_mandarin' => '太平洋榅桲',
          'fonetik_mandarin' => 'Tàipíngyáng wēnpō',
          'kategori' => 'Buah-buahan',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Sawo',
          'bahasa_inggris' => 'Sapodilla',
          'fonetik' => 'se-po-di-la',
          'bahasa_arab' => 'سَبُودِيَّا',
          'fonetik_arab' => 'Sabūdiyyā',
          'bahasa_mandarin' => '人参果',
          'fonetik_mandarin' => 'Rénshēnguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Jambu Air',
          'bahasa_inggris' => 'Water apple',
          'fonetik' => 'wo-ter e-pel',
          'bahasa_arab' => 'تُفَّاحُ الْمَاءِ',
          'fonetik_arab' => 'Tuffāḥu al-Māʾi',
          'bahasa_mandarin' => '莲雾',
          'fonetik_mandarin' => 'Liánwù',
          'kategori' => 'Buah-buahan',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Jambu Bol',
          'bahasa_inggris' => 'Malay apple',
          'fonetik' => 'me-ley e-pel',
          'bahasa_arab' => 'تُفَّاحُ مَالِي',
          'fonetik_arab' => 'Tuffāḥu Mālī',
          'bahasa_mandarin' => '马六甲蒲桃',
          'fonetik_mandarin' => 'Mǎliùjiǎ pútáo',
          'kategori' => 'Buah-buahan',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Belimbing Wuluh',
          'bahasa_inggris' => 'Bilimbi',
          'fonetik' => 'bi-lim-bi',
          'bahasa_arab' => 'بِيلِيمبِي',
          'fonetik_arab' => 'Bīlīmbī',
          'bahasa_mandarin' => '三敛',
          'fonetik_mandarin' => 'Sānliǎn',
          'kategori' => 'Buah-buahan',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Ceremai',
          'bahasa_inggris' => 'Starberry',
          'fonetik' => 'star-be-ri',
          'bahasa_arab' => 'سِيْرِيمَاي',
          'fonetik_arab' => 'Sīrīmāy',
          'bahasa_mandarin' => '西印度醋栗',
          'fonetik_mandarin' => 'Xīyìndù cùlì',
          'kategori' => 'Buah-buahan',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Blewah',
          'bahasa_inggris' => 'Cantaloupe',
          'fonetik' => 'ken-te-loup',
          'bahasa_arab' => 'كَنْتَالُوب',
          'fonetik_arab' => 'Kantālūb',
          'bahasa_mandarin' => '哈密瓜',
          'fonetik_mandarin' => 'Hāmìguā',
          'kategori' => 'Buah-buahan',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Honeydew',
          'bahasa_inggris' => 'Honeydew',
          'fonetik' => 'ha-ni-dyu',
          'bahasa_arab' => 'شَمَّامٌ عَسَلِيٌّ',
          'fonetik_arab' => 'Shammāmun ʿAsalīyun',
          'bahasa_mandarin' => '蜜瓜',
          'fonetik_mandarin' => 'Mìguā',
          'kategori' => 'Buah-buahan',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Labu',
          'bahasa_inggris' => 'Pumpkin',
          'fonetik' => 'pam-kin',
          'bahasa_arab' => 'يَقْطِينٌ',
          'fonetik_arab' => 'Yaqṭīnun',
          'bahasa_mandarin' => '南瓜',
          'fonetik_mandarin' => 'Nánguā',
          'kategori' => 'Buah-buahan',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Loquat',
          'bahasa_inggris' => 'Loquat',
          'fonetik' => 'lou-kwat',
          'bahasa_arab' => 'بَشْمَلَةٌ',
          'fonetik_arab' => 'Bashmalatun',
          'bahasa_mandarin' => '枇杷',
          'fonetik_mandarin' => 'Pípá',
          'kategori' => 'Buah-buahan',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Quince',
          'bahasa_inggris' => 'Quince',
          'fonetik' => 'kwins',
          'bahasa_arab' => 'سَفَرْجَلٌ',
          'fonetik_arab' => 'Safarjalun',
          'bahasa_mandarin' => '榅桲',
          'fonetik_mandarin' => 'Wēnpō',
          'kategori' => 'Buah-buahan',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Elderberry',
          'bahasa_inggris' => 'Elderberry',
          'fonetik' => 'el-der-be-ri',
          'bahasa_arab' => 'بَيْلَسَانٌ',
          'fonetik_arab' => 'Baylasānun',
          'bahasa_mandarin' => '接骨木莓',
          'fonetik_mandarin' => 'Jiēgǔmù méi',
          'kategori' => 'Buah-buahan',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Kacang Kenari',
          'bahasa_inggris' => 'Walnut',
          'fonetik' => 'wol-nat',
          'bahasa_arab' => 'جَوْزٌ',
          'fonetik_arab' => 'Jawzun',
          'bahasa_mandarin' => '核桃',
          'fonetik_mandarin' => 'Hétáo',
          'kategori' => 'Buah-buahan',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Jambu Mete',
          'bahasa_inggris' => 'Cashew fruit',
          'fonetik' => 'ke-syu frut',
          'bahasa_arab' => 'ثَمَرَةُ الْكَاجُو',
          'fonetik_arab' => 'Thamāratu al-Kājū',
          'bahasa_mandarin' => '腰果梨',
          'fonetik_mandarin' => 'Yāoguǒlí',
          'kategori' => 'Buah-buahan',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Almond',
          'bahasa_inggris' => 'Almond',
          'fonetik' => 'a-mend',
          'bahasa_arab' => 'لَوْزٌ',
          'fonetik_arab' => 'Lawzun',
          'bahasa_mandarin' => '杏仁',
          'fonetik_mandarin' => 'Xìngrén',
          'kategori' => 'Buah-buahan',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Pistachio',
          'bahasa_inggris' => 'Pistachio',
          'fonetik' => 'pis-ta-syio',
          'bahasa_arab' => 'فُسْتُقٌ',
          'fonetik_arab' => 'Fustuqun',
          'bahasa_mandarin' => '开心果',
          'fonetik_mandarin' => 'Kāixīnguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Chestnut',
          'bahasa_inggris' => 'Chestnut',
          'fonetik' => 'ces-nat',
          'bahasa_arab' => 'كَسْتَنَاءٌ',
          'fonetik_arab' => 'Kastanāʾun',
          'bahasa_mandarin' => '栗子',
          'fonetik_mandarin' => 'Lìzi',
          'kategori' => 'Buah-buahan',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Hazelnut',
          'bahasa_inggris' => 'Hazelnut',
          'fonetik' => 'hey-zel-nat',
          'bahasa_arab' => 'بُنْدُقٌ',
          'fonetik_arab' => 'Bunduqun',
          'bahasa_mandarin' => '榛子',
          'fonetik_mandarin' => 'Zhēnzi',
          'kategori' => 'Buah-buahan',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Terong Belanda',
          'bahasa_inggris' => 'Tamarillo',
          'fonetik' => 'te-me-ri-lou',
          'bahasa_arab' => 'تَامَارِيلُو',
          'fonetik_arab' => 'Tāmārīlū',
          'bahasa_mandarin' => '树番茄',
          'fonetik_mandarin' => 'Shùfānqié',
          'kategori' => 'Buah-buahan',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Ciplukan',
          'bahasa_inggris' => 'Physalis',
          'fonetik' => 'fai-sa-lis',
          'bahasa_arab' => 'حَرَنْكَش',
          'fonetik_arab' => 'Ḥarankash',
          'bahasa_mandarin' => '灯笼果',
          'fonetik_mandarin' => 'Dēnglóngguǒ',
          'kategori' => 'Buah-buahan',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Jujube',
          'bahasa_inggris' => 'Jujube',
          'fonetik' => 'ju-jub',
          'bahasa_arab' => 'عُنَّابٌ',
          'fonetik_arab' => 'ʿUnnābun',
          'bahasa_mandarin' => '枣子',
          'fonetik_mandarin' => 'Zǎōzi',
          'kategori' => 'Buah-buahan',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Goji Berry',
          'bahasa_inggris' => 'Goji berry',
          'fonetik' => 'go-ji be-ri',
          'bahasa_arab' => 'تُوتُ الْغُوجِي',
          'fonetik_arab' => 'Tūtu al-Ghūjī',
          'bahasa_mandarin' => '枸杞',
          'fonetik_mandarin' => 'Gǒuqǐ',
          'kategori' => 'Buah-buahan',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Bidara',
          'bahasa_inggris' => 'Jujube fruit',
          'fonetik' => 'ju-jub frut',
          'bahasa_arab' => 'سِدْرٌ',
          'fonetik_arab' => 'Sidrun',
          'bahasa_mandarin' => '酸枣',
          'fonetik_mandarin' => 'Suānzǎo',
          'kategori' => 'Buah-buahan',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Acai Berry',
          'bahasa_inggris' => 'Acai berry',
          'fonetik' => 'a-sai-be-ri',
          'bahasa_arab' => 'تُوتُ الأَسَايِي',
          'fonetik_arab' => 'Tūtu al-Asāyī',
          'bahasa_mandarin' => '巴西莓',
          'fonetik_mandarin' => 'Bāxīméi',
          'kategori' => 'Buah-buahan',
          'hari' => 13,
        ),
    );
  }
}