<?php

namespace Database\Seeders\Support\Game\Blueprints;

class HewanDarat
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Kucing',
          'bahasa_inggris' => 'Cat',
          'fonetik' => 'ket',
          'bahasa_arab' => 'قِطَّةٌ',
          'fonetik_arab' => 'Qiṭṭatun',
          'bahasa_mandarin' => '猫',
          'fonetik_mandarin' => 'Māo',
          'kategori' => 'Hewan Darat',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Anjing',
          'bahasa_inggris' => 'Dog',
          'fonetik' => 'dog',
          'bahasa_arab' => 'كَلْبٌ',
          'fonetik_arab' => 'Kalbun',
          'bahasa_mandarin' => '狗',
          'fonetik_mandarin' => 'Gǒu',
          'kategori' => 'Hewan Darat',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Ayam',
          'bahasa_inggris' => 'Chicken',
          'fonetik' => 'ci-ken',
          'bahasa_arab' => 'دَجَاجَةٌ',
          'fonetik_arab' => 'Dajājātun',
          'bahasa_mandarin' => '鸡',
          'fonetik_mandarin' => 'Jī',
          'kategori' => 'Hewan Darat',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Sapi',
          'bahasa_inggris' => 'Cow',
          'fonetik' => 'kau',
          'bahasa_arab' => 'بَقَرَةٌ',
          'fonetik_arab' => 'Baqaratun',
          'bahasa_mandarin' => '牛',
          'fonetik_mandarin' => 'Niú',
          'kategori' => 'Hewan Darat',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Kuda',
          'bahasa_inggris' => 'Horse',
          'fonetik' => 'hors',
          'bahasa_arab' => 'حِصَانٌ',
          'fonetik_arab' => 'Ḥiṣānun',
          'bahasa_mandarin' => '马',
          'fonetik_mandarin' => 'Mǎ',
          'kategori' => 'Hewan Darat',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Domba',
          'bahasa_inggris' => 'Sheep',
          'fonetik' => 'syip',
          'bahasa_arab' => 'خَرُوفٌ',
          'fonetik_arab' => 'Kharūfun',
          'bahasa_mandarin' => '羊',
          'fonetik_mandarin' => 'Yáng',
          'kategori' => 'Hewan Darat',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Gajah',
          'bahasa_inggris' => 'Elephant',
          'fonetik' => 'e-le-fen',
          'bahasa_arab' => 'فِيلٌ',
          'fonetik_arab' => 'Fīlun',
          'bahasa_mandarin' => '大象',
          'fonetik_mandarin' => 'Dàxiàng',
          'kategori' => 'Hewan Darat',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Singa',
          'bahasa_inggris' => 'Lion',
          'fonetik' => 'lai-yen',
          'bahasa_arab' => 'أَسَدٌ',
          'fonetik_arab' => 'Asadun',
          'bahasa_mandarin' => '狮子',
          'fonetik_mandarin' => 'Shīzi',
          'kategori' => 'Hewan Darat',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Harimau',
          'bahasa_inggris' => 'Tiger',
          'fonetik' => 'tai-ger',
          'bahasa_arab' => 'نَمِرٌ',
          'fonetik_arab' => 'Namirun',
          'bahasa_mandarin' => '老虎',
          'fonetik_mandarin' => 'Lǎohǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Monyet',
          'bahasa_inggris' => 'Monkey',
          'fonetik' => 'mang-ki',
          'bahasa_arab' => 'قِرْدٌ',
          'fonetik_arab' => 'Qirdun',
          'bahasa_mandarin' => '猴子',
          'fonetik_mandarin' => 'Hóuzi',
          'kategori' => 'Hewan Darat',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Kelinci',
          'bahasa_inggris' => 'Rabbit',
          'fonetik' => 'ra-bit',
          'bahasa_arab' => 'أَرْنَبٌ',
          'fonetik_arab' => 'Arnabun',
          'bahasa_mandarin' => '兔子',
          'fonetik_mandarin' => 'Tùzi',
          'kategori' => 'Hewan Darat',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Beruang',
          'bahasa_inggris' => 'Bear',
          'fonetik' => 'ber',
          'bahasa_arab' => 'دُبٌّ',
          'fonetik_arab' => 'Dubbun',
          'bahasa_mandarin' => '熊',
          'fonetik_mandarin' => 'Xióng',
          'kategori' => 'Hewan Darat',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Kambing',
          'bahasa_inggris' => 'Goat',
          'fonetik' => 'gout',
          'bahasa_arab' => 'مَاعِزٌ',
          'fonetik_arab' => 'Māʿizun',
          'bahasa_mandarin' => '山羊',
          'fonetik_mandarin' => 'Shānyáng',
          'kategori' => 'Hewan Darat',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Jerapah',
          'bahasa_inggris' => 'Giraffe',
          'fonetik' => 'ji-raf',
          'bahasa_arab' => 'زَرَافَةٌ',
          'fonetik_arab' => 'Zarāfatun',
          'bahasa_mandarin' => '长颈鹿',
          'fonetik_mandarin' => 'Chángjǐnglù',
          'kategori' => 'Hewan Darat',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Semut',
          'bahasa_inggris' => 'Ant',
          'fonetik' => 'ent',
          'bahasa_arab' => 'نَمْلَةٌ',
          'fonetik_arab' => 'Namlatun',
          'bahasa_mandarin' => '蚂蚁',
          'fonetik_mandarin' => 'Mǎyǐ',
          'kategori' => 'Hewan Darat',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Ular',
          'bahasa_inggris' => 'Snake',
          'fonetik' => 'sneyk',
          'bahasa_arab' => 'ثُعْبَانٌ',
          'fonetik_arab' => 'Thuʿbānun',
          'bahasa_mandarin' => '蛇',
          'fonetik_mandarin' => 'Shé',
          'kategori' => 'Hewan Darat',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Zebra',
          'bahasa_inggris' => 'Zebra',
          'fonetik' => 'zi-bra',
          'bahasa_arab' => 'حِمَارٌ وَحْشِيٌّ',
          'fonetik_arab' => 'Ḥimār Waḥshī',
          'bahasa_mandarin' => '斑马',
          'fonetik_mandarin' => 'Bānmǎ',
          'kategori' => 'Hewan Darat',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Panda',
          'bahasa_inggris' => 'Panda',
          'fonetik' => 'pen-da',
          'bahasa_arab' => 'بَانْدَا',
          'fonetik_arab' => 'Bāndā',
          'bahasa_mandarin' => '熊猫',
          'fonetik_mandarin' => 'Xióngmāo',
          'kategori' => 'Hewan Darat',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Unta',
          'bahasa_inggris' => 'Camel',
          'fonetik' => 'ke-mel',
          'bahasa_arab' => 'جَمَلٌ',
          'fonetik_arab' => 'Jamālun',
          'bahasa_mandarin' => '骆驼',
          'fonetik_mandarin' => 'Luòtuo',
          'kategori' => 'Hewan Darat',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Tikus',
          'bahasa_inggris' => 'Mouse',
          'fonetik' => 'maus',
          'bahasa_arab' => 'فَأْرٌ',
          'fonetik_arab' => 'Faʾrun',
          'bahasa_mandarin' => '老鼠',
          'fonetik_mandarin' => 'Lǎoshǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Rubah',
          'bahasa_inggris' => 'Fox',
          'fonetik' => 'foks',
          'bahasa_arab' => 'ثَعْلَبٌ',
          'fonetik_arab' => 'Thaʿlabun',
          'bahasa_mandarin' => '狐狸',
          'fonetik_mandarin' => 'Húli',
          'kategori' => 'Hewan Darat',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Serigala',
          'bahasa_inggris' => 'Wolf',
          'fonetik' => 'wulf',
          'bahasa_arab' => 'ذِئْبٌ',
          'fonetik_arab' => 'Dhiʾbun',
          'bahasa_mandarin' => '狼',
          'fonetik_mandarin' => 'Láng',
          'kategori' => 'Hewan Darat',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Rusa',
          'bahasa_inggris' => 'Deer',
          'fonetik' => 'dir',
          'bahasa_arab' => 'غَزَالٌ',
          'fonetik_arab' => 'Ghazālun',
          'bahasa_mandarin' => '鹿',
          'fonetik_mandarin' => 'Lù',
          'kategori' => 'Hewan Darat',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Babi',
          'bahasa_inggris' => 'Pig',
          'fonetik' => 'pig',
          'bahasa_arab' => 'خِنْزِيرٌ',
          'fonetik_arab' => 'Khinzīrun',
          'bahasa_mandarin' => '猪',
          'fonetik_mandarin' => 'Zhū',
          'kategori' => 'Hewan Darat',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Koala',
          'bahasa_inggris' => 'Koala',
          'fonetik' => 'ko-wa-la',
          'bahasa_arab' => 'كُوَالَا',
          'fonetik_arab' => 'Kuwālā',
          'bahasa_mandarin' => '考拉',
          'fonetik_mandarin' => 'Kǎolā',
          'kategori' => 'Hewan Darat',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Kanguru',
          'bahasa_inggris' => 'Kangaroo',
          'fonetik' => 'keng-ge-ru',
          'bahasa_arab' => 'كَنْغَرٌ',
          'fonetik_arab' => 'Kangarun',
          'bahasa_mandarin' => '袋鼠',
          'fonetik_mandarin' => 'Dàishǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Badak',
          'bahasa_inggris' => 'Rhinoceros',
          'fonetik' => 'rai-no-se-res',
          'bahasa_arab' => 'وَحِيدُ الْقَرْنِ',
          'fonetik_arab' => 'Waḥīd al-Qarn',
          'bahasa_mandarin' => '犀牛',
          'fonetik_mandarin' => 'Xīniú',
          'kategori' => 'Hewan Darat',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Kuda Nil',
          'bahasa_inggris' => 'Hippopotamus',
          'fonetik' => 'hi-po-po-te-mes',
          'bahasa_arab' => 'فَرَسُ النَّهْرِ',
          'fonetik_arab' => 'Faras an-Nahr',
          'bahasa_mandarin' => '河马',
          'fonetik_mandarin' => 'Hémǎ',
          'kategori' => 'Hewan Darat',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Gorila',
          'bahasa_inggris' => 'Gorilla',
          'fonetik' => 'go-ri-la',
          'bahasa_arab' => 'غُورِيلَا',
          'fonetik_arab' => 'Ghūrīlā',
          'bahasa_mandarin' => '大猩猩',
          'fonetik_mandarin' => 'Dàxīngxīng',
          'kategori' => 'Hewan Darat',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Kadal',
          'bahasa_inggris' => 'Lizard',
          'fonetik' => 'li-zerd',
          'bahasa_arab' => 'سِحْلِيَّةٌ',
          'fonetik_arab' => 'Siḥliyyatun',
          'bahasa_mandarin' => '蜥蜴',
          'fonetik_mandarin' => 'Xīyì',
          'kategori' => 'Hewan Darat',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Cicak',
          'bahasa_inggris' => 'Gecko',
          'fonetik' => 'ge-ko',
          'bahasa_arab' => 'وَزَغٌ',
          'fonetik_arab' => 'Wazaghun',
          'bahasa_mandarin' => '壁虎',
          'fonetik_mandarin' => 'Bìhǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Tupai',
          'bahasa_inggris' => 'Squirrel',
          'fonetik' => 'skwi-rel',
          'bahasa_arab' => 'سَنْجَابٌ',
          'fonetik_arab' => 'Sanjābún',
          'bahasa_mandarin' => '松鼠',
          'fonetik_mandarin' => 'Sōngshǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Landak',
          'bahasa_inggris' => 'Porcupine',
          'fonetik' => 'por-kyu-pain',
          'bahasa_arab' => 'قُنْفُذٌ',
          'fonetik_arab' => 'Qunfudhún',
          'bahasa_mandarin' => '刺猬',
          'fonetik_mandarin' => 'Cìwèi',
          'kategori' => 'Hewan Darat',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Rakun',
          'bahasa_inggris' => 'Raccoon',
          'fonetik' => 'ra-kun',
          'bahasa_arab' => 'رَاكُونٌ',
          'fonetik_arab' => 'Rākūnun',
          'bahasa_mandarin' => '浣熊',
          'fonetik_mandarin' => 'Huànxióng',
          'kategori' => 'Hewan Darat',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Macan Tutul',
          'bahasa_inggris' => 'Leopard',
          'fonetik' => 'le-perd',
          'bahasa_arab' => 'فَهْدٌ',
          'fonetik_arab' => 'Fahdun',
          'bahasa_mandarin' => '豹',
          'fonetik_mandarin' => 'Bào',
          'kategori' => 'Hewan Darat',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Musang',
          'bahasa_inggris' => 'Ferret',
          'fonetik' => 'fe-ret',
          'bahasa_arab' => 'قُطْرُبٌ',
          'fonetik_arab' => 'Quṭrubun',
          'bahasa_mandarin' => '鼬',
          'fonetik_mandarin' => 'Yòu',
          'kategori' => 'Hewan Darat',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Bunglon',
          'bahasa_inggris' => 'Chameleon',
          'fonetik' => 'ka-mi-li-yen',
          'bahasa_arab' => 'حِرْبَاءٌ',
          'fonetik_arab' => 'Ḥirbāʾun',
          'bahasa_mandarin' => '变色龙',
          'fonetik_mandarin' => 'Biànsèlóng',
          'kategori' => 'Hewan Darat',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Armadillo',
          'bahasa_inggris' => 'Armadillo',
          'fonetik' => 'ar-ma-di-lo',
          'bahasa_arab' => 'أَرْمَادِيلُو',
          'fonetik_arab' => 'Armādīlū',
          'bahasa_mandarin' => '犰狳',
          'fonetik_mandarin' => 'Qiúyú',
          'kategori' => 'Hewan Darat',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Platipus',
          'bahasa_inggris' => 'Platypus',
          'fonetik' => 'pla-ti-pes',
          'bahasa_arab' => 'بِلَاتِيبُوس',
          'fonetik_arab' => 'Blātībūs',
          'bahasa_mandarin' => '鸭嘴兽',
          'fonetik_mandarin' => 'Yāzuǐshòu',
          'kategori' => 'Hewan Darat',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Kukang',
          'bahasa_inggris' => 'Sloth',
          'fonetik' => 'sloth',
          'bahasa_arab' => 'كَسْلَانُ',
          'fonetik_arab' => 'Kaslānun',
          'bahasa_mandarin' => '树懒',
          'fonetik_mandarin' => 'Shùlǎn',
          'kategori' => 'Hewan Darat',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Hyena',
          'bahasa_inggris' => 'Hyena',
          'fonetik' => 'hai-i-na',
          'bahasa_arab' => 'ضَبْعٌ',
          'fonetik_arab' => 'Ḍabʿun',
          'bahasa_mandarin' => '鬣狗',
          'fonetik_mandarin' => 'Liègǒu',
          'kategori' => 'Hewan Darat',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Tapir',
          'bahasa_inggris' => 'Tapir',
          'fonetik' => 'tei-per',
          'bahasa_arab' => 'تَابِرٌ',
          'fonetik_arab' => 'Tābirun',
          'bahasa_mandarin' => '貘',
          'fonetik_mandarin' => 'Mò',
          'kategori' => 'Hewan Darat',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Laba-laba',
          'bahasa_inggris' => 'Spider',
          'fonetik' => 'spai-der',
          'bahasa_arab' => 'عَنْكَبُوْتٌ',
          'fonetik_arab' => 'Ankabuutun',
          'bahasa_mandarin' => '蜘蛛',
          'fonetik_mandarin' => 'Zhīzhū',
          'kategori' => 'Hewan Darat',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Kalajengking',
          'bahasa_inggris' => 'Scorpion',
          'fonetik' => 'skor-pi-yen',
          'bahasa_arab' => 'عَقْرَبٌ',
          'fonetik_arab' => 'Aqrabun',
          'bahasa_mandarin' => '蝎子',
          'fonetik_mandarin' => 'Xiēzi',
          'kategori' => 'Hewan Darat',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Cacing',
          'bahasa_inggris' => 'Worm',
          'fonetik' => 'werm',
          'bahasa_arab' => 'دُوْدَةٌ',
          'fonetik_arab' => 'Duudatun',
          'bahasa_mandarin' => '蚯蚓',
          'fonetik_mandarin' => 'Qiūyǐn',
          'kategori' => 'Hewan Darat',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Siput',
          'bahasa_inggris' => 'Snail',
          'fonetik' => 'sneil',
          'bahasa_arab' => 'حَلَزُوْنٌ',
          'fonetik_arab' => 'Halazuunun',
          'bahasa_mandarin' => '蜗牛',
          'fonetik_mandarin' => 'Wōniú',
          'kategori' => 'Hewan Darat',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Bebek',
          'bahasa_inggris' => 'Duck',
          'fonetik' => 'dak',
          'bahasa_arab' => 'بَطَّةٌ',
          'fonetik_arab' => 'Baththatun',
          'bahasa_mandarin' => '鸭子',
          'fonetik_mandarin' => 'Yāzi',
          'kategori' => 'Hewan Darat',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Kura-kura',
          'bahasa_inggris' => 'Turtle',
          'fonetik' => 'ter-tel',
          'bahasa_arab' => 'سُلَحْفَاةٌ',
          'fonetik_arab' => 'Sulahfaatun',
          'bahasa_mandarin' => '乌龟',
          'fonetik_mandarin' => 'Wūguī',
          'kategori' => 'Hewan Darat',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Katak',
          'bahasa_inggris' => 'Frog',
          'fonetik' => 'frog',
          'bahasa_arab' => 'ضِفْدَعٌ',
          'fonetik_arab' => 'Dhifdaʿun',
          'bahasa_mandarin' => '青蛙',
          'fonetik_mandarin' => 'Qīngwā',
          'kategori' => 'Hewan Darat',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Belalang',
          'bahasa_inggris' => 'Grasshopper',
          'fonetik' => 'gres-ho-per',
          'bahasa_arab' => 'جَرَادٌ',
          'fonetik_arab' => 'Jarādun',
          'bahasa_mandarin' => '蚱蜢',
          'fonetik_mandarin' => 'Zhàměng',
          'kategori' => 'Hewan Darat',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Semut Merah',
          'bahasa_inggris' => 'Fire Ant',
          'fonetik' => 'fai-yer ent',
          'bahasa_arab' => 'نَمْلَةٌ حَمْرَاءُ',
          'fonetik_arab' => 'Namlatun Ḥamrāʾu',
          'bahasa_mandarin' => '红火蚁',
          'fonetik_mandarin' => 'Hónghuǒyǐ',
          'kategori' => 'Hewan Darat',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Jangkrik',
          'bahasa_inggris' => 'Cricket',
          'fonetik' => 'kri-ket',
          'bahasa_arab' => 'صَرَّارٌ',
          'fonetik_arab' => 'Ṣarrārun',
          'bahasa_mandarin' => '蟋蟀',
          'fonetik_mandarin' => 'Xīshuài',
          'kategori' => 'Hewan Darat',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Lipan',
          'bahasa_inggris' => 'Centipede',
          'fonetik' => 'sen-ti-pid',
          'bahasa_arab' => 'حَرِيْشٌ',
          'fonetik_arab' => 'Ḥarīshun',
          'bahasa_mandarin' => '蜈蚣',
          'fonetik_mandarin' => 'Wúgōng',
          'kategori' => 'Hewan Darat',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Kaki Seribu',
          'bahasa_inggris' => 'Millipede',
          'fonetik' => 'mi-li-pid',
          'bahasa_arab' => 'أَلْفِيَّةُ الأَرْجُلِ',
          'fonetik_arab' => 'Alfiyyatul Arjul',
          'bahasa_mandarin' => '马陆',
          'fonetik_mandarin' => 'Mǎlù',
          'kategori' => 'Hewan Darat',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Cheetah',
          'bahasa_inggris' => 'Cheetah',
          'fonetik' => 'ci-ta',
          'bahasa_arab' => 'فَهْدٌ شَيْطَانِيٌّ',
          'fonetik_arab' => 'Fahdun Syayṭāniyyun',
          'bahasa_mandarin' => '猎豹',
          'fonetik_mandarin' => 'Lièbào',
          'kategori' => 'Hewan Darat',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Jaguar',
          'bahasa_inggris' => 'Jaguar',
          'fonetik' => 'je-gu-ar',
          'bahasa_arab' => 'نَمِرٌ أَمْرِيكِيٌّ',
          'fonetik_arab' => 'Namirun Amrīkiyyun',
          'bahasa_mandarin' => '美洲豹',
          'fonetik_mandarin' => 'Měizhōubào',
          'kategori' => 'Hewan Darat',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Macan Dahan',
          'bahasa_inggris' => 'Clouded Leopard',
          'fonetik' => 'klau-ded le-perd',
          'bahasa_arab' => 'نَمِرٌ مُلَطَّخٌ',
          'fonetik_arab' => 'Namirun Mulaṭṭakhun',
          'bahasa_mandarin' => '云豹',
          'fonetik_mandarin' => 'Yúnbào',
          'kategori' => 'Hewan Darat',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Puma',
          'bahasa_inggris' => 'Puma',
          'fonetik' => 'pyu-ma',
          'bahasa_arab' => 'بُومَا',
          'fonetik_arab' => 'Būmā',
          'bahasa_mandarin' => '美洲狮',
          'fonetik_mandarin' => 'Měizhōushī',
          'kategori' => 'Hewan Darat',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Srigala Hutan',
          'bahasa_inggris' => 'Coyote',
          'fonetik' => 'kai-yo-ti',
          'bahasa_arab' => 'قِيُوط',
          'fonetik_arab' => 'Qiyūṭ',
          'bahasa_mandarin' => '郊狼',
          'fonetik_mandarin' => 'Jiāoláng',
          'kategori' => 'Hewan Darat',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Rubah Salju',
          'bahasa_inggris' => 'Arctic Fox',
          'fonetik' => 'ark-tik foks',
          'bahasa_arab' => 'ثَعْلَبٌ قُطْبِيٌّ',
          'fonetik_arab' => 'Thaʿlabun Quṭbiyyun',
          'bahasa_mandarin' => '北极狐',
          'fonetik_mandarin' => 'Běijíhú',
          'kategori' => 'Hewan Darat',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Keledai',
          'bahasa_inggris' => 'Donkey',
          'fonetik' => 'dong-ki',
          'bahasa_arab' => 'حِمَارٌ',
          'fonetik_arab' => 'Ḥimārun',
          'bahasa_mandarin' => '驴',
          'fonetik_mandarin' => 'Lǘ',
          'kategori' => 'Hewan Darat',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Bagal',
          'bahasa_inggris' => 'Mule',
          'fonetik' => 'myul',
          'bahasa_arab' => 'بَغْلٌ',
          'fonetik_arab' => 'Baghulun',
          'bahasa_mandarin' => '骡子',
          'fonetik_mandarin' => 'Luózi',
          'kategori' => 'Hewan Darat',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Kerbau',
          'bahasa_inggris' => 'Buffalo',
          'fonetik' => 'ba-fe-lo',
          'bahasa_arab' => 'جَامُوسٌ',
          'fonetik_arab' => 'Jāmūsun',
          'bahasa_mandarin' => '水牛',
          'fonetik_mandarin' => 'Shuǐniú',
          'kategori' => 'Hewan Darat',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Banteng',
          'bahasa_inggris' => 'Bull',
          'fonetik' => 'bul',
          'bahasa_arab' => 'ثَوْرٌ',
          'fonetik_arab' => 'Thawrun',
          'bahasa_mandarin' => '公牛',
          'fonetik_mandarin' => 'Gōngniú',
          'kategori' => 'Hewan Darat',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Bison',
          'bahasa_inggris' => 'Bison',
          'fonetik' => 'bai-sen',
          'bahasa_arab' => 'بَيْسُون',
          'fonetik_arab' => 'Baysūn',
          'bahasa_mandarin' => '野牛',
          'fonetik_mandarin' => 'Yěniú',
          'kategori' => 'Hewan Darat',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Yak',
          'bahasa_inggris' => 'Yak',
          'fonetik' => 'yek',
          'bahasa_arab' => 'يَاك',
          'fonetik_arab' => 'Yāk',
          'bahasa_mandarin' => '牦牛',
          'fonetik_mandarin' => 'Máoniú',
          'kategori' => 'Hewan Darat',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Lemur',
          'bahasa_inggris' => 'Lemur',
          'fonetik' => 'li-mer',
          'bahasa_arab' => 'لِيْمُور',
          'fonetik_arab' => 'Līmūr',
          'bahasa_mandarin' => '狐猴',
          'fonetik_mandarin' => 'Húhóu',
          'kategori' => 'Hewan Darat',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Meerkat',
          'bahasa_inggris' => 'Meerkat',
          'fonetik' => 'mir-ket',
          'bahasa_arab' => 'سُرِيْكَات',
          'fonetik_arab' => 'Surīkāt',
          'bahasa_mandarin' => '狐獴',
          'fonetik_mandarin' => 'Húměng',
          'kategori' => 'Hewan Darat',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Hamster',
          'bahasa_inggris' => 'Hamster',
          'fonetik' => 'hem-ster',
          'bahasa_arab' => 'هَامِسْتَر',
          'fonetik_arab' => 'Hāmistar',
          'bahasa_mandarin' => '仓鼠',
          'fonetik_mandarin' => 'Cāngshǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Marmut',
          'bahasa_inggris' => 'Guinea Pig',
          'fonetik' => 'gi-ni pig',
          'bahasa_arab' => 'خِنْزِيْرُ غِيْنِيَا',
          'fonetik_arab' => 'Khinzīru Gīniyā',
          'bahasa_mandarin' => '豚鼠',
          'fonetik_mandarin' => 'Túnshǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Landak Susu',
          'bahasa_inggris' => 'Hedgehog',
          'fonetik' => 'hej-hog',
          'bahasa_arab' => 'قُنْفُذٌ بَرِّيّ',
          'fonetik_arab' => 'Qunfudhun Barriyyun',
          'bahasa_mandarin' => '刺猬',
          'fonetik_mandarin' => 'Cìwèi',
          'kategori' => 'Hewan Darat',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Trenggiling',
          'bahasa_inggris' => 'Pangolin',
          'fonetik' => 'peng-go-lin',
          'bahasa_arab' => 'آكِلُ النَّمْلِ الْحَرْشَفِيُّ',
          'fonetik_arab' => 'Ākilun Namlil Ḥarsyafī',
          'bahasa_mandarin' => '穿山甲',
          'fonetik_mandarin' => 'Chuānshānjiǎ',
          'kategori' => 'Hewan Darat',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Komodo',
          'bahasa_inggris' => 'Komodo Dragon',
          'fonetik' => 'ke-mo-do dre-gen',
          'bahasa_arab' => 'تِنِّيْنُ كُومُودُو',
          'fonetik_arab' => 'Tinnīnu Kūmūdū',
          'bahasa_mandarin' => '科莫多巨蜥',
          'fonetik_mandarin' => 'Kēmòduō jùxī',
          'kategori' => 'Hewan Darat',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Iguana',
          'bahasa_inggris' => 'Iguana',
          'fonetik' => 'i-gu-a-na',
          'bahasa_arab' => 'إِيغُوَانَا',
          'fonetik_arab' => 'Īghuwānā',
          'bahasa_mandarin' => '美洲大蜥蜴',
          'fonetik_mandarin' => 'Měizhōu dàxīyì',
          'kategori' => 'Hewan Darat',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Tokek',
          'bahasa_inggris' => 'Tokay Gecko',
          'fonetik' => 'tou-kei ge-ko',
          'bahasa_arab' => 'تُوكَاي جِيْكُو',
          'fonetik_arab' => 'Tūkāy Jīkū',
          'bahasa_mandarin' => '大壁虎',
          'fonetik_mandarin' => 'Dàbìhǔ',
          'kategori' => 'Hewan Darat',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Buaya',
          'bahasa_inggris' => 'Crocodile',
          'fonetik' => 'kro-ke-dail',
          'bahasa_arab' => 'تِمْسَاحٌ',
          'fonetik_arab' => 'Timsāḥun',
          'bahasa_mandarin' => '鳄鱼',
          'fonetik_mandarin' => 'Èyú',
          'kategori' => 'Hewan Darat',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Aligator',
          'bahasa_inggris' => 'Alligator',
          'fonetik' => 'a-li-gei-ter',
          'bahasa_arab' => 'قَاطُور',
          'fonetik_arab' => 'Qāṭūr',
          'bahasa_mandarin' => '短吻鳄',
          'fonetik_mandarin' => "Duǎnwn'è",
          'kategori' => 'Hewan Darat',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Biawak',
          'bahasa_inggris' => 'Monitor Lizard',
          'fonetik' => 'mo-ni-ter li-zerd',
          'bahasa_arab' => 'وَرَلٌ',
          'fonetik_arab' => 'Waralun',
          'bahasa_mandarin' => '巨蜥',
          'fonetik_mandarin' => 'Jùxī',
          'kategori' => 'Hewan Darat',
          'hari' => 13,
        ),
    );
  }
}