<?php

namespace Database\Seeders\Support\Game\Blueprints;

class HewanUdara
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Burung',
          'bahasa_inggris' => 'Bird',
          'fonetik' => 'berd',
          'bahasa_arab' => 'طَائِرٌ',
          'fonetik_arab' => 'Ṭāʾirun',
          'bahasa_mandarin' => '鸟',
          'fonetik_mandarin' => 'Niǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Kupu-kupu',
          'bahasa_inggris' => 'Butterfly',
          'fonetik' => 'ba-ter-flai',
          'bahasa_arab' => 'فَرَاشَةٌ',
          'fonetik_arab' => 'Farāshatun',
          'bahasa_mandarin' => '蝴蝶',
          'fonetik_mandarin' => 'Húdié',
          'kategori' => 'Hewan Udara',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Lebah',
          'bahasa_inggris' => 'Bee',
          'fonetik' => 'bi',
          'bahasa_arab' => 'نَحْلَةٌ',
          'fonetik_arab' => 'Naḥlatun',
          'bahasa_mandarin' => '蜜蜂',
          'fonetik_mandarin' => 'Mìfēng',
          'kategori' => 'Hewan Udara',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Nyamuk',
          'bahasa_inggris' => 'Mosquito',
          'fonetik' => 'mes-ki-to',
          'bahasa_arab' => 'بَعُوضَةٌ',
          'fonetik_arab' => 'Baʿūḍatun',
          'bahasa_mandarin' => '蚊子',
          'fonetik_mandarin' => 'Wénzi',
          'kategori' => 'Hewan Udara',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Elang',
          'bahasa_inggris' => 'Eagle',
          'fonetik' => 'i-gel',
          'bahasa_arab' => 'نَسْرٌ',
          'fonetik_arab' => 'Nasrún',
          'bahasa_mandarin' => '老鹰',
          'fonetik_mandarin' => 'Lǎoyīng',
          'kategori' => 'Hewan Udara',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Merpati',
          'bahasa_inggris' => 'Dove',
          'fonetik' => 'dav',
          'bahasa_arab' => 'حَمَامَةٌ',
          'fonetik_arab' => 'Ḥamāmatun',
          'bahasa_mandarin' => '鸽子',
          'fonetik_mandarin' => 'Gēzi',
          'kategori' => 'Hewan Udara',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Burung Hantu',
          'bahasa_inggris' => 'Owl',
          'fonetik' => 'aul',
          'bahasa_arab' => 'بُومَةٌ',
          'fonetik_arab' => 'Būmatun',
          'bahasa_mandarin' => '猫头鹰',
          'fonetik_mandarin' => 'Māotóuyīng',
          'kategori' => 'Hewan Udara',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Angsa',
          'bahasa_inggris' => 'Swan',
          'fonetik' => 'swon',
          'bahasa_arab' => 'إِوَزَّةٌ',
          'fonetik_arab' => 'I Wazatun',
          'bahasa_mandarin' => '天鹅',
          'fonetik_mandarin' => 'Tiān\'é',
          'kategori' => 'Hewan Udara',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Gagak',
          'bahasa_inggris' => 'Crow',
          'fonetik' => 'krou',
          'bahasa_arab' => 'غُرَابٌ',
          'fonetik_arab' => 'Ghurābun',
          'bahasa_mandarin' => '乌鸦',
          'fonetik_mandarin' => 'Wūyā',
          'kategori' => 'Hewan Udara',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Kelelawar',
          'bahasa_inggris' => 'Bat',
          'fonetik' => 'bet',
          'bahasa_arab' => 'وَطْوَاطٌ',
          'fonetik_arab' => 'Waṭwāṭun',
          'bahasa_mandarin' => '蝙蝠',
          'fonetik_mandarin' => 'Biānfú',
          'kategori' => 'Hewan Udara',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Capung',
          'bahasa_inggris' => 'Dragonfly',
          'fonetik' => 'dre-gen-flai',
          'bahasa_arab' => 'يَعْسُوبٌ',
          'fonetik_arab' => 'Yaʿsūbun',
          'bahasa_mandarin' => '蜻蜓',
          'fonetik_mandarin' => 'Qīngtíng',
          'kategori' => 'Hewan Udara',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Lalat',
          'bahasa_inggris' => 'Fly',
          'fonetik' => 'flai',
          'bahasa_arab' => 'ذُبَابَةٌ',
          'fonetik_arab' => 'Dhubābatun',
          'bahasa_mandarin' => '苍蝇',
          'fonetik_mandarin' => 'Cāngying',
          'kategori' => 'Hewan Udara',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Burung Beo',
          'bahasa_inggris' => 'Parrot',
          'fonetik' => 'pe-ret',
          'bahasa_arab' => 'بَبَّغَاءٌ',
          'fonetik_arab' => 'Babaghāʾun',
          'bahasa_mandarin' => '鹦鹉',
          'fonetik_mandarin' => 'Yīngwǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Pelikan',
          'bahasa_inggris' => 'Pelican',
          'fonetik' => 'pe-li-ken',
          'bahasa_arab' => 'بِجْعَةٌ',
          'fonetik_arab' => 'Bijʿatun',
          'bahasa_mandarin' => '鹈鹕',
          'fonetik_mandarin' => 'Tíhú',
          'kategori' => 'Hewan Udara',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Burung Kolibri',
          'bahasa_inggris' => 'Hummingbird',
          'fonetik' => 'ha-ming-berd',
          'bahasa_arab' => 'طَائِرُ الطَّنَّانِ',
          'fonetik_arab' => 'Ṭāʾir aṭ-Ṭannān',
          'bahasa_mandarin' => '蜂鸟',
          'fonetik_mandarin' => 'Fēngniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Flamingo',
          'bahasa_inggris' => 'Flamingo',
          'fonetik' => 'fla-ming-go',
          'bahasa_arab' => 'فَلَامِنْغُو',
          'fonetik_arab' => 'Falāminghū',
          'bahasa_mandarin' => '火烈鸟',
          'fonetik_mandarin' => 'Huǒlièniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Burung Unta',
          'bahasa_inggris' => 'Ostrich',
          'fonetik' => 'os-tric',
          'bahasa_arab' => 'نَعَامَةٌ',
          'fonetik_arab' => 'Naʿāmatun',
          'bahasa_mandarin' => '鸵鸟',
          'fonetik_mandarin' => 'Tuóniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Pinguin',
          'bahasa_inggris' => 'Penguin',
          'fonetik' => 'peng-gwin',
          'bahasa_arab' => 'بَطْرِيقٌ',
          'fonetik_arab' => 'Baṭrīqun',
          'bahasa_mandarin' => '企鹅',
          'fonetik_mandarin' => 'Qǐ\'é',
          'kategori' => 'Hewan Udara',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Burung Kakaktua',
          'bahasa_inggris' => 'Cockatoo',
          'fonetik' => 'ko-ka-tu',
          'bahasa_arab' => 'بَبَّغَاءُ كَاكَاتُو',
          'fonetik_arab' => 'Babaghāʾu Kākātū',
          'bahasa_mandarin' => '凤头鹦鹉',
          'fonetik_mandarin' => 'Fèngtóu yīngwǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Burung Nuri',
          'bahasa_inggris' => 'Lory',
          'fonetik' => 'lo-ri',
          'bahasa_arab' => 'بَبَّغَاءُ اللُّورِي',
          'fonetik_arab' => 'Babaghāʾul Lūrī',
          'bahasa_mandarin' => '吸蜜鹦鹉',
          'fonetik_mandarin' => 'Xīmì yīngwǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Burung Cendrawasih',
          'bahasa_inggris' => 'Bird of Paradise',
          'fonetik' => 'berd of pe-re-dais',
          'bahasa_arab' => 'طَائِرُ الْجَنَّةِ',
          'fonetik_arab' => 'Ṭāʾirul Jannati',
          'bahasa_mandarin' => '极乐鸟',
          'fonetik_mandarin' => 'Jílèniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Burung Kasuari',
          'bahasa_inggris' => 'Cassowary',
          'fonetik' => 'ka-se-we-ri',
          'bahasa_arab' => 'شَبْنَمٌ',
          'fonetik_arab' => 'Syabnamun',
          'bahasa_mandarin' => '鹤鸵',
          'fonetik_mandarin' => 'Hètuó',
          'kategori' => 'Hewan Udara',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Burung Pelatuk',
          'bahasa_inggris' => 'Woodpecker',
          'fonetik' => 'wud-pe-ker',
          'bahasa_arab' => 'نَقَّارُ الْخَشَبِ',
          'fonetik_arab' => 'Naqqārul Khasyabi',
          'bahasa_mandarin' => '啄木鸟',
          'fonetik_mandarin' => 'Zhuómùniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Burung Pipit',
          'bahasa_inggris' => 'Sparrow',
          'fonetik' => 'spe-ro',
          'bahasa_arab' => 'عُصْفُوْرٌ',
          'fonetik_arab' => 'Usfuurun',
          'bahasa_mandarin' => '麻雀',
          'fonetik_mandarin' => 'Máquè',
          'kategori' => 'Hewan Udara',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Burung Kenari',
          'bahasa_inggris' => 'Canary',
          'fonetik' => 'ke-ne-ri',
          'bahasa_arab' => 'كَنَارِيّ',
          'fonetik_arab' => 'Kanāriyyun',
          'bahasa_mandarin' => '金丝雀',
          'fonetik_mandarin' => 'Jīnsīquè',
          'kategori' => 'Hewan Udara',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Burung Jalak',
          'bahasa_inggris' => 'Starling',
          'fonetik' => 'star-ling',
          'bahasa_arab' => 'زُرْزُوْرٌ',
          'fonetik_arab' => 'Zurzuurun',
          'bahasa_mandarin' => '八哥',
          'fonetik_mandarin' => 'Bāgē',
          'kategori' => 'Hewan Udara',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Burung Manyar',
          'bahasa_inggris' => 'Weaver Bird',
          'fonetik' => 'wi-ver berd',
          'bahasa_arab' => 'طَائِرُ الْحَبَّاكِ',
          'fonetik_arab' => 'Ṭāʾirul Ḥabbāki',
          'bahasa_mandarin' => '织布鸟',
          'fonetik_mandarin' => 'Zhībùniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Burung Gereja',
          'bahasa_inggris' => 'Eurasian Tree Sparrow',
          'fonetik' => 'yu-rei-zyen tri spe-ro',
          'bahasa_arab' => 'عُصْفُوْرٌ دُوْرِيّ',
          'fonetik_arab' => 'Usfuurun Duuriyy',
          'bahasa_mandarin' => '树麻雀',
          'fonetik_mandarin' => 'Shùmáquè',
          'kategori' => 'Hewan Udara',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Burung Tekukur',
          'bahasa_inggris' => 'Spotted Dove',
          'fonetik' => 'spo-ted dav',
          'bahasa_arab' => 'حَمَامٌ مُطَوَّقٌ',
          'fonetik_arab' => 'Hamāmun Muṭawwaqun',
          'bahasa_mandarin' => '珠颈斑鸠',
          'fonetik_mandarin' => 'Zhūjǐng bānjiū',
          'kategori' => 'Hewan Udara',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Burung Perkutut',
          'bahasa_inggris' => 'Zebra Dove',
          'fonetik' => 'zi-bra dav',
          'bahasa_arab' => 'حَمَامٌ مُخَطَّطٌ',
          'fonetik_arab' => 'Hamāmun Mukhaṭṭaṭun',
          'bahasa_mandarin' => '斑姬地鸠',
          'fonetik_mandarin' => 'Bānjī dìjiū',
          'kategori' => 'Hewan Udara',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Burung Walet',
          'bahasa_inggris' => 'Swift',
          'fonetik' => 'swift',
          'bahasa_arab' => 'سَمَامَةٌ',
          'fonetik_arab' => 'Samāmatun',
          'bahasa_mandarin' => '雨燕',
          'fonetik_mandarin' => 'Yǔyàn',
          'kategori' => 'Hewan Udara',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Burung Layang-layang',
          'bahasa_inggris' => 'Swallow',
          'fonetik' => 'swa-lou',
          'bahasa_arab' => 'سُنُوْنُوْ',
          'fonetik_arab' => 'Sunuunuu',
          'bahasa_mandarin' => '燕子',
          'fonetik_mandarin' => 'Yànzi',
          'kategori' => 'Hewan Udara',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Burung Rajawali',
          'bahasa_inggris' => 'Falcon',
          'fonetik' => 'fel-ken',
          'bahasa_arab' => 'صَقْرٌ',
          'fonetik_arab' => 'Ṣaqrun',
          'bahasa_mandarin' => '隼',
          'fonetik_mandarin' => 'Sǔn',
          'kategori' => 'Hewan Udara',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Burung Bangau',
          'bahasa_inggris' => 'Stork',
          'fonetik' => 'stork',
          'bahasa_arab' => 'لَقْلَقٌ',
          'fonetik_arab' => 'Laqlaqun',
          'bahasa_mandarin' => '鹳',
          'fonetik_mandarin' => 'Guàn',
          'kategori' => 'Hewan Udara',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Burung Kuntul',
          'bahasa_inggris' => 'Egret',
          'fonetik' => 'i-gret',
          'bahasa_arab' => 'بَلَشُوْنٌ',
          'fonetik_arab' => 'Balasyuunun',
          'bahasa_mandarin' => '白鹭',
          'fonetik_mandarin' => 'Báilù',
          'kategori' => 'Hewan Udara',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Burung Camar',
          'bahasa_inggris' => 'Seagull',
          'fonetik' => 'si-gal',
          'bahasa_arab' => 'نَوْرَسٌ',
          'fonetik_arab' => 'Nawrasun',
          'bahasa_mandarin' => '海鸥',
          'fonetik_mandarin' => 'Hǎiōu',
          'kategori' => 'Hewan Udara',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Burung Merak',
          'bahasa_inggris' => 'Peacock',
          'fonetik' => 'pi-kok',
          'bahasa_arab' => 'طَاوُوْسٌ',
          'fonetik_arab' => 'Ṭāwūsun',
          'bahasa_mandarin' => '孔雀',
          'fonetik_mandarin' => 'Kǒngquè',
          'kategori' => 'Hewan Udara',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Burung Albatros',
          'bahasa_inggris' => 'Albatross',
          'fonetik' => 'al-be-tros',
          'bahasa_arab' => 'قَطْرَسٌ',
          'fonetik_arab' => 'Qaṭrasun',
          'bahasa_mandarin' => '信天翁',
          'fonetik_mandarin' => 'Xìntiānwēng',
          'kategori' => 'Hewan Udara',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Burung Elang Bondol',
          'bahasa_inggris' => 'Brahminy Kite',
          'fonetik' => 'bra-mi-ni kait',
          'bahasa_arab' => 'حِدَأَةٌ بَرَاهِمِيَّة',
          'fonetik_arab' => 'Ḥidaʾatun Barāhimiyyah',
          'bahasa_mandarin' => '栗鸢',
          'fonetik_mandarin' => 'Lìyuān',
          'kategori' => 'Hewan Udara',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Burung Elang Jawa',
          'bahasa_inggris' => 'Javan Hawk-Eagle',
          'fonetik' => 'ja-ven hok i-gel',
          'bahasa_arab' => 'عُقَابُ الْجَاوِيّ',
          'fonetik_arab' => 'ʿUqābul Jāwiyy',
          'bahasa_mandarin' => '爪哇鹰雕',
          'fonetik_mandarin' => 'Zhǎowā yīngdiāo',
          'kategori' => 'Hewan Udara',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Burung Bangau Bluwok',
          'bahasa_inggris' => 'Milky Stork',
          'fonetik' => 'mil-ki stork',
          'bahasa_arab' => 'لَقْلَقٌ لَبَنِيّ',
          'fonetik_arab' => 'Laqlaqun Labaniyy',
          'bahasa_mandarin' => '白鹮鹳',
          'fonetik_mandarin' => 'Báihuánguàn',
          'kategori' => 'Hewan Udara',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Burung Cerek',
          'bahasa_inggris' => 'Plover',
          'fonetik' => 'pla-ver',
          'bahasa_arab' => 'زَقْزَاقٌ',
          'fonetik_arab' => 'Zaqzāqun',
          'bahasa_mandarin' => '鸻',
          'fonetik_mandarin' => 'Héng',
          'kategori' => 'Hewan Udara',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Burung Serak Jawa',
          'bahasa_inggris' => 'Barn Owl',
          'fonetik' => 'barn aul',
          'bahasa_arab' => 'هَامَةٌ',
          'fonetik_arab' => 'Hāmatun',
          'bahasa_mandarin' => '仓鸮',
          'fonetik_mandarin' => 'Cāngxiāo',
          'kategori' => 'Hewan Udara',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Burung Elang Tikus',
          'bahasa_inggris' => 'Black-winged Kite',
          'fonetik' => 'blek-wing kait',
          'bahasa_arab' => 'حِدَأَةٌ مَسْوَدَّةُ الْجَنَاحِ',
          'fonetik_arab' => 'Ḥidaʾatun Maswaddatul Janāḥi',
          'bahasa_mandarin' => '黑翅鸢',
          'fonetik_mandarin' => 'Hēichì yuān',
          'kategori' => 'Hewan Udara',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Burung Gagak Bangkai',
          'bahasa_inggris' => 'Carrion Crow',
          'fonetik' => 'ke-ri-yen krou',
          'bahasa_arab' => 'غُرَابُ الْأَسْحَم',
          'fonetik_arab' => 'Ghurābul As-ḥam',
          'bahasa_mandarin' => '小嘴乌鸦',
          'fonetik_mandarin' => 'Xiǎozuǐ wūyā',
          'kategori' => 'Hewan Udara',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Burung Nazar',
          'bahasa_inggris' => 'Vulture',
          'fonetik' => 'val-cer',
          'bahasa_arab' => 'نَسْرٌ',
          'fonetik_arab' => 'Nasrun',
          'bahasa_mandarin' => '秃鹫',
          'fonetik_mandarin' => 'Tūjiù',
          'kategori' => 'Hewan Udara',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Burung Kondor',
          'bahasa_inggris' => 'Condor',
          'fonetik' => 'kon-der',
          'bahasa_arab' => 'كُونْدُور',
          'fonetik_arab' => 'Kūndūr',
          'bahasa_mandarin' => '秃鹰',
          'fonetik_mandarin' => 'Tūyīng',
          'kategori' => 'Hewan Udara',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Burung Sekretaris',
          'bahasa_inggris' => 'Secretary Bird',
          'fonetik' => 'se-kre-te-ri berd',
          'bahasa_arab' => 'طَائِرُ السِّكْرِيتِيْر',
          'fonetik_arab' => 'Ṭāʾirus Sikrītiyīr',
          'bahasa_mandarin' => '蛇鹫',
          'fonetik_mandarin' => 'Shéjiù',
          'kategori' => 'Hewan Udara',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Tawon',
          'bahasa_inggris' => 'Wasp',
          'fonetik' => 'wosp',
          'bahasa_arab' => 'دَبُّورٌ',
          'fonetik_arab' => 'Dabbūrun',
          'bahasa_mandarin' => '黄蜂',
          'fonetik_mandarin' => 'Huángfēng',
          'kategori' => 'Hewan Udara',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Hornet',
          'bahasa_inggris' => 'Hornet',
          'fonetik' => 'hor-net',
          'bahasa_arab' => 'زُنْبُورٌ',
          'fonetik_arab' => 'Zunbūrun',
          'bahasa_mandarin' => '大黄蜂',
          'fonetik_mandarin' => 'Dàhuángfēng',
          'kategori' => 'Hewan Udara',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Kumbang Koksi',
          'bahasa_inggris' => 'Ladybug',
          'fonetik' => 'lei-di-bag',
          'bahasa_arab' => 'خُنْفُسَاءُ مَنْقُوطَة',
          'fonetik_arab' => 'Khunfusyāʾu Manqūṭah',
          'bahasa_mandarin' => '瓢虫',
          'fonetik_mandarin' => 'Piáochóng',
          'kategori' => 'Hewan Udara',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Wereng',
          'bahasa_inggris' => 'Planthopper',
          'fonetik' => 'plent-ho-per',
          'bahasa_arab' => 'قَفَّازُ النَّبَات',
          'fonetik_arab' => 'Qaffāzun Nabāti',
          'bahasa_mandarin' => '飞虱',
          'fonetik_mandarin' => 'Fēishī',
          'kategori' => 'Hewan Udara',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Ngengat',
          'bahasa_inggris' => 'Moth',
          'fonetik' => 'moth',
          'bahasa_arab' => 'عُثَّةٌ',
          'fonetik_arab' => 'ʿUththatun',
          'bahasa_mandarin' => '蛾',
          'fonetik_mandarin' => 'É',
          'kategori' => 'Hewan Udara',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Ulat Sutra',
          'bahasa_inggris' => 'Silkworm Moth',
          'fonetik' => 'silk-werm moth',
          'bahasa_arab' => 'عُثَّةُ دُوْدَةِ الْقَزّ',
          'fonetik_arab' => 'ʿUththatu Duudatil Qazzi',
          'bahasa_mandarin' => '蚕蛾',
          'fonetik_mandarin' => "Cán'é",
          'kategori' => 'Hewan Udara',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Kalong',
          'bahasa_inggris' => 'Flying Fox',
          'fonetik' => 'flai-ing foks',
          'bahasa_arab' => 'ثَعْلَبٌ طَيَّارٌ',
          'fonetik_arab' => 'Thaʿlabun Ṭayyārun',
          'bahasa_mandarin' => '狐蝠',
          'fonetik_mandarin' => 'Húfú',
          'kategori' => 'Hewan Udara',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Codot',
          'bahasa_inggris' => 'Short-nosed Fruit Bat',
          'fonetik' => 'syort-nouzd frut bet',
          'bahasa_arab' => 'خُفَّاشُ الثَّمَار',
          'fonetik_arab' => 'Khuffāsyuts Tsamāri',
          'bahasa_mandarin' => '果蝠',
          'fonetik_mandarin' => 'Guǒfú',
          'kategori' => 'Hewan Udara',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Kelelawar Tapal Kuda',
          'bahasa_inggris' => 'Horseshoe Bat',
          'fonetik' => 'hors-syu bet',
          'bahasa_arab' => 'خُفَّاشُ حِذَاءِ الْفَرَس',
          'fonetik_arab' => 'Khuffāsyu Ḥidhāʾil Farasi',
          'bahasa_mandarin' => '菊头蝠',
          'fonetik_mandarin' => 'Jútóufú',
          'kategori' => 'Hewan Udara',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Lemur Terbang',
          'bahasa_inggris' => 'Colugo',
          'fonetik' => 'ko-lu-go',
          'bahasa_arab' => 'لِيْمُور طَيَّار',
          'fonetik_arab' => 'Līmūr Ṭayyārun',
          'bahasa_mandarin' => '鼯猴',
          'fonetik_mandarin' => 'Wúhóu',
          'kategori' => 'Hewan Udara',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Bajing Terbang',
          'bahasa_inggris' => 'Flying Squirrel',
          'fonetik' => 'flai-ing skwi-rel',
          'bahasa_arab' => 'سَنْجَابٌ طَيَّارٌ',
          'fonetik_arab' => 'Sanjābun Ṭayyārun',
          'bahasa_mandarin' => '鼯鼠',
          'fonetik_mandarin' => 'Wúshǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Kadal Terbang',
          'bahasa_inggris' => 'Draco Lizard',
          'fonetik' => 'dra-ko li-zerd',
          'bahasa_arab' => 'سِحْلِيَّةٌ طَيَّارَة',
          'fonetik_arab' => 'Siḥliyyatun Ṭayyārah',
          'bahasa_mandarin' => '飞蜥',
          'fonetik_mandarin' => 'Fēixī',
          'kategori' => 'Hewan Udara',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Ayam Hutan',
          'bahasa_inggris' => 'Junglefowl',
          'fonetik' => 'jang-gel-foul',
          'bahasa_arab' => 'دَجَاجُ الْغَابَةِ',
          'fonetik_arab' => 'Dajājul Ghābati',
          'bahasa_mandarin' => '原鸡',
          'fonetik_mandarin' => 'Yuánjī',
          'kategori' => 'Hewan Udara',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Burung Puyuh',
          'bahasa_inggris' => 'Quail',
          'fonetik' => 'kweil',
          'bahasa_arab' => 'سُمَانَى',
          'fonetik_arab' => 'Sumānā',
          'bahasa_mandarin' => '鹌鹑',
          'fonetik_mandarin' => 'Ānchún',
          'kategori' => 'Hewan Udara',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Burung Maleo',
          'bahasa_inggris' => 'Maleo',
          'fonetik' => 'ma-le-o',
          'bahasa_arab' => 'مَالِيو',
          'fonetik_arab' => 'Māliyū',
          'bahasa_mandarin' => '苏拉冢雉',
          'fonetik_mandarin' => 'Sūlā zhǒngzhì',
          'kategori' => 'Hewan Udara',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Burung Kiwi',
          'bahasa_inggris' => 'Kiwi Bird',
          'fonetik' => 'ki-wi berd',
          'bahasa_arab' => 'كِيْوِي',
          'fonetik_arab' => 'Kīwī',
          'bahasa_mandarin' => '几维鸟',
          'fonetik_mandarin' => 'Jǐwéiniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Burung Emu',
          'bahasa_inggris' => 'Emu',
          'fonetik' => 'i-myu',
          'bahasa_arab' => 'إِيْمُو',
          'fonetik_arab' => 'Īmyū',
          'bahasa_mandarin' => '鸸鹋',
          'fonetik_mandarin' => 'Érmiáo',
          'kategori' => 'Hewan Udara',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Burung Merpati Hutan',
          'bahasa_inggris' => 'Wood Pigeon',
          'fonetik' => 'wud pi-jen',
          'bahasa_arab' => 'حَمَامُ الْغَابَةِ',
          'fonetik_arab' => 'Ḥamāmul Ghābati',
          'bahasa_mandarin' => '斑尾林鸽',
          'fonetik_mandarin' => 'Bānwěi língē',
          'kategori' => 'Hewan Udara',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Burung Lovebird',
          'bahasa_inggris' => 'Lovebird',
          'fonetik' => 'lav-berd',
          'bahasa_arab' => 'طَائِرُ الْحُبِّ',
          'fonetik_arab' => 'Ṭāʾirul Ḥubbi',
          'bahasa_mandarin' => '情侣鹦鹉',
          'fonetik_mandarin' => 'Qínglǚ yīngwǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Burung Parkit',
          'bahasa_inggris' => 'Parakeet',
          'fonetik' => 'pa-re-kit',
          'bahasa_arab' => 'دُرَّةٌ',
          'fonetik_arab' => 'Durratun',
          'bahasa_mandarin' => '长尾鹦鹉',
          'fonetik_mandarin' => 'Chángwěi yīngwǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Burung Macaw',
          'bahasa_inggris' => 'Macaw',
          'fonetik' => 'ma-ko',
          'bahasa_arab' => 'مَكَّاو',
          'fonetik_arab' => 'Makkāw',
          'bahasa_mandarin' => '金刚鹦鹉',
          'fonetik_mandarin' => 'Jīngāng yīngwǔ',
          'kategori' => 'Hewan Udara',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Burung Tukan',
          'bahasa_inggris' => 'Toucan',
          'fonetik' => 'tu-ken',
          'bahasa_arab' => 'طُوقَانٌ',
          'fonetik_arab' => 'Ṭūqānun',
          'bahasa_mandarin' => '巨嘴鸟',
          'fonetik_mandarin' => 'Jùzuǐniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Burung Rangkong',
          'bahasa_inggris' => 'Hornbill',
          'fonetik' => 'horn-bil',
          'bahasa_arab' => 'أَبُو مَنْجَلٍ',
          'fonetik_arab' => 'Abū Manjalin',
          'bahasa_mandarin' => '犀鸟',
          'fonetik_mandarin' => 'Xīniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Burung Enggang',
          'bahasa_inggris' => 'Buceros',
          'fonetik' => 'bu-se-ros',
          'bahasa_arab' => 'إِنْغَانْغ',
          'fonetik_arab' => "Ingān'gh",
          'bahasa_mandarin' => '双角犀鸟',
          'fonetik_mandarin' => 'Shuāngjiǎo xīniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Burung Murai Batu',
          'bahasa_inggris' => 'White-rumped Shama',
          'fonetik' => 'wait-rampt syama',
          'bahasa_arab' => 'مُورَاي بَاتُو',
          'fonetik_arab' => 'Mūrāy Bātū',
          'bahasa_mandarin' => '白腰鹊鸲',
          'fonetik_mandarin' => 'Báiyāo quèqú',
          'kategori' => 'Hewan Udara',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Burung Kacer',
          'bahasa_inggris' => 'Oriental Magpie-Robin',
          'fonetik' => 'o-ri-yen-tel meg-pai ro-bin',
          'bahasa_arab' => 'كَاتْشِيْر',
          'fonetik_arab' => 'Kātshīr',
          'bahasa_mandarin' => '鹊鸲',
          'fonetik_mandarin' => 'Quèqú',
          'kategori' => 'Hewan Udara',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Burung Cucak Ijo',
          'bahasa_inggris' => 'Greater Green Leafbird',
          'fonetik' => 'grei-ter grin lif-berd',
          'bahasa_arab' => 'تْشُوتْشَاك إِيْجُو',
          'fonetik_arab' => 'Tsyūtsyāk Ījū',
          'bahasa_mandarin' => '大绿叶鹎',
          'fonetik_mandarin' => 'Dà lǜyèbēi',
          'kategori' => 'Hewan Udara',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Burung Pleci',
          'bahasa_inggris' => 'White-eye Bird',
          'fonetik' => 'wait-ai berd',
          'bahasa_arab' => 'بْلِيْتْشِي',
          'fonetik_arab' => 'Blītsyī',
          'bahasa_mandarin' => '绣眼鸟',
          'fonetik_mandarin' => 'Xiùyǎnniǎo',
          'kategori' => 'Hewan Udara',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Burung Anis Merah',
          'bahasa_inggris' => 'Orange-headed Thrush',
          'fonetik' => 'o-renj-he-ded thrasy',
          'bahasa_arab' => 'أَنِيْس مِيْرَاه',
          'fonetik_arab' => 'Anīs Mīrāh',
          'bahasa_mandarin' => '橙头地鸫',
          'fonetik_mandarin' => 'Chéngtóu dìdōng',
          'kategori' => 'Hewan Udara',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Burung Kepodang',
          'bahasa_inggris' => 'Black-naped Oriole',
          'fonetik' => 'blek-neipt o-ri-yol',
          'bahasa_arab' => 'أُورِيُول',
          'fonetik_arab' => 'Ūriyūl',
          'bahasa_mandarin' => '黑枕黄鹂',
          'fonetik_mandarin' => 'Hēizhěn huánglí',
          'kategori' => 'Hewan Udara',
          'hari' => 13,
        ),
    );
  }
}