<?php

namespace Database\Seeders\Support\Game\Blueprints;

class HewanLaut
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Ikan',
          'bahasa_inggris' => 'Fish',
          'fonetik' => 'fisy',
          'bahasa_arab' => 'سَمَكَةٌ',
          'fonetik_arab' => 'Samakatun',
          'bahasa_mandarin' => '鱼',
          'fonetik_mandarin' => 'Yú',
          'kategori' => 'Hewan Laut',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Hiu',
          'bahasa_inggris' => 'Shark',
          'fonetik' => 'syark',
          'bahasa_arab' => 'قِرْشٌ',
          'fonetik_arab' => 'Qirshun',
          'bahasa_mandarin' => '鲨鱼',
          'fonetik_mandarin' => 'Shāyú',
          'kategori' => 'Hewan Laut',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Paus',
          'bahasa_inggris' => 'Whale',
          'fonetik' => 'weyl',
          'bahasa_arab' => 'حُوتٌ',
          'fonetik_arab' => 'Ḥūtun',
          'bahasa_mandarin' => '鲸鱼',
          'fonetik_mandarin' => 'Jīngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Lumba-lumba',
          'bahasa_inggris' => 'Dolphin',
          'fonetik' => 'dol-fin',
          'bahasa_arab' => 'دُلْفِينٌ',
          'fonetik_arab' => 'Dulfīnún',
          'bahasa_mandarin' => '海豚',
          'fonetik_mandarin' => 'Hǎitún',
          'kategori' => 'Hewan Laut',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Gurita',
          'bahasa_inggris' => 'Octopus',
          'fonetik' => 'ok-to-pes',
          'bahasa_arab' => 'أَخْطَبُوطٌ',
          'fonetik_arab' => 'Akhṭabūṭun',
          'bahasa_mandarin' => '章鱼',
          'fonetik_mandarin' => 'Zhāngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Kepiting',
          'bahasa_inggris' => 'Crab',
          'fonetik' => 'kreb',
          'bahasa_arab' => 'سَرَطَانٌ',
          'fonetik_arab' => 'Saraṭānun',
          'bahasa_mandarin' => '螃蟹',
          'fonetik_mandarin' => 'Pángxiè',
          'kategori' => 'Hewan Laut',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Udang',
          'bahasa_inggris' => 'Shrimp',
          'fonetik' => 'syrimp',
          'bahasa_arab' => 'جَمْبَرِيٌّ',
          'fonetik_arab' => 'Jambariyyun',
          'bahasa_mandarin' => '虾',
          'fonetik_mandarin' => 'Xiā',
          'kategori' => 'Hewan Laut',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Penyu',
          'bahasa_inggris' => 'Turtle',
          'fonetik' => 'ter-tel',
          'bahasa_arab' => 'سُلَحْفَاةٌ',
          'fonetik_arab' => 'Sulaḥfāh',
          'bahasa_mandarin' => '海龟',
          'fonetik_mandarin' => 'Hǎiguī',
          'kategori' => 'Hewan Laut',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Ubur-ubur',
          'bahasa_inggris' => 'Jellyfish',
          'fonetik' => 'je-li-fisy',
          'bahasa_arab' => 'قِنْدِيلُ الْبَحْرِ',
          'fonetik_arab' => 'Qindīl al-Baḥr',
          'bahasa_mandarin' => '水母',
          'fonetik_mandarin' => 'Shuǐmǔ',
          'kategori' => 'Hewan Laut',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Bintang Laut',
          'bahasa_inggris' => 'Starfish',
          'fonetik' => 'star-fisy',
          'bahasa_arab' => 'نَجْمَةُ الْبَحْرِ',
          'fonetik_arab' => 'Najmat al-Baḥr',
          'bahasa_mandarin' => '海星',
          'fonetik_mandarin' => 'Hǎixīng',
          'kategori' => 'Hewan Laut',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Anjing Laut',
          'bahasa_inggris' => 'Seal',
          'fonetik' => 'sil',
          'bahasa_arab' => 'فُقْمَةٌ',
          'fonetik_arab' => 'Fuqmatun',
          'bahasa_mandarin' => '海豹',
          'fonetik_mandarin' => 'Hǎibào',
          'kategori' => 'Hewan Laut',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Kuda Laut',
          'bahasa_inggris' => 'Seahorse',
          'fonetik' => 'si-hors',
          'bahasa_arab' => 'حِصَانُ الْبَحْرِ',
          'fonetik_arab' => 'Ḥiṣān al-Baḥr',
          'bahasa_mandarin' => '海马',
          'fonetik_mandarin' => 'Hǎimǎ',
          'kategori' => 'Hewan Laut',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Cumi-cumi',
          'bahasa_inggris' => 'Squid',
          'fonetik' => 'skwid',
          'bahasa_arab' => 'حَبَّارٌ',
          'fonetik_arab' => 'Ḥabbārun',
          'bahasa_mandarin' => '鱿鱼',
          'fonetik_mandarin' => 'Yóuyú',
          'kategori' => 'Hewan Laut',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Kerang',
          'bahasa_inggris' => 'Clam',
          'fonetik' => 'klem',
          'bahasa_arab' => 'مَحَارٌ',
          'fonetik_arab' => 'Maḥārun',
          'bahasa_mandarin' => '蛤蜊',
          'fonetik_mandarin' => 'Gélí',
          'kategori' => 'Hewan Laut',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Tiram',
          'bahasa_inggris' => 'Oyster',
          'fonetik' => 'ois-ter',
          'bahasa_arab' => 'مَحَارَةٌ',
          'fonetik_arab' => 'Maḥāratun',
          'bahasa_mandarin' => '牡蛎',
          'fonetik_mandarin' => 'Mǔlì',
          'kategori' => 'Hewan Laut',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Lobster',
          'bahasa_inggris' => 'Lobster',
          'fonetik' => 'lob-ster',
          'bahasa_arab' => 'كَرْكَنْدُ',
          'fonetik_arab' => 'Karkandun',
          'bahasa_mandarin' => '龙虾',
          'fonetik_mandarin' => 'Lóngxiā',
          'kategori' => 'Hewan Laut',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Ikan Pari',
          'bahasa_inggris' => 'Stingray',
          'fonetik' => 'sting-rey',
          'bahasa_arab' => 'لَاذِعٌ بَحْرِيٌّ',
          'fonetik_arab' => 'Lādhiʿ Baḥrī',
          'bahasa_mandarin' => '黄貂鱼',
          'fonetik_mandarin' => 'Huángdiāoyú',
          'kategori' => 'Hewan Laut',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Singa Laut',
          'bahasa_inggris' => 'Sea lion',
          'fonetik' => 'si lai-yen',
          'bahasa_arab' => 'أَسَدُ الْبَحْرِ',
          'fonetik_arab' => 'Asad al-Baḥr',
          'bahasa_mandarin' => '海狮',
          'fonetik_mandarin' => 'Hǎishī',
          'kategori' => 'Hewan Laut',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Ikan Badut',
          'bahasa_inggris' => 'Clownfish',
          'fonetik' => 'klaun-fish',
          'bahasa_arab' => 'سَمَكَةُ الْمَهْرِجِ',
          'fonetik_arab' => 'Samakat al-Mahrāj',
          'bahasa_mandarin' => '小丑鱼',
          'fonetik_mandarin' => 'Xiǎochǒuyú',
          'kategori' => 'Hewan Laut',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Belut',
          'bahasa_inggris' => 'Eel',
          'fonetik' => 'il',
          'bahasa_arab' => 'ثُعْبَانُ الْبَحْرِ',
          'fonetik_arab' => 'Thuʿbān al-Baḥr',
          'bahasa_mandarin' => '鳗鱼',
          'fonetik_mandarin' => 'Mányú',
          'kategori' => 'Hewan Laut',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Walrus',
          'bahasa_inggris' => 'Walrus',
          'fonetik' => 'wol-res',
          'bahasa_arab' => 'فَظٌّ',
          'fonetik_arab' => 'Faẓẓun',
          'bahasa_mandarin' => '海象',
          'fonetik_mandarin' => 'Hǎixiàng',
          'kategori' => 'Hewan Laut',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Teripang',
          'bahasa_inggris' => 'Sea cucumber',
          'fonetik' => 'si kyu-kam-ber',
          'bahasa_arab' => 'خِيَارُ الْبَحْرِ',
          'fonetik_arab' => 'Khiyār al-Baḥr',
          'bahasa_mandarin' => '海参',
          'fonetik_mandarin' => 'Hǎishēn',
          'kategori' => 'Hewan Laut',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Bulu Babi',
          'bahasa_inggris' => 'Sea urchin',
          'fonetik' => 'si er-cin',
          'bahasa_arab' => 'قُنْفُذُ الْبَحْرِ',
          'fonetik_arab' => 'Qunfudh al-Baḥr',
          'bahasa_mandarin' => '海胆',
          'fonetik_mandarin' => 'Hǎidǎn',
          'kategori' => 'Hewan Laut',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Karang',
          'bahasa_inggris' => 'Coral',
          'fonetik' => 'ko-ral',
          'bahasa_arab' => 'مُرْجَانٌ',
          'fonetik_arab' => 'Murjānun',
          'bahasa_mandarin' => '珊瑚',
          'fonetik_mandarin' => 'Shānhú',
          'kategori' => 'Hewan Laut',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Ikan Salmon',
          'bahasa_inggris' => 'Salmon',
          'fonetik' => 'se-men',
          'bahasa_arab' => 'سَمَكُ السَّلَمُوْن',
          'fonetik_arab' => 'Samak as-Salamūn',
          'bahasa_mandarin' => '三文鱼',
          'fonetik_mandarin' => 'Sānwényú',
          'kategori' => 'Hewan Laut',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Ikan Tuna',
          'bahasa_inggris' => 'Tuna',
          'fonetik' => 'tyu-na',
          'bahasa_arab' => 'تُوْنَةٌ',
          'fonetik_arab' => 'Tūnatun',
          'bahasa_mandarin' => '金枪鱼',
          'fonetik_mandarin' => 'Jīnqiāngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Paus Pembunuh',
          'bahasa_inggris' => 'Orca',
          'fonetik' => 'or-ka',
          'bahasa_arab' => 'أُورْكَا',
          'fonetik_arab' => 'Ūrkā',
          'bahasa_mandarin' => '虎鲸',
          'fonetik_mandarin' => 'Hǔjīng',
          'kategori' => 'Hewan Laut',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Paus Biru',
          'bahasa_inggris' => 'Blue Whale',
          'fonetik' => 'blu weyl',
          'bahasa_arab' => 'الْحُوْتُ الْأَزْرَق',
          'fonetik_arab' => 'Al-Ḥūt al-Azraq',
          'bahasa_mandarin' => '蓝鲸',
          'fonetik_mandarin' => 'Lánjīng',
          'kategori' => 'Hewan Laut',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Ikan Sarden',
          'bahasa_inggris' => 'Sardine',
          'fonetik' => 'sar-din',
          'bahasa_arab' => 'سَرْدِيْنٌ',
          'fonetik_arab' => 'Sardīnun',
          'bahasa_mandarin' => '沙丁鱼',
          'fonetik_mandarin' => 'Shādīngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Ikan Teri',
          'bahasa_inggris' => 'Anchovy',
          'fonetik' => 'en-co-vi',
          'bahasa_arab' => 'أَنْشُوفَةٌ',
          'fonetik_arab' => 'Ansyūfatun',
          'bahasa_mandarin' => '凤尾鱼',
          'fonetik_mandarin' => 'Fèngwěiyú',
          'kategori' => 'Hewan Laut',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Ikan Kembung',
          'bahasa_inggris' => 'Mackerel',
          'fonetik' => 'ma-ke-rel',
          'bahasa_arab' => 'إِسْقُمْرِيّ',
          'fonetik_arab' => 'Isqumriyyun',
          'bahasa_mandarin' => '鲭鱼',
          'fonetik_mandarin' => 'Qīngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Ikan Pedang',
          'bahasa_inggris' => 'Swordfish',
          'fonetik' => 'sord-fish',
          'bahasa_arab' => 'أَبُو سَيْفٍ',
          'fonetik_arab' => 'Abū Sayfin',
          'bahasa_mandarin' => '剑鱼',
          'fonetik_mandarin' => 'Jiànyú',
          'kategori' => 'Hewan Laut',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Ikan Layaran',
          'bahasa_inggris' => 'Sailfish',
          'fonetik' => 'seil-fish',
          'bahasa_arab' => 'سَمَكُ الشِّرَاعِ',
          'fonetik_arab' => 'Samak as-Syirāʾi',
          'bahasa_mandarin' => '旗鱼',
          'fonetik_mandarin' => 'Qíyú',
          'kategori' => 'Hewan Laut',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Ikan Terbang',
          'bahasa_inggris' => 'Flying fish',
          'fonetik' => 'flai-ing fish',
          'bahasa_arab' => 'سَمَكٌ طَيَّارٌ',
          'fonetik_arab' => 'Samakun Ṭayyārun',
          'bahasa_mandarin' => '飞鱼',
          'fonetik_mandarin' => 'Fēiyú',
          'kategori' => 'Hewan Laut',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Ikan Buntal',
          'bahasa_inggris' => 'Pufferfish',
          'fonetik' => 'pa-fer-fish',
          'bahasa_arab' => 'سَمَكَةٌ مُنْتَفِخَةٌ',
          'fonetik_arab' => 'Samakatun Muntafikhah',
          'bahasa_mandarin' => '河豚',
          'fonetik_mandarin' => 'Hétún',
          'kategori' => 'Hewan Laut',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Ikan Angler',
          'bahasa_inggris' => 'Anglerfish',
          'fonetik' => 'eng-gler-fish',
          'bahasa_arab' => 'أَبُو الشِّيْصِ',
          'fonetik_arab' => 'Abū as-Syīṣi',
          'bahasa_mandarin' => '鮟鱇鱼',
          'fonetik_mandarin' => 'Ānkāngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Ikan Naga',
          'bahasa_inggris' => 'Dragonfish',
          'fonetik' => 'dre-gen-fish',
          'bahasa_arab' => 'السَّمَكُ التِّنِّين',
          'fonetik_arab' => 'As-Samak at-Tinnīn',
          'bahasa_mandarin' => '龙鱼',
          'fonetik_mandarin' => 'Lóngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Ikan Senter',
          'bahasa_inggris' => 'Lanternfish',
          'fonetik' => 'len-tern-fish',
          'bahasa_arab' => 'سَمَكَةُ الْفَانُوسِ',
          'fonetik_arab' => 'Samakat al-Fānūsi',
          'bahasa_mandarin' => '灯笼鱼',
          'fonetik_mandarin' => 'Dēnglóngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Belut Listrik',
          'bahasa_inggris' => 'Electric Eel',
          'fonetik' => 'e-lek-trik il',
          'bahasa_arab' => 'أَنْقَلِيسٌ كَهْرَبَائِيٌّ',
          'fonetik_arab' => 'Anqalīsun Kahrabāʾiyyun',
          'bahasa_mandarin' => '电鳗',
          'fonetik_mandarin' => 'Diànmán',
          'kategori' => 'Hewan Laut',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Sotong',
          'bahasa_inggris' => 'Cuttlefish',
          'fonetik' => 'ka-tel-fish',
          'bahasa_arab' => 'خَثَّاقٌ',
          'fonetik_arab' => 'Khathsāqun',
          'bahasa_mandarin' => '乌贼',
          'fonetik_mandarin' => 'Wūzéi',
          'kategori' => 'Hewan Laut',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Nautilus',
          'bahasa_inggris' => 'Nautilus',
          'fonetik' => 'no-ti-les',
          'bahasa_arab' => 'نُوتِيْلُوس',
          'fonetik_arab' => 'Nūtīlūs',
          'bahasa_mandarin' => '鹦鹉螺',
          'fonetik_mandarin' => 'Yīngwǔluó',
          'kategori' => 'Hewan Laut',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Dugong',
          'bahasa_inggris' => 'Dugong',
          'fonetik' => 'du-gong',
          'bahasa_arab' => 'أُطُوْمٌ',
          'fonetik_arab' => 'Uṭūmun',
          'bahasa_mandarin' => '儒艮',
          'fonetik_mandarin' => 'Rúgèn',
          'kategori' => 'Hewan Laut',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Ikan Dori',
          'bahasa_inggris' => 'Blue Tang',
          'fonetik' => 'blu teng',
          'bahasa_arab' => 'تَانْغُ الْأَزْرَق',
          'fonetik_arab' => 'Tāng al-Azraq',
          'bahasa_mandarin' => '蓝唐王鱼',
          'fonetik_mandarin' => 'Lántáng wángyú',
          'kategori' => 'Hewan Laut',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Ikan Kepe-kepe',
          'bahasa_inggris' => 'Butterflyfish',
          'fonetik' => 'ba-ter-flai-fish',
          'bahasa_arab' => 'سَمَكَةُ الْفَرَاشَةِ',
          'fonetik_arab' => 'Samakat al-Farāsyati',
          'bahasa_mandarin' => '蝴蝶鱼',
          'fonetik_mandarin' => 'Húdiéyú',
          'kategori' => 'Hewan Laut',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Ikan Kakatua',
          'bahasa_inggris' => 'Parrotfish',
          'fonetik' => 'pe-ret-fish',
          'bahasa_arab' => 'سَمَكَةُ الْبَبَّغَاءِ',
          'fonetik_arab' => 'Samakat al-Babaghāʾi',
          'bahasa_mandarin' => '鹦嘴鱼',
          'fonetik_mandarin' => 'Yīngzuǐyú',
          'kategori' => 'Hewan Laut',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Ikan Sumpit',
          'bahasa_inggris' => 'Archerfish',
          'fonetik' => 'ar-cer-fish',
          'bahasa_arab' => 'السَّمَكُ النَّبَّال',
          'fonetik_arab' => 'As-Samak an-Nabbāl',
          'bahasa_mandarin' => '射水鱼',
          'fonetik_mandarin' => 'Shèshuǐyú',
          'kategori' => 'Hewan Laut',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Ikan Barakuda',
          'bahasa_inggris' => 'Barracuda',
          'fonetik' => 'ba-re-ku-da',
          'bahasa_arab' => 'بَارَاكُودَا',
          'fonetik_arab' => 'Bārākūdā',
          'bahasa_mandarin' => '梭子鱼',
          'fonetik_mandarin' => 'Suōzīyú',
          'kategori' => 'Hewan Laut',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Ikan Todak',
          'bahasa_inggris' => 'Marlin',
          'fonetik' => 'mar-lin',
          'bahasa_arab' => 'مَارْلِيْن',
          'fonetik_arab' => 'Mārlīn',
          'bahasa_mandarin' => '马林鱼',
          'fonetik_mandarin' => 'Mǎlínyú',
          'kategori' => 'Hewan Laut',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Gajah Laut',
          'bahasa_inggris' => 'Elephant Seal',
          'fonetik' => 'e-le-fen sil',
          'bahasa_arab' => 'فِيْلُ الْبَحْرِ',
          'fonetik_arab' => 'Fīl al-Baḥr',
          'bahasa_mandarin' => '海象',
          'fonetik_mandarin' => 'Hǎixiàng',
          'kategori' => 'Hewan Laut',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Beruang Es',
          'bahasa_inggris' => 'Polar Bear',
          'fonetik' => 'po-ler ber',
          'bahasa_arab' => 'دُبٌّ قُطْبِيٌّ',
          'fonetik_arab' => 'Dubbun Quṭbiyyun',
          'bahasa_mandarin' => '北极熊',
          'fonetik_mandarin' => 'Běijíxióng',
          'kategori' => 'Hewan Laut',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Otter Laut',
          'bahasa_inggris' => 'Sea Otter',
          'fonetik' => 'si o-ter',
          'bahasa_arab' => 'قُضَّاعَةُ الْبَحْرِ',
          'fonetik_arab' => 'Quḍḍāʿat al-Baḥr',
          'bahasa_mandarin' => '海獭',
          'fonetik_mandarin' => 'Hǎità',
          'kategori' => 'Hewan Laut',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Manatee',
          'bahasa_inggris' => 'Manatee',
          'fonetik' => 'ma-ne-ti',
          'bahasa_arab' => 'خَرُوفُ الْبَحْرِ',
          'fonetik_arab' => 'Kharūf al-Baḥr',
          'bahasa_mandarin' => '海牛',
          'fonetik_mandarin' => 'Hǎiniú',
          'kategori' => 'Hewan Laut',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Singa Laut Steller',
          'bahasa_inggris' => 'Steller Sea Lion',
          'fonetik' => 'ste-ler si lai-yen',
          'bahasa_arab' => 'أَسَدُ بَحْرِ سْتِيْلَر',
          'fonetik_arab' => 'Asad Baḥr Stīlar',
          'bahasa_mandarin' => '北海狮',
          'fonetik_mandarin' => 'Běihǎishī',
          'kategori' => 'Hewan Laut',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Lumba-lumba Sungai',
          'bahasa_inggris' => 'River Dolphin',
          'fonetik' => 'ri-ver dol-fin',
          'bahasa_arab' => 'دُلْفِينُ النَّهْرِ',
          'fonetik_arab' => 'Dulfīn an-Nahri',
          'bahasa_mandarin' => '河豚',
          'fonetik_mandarin' => 'Hétún',
          'kategori' => 'Hewan Laut',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Anemon Laut',
          'bahasa_inggris' => 'Sea Anemone',
          'fonetik' => 'si e-ne-mo-ni',
          'bahasa_arab' => 'شَقَائِقُ النُّعْمَانِ الْبَحْرِيَّة',
          'fonetik_arab' => 'Syaqāʾiq an-Nuʿmān al-Baḥriyyah',
          'bahasa_mandarin' => '海葵',
          'fonetik_mandarin' => 'Hǎikuí',
          'kategori' => 'Hewan Laut',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Bunga Karang',
          'bahasa_inggris' => 'Sea Sponge',
          'fonetik' => 'si spanj',
          'bahasa_arab' => 'إِسْفَنْجُ الْبَحْرِ',
          'fonetik_arab' => 'Isfanj al-Baḥr',
          'bahasa_mandarin' => '海绵',
          'fonetik_mandarin' => 'Hǎimián',
          'kategori' => 'Hewan Laut',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Bintang Laut Merah',
          'bahasa_inggris' => 'Red Starfish',
          'fonetik' => 'red star-fish',
          'bahasa_arab' => 'نَجْمَةُ الْبَحْرِ الْحَمْرَاء',
          'fonetik_arab' => 'Najmat al-Baḥr al-Ḥamrāʾ',
          'bahasa_mandarin' => '红海星',
          'fonetik_mandarin' => 'Hónghǎixīng',
          'kategori' => 'Hewan Laut',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Bulu Seribu',
          'bahasa_inggris' => 'Crinoid',
          'fonetik' => 'kri-noid',
          'bahasa_arab' => 'زَنْبَقُ الْبَحْرِ',
          'fonetik_arab' => 'Zanbaq al-Baḥr',
          'bahasa_mandarin' => '海百合',
          'fonetik_mandarin' => 'Hǎibǎihé',
          'kategori' => 'Hewan Laut',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Siput Laut',
          'bahasa_inggris' => 'Sea Slug',
          'fonetik' => 'si slag',
          'bahasa_arab' => 'بُزَّاقُ الْبَحْرِ',
          'fonetik_arab' => 'Buzzāq al-Baḥr',
          'bahasa_mandarin' => '海兔',
          'fonetik_mandarin' => 'Hǎitù',
          'kategori' => 'Hewan Laut',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Kerang Mutiara',
          'bahasa_inggris' => 'Pearl Oyster',
          'fonetik' => 'perl ois-ter',
          'bahasa_arab' => 'مَحَارُ اللُّؤْلُؤِ',
          'fonetik_arab' => 'Maḥār al-Luʾluʾi',
          'bahasa_mandarin' => '珍珠贝',
          'fonetik_mandarin' => 'Zhēnzhūbèi',
          'kategori' => 'Hewan Laut',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Kepiting Raja',
          'bahasa_inggris' => 'King Crab',
          'fonetik' => 'king kreb',
          'bahasa_arab' => 'سَرَطَانُ الْمَلِكِ',
          'fonetik_arab' => 'Saraṭān al-Maliki',
          'bahasa_mandarin' => '帝王蟹',
          'fonetik_mandarin' => 'Dìwángxiè',
          'kategori' => 'Hewan Laut',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Udang Galah',
          'bahasa_inggris' => 'Prawn',
          'fonetik' => 'pron',
          'bahasa_arab' => 'جَمْبَرِيٌّ كَبِيْرٌ',
          'fonetik_arab' => 'Jambariyyun Kabīrun',
          'bahasa_mandarin' => '大虾',
          'fonetik_mandarin' => 'Dàxiā',
          'kategori' => 'Hewan Laut',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Teritip',
          'bahasa_inggris' => 'Barnacle',
          'fonetik' => 'bar-ne-kel',
          'bahasa_arab' => 'بَرْنَقِيل',
          'fonetik_arab' => 'Barnaqīl',
          'bahasa_mandarin' => '藤壶',
          'fonetik_mandarin' => 'Ténghú',
          'kategori' => 'Hewan Laut',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Kelomang',
          'bahasa_inggris' => 'Hermit Crab',
          'fonetik' => 'her-mit kreb',
          'bahasa_arab' => 'سَرَطَانٌ نَاسِكٌ',
          'fonetik_arab' => 'Saraṭānun Nāsikun',
          'bahasa_mandarin' => '寄居蟹',
          'fonetik_mandarin' => 'Jìjūxiè',
          'kategori' => 'Hewan Laut',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Udang Karang',
          'bahasa_inggris' => 'Crayfish',
          'fonetik' => 'krei-fish',
          'bahasa_arab' => 'جَرَادُ الْبَحْرِ',
          'fonetik_arab' => 'Jarād al-Baḥr',
          'bahasa_mandarin' => '淡水龙虾',
          'fonetik_mandarin' => 'Dànshuǐ lóngxiā',
          'kategori' => 'Hewan Laut',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Krill',
          'bahasa_inggris' => 'Krill',
          'fonetik' => 'kril',
          'bahasa_arab' => 'كِرِيْل',
          'fonetik_arab' => 'Kirīl',
          'bahasa_mandarin' => '磷虾',
          'fonetik_mandarin' => 'Línxiā',
          'kategori' => 'Hewan Laut',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Ikan Paus Hiu',
          'bahasa_inggris' => 'Whale Shark',
          'fonetik' => 'weyl syark',
          'bahasa_arab' => 'قِرْشٌ حُوتِيٌّ',
          'fonetik_arab' => 'Qirshun Ḥūtiyyun',
          'bahasa_mandarin' => '鲸鲨',
          'fonetik_mandarin' => 'Jīngshā',
          'kategori' => 'Hewan Laut',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Ikan Gergaji',
          'bahasa_inggris' => 'Sawfish',
          'fonetik' => 'so-fish',
          'bahasa_arab' => 'سَمَكُ الْمِنْشَارِ',
          'fonetik_arab' => 'Samak al-Minsyāri',
          'bahasa_mandarin' => '锯鳐',
          'fonetik_mandarin' => 'Jùyáo',
          'kategori' => 'Hewan Laut',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Ikan Martil',
          'bahasa_inggris' => 'Hammerhead Shark',
          'fonetik' => 'he-mer-hed syark',
          'bahasa_arab' => 'قِرْشُ الْمِطْرَقَةِ',
          'fonetik_arab' => 'Qirsyu al-Miṭraqati',
          'bahasa_mandarin' => '锤头鲨',
          'fonetik_mandarin' => 'Chuítóushā',
          'kategori' => 'Hewan Laut',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Ikan Pari Manta',
          'bahasa_inggris' => 'Manta Ray',
          'fonetik' => 'men-ta rey',
          'bahasa_arab' => 'شَيْطَانُ الْبَحْرِ',
          'fonetik_arab' => 'Syayṭān al-Baḥr',
          'bahasa_mandarin' => '蝠鲼',
          'fonetik_mandarin' => 'Fúfèn',
          'kategori' => 'Hewan Laut',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Ikan Belida',
          'bahasa_inggris' => 'Featherback',
          'fonetik' => 'fe-ther-bek',
          'bahasa_arab' => 'سَمَكُ السِّكِّين',
          'fonetik_arab' => 'Samak as-Sikkīn',
          'bahasa_mandarin' => '弓背鱼',
          'fonetik_mandarin' => 'Gōngbèiyú',
          'kategori' => 'Hewan Laut',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Ikan Kakap',
          'bahasa_inggris' => 'Snapper',
          'fonetik' => 'sne-per',
          'bahasa_arab' => 'سَمَكُ النَّهَّاش',
          'fonetik_arab' => 'Samak an-Nahhāsy',
          'bahasa_mandarin' => '鲷鱼',
          'fonetik_mandarin' => 'Diāoyú',
          'kategori' => 'Hewan Laut',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Ikan Kerapu',
          'bahasa_inggris' => 'Grouper',
          'fonetik' => 'gru-per',
          'bahasa_arab' => 'هَامُوْرٌ',
          'fonetik_arab' => 'Hāmūrun',
          'bahasa_mandarin' => '石斑鱼',
          'fonetik_mandarin' => 'Shíbānyú',
          'kategori' => 'Hewan Laut',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Ikan Bawal',
          'bahasa_inggris' => 'Pomfret',
          'fonetik' => 'pom-fret',
          'bahasa_arab' => 'سَمَكُ الزُّبَيْدِيّ',
          'fonetik_arab' => 'Samak az-Zubaydiy',
          'bahasa_mandarin' => '鲳鱼',
          'fonetik_mandarin' => 'Chāngyú',
          'kategori' => 'Hewan Laut',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Ikan Tenggiri',
          'bahasa_inggris' => 'Spanish Mackerel',
          'fonetik' => 'spe-nis ma-ke-rel',
          'bahasa_arab' => 'سَمَكُ الْكَنَعْد',
          'fonetik_arab' => 'Samak al-Kanaʿd',
          'bahasa_mandarin' => '马鲛鱼',
          'fonetik_mandarin' => 'Mǎjiāoyú',
          'kategori' => 'Hewan Laut',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Ikan Kakap Merah',
          'bahasa_inggris' => 'Red Snapper',
          'fonetik' => 'red sne-per',
          'bahasa_arab' => 'الْحَمْرَاءُ الْأَصِيلَة',
          'fonetik_arab' => 'Al-Ḥamrāʾ al-Aṣīlah',
          'bahasa_mandarin' => '红鲷鱼',
          'fonetik_mandarin' => 'Hóngdiāoyú',
          'kategori' => 'Hewan Laut',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Ikan Pari Elang',
          'bahasa_inggris' => 'Eagle Ray',
          'fonetik' => 'i-gel rey',
          'bahasa_arab' => 'شِفْنِيْنُ الْعُقَابِ',
          'fonetik_arab' => 'Syifnīn al-ʿUqābi',
          'bahasa_mandarin' => '鲼',
          'fonetik_mandarin' => 'Fèn',
          'kategori' => 'Hewan Laut',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Ikan Lepu',
          'bahasa_inggris' => 'Stonefish',
          'fonetik' => 'stoun-fish',
          'bahasa_arab' => 'السَّمَكَةُ الصَّخْرِيَّة',
          'fonetik_arab' => 'As-Samakat as-Ṣakhriyyah',
          'bahasa_mandarin' => '石头鱼',
          'fonetik_mandarin' => 'Shítóuyú',
          'kategori' => 'Hewan Laut',
          'hari' => 13,
        ),
    );
  }
}