<?php

namespace Database\Seeders\Support\Game\Blueprints;

class KataKerja
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Makan',
          'bahasa_inggris' => 'Eat',
          'fonetik' => 'it',
          'bahasa_arab' => 'يَأْكُلُ',
          'fonetik_arab' => 'Yaʾkulú',
          'bahasa_mandarin' => '吃',
          'fonetik_mandarin' => 'Chī',
          'kategori' => 'Kata Kerja',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Minum',
          'bahasa_inggris' => 'Drink',
          'fonetik' => 'drink',
          'bahasa_arab' => 'يَشْرَبُ',
          'fonetik_arab' => 'Yashrabu',
          'bahasa_mandarin' => '喝',
          'fonetik_mandarin' => 'Hē',
          'kategori' => 'Kata Kerja',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Tidur',
          'bahasa_inggris' => 'Sleep',
          'fonetik' => 'slip',
          'bahasa_arab' => 'يَنَامُ',
          'fonetik_arab' => 'Yanāmu',
          'bahasa_mandarin' => '睡觉',
          'fonetik_mandarin' => 'Shuìjiào',
          'kategori' => 'Kata Kerja',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Lari',
          'bahasa_inggris' => 'Run',
          'fonetik' => 'ran',
          'bahasa_arab' => 'يَجْرِي',
          'fonetik_arab' => 'Yajrī',
          'bahasa_mandarin' => '跑',
          'fonetik_mandarin' => 'Pǎo',
          'kategori' => 'Kata Kerja',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Membaca',
          'bahasa_inggris' => 'Read',
          'fonetik' => 'rid',
          'bahasa_arab' => 'يَقْرَأُ',
          'fonetik_arab' => 'Yaqraʾu',
          'bahasa_mandarin' => '读',
          'fonetik_mandarin' => 'Dú',
          'kategori' => 'Kata Kerja',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Bermain',
          'bahasa_inggris' => 'Play',
          'fonetik' => 'pley',
          'bahasa_arab' => 'يَلْعَبُ',
          'fonetik_arab' => 'Yalʿabu',
          'bahasa_mandarin' => '玩',
          'fonetik_mandarin' => 'Wán',
          'kategori' => 'Kata Kerja',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Jalan',
          'bahasa_inggris' => 'Walk',
          'fonetik' => 'wok',
          'bahasa_arab' => 'يَمْشِي',
          'fonetik_arab' => 'Yamshī',
          'bahasa_mandarin' => '走',
          'fonetik_mandarin' => 'Zǒu',
          'kategori' => 'Kata Kerja',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Duduk',
          'bahasa_inggris' => 'Sit',
          'fonetik' => 'sit',
          'bahasa_arab' => 'يَجْلِسُ',
          'fonetik_arab' => 'Yajlisu',
          'bahasa_mandarin' => '坐',
          'fonetik_mandarin' => 'Zuò',
          'kategori' => 'Kata Kerja',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Berdiri',
          'bahasa_inggris' => 'Stand',
          'fonetik' => 'stend',
          'bahasa_arab' => 'يَقِفُ',
          'fonetik_arab' => 'Yaqifu',
          'bahasa_mandarin' => '站',
          'fonetik_mandarin' => 'Zhàn',
          'kategori' => 'Kata Kerja',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Tulis',
          'bahasa_inggris' => 'Write',
          'fonetik' => 'rait',
          'bahasa_arab' => 'يَكْتُبُ',
          'fonetik_arab' => 'Yaktubu',
          'bahasa_mandarin' => '写',
          'fonetik_mandarin' => 'Xiě',
          'kategori' => 'Kata Kerja',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Gambar',
          'bahasa_inggris' => 'Draw',
          'fonetik' => 'dro',
          'bahasa_arab' => 'يَرْسُمُ',
          'fonetik_arab' => 'Yarsumu',
          'bahasa_mandarin' => '画',
          'fonetik_mandarin' => 'Huà',
          'kategori' => 'Kata Kerja',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Nyanyi',
          'bahasa_inggris' => 'Sing',
          'fonetik' => 'sing',
          'bahasa_arab' => 'يُغَنِّي',
          'fonetik_arab' => 'Yughannī',
          'bahasa_mandarin' => '唱',
          'fonetik_mandarin' => 'Chàng',
          'kategori' => 'Kata Kerja',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Lihat',
          'bahasa_inggris' => 'See',
          'fonetik' => 'si',
          'bahasa_arab' => 'يَرَى',
          'fonetik_arab' => 'Yarā',
          'bahasa_mandarin' => '看',
          'fonetik_mandarin' => 'Kàn',
          'kategori' => 'Kata Kerja',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Dengar',
          'bahasa_inggris' => 'Hear',
          'fonetik' => 'hir',
          'bahasa_arab' => 'يَسْمَعُ',
          'fonetik_arab' => 'Yasmaʿu',
          'bahasa_mandarin' => '听',
          'fonetik_mandarin' => 'Tīng',
          'kategori' => 'Kata Kerja',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Bicara',
          'bahasa_inggris' => 'Talk',
          'fonetik' => 'tok',
          'bahasa_arab' => 'يَتَكَلَّمُ',
          'fonetik_arab' => 'Yatakallamu',
          'bahasa_mandarin' => '说',
          'fonetik_mandarin' => 'Shuō',
          'kategori' => 'Kata Kerja',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Tertawa',
          'bahasa_inggris' => 'Laugh',
          'fonetik' => 'laf',
          'bahasa_arab' => 'يَضْحَكُ',
          'fonetik_arab' => 'Yaḍḥaku',
          'bahasa_mandarin' => '笑',
          'fonetik_mandarin' => 'Xiào',
          'kategori' => 'Kata Kerja',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Menangis',
          'bahasa_inggris' => 'Cry',
          'fonetik' => 'krai',
          'bahasa_arab' => 'يَبْكِي',
          'fonetik_arab' => 'Yabkī',
          'bahasa_mandarin' => '哭',
          'fonetik_mandarin' => 'Kū',
          'kategori' => 'Kata Kerja',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Lompat',
          'bahasa_inggris' => 'Jump',
          'fonetik' => 'jamp',
          'bahasa_arab' => 'يَقْفِزُ',
          'fonetik_arab' => 'Yaqfizu',
          'bahasa_mandarin' => '跳',
          'fonetik_mandarin' => 'Tiào',
          'kategori' => 'Kata Kerja',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Buka',
          'bahasa_inggris' => 'Open',
          'fonetik' => 'ou-pen',
          'bahasa_arab' => 'يَفْتَحُ',
          'fonetik_arab' => 'Yaftaḥu',
          'bahasa_mandarin' => '开',
          'fonetik_mandarin' => 'Kāi',
          'kategori' => 'Kata Kerja',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Tutup',
          'bahasa_inggris' => 'Close',
          'fonetik' => 'klouz',
          'bahasa_arab' => 'يُغْلِقُ',
          'fonetik_arab' => 'Yughliqu',
          'bahasa_mandarin' => '关',
          'fonetik_mandarin' => 'Guān',
          'kategori' => 'Kata Kerja',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Dorong',
          'bahasa_inggris' => 'Push',
          'fonetik' => 'pusy',
          'bahasa_arab' => 'يَدْفَعُ',
          'fonetik_arab' => 'Yadfaʿu',
          'bahasa_mandarin' => '推',
          'fonetik_mandarin' => 'Tuī',
          'kategori' => 'Kata Kerja',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Tarik',
          'bahasa_inggris' => 'Pull',
          'fonetik' => 'pul',
          'bahasa_arab' => 'يَسْحَبُ',
          'fonetik_arab' => 'Yasḥabu',
          'bahasa_mandarin' => '拉',
          'fonetik_mandarin' => 'Lā',
          'kategori' => 'Kata Kerja',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Beri',
          'bahasa_inggris' => 'Give',
          'fonetik' => 'giv',
          'bahasa_arab' => 'يُعْطِي',
          'fonetik_arab' => 'Yuʿṭī',
          'bahasa_mandarin' => '给',
          'fonetik_mandarin' => 'Gěi',
          'kategori' => 'Kata Kerja',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Ambil',
          'bahasa_inggris' => 'Take',
          'fonetik' => 'teyk',
          'bahasa_arab' => 'يَأْخُذُ',
          'fonetik_arab' => 'Yaʾkhudhu',
          'bahasa_mandarin' => '拿',
          'fonetik_mandarin' => 'Ná',
          'kategori' => 'Kata Kerja',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Masak',
          'bahasa_inggris' => 'Cook',
          'fonetik' => 'kuk',
          'bahasa_arab' => 'يَطْبَخُ',
          'fonetik_arab' => 'Yaṭbakhu',
          'bahasa_mandarin' => '做饭',
          'fonetik_mandarin' => 'Zuòfàn',
          'kategori' => 'Kata Kerja',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Cuci',
          'bahasa_inggris' => 'Wash',
          'fonetik' => 'wosh',
          'bahasa_arab' => 'يَغْسِلُ',
          'fonetik_arab' => 'Yaghsilu',
          'bahasa_mandarin' => '洗',
          'fonetik_mandarin' => 'Xǐ',
          'kategori' => 'Kata Kerja',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Bersih',
          'bahasa_inggris' => 'Clean',
          'fonetik' => 'klin',
          'bahasa_arab' => 'يُنَظِّفُ',
          'fonetik_arab' => 'Yunaẓẓifu',
          'bahasa_mandarin' => '打扫',
          'fonetik_mandarin' => 'Dǎsǎo',
          'kategori' => 'Kata Kerja',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Bantu',
          'bahasa_inggris' => 'Help',
          'fonetik' => 'help',
          'bahasa_arab' => 'يُسَاعِدُ',
          'fonetik_arab' => 'Yusāʿidu',
          'bahasa_mandarin' => '帮忙',
          'fonetik_mandarin' => 'Bāngmáng',
          'kategori' => 'Kata Kerja',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Tunggu',
          'bahasa_inggris' => 'Wait',
          'fonetik' => 'weit',
          'bahasa_arab' => 'يَنْتَظِرُ',
          'fonetik_arab' => 'Yantaẓiru',
          'bahasa_mandarin' => '等',
          'fonetik_mandarin' => 'Děng',
          'kategori' => 'Kata Kerja',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Tanya',
          'bahasa_inggris' => 'Ask',
          'fonetik' => 'ask',
          'bahasa_arab' => 'يَسْأَلُ',
          'fonetik_arab' => 'Yasʾalu',
          'bahasa_mandarin' => '问',
          'fonetik_mandarin' => 'Wèn',
          'kategori' => 'Kata Kerja',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Jawab',
          'bahasa_inggris' => 'Answer',
          'fonetik' => 'en-ser',
          'bahasa_arab' => 'يُجِيبُ',
          'fonetik_arab' => 'Yujību',
          'bahasa_mandarin' => '回答',
          'fonetik_mandarin' => 'Huídá',
          'kategori' => 'Kata Kerja',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Pikir',
          'bahasa_inggris' => 'Think',
          'fonetik' => 'thingk',
          'bahasa_arab' => 'يُفَكِّرُ',
          'fonetik_arab' => 'Yufakkiru',
          'bahasa_mandarin' => '想',
          'fonetik_mandarin' => 'Xiǎng',
          'kategori' => 'Kata Kerja',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Cinta',
          'bahasa_inggris' => 'Love',
          'fonetik' => 'lav',
          'bahasa_arab' => 'يُحِبُّ',
          'fonetik_arab' => 'Yuḥibbu',
          'bahasa_mandarin' => '爱',
          'fonetik_mandarin' => 'Ài',
          'kategori' => 'Kata Kerja',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Suka',
          'bahasa_inggris' => 'Like',
          'fonetik' => 'laik',
          'bahasa_arab' => 'يُفَضِّلُ',
          'fonetik_arab' => 'Yufaḍḍilu',
          'bahasa_mandarin' => '喜欢',
          'fonetik_mandarin' => 'Xǐhuān',
          'kategori' => 'Kata Kerja',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Ingin',
          'bahasa_inggris' => 'Want',
          'fonetik' => 'wont',
          'bahasa_arab' => 'يُرِيدُ',
          'fonetik_arab' => 'Yurīdu',
          'bahasa_mandarin' => '想要',
          'fonetik_mandarin' => 'Xiǎngyào',
          'kategori' => 'Kata Kerja',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Perlu',
          'bahasa_inggris' => 'Need',
          'fonetik' => 'nid',
          'bahasa_arab' => 'يَحْتَاجُ',
          'fonetik_arab' => 'Yaḥtāju',
          'bahasa_mandarin' => '需要',
          'fonetik_mandarin' => 'Xūyào',
          'kategori' => 'Kata Kerja',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Pergi',
          'bahasa_inggris' => 'Go',
          'fonetik' => 'gou',
          'bahasa_arab' => 'يَذْهَبُ',
          'fonetik_arab' => 'Yadhhabu',
          'bahasa_mandarin' => '去',
          'fonetik_mandarin' => 'Qù',
          'kategori' => 'Kata Kerja',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Datang',
          'bahasa_inggris' => 'Come',
          'fonetik' => 'kam',
          'bahasa_arab' => 'يَأْتِي',
          'fonetik_arab' => 'Yaʾtī',
          'bahasa_mandarin' => '来',
          'fonetik_mandarin' => 'Lái',
          'kategori' => 'Kata Kerja',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Buat',
          'bahasa_inggris' => 'Make',
          'fonetik' => 'meyk',
          'bahasa_arab' => 'يَصْنَعُ',
          'fonetik_arab' => 'Yaṣnaʿu',
          'bahasa_mandarin' => '做',
          'fonetik_mandarin' => 'Zuò',
          'kategori' => 'Kata Kerja',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Gunakan',
          'bahasa_inggris' => 'Use',
          'fonetik' => 'yuz',
          'bahasa_arab' => 'يَسْتَخْدِمُ',
          'fonetik_arab' => 'Yastakhdimu',
          'bahasa_mandarin' => '用',
          'fonetik_mandarin' => 'Yòng',
          'kategori' => 'Kata Kerja',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Cari',
          'bahasa_inggris' => 'Find',
          'fonetik' => 'faind',
          'bahasa_arab' => 'يَجِدُ',
          'fonetik_arab' => 'Yajidu',
          'bahasa_mandarin' => '找',
          'fonetik_mandarin' => 'Zhǎo',
          'kategori' => 'Kata Kerja',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Kerja',
          'bahasa_inggris' => 'Work',
          'fonetik' => 'werk',
          'bahasa_arab' => 'يَعْمَلُ',
          'fonetik_arab' => 'Yaʿmalu',
          'bahasa_mandarin' => '工作',
          'fonetik_mandarin' => 'Gōngzuò',
          'kategori' => 'Kata Kerja',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Belajar',
          'bahasa_inggris' => 'Learn',
          'fonetik' => 'lern',
          'bahasa_arab' => 'يَتَعَلَّمُ',
          'fonetik_arab' => 'Yataʿallamu',
          'bahasa_mandarin' => '学习',
          'fonetik_mandarin' => 'Xuéxí',
          'kategori' => 'Kata Kerja',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Ajar',
          'bahasa_inggris' => 'Teach',
          'fonetik' => 'tic',
          'bahasa_arab' => 'يُعَلِّمُ',
          'fonetik_arab' => 'Yuʿallimu',
          'bahasa_mandarin' => '教',
          'fonetik_mandarin' => 'Jiāo',
          'kategori' => 'Kata Kerja',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Terbang',
          'bahasa_inggris' => 'Fly',
          'fonetik' => 'flai',
          'bahasa_arab' => 'يَطِيرُ',
          'fonetik_arab' => 'Yaṭīru',
          'bahasa_mandarin' => '飞',
          'fonetik_mandarin' => 'Fēi',
          'kategori' => 'Kata Kerja',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Berenang',
          'bahasa_inggris' => 'Swim',
          'fonetik' => 'swim',
          'bahasa_arab' => 'يَسْبَحُ',
          'fonetik_arab' => 'Yasbaḥu',
          'bahasa_mandarin' => '游泳',
          'fonetik_mandarin' => 'Yóuyǒng',
          'kategori' => 'Kata Kerja',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Menari',
          'bahasa_inggris' => 'Dance',
          'fonetik' => 'dens',
          'bahasa_arab' => 'يَرْقُصُ',
          'fonetik_arab' => 'Yarqaṣu',
          'bahasa_mandarin' => '跳舞',
          'fonetik_mandarin' => 'Tiàowǔ',
          'kategori' => 'Kata Kerja',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Potong',
          'bahasa_inggris' => 'Cut',
          'fonetik' => 'kat',
          'bahasa_arab' => 'يَقْطَعُ',
          'fonetik_arab' => 'Yaqṭaʿu',
          'bahasa_mandarin' => '剪',
          'fonetik_mandarin' => 'Jiǎn',
          'kategori' => 'Kata Kerja',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Merasakan',
          'bahasa_inggris' => 'Feel',
          'fonetik' => 'fil',
          'bahasa_arab' => 'يَشْعُرُ',
          'fonetik_arab' => 'Yasyʿuru',
          'bahasa_mandarin' => '感觉',
          'fonetik_mandarin' => 'Gǎnjué',
          'kategori' => 'Kata Kerja',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Menyentuh',
          'bahasa_inggris' => 'Touch',
          'fonetik' => 'tac',
          'bahasa_arab' => 'يَلْمَسُ',
          'fonetik_arab' => 'Yalmasu',
          'bahasa_mandarin' => '触摸',
          'fonetik_mandarin' => 'Chùmō',
          'kategori' => 'Kata Kerja',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Memegang',
          'bahasa_inggris' => 'Hold',
          'fonetik' => 'hould',
          'bahasa_arab' => 'يُمْسِكُ',
          'fonetik_arab' => 'Yumsiku',
          'bahasa_mandarin' => '拿',
          'fonetik_mandarin' => 'Ná',
          'kategori' => 'Kata Kerja',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Melempar',
          'bahasa_inggris' => 'Throw',
          'fonetik' => 'throu',
          'bahasa_arab' => 'يَرْمِي',
          'fonetik_arab' => 'Yarmī',
          'bahasa_mandarin' => '扔',
          'fonetik_mandarin' => 'Rēng',
          'kategori' => 'Kata Kerja',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Menangkap',
          'bahasa_inggris' => 'Catch',
          'fonetik' => 'kec',
          'bahasa_arab' => 'يَلْتَقِطُ',
          'fonetik_arab' => 'Yaltaqiṭu',
          'bahasa_mandarin' => '捉',
          'fonetik_mandarin' => 'Zhuō',
          'kategori' => 'Kata Kerja',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Menendang',
          'bahasa_inggris' => 'Kick',
          'fonetik' => 'kik',
          'bahasa_arab' => 'يَرْكُلُ',
          'fonetik_arab' => 'Yarkulu',
          'bahasa_mandarin' => '踢',
          'fonetik_mandarin' => 'Tī',
          'kategori' => 'Kata Kerja',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Memutuskan',
          'bahasa_inggris' => 'Decide',
          'fonetik' => 'di-said',
          'bahasa_arab' => 'يُقَرِّرُ',
          'fonetik_arab' => 'Yuqarriru',
          'bahasa_mandarin' => '决定',
          'fonetik_mandarin' => 'Juédìng',
          'kategori' => 'Kata Kerja',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Berjanji',
          'bahasa_inggris' => 'Promise',
          'fonetik' => 'pro-mis',
          'bahasa_arab' => 'يَعِدُ',
          'fonetik_arab' => 'Yaʿidu',
          'bahasa_mandarin' => '答应',
          'fonetik_mandarin' => 'Dāying',
          'kategori' => 'Kata Kerja',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Bermimpi',
          'bahasa_inggris' => 'Dream',
          'fonetik' => 'drim',
          'bahasa_arab' => 'يَحْلُمُ',
          'fonetik_arab' => 'Yaḥlumu',
          'bahasa_mandarin' => '梦',
          'fonetik_mandarin' => 'Mèng',
          'kategori' => 'Kata Kerja',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Mengingat',
          'bahasa_inggris' => 'Remember',
          'fonetik' => 'ri-mem-ber',
          'bahasa_arab' => 'يَتَذَكَّرُ',
          'fonetik_arab' => 'Yatadhakkaru',
          'bahasa_mandarin' => '记得',
          'fonetik_mandarin' => 'Jìdé',
          'kategori' => 'Kata Kerja',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Melupakan',
          'bahasa_inggris' => 'Forget',
          'fonetik' => 'for-get',
          'bahasa_arab' => 'يَنْسَى',
          'fonetik_arab' => 'Yansā',
          'bahasa_mandarin' => '忘记',
          'fonetik_mandarin' => 'Wàngjì',
          'kategori' => 'Kata Kerja',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Mengerti',
          'bahasa_inggris' => 'Understand',
          'fonetik' => 'an-der-stend',
          'bahasa_arab' => 'يَفْهَمُ',
          'fonetik_arab' => 'Yafhamu',
          'bahasa_mandarin' => '懂',
          'fonetik_mandarin' => 'Dǒng',
          'kategori' => 'Kata Kerja',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Merangkak',
          'bahasa_inggris' => 'Crawl',
          'fonetik' => 'krol',
          'bahasa_arab' => 'يَحْبُو',
          'fonetik_arab' => 'Yaḥbū',
          'bahasa_mandarin' => '爬',
          'fonetik_mandarin' => 'Pá',
          'kategori' => 'Kata Kerja',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Menggigit',
          'bahasa_inggris' => 'Bite',
          'fonetik' => 'bait',
          'bahasa_arab' => 'يَعَضُّ',
          'fonetik_arab' => 'Yaʿaḍḍu',
          'bahasa_mandarin' => '咬',
          'fonetik_mandarin' => 'Yǎo',
          'kategori' => 'Kata Kerja',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Menggonggong',
          'bahasa_inggris' => 'Bark',
          'fonetik' => 'bark',
          'bahasa_arab' => 'يَنْبَحُ',
          'fonetik_arab' => 'Yanbaḥu',
          'bahasa_mandarin' => '吠',
          'fonetik_mandarin' => 'Fèi',
          'kategori' => 'Kata Kerja',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Mengeong',
          'bahasa_inggris' => 'Meow',
          'fonetik' => 'mi-yaw',
          'bahasa_arab' => 'يَمُوءُ',
          'fonetik_arab' => 'Yamūʾu',
          'bahasa_mandarin' => '喵',
          'fonetik_mandarin' => 'Miāo',
          'kategori' => 'Kata Kerja',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Mendengkur',
          'bahasa_inggris' => 'Snore',
          'fonetik' => 'snor',
          'bahasa_arab' => 'يَشْخَرُ',
          'fonetik_arab' => 'Yasykharu',
          'bahasa_mandarin' => '打鼾',
          'fonetik_mandarin' => 'Dǎhān',
          'kategori' => 'Kata Kerja',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Berdoa',
          'bahasa_inggris' => 'Pray',
          'fonetik' => 'prey',
          'bahasa_arab' => 'يُصَلِّي',
          'fonetik_arab' => 'Yuṣallī',
          'bahasa_mandarin' => '祈祷',
          'fonetik_mandarin' => 'Qídǎo',
          'kategori' => 'Kata Kerja',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Menyetir',
          'bahasa_inggris' => 'Drive',
          'fonetik' => 'draiv',
          'bahasa_arab' => 'يَقُودُ',
          'fonetik_arab' => 'Yaqūdu',
          'bahasa_mandarin' => '开车',
          'fonetik_mandarin' => 'Kāichē',
          'kategori' => 'Kata Kerja',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Menaiki',
          'bahasa_inggris' => 'Ride',
          'fonetik' => 'raid',
          'bahasa_arab' => 'يَرْكَبُ',
          'fonetik_arab' => 'Yarkabu',
          'bahasa_mandarin' => '骑',
          'fonetik_mandarin' => 'Qí',
          'kategori' => 'Kata Kerja',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Menghitung',
          'bahasa_inggris' => 'Count',
          'fonetik' => 'kaunt',
          'bahasa_arab' => 'يَعُدُّ',
          'fonetik_arab' => 'Yaʿuddu',
          'bahasa_mandarin' => '数',
          'fonetik_mandarin' => 'Shǔ',
          'kategori' => 'Kata Kerja',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Membayar',
          'bahasa_inggris' => 'Pay',
          'fonetik' => 'pey',
          'bahasa_arab' => 'يَدْفَعُ',
          'fonetik_arab' => 'Yadfaʿu',
          'bahasa_mandarin' => '付',
          'fonetik_mandarin' => 'Fù',
          'kategori' => 'Kata Kerja',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Menitip',
          'bahasa_inggris' => 'Entrust',
          'fonetik' => 'en-trast',
          'bahasa_arab' => 'يُودِعُ',
          'fonetik_arab' => 'Yūdiʿu',
          'bahasa_mandarin' => '寄放',
          'fonetik_mandarin' => 'Jìfàng',
          'kategori' => 'Kata Kerja',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Meminjam',
          'bahasa_inggris' => 'Borrow',
          'fonetik' => 'bo-rou',
          'bahasa_arab' => 'يَسْتَعِيرُ',
          'fonetik_arab' => 'Yastaʿīru',
          'bahasa_mandarin' => '借',
          'fonetik_mandarin' => 'Jiè',
          'kategori' => 'Kata Kerja',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Menjemput',
          'bahasa_inggris' => 'Pick up',
          'fonetik' => 'pik ap',
          'bahasa_arab' => 'يَسْتَقْبِلُ',
          'fonetik_arab' => 'Yastaqbilu',
          'bahasa_mandarin' => '接',
          'fonetik_mandarin' => 'Jiē',
          'kategori' => 'Kata Kerja',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Mengirim',
          'bahasa_inggris' => 'Send',
          'fonetik' => 'send',
          'bahasa_arab' => 'يُرْسِلُ',
          'fonetik_arab' => 'Yursilu',
          'bahasa_mandarin' => '发',
          'fonetik_mandarin' => 'Fā',
          'kategori' => 'Kata Kerja',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Menerima',
          'bahasa_inggris' => 'Receive',
          'fonetik' => 'ri-siv',
          'bahasa_arab' => 'يَسْتَلِمُ',
          'fonetik_arab' => 'Yastalimu',
          'bahasa_mandarin' => '收到',
          'fonetik_mandarin' => 'Shōudào',
          'kategori' => 'Kata Kerja',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Menghapus',
          'bahasa_inggris' => 'Erase',
          'fonetik' => 'i-reys',
          'bahasa_arab' => 'يَمْسَحُ',
          'fonetik_arab' => 'Yamsahu',
          'bahasa_mandarin' => '擦',
          'fonetik_mandarin' => 'Cā',
          'kategori' => 'Kata Kerja',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Mengganti',
          'bahasa_inggris' => 'Change',
          'fonetik' => 'cenj',
          'bahasa_arab' => 'يُبَدِّلُ',
          'fonetik_arab' => 'Yubaddilu',
          'bahasa_mandarin' => '换',
          'fonetik_mandarin' => 'Huàn',
          'kategori' => 'Kata Kerja',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Memperbaiki',
          'bahasa_inggris' => 'Repairs',
          'fonetik' => 'ri-pers',
          'bahasa_arab' => 'يُصْلِحُ',
          'fonetik_arab' => 'Yuṣliḥu',
          'bahasa_mandarin' => '修理',
          'fonetik_mandarin' => 'Xiūlǐ',
          'kategori' => 'Kata Kerja',
          'hari' => 13,
        ),
    );
  }
}