<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Keluarga
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Ibu',
          'bahasa_inggris' => 'Mother',
          'fonetik' => 'ma-dher',
          'bahasa_arab' => 'أُمٌّ',
          'fonetik_arab' => 'Ummun',
          'bahasa_mandarin' => '母亲',
          'fonetik_mandarin' => 'Mǔqīn',
          'kategori' => 'Keluarga',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Ayah',
          'bahasa_inggris' => 'Father',
          'fonetik' => 'fa-dher',
          'bahasa_arab' => 'أَبٌ',
          'fonetik_arab' => 'Abun',
          'bahasa_mandarin' => '父亲',
          'fonetik_mandarin' => 'Fùqīn',
          'kategori' => 'Keluarga',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Anak Laki-laki',
          'bahasa_inggris' => 'Son',
          'fonetik' => 'san',
          'bahasa_arab' => 'اِبْنٌ',
          'fonetik_arab' => 'Ibnun',
          'bahasa_mandarin' => '儿子',
          'fonetik_mandarin' => 'Érzi',
          'kategori' => 'Keluarga',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Anak Perempuan',
          'bahasa_inggris' => 'Daughter',
          'fonetik' => 'do-ter',
          'bahasa_arab' => 'اِبْنَةٌ',
          'fonetik_arab' => 'Ibnatun',
          'bahasa_mandarin' => '女儿',
          'fonetik_mandarin' => 'Nǚ\'ér',
          'kategori' => 'Keluarga',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Bayi',
          'bahasa_inggris' => 'Baby',
          'fonetik' => 'bey-bi',
          'bahasa_arab' => 'رَضِيْعٌ',
          'fonetik_arab' => 'Raḍīʿun',
          'bahasa_mandarin' => '婴儿',
          'fonetik_mandarin' => 'Yīng\'ér',
          'kategori' => 'Keluarga',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Anak',
          'bahasa_inggris' => 'Child',
          'fonetik' => 'caild',
          'bahasa_arab' => 'وَلَدٌ',
          'fonetik_arab' => 'Waladun',
          'bahasa_mandarin' => '孩子',
          'fonetik_mandarin' => 'Háizi',
          'kategori' => 'Keluarga',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Kakek',
          'bahasa_inggris' => 'Grandfather',
          'fonetik' => 'grend-fa-dher',
          'bahasa_arab' => 'جَدٌّ',
          'fonetik_arab' => 'Jaddun',
          'bahasa_mandarin' => '爷爷',
          'fonetik_mandarin' => 'Yéye',
          'kategori' => 'Keluarga',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Nenek',
          'bahasa_inggris' => 'Grandmother',
          'fonetik' => 'grend-ma-dher',
          'bahasa_arab' => 'جَدَّةٌ',
          'fonetik_arab' => 'Jaddatun',
          'bahasa_mandarin' => '奶奶',
          'fonetik_mandarin' => 'Nǎinai',
          'kategori' => 'Keluarga',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Paman',
          'bahasa_inggris' => 'Uncle',
          'fonetik' => 'ang-kel',
          'bahasa_arab' => 'عَمٌّ',
          'fonetik_arab' => 'ʿAmmun',
          'bahasa_mandarin' => '叔叔',
          'fonetik_mandarin' => 'Shūshu',
          'kategori' => 'Keluarga',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Bibi',
          'bahasa_inggris' => 'Aunt',
          'fonetik' => 'ant',
          'bahasa_arab' => 'عَمَّةٌ',
          'fonetik_arab' => 'ʿAmmatun',
          'bahasa_mandarin' => '阿姨',
          'fonetik_mandarin' => 'Āyí',
          'kategori' => 'Keluarga',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Sepupu',
          'bahasa_inggris' => 'Cousin',
          'fonetik' => 'ka-zen',
          'bahasa_arab' => 'اِبْنُ الْعَمِّ',
          'fonetik_arab' => 'Ibnul ʿAmmi',
          'bahasa_mandarin' => '表亲',
          'fonetik_mandarin' => 'Biǎoqīn',
          'kategori' => 'Keluarga',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Keponakan',
          'bahasa_inggris' => 'Nephew',
          'fonetik' => 'ne-fyu',
          'bahasa_arab' => 'اِبْنُ الْأَخِ',
          'fonetik_arab' => 'Ibnul Akhi',
          'bahasa_mandarin' => '侄子',
          'fonetik_mandarin' => 'Zhízi',
          'kategori' => 'Keluarga',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Suami',
          'bahasa_inggris' => 'Husband',
          'fonetik' => 'has-bend',
          'bahasa_arab' => 'زَوْجٌ',
          'fonetik_arab' => 'Zawjun',
          'bahasa_mandarin' => '丈夫',
          'fonetik_mandarin' => 'Zhàngfu',
          'kategori' => 'Keluarga',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Istri',
          'bahasa_inggris' => 'Wife',
          'fonetik' => 'waif',
          'bahasa_arab' => 'زَوْجَةٌ',
          'fonetik_arab' => 'Zawjatun',
          'bahasa_mandarin' => '妻子',
          'fonetik_mandarin' => 'Qīzi',
          'kategori' => 'Keluarga',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Cucu',
          'bahasa_inggris' => 'Grandchild',
          'fonetik' => 'grend-caild',
          'bahasa_arab' => 'حَفِيْدٌ',
          'fonetik_arab' => 'Ḥafīdun',
          'bahasa_mandarin' => '孙子',
          'fonetik_mandarin' => 'Sūnzi',
          'kategori' => 'Keluarga',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Mertua',
          'bahasa_inggris' => 'Parent-in-law',
          'fonetik' => 'pe-rent in lo',
          'bahasa_arab' => 'حَمٌ',
          'fonetik_arab' => 'Ḥamun',
          'bahasa_mandarin' => '岳父母',
          'fonetik_mandarin' => 'Yuèfùmǔ',
          'kategori' => 'Keluarga',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Menantu',
          'bahasa_inggris' => 'Child-in-law',
          'fonetik' => 'caild in lo',
          'bahasa_arab' => 'صِهْرٌ',
          'fonetik_arab' => 'Ṣihrun',
          'bahasa_mandarin' => '女婿/儿媳',
          'fonetik_mandarin' => 'Nǚxu/Érxí',
          'kategori' => 'Keluarga',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Besan',
          'bahasa_inggris' => 'In-law parent',
          'fonetik' => 'in lo pe-rent',
          'bahasa_arab' => 'صِهْرٌ',
          'fonetik_arab' => 'Ṣihrun',
          'bahasa_mandarin' => '亲家',
          'fonetik_mandarin' => 'Qìngjia',
          'kategori' => 'Keluarga',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Kakak Laki-laki',
          'bahasa_inggris' => 'Older Brother',
          'fonetik' => 'ol-der bra-dher',
          'bahasa_arab' => 'أَخٌ كَبِيْرٌ',
          'fonetik_arab' => 'Akhun Kabiirun',
          'bahasa_mandarin' => '哥哥',
          'fonetik_mandarin' => 'Gēge',
          'kategori' => 'Keluarga',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Adik Laki-laki',
          'bahasa_inggris' => 'Younger Brother',
          'fonetik' => 'yang-ger bra-dher',
          'bahasa_arab' => 'أَخٌ صَغِيْرٌ',
          'fonetik_arab' => 'Akhun Shaghiirun',
          'bahasa_mandarin' => '弟弟',
          'fonetik_mandarin' => 'Dìdi',
          'kategori' => 'Keluarga',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Kakak Perempuan',
          'bahasa_inggris' => 'Older Sister',
          'fonetik' => 'ol-der sis-ter',
          'bahasa_arab' => 'أُخْتٌ كَبِيْرَةٌ',
          'fonetik_arab' => 'Ukhtun Kabiiratun',
          'bahasa_mandarin' => '姐姐',
          'fonetik_mandarin' => 'Jiějie',
          'kategori' => 'Keluarga',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Adik Perempuan',
          'bahasa_inggris' => 'Younger Sister',
          'fonetik' => 'yang-ger sis-ter',
          'bahasa_arab' => 'أُخْتٌ صَغِيْرَةٌ',
          'fonetik_arab' => 'Ukhtun Shaghiiratun',
          'bahasa_mandarin' => '妹妹',
          'fonetik_mandarin' => 'Mèimei',
          'kategori' => 'Keluarga',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Saudara Kandung',
          'bahasa_inggris' => 'Siblings',
          'fonetik' => 'sib-lings',
          'bahasa_arab' => 'أَشِقَّاءُ',
          'fonetik_arab' => 'Asyiqqāʾu',
          'bahasa_mandarin' => '兄弟姐妹',
          'fonetik_mandarin' => 'Xiōngdì jiěmèi',
          'kategori' => 'Keluarga',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Saudara Tiri',
          'bahasa_inggris' => 'Step-sibling',
          'fonetik' => 'step sib-ling',
          'bahasa_arab' => 'أَخٌ لِغَيْرِ الْأُمِّ',
          'fonetik_arab' => 'Akhun lighayril Ummi',
          'bahasa_mandarin' => '异父母兄弟姐妹',
          'fonetik_mandarin' => 'Yì fùmǔ xiōngdì jiěmèi',
          'kategori' => 'Keluarga',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Ayah Tiri',
          'bahasa_inggris' => 'Stepfather',
          'fonetik' => 'step-fa-dher',
          'bahasa_arab' => 'زَوْجُ الْأُمِّ',
          'fonetik_arab' => 'Zawjul Ummi',
          'bahasa_mandarin' => '继父',
          'fonetik_mandarin' => 'Jìfù',
          'kategori' => 'Keluarga',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Ibu Tiri',
          'bahasa_inggris' => 'Stepmother',
          'fonetik' => 'step-ma-dher',
          'bahasa_arab' => 'زَوْجَةُ الْأَبِ',
          'fonetik_arab' => 'Zawjatul Abi',
          'bahasa_mandarin' => '继母',
          'fonetik_mandarin' => 'Jìmǔ',
          'kategori' => 'Keluarga',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Anak Tiri',
          'bahasa_inggris' => 'Stepchild',
          'fonetik' => 'step-caild',
          'bahasa_arab' => 'رَبِيْبٌ',
          'fonetik_arab' => 'Rabībun',
          'bahasa_mandarin' => '继子/女',
          'fonetik_mandarin' => 'Jìzǐ/nǚ',
          'kategori' => 'Keluarga',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Wali',
          'bahasa_inggris' => 'Guardian',
          'fonetik' => 'gar-di-yen',
          'bahasa_arab' => 'وَلِيٌّ',
          'fonetik_arab' => 'Waliyyun',
          'bahasa_mandarin' => '监护人',
          'fonetik_mandarin' => 'Jiānhùrén',
          'kategori' => 'Keluarga',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Orang Tua Angkat',
          'bahasa_inggris' => 'Adoptive Parents',
          'fonetik' => 'e-dop-tiv pe-rents',
          'bahasa_arab' => 'وَالِدَانِ بِالتَّبَنِّي',
          'fonetik_arab' => 'Walidāni bit-Tabannī',
          'bahasa_mandarin' => '养父母',
          'fonetik_mandarin' => 'Yǎngfùmǔ',
          'kategori' => 'Keluarga',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Anak Angkat',
          'bahasa_inggris' => 'Adopted Child',
          'fonetik' => 'e-dop-ted caild',
          'bahasa_arab' => 'اِبْنٌ بِالتَّبَنِّي',
          'fonetik_arab' => 'Ibnun bit-Tabannī',
          'bahasa_mandarin' => '养子',
          'fonetik_mandarin' => 'Yǎngzǐ',
          'kategori' => 'Keluarga',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Teman',
          'bahasa_inggris' => 'Friend',
          'fonetik' => 'frend',
          'bahasa_arab' => 'صَدِيْقٌ',
          'fonetik_arab' => 'Ṣadīqun',
          'bahasa_mandarin' => '朋友',
          'fonetik_mandarin' => 'Péngyou',
          'kategori' => 'Keluarga',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Sahabat',
          'bahasa_inggris' => 'Best Friend',
          'fonetik' => 'best frend',
          'bahasa_arab' => 'صَدِيْقٌ حَمِيْمٌ',
          'fonetik_arab' => 'Ṣadīqun Ḥamīmun',
          'bahasa_mandarin' => '好朋友',
          'fonetik_mandarin' => 'Hǎopéngyou',
          'kategori' => 'Keluarga',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Tetangga',
          'bahasa_inggris' => 'Neighbor',
          'fonetik' => 'ney-ber',
          'bahasa_arab' => 'جَارٌ',
          'fonetik_arab' => 'Jārun',
          'bahasa_mandarin' => '邻居',
          'fonetik_mandarin' => 'Línjū',
          'kategori' => 'Keluarga',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Tamu',
          'bahasa_inggris' => 'Guest',
          'fonetik' => 'gest',
          'bahasa_arab' => 'ضَيْفٌ',
          'fonetik_arab' => 'Ḍayfun',
          'bahasa_mandarin' => '客人',
          'fonetik_mandarin' => 'Kèrén',
          'kategori' => 'Keluarga',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Guru',
          'bahasa_inggris' => 'Teacher',
          'fonetik' => 'ti-cer',
          'bahasa_arab' => 'مُعَلِّمٌ',
          'fonetik_arab' => 'Muʿallimun',
          'bahasa_mandarin' => '老师',
          'fonetik_mandarin' => 'Lǎoshī',
          'kategori' => 'Keluarga',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Murid',
          'bahasa_inggris' => 'Student',
          'fonetik' => 'styu-dent',
          'bahasa_arab' => 'تِلْمِيْذٌ',
          'fonetik_arab' => 'Tilmīdhun',
          'bahasa_mandarin' => '学生',
          'fonetik_mandarin' => 'Xuésheng',
          'kategori' => 'Keluarga',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Majikan',
          'bahasa_inggris' => 'Employer',
          'fonetik' => 'em-ploy-er',
          'bahasa_arab' => 'صَاحِبُ الْعَمَلِ',
          'fonetik_arab' => 'Ṣāḥibul ʿAmali',
          'bahasa_mandarin' => '雇主',
          'fonetik_mandarin' => 'Gùzhǔ',
          'kategori' => 'Keluarga',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Pembantu',
          'bahasa_inggris' => 'Maid',
          'fonetik' => 'meyd',
          'bahasa_arab' => 'خَادِمَةٌ',
          'fonetik_arab' => 'Khādimatun',
          'bahasa_mandarin' => '佣人',
          'fonetik_mandarin' => 'Yòngrén',
          'kategori' => 'Keluarga',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Pengasuh',
          'bahasa_inggris' => 'Nanny',
          'fonetik' => 'ne-ni',
          'bahasa_arab' => 'مُرَبِّيَةٌ',
          'fonetik_arab' => 'Murabbiyatun',
          'bahasa_mandarin' => '保姆',
          'fonetik_mandarin' => 'Bǎomǔ',
          'kategori' => 'Keluarga',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Sopir',
          'bahasa_inggris' => 'Driver',
          'fonetik' => 'drai-ver',
          'bahasa_arab' => 'سَائِقٌ',
          'fonetik_arab' => 'Sāʾiqun',
          'bahasa_mandarin' => '司机',
          'fonetik_mandarin' => 'Sījī',
          'kategori' => 'Keluarga',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Tukang Kebun',
          'bahasa_inggris' => 'Gardener',
          'fonetik' => 'gar-de-ner',
          'bahasa_arab' => 'بُسْتَانِيٌّ',
          'fonetik_arab' => 'Bustāniyyun',
          'bahasa_mandarin' => '园丁',
          'fonetik_mandarin' => 'Yuándīng',
          'kategori' => 'Keluarga',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Satpam',
          'bahasa_inggris' => 'Security Guard',
          'fonetik' => 'si-kyu-ri-ti gard',
          'bahasa_arab' => 'حَارِسُ الْأَمْنِ',
          'fonetik_arab' => 'Ḥārisul Amni',
          'bahasa_mandarin' => '保安',
          'fonetik_mandarin' => 'Bǎo\'ān',
          'kategori' => 'Keluarga',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Balita',
          'bahasa_inggris' => 'Toddler',
          'fonetik' => 'tod-ler',
          'bahasa_arab' => 'طِفْلٌ دَارِجٌ',
          'fonetik_arab' => 'Ṭiflun Dārijun',
          'bahasa_mandarin' => '幼儿',
          'fonetik_mandarin' => 'Yòu\'ér',
          'kategori' => 'Keluarga',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Remaja',
          'bahasa_inggris' => 'Teenager',
          'fonetik' => 'ti-ney-jer',
          'bahasa_arab' => 'مُرَاهِقٌ',
          'fonetik_arab' => 'Murāhiqun',
          'bahasa_mandarin' => '青少年',
          'fonetik_mandarin' => 'Qīngshàonián',
          'kategori' => 'Keluarga',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Pemuda',
          'bahasa_inggris' => 'Young Man',
          'fonetik' => 'yang men',
          'bahasa_arab' => 'شَابٌّ',
          'fonetik_arab' => 'Syābbun',
          'bahasa_mandarin' => '青年',
          'fonetik_mandarin' => 'Qīngnián',
          'kategori' => 'Keluarga',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Dewasa',
          'bahasa_inggris' => 'Adult',
          'fonetik' => 'e-dalt',
          'bahasa_arab' => 'بَالِغٌ',
          'fonetik_arab' => 'Bālighun',
          'bahasa_mandarin' => '成年人',
          'fonetik_mandarin' => 'Chéngniánrén',
          'kategori' => 'Keluarga',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Lansia',
          'bahasa_inggris' => 'Elderly',
          'fonetik' => 'el-der-li',
          'bahasa_arab' => 'مُسِنٌّ',
          'fonetik_arab' => 'Musinnun',
          'bahasa_mandarin' => '老人',
          'fonetik_mandarin' => 'Lǎorén',
          'kategori' => 'Keluarga',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Anak-anak',
          'bahasa_inggris' => 'Children',
          'fonetik' => 'cil-dren',
          'bahasa_arab' => 'أَطْفَالٌ',
          'fonetik_arab' => 'Aṭfālun',
          'bahasa_mandarin' => '孩子们',
          'fonetik_mandarin' => 'Háizimen',
          'kategori' => 'Keluarga',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Buyut',
          'bahasa_inggris' => 'Great-grandparent',
          'fonetik' => 'greit grend-pe-rent',
          'bahasa_arab' => 'أَبُ الْجَدِّ',
          'fonetik_arab' => 'Abul Jaddi',
          'bahasa_mandarin' => '曾祖父母',
          'fonetik_mandarin' => 'Zēngzǔfùmǔ',
          'kategori' => 'Keluarga',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Cicit',
          'bahasa_inggris' => 'Great-grandchild',
          'fonetik' => 'greit grend-caild',
          'bahasa_arab' => 'اِبْنُ الْحَفِيْدِ',
          'fonetik_arab' => 'Ibnul Ḥafīdi',
          'bahasa_mandarin' => '曾孙',
          'fonetik_mandarin' => 'Zēngsūn',
          'kategori' => 'Keluarga',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Leluhur',
          'bahasa_inggris' => 'Ancestor',
          'fonetik' => 'an-ses-ter',
          'bahasa_arab' => 'سَلَفٌ',
          'fonetik_arab' => 'Salafun',
          'bahasa_mandarin' => '祖先',
          'fonetik_mandarin' => 'Zǔxiān',
          'kategori' => 'Keluarga',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Keturunan',
          'bahasa_inggris' => 'Descendant',
          'fonetik' => 'di-sen-dent',
          'bahasa_arab' => 'نَسْلٌ',
          'fonetik_arab' => 'Naslun',
          'bahasa_mandarin' => '后裔',
          'fonetik_mandarin' => 'Hòuyì',
          'kategori' => 'Keluarga',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Garis Keturunan',
          'bahasa_inggris' => 'Lineage',
          'fonetik' => 'li-ni-yej',
          'bahasa_arab' => 'سُلَالَةٌ',
          'fonetik_arab' => 'Sulālatun',
          'bahasa_mandarin' => '血统',
          'fonetik_mandarin' => 'Xuètǒng',
          'kategori' => 'Keluarga',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Keluarga Besar',
          'bahasa_inggris' => 'Extended Family',
          'fonetik' => 'eks-ten-ded fe-mi-li',
          'bahasa_arab' => 'عَائِلَةٌ مُمْتَدَّةٌ',
          'fonetik_arab' => 'ʿĀʾilatun Mumtaddatun',
          'bahasa_mandarin' => '大家庭',
          'fonetik_mandarin' => 'Dàjiātíng',
          'kategori' => 'Keluarga',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Tunangan',
          'bahasa_inggris' => 'Fiancé',
          'fonetik' => 'fi-ang-sey',
          'bahasa_arab' => 'خَطِيْبٌ',
          'fonetik_arab' => 'Khaṭībun',
          'bahasa_mandarin' => '未婚夫/妻',
          'fonetik_mandarin' => 'Wèihūnfū/qī',
          'kategori' => 'Keluarga',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Pengantin Laki-laki',
          'bahasa_inggris' => 'Groom',
          'fonetik' => 'grum',
          'bahasa_arab' => 'عَرِيْسٌ',
          'fonetik_arab' => 'ʿArīsun',
          'bahasa_mandarin' => '新郎',
          'fonetik_mandarin' => 'Xīnláng',
          'kategori' => 'Keluarga',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Pengantin Perempuan',
          'bahasa_inggris' => 'Bride',
          'fonetik' => 'braid',
          'bahasa_arab' => 'عَرُوْسٌ',
          'fonetik_arab' => 'ʿArūsun',
          'bahasa_mandarin' => '新娘',
          'fonetik_mandarin' => 'Xīnniáng',
          'kategori' => 'Keluarga',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Duda',
          'bahasa_inggris' => 'Widower',
          'fonetik' => 'wi-dou-wer',
          'bahasa_arab' => 'أَرْمَلٌ',
          'fonetik_arab' => 'Armalun',
          'bahasa_mandarin' => '鳏夫',
          'fonetik_mandarin' => 'Guānfū',
          'kategori' => 'Keluarga',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Janda',
          'bahasa_inggris' => 'Widow',
          'fonetik' => 'wi-dou',
          'bahasa_arab' => 'أَرْمَلَةٌ',
          'fonetik_arab' => 'Armalatun',
          'bahasa_mandarin' => '寡妇',
          'fonetik_mandarin' => 'Guǎfu',
          'kategori' => 'Keluarga',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Yatim Piatu',
          'bahasa_inggris' => 'Orphan',
          'fonetik' => 'or-fan',
          'bahasa_arab' => 'يَتِيْمٌ',
          'fonetik_arab' => 'Yatīmun',
          'bahasa_mandarin' => '孤儿',
          'fonetik_mandarin' => 'Gū\'ér',
          'kategori' => 'Keluarga',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Anak Sulung',
          'bahasa_inggris' => 'Firstborn',
          'fonetik' => 'ferst-born',
          'bahasa_arab' => 'اِبْنٌ بكرٌ',
          'fonetik_arab' => 'Ibnun Bikrun',
          'bahasa_mandarin' => '长子/女',
          'fonetik_mandarin' => 'Zhǎngzǐ/nǚ',
          'kategori' => 'Keluarga',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Anak Tengah',
          'bahasa_inggris' => 'Middle Child',
          'fonetik' => 'mi-del caild',
          'bahasa_arab' => 'اِبْنٌ أَوْسَطُ',
          'fonetik_arab' => 'Ibnun Awsaṭu',
          'bahasa_mandarin' => '中间的孩子',
          'fonetik_mandarin' => 'Zhōngjiān de háizi',
          'kategori' => 'Keluarga',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Anak Bungsu',
          'bahasa_inggris' => 'Youngest Child',
          'fonetik' => 'yang-gest caild',
          'bahasa_arab' => 'اِبْنٌ أَصْغَرُ',
          'fonetik_arab' => 'Ibnun Ashgharu',
          'bahasa_mandarin' => '最小的孩子',
          'fonetik_mandarin' => 'Zuìxiǎo de háizi',
          'kategori' => 'Keluarga',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Anak Tunggal',
          'bahasa_inggris' => 'Only Child',
          'fonetik' => 'on-li caild',
          'bahasa_arab' => 'اِبْنٌ وَحِيْدٌ',
          'fonetik_arab' => 'Ibnun Waḥīdun',
          'bahasa_mandarin' => '独生子/女',
          'fonetik_mandarin' => 'Dúshēngzǐ/nǚ',
          'kategori' => 'Keluarga',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Anak Kembar',
          'bahasa_inggris' => 'Twins',
          'fonetik' => 'twinz',
          'bahasa_arab' => 'تَوْأَمٌ',
          'fonetik_arab' => 'Tawʾamun',
          'bahasa_mandarin' => '双胞胎',
          'fonetik_mandarin' => 'Shuāngbāotāi',
          'kategori' => 'Keluarga',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Anak Pertama',
          'bahasa_inggris' => 'The First Child',
          'fonetik' => 'dhe ferst caild',
          'bahasa_arab' => 'الْوَلَدُ الْأَوَّلُ',
          'fonetik_arab' => 'Al-Waladul Awwalu',
          'bahasa_mandarin' => '第一胎',
          'fonetik_mandarin' => 'Dì yītāi',
          'kategori' => 'Keluarga',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Rekan Kerja',
          'bahasa_inggris' => 'Colleague',
          'fonetik' => 'ko-lig',
          'bahasa_arab' => 'زَمِيْلُ الْعَمَلِ',
          'fonetik_arab' => 'Zamīlul ʿAmali',
          'bahasa_mandarin' => '同事',
          'fonetik_mandarin' => 'Tóngshì',
          'kategori' => 'Keluarga',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Atasan',
          'bahasa_inggris' => 'Superior',
          'fonetik' => 'su-pi-ri-yer',
          'bahasa_arab' => 'مُدِيْرٌ',
          'fonetik_arab' => 'Mudīrun',
          'bahasa_mandarin' => '上司',
          'fonetik_mandarin' => 'Shàngsī',
          'kategori' => 'Keluarga',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Bawahan',
          'bahasa_inggris' => 'Subordinate',
          'fonetik' => 'sa-bor-di-neyt',
          'bahasa_arab' => 'مَرْؤُوْسٌ',
          'fonetik_arab' => 'Marʾūsun',
          'bahasa_mandarin' => '下属',
          'fonetik_mandarin' => 'Xiàshǔ',
          'kategori' => 'Keluarga',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Kenalan',
          'bahasa_inggris' => 'Acquaintance',
          'fonetik' => 'e-kwen-tens',
          'bahasa_arab' => 'مَعْرِفَةٌ',
          'fonetik_arab' => 'Maʿrifatun',
          'bahasa_mandarin' => '熟人',
          'fonetik_mandarin' => 'Shúrén',
          'kategori' => 'Keluarga',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Musuh',
          'bahasa_inggris' => 'Enemy',
          'fonetik' => 'e-ne-mi',
          'bahasa_arab' => 'عَدُوٌّ',
          'fonetik_arab' => 'ʿAduwwun',
          'bahasa_mandarin' => '敌人',
          'fonetik_mandarin' => 'Dírén',
          'kategori' => 'Keluarga',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Saingan',
          'bahasa_inggris' => 'Rival',
          'fonetik' => 'rai-vel',
          'bahasa_arab' => 'مُنَافِسٌ',
          'fonetik_arab' => 'Munāfisun',
          'bahasa_mandarin' => '对手',
          'fonetik_mandarin' => 'Duìshǒu',
          'kategori' => 'Keluarga',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Kakak Ipar',
          'bahasa_inggris' => 'Brother-in-law (Older)',
          'fonetik' => 'bra-dher in lo',
          'bahasa_arab' => 'حَمٌ',
          'fonetik_arab' => 'Ḥamun',
          'bahasa_mandarin' => '姐夫/姐夫',
          'fonetik_mandarin' => 'Jiěfu/Jiěfu',
          'kategori' => 'Keluarga',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Adik Ipar',
          'bahasa_inggris' => 'Sister-in-law (Younger)',
          'fonetik' => 'sis-ter in lo',
          'bahasa_arab' => 'حَمَاةٌ',
          'fonetik_arab' => 'Ḥamātun',
          'bahasa_mandarin' => '小叔/小姑',
          'fonetik_mandarin' => 'Xiǎoshū/Xiǎogū',
          'kategori' => 'Keluarga',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Saudara Seayah',
          'bahasa_inggris' => 'Paternal Half-sibling',
          'fonetik' => 'pa-ter-nal haf sib-ling',
          'bahasa_arab' => 'أَخٌ لِأَبٍ',
          'fonetik_arab' => 'Akhun li-Abin',
          'bahasa_mandarin' => '同父异母兄弟姐妹',
          'fonetik_mandarin' => 'Tóngfù yìmǔ xiōngdì jiěmèi',
          'kategori' => 'Keluarga',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Saudara Seibu',
          'bahasa_inggris' => 'Maternal Half-sibling',
          'fonetik' => 'ma-ter-nal haf sib-ling',
          'bahasa_arab' => 'أَخٌ لِأُمٍّ',
          'fonetik_arab' => 'Akhun li-Ummin',
          'bahasa_mandarin' => '同母异父兄弟姐妹',
          'fonetik_mandarin' => 'Tóngmǔ yìfù xiōngdì jiěmèi',
          'kategori' => 'Keluarga',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Ibu Mertua',
          'bahasa_inggris' => 'Mother-in-law',
          'fonetik' => 'ma-dher in lo',
          'bahasa_arab' => 'حَمَاةٌ',
          'fonetik_arab' => 'Ḥamātun',
          'bahasa_mandarin' => '婆婆/岳母',
          'fonetik_mandarin' => 'Pópo/Yuèmǔ',
          'kategori' => 'Keluarga',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Bapak Mertua',
          'bahasa_inggris' => 'Father-in-law',
          'fonetik' => 'fa-dher in lo',
          'bahasa_arab' => 'حَمٌ',
          'fonetik_arab' => 'Ḥamun',
          'bahasa_mandarin' => '公公/岳父',
          'fonetik_mandarin' => 'Gōnggong/Yuèfù',
          'kategori' => 'Keluarga',
          'hari' => 13,
        ),
    );
  }
}