<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Kendaraan
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Mobil',
          'bahasa_inggris' => 'Car',
          'fonetik' => 'kar',
          'bahasa_arab' => 'سَيَّارَةٌ',
          'fonetik_arab' => 'Sayyāratun',
          'bahasa_mandarin' => '汽车',
          'fonetik_mandarin' => 'Qìchē',
          'kategori' => 'Kendaraan',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Bus',
          'bahasa_inggris' => 'Bus',
          'fonetik' => 'bas',
          'bahasa_arab' => 'حَافِلَةٌ',
          'fonetik_arab' => 'Ḥāfilatun',
          'bahasa_mandarin' => '公交车',
          'fonetik_mandarin' => 'Gōngjiāochē',
          'kategori' => 'Kendaraan',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Truk',
          'bahasa_inggris' => 'Truck',
          'fonetik' => 'trak',
          'bahasa_arab' => 'شَاحِنَةٌ',
          'fonetik_arab' => 'Shāḥinatun',
          'bahasa_mandarin' => '卡车',
          'fonetik_mandarin' => 'Kǎchē',
          'kategori' => 'Kendaraan',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Motor',
          'bahasa_inggris' => 'Motorcycle',
          'fonetik' => 'mo-ter-sai-kel',
          'bahasa_arab' => 'دَرَّاجَةٌ نَارِيَّةٌ',
          'fonetik_arab' => 'Darrājatun Nāriyyah',
          'bahasa_mandarin' => '摩托车',
          'fonetik_mandarin' => 'Mótuōchē',
          'kategori' => 'Kendaraan',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Sepeda',
          'bahasa_inggris' => 'Bicycle',
          'fonetik' => 'bai-si-kel',
          'bahasa_arab' => 'دَرَّاجَةٌ هَوَائِيَّةٌ',
          'fonetik_arab' => 'Darrājatun Hawāʾiyyah',
          'bahasa_mandarin' => '自行车',
          'fonetik_mandarin' => 'Zìxíngchē',
          'kategori' => 'Kendaraan',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Kereta Api',
          'bahasa_inggris' => 'Train',
          'fonetik' => 'trein',
          'bahasa_arab' => 'قِطَارٌ',
          'fonetik_arab' => 'Qiṭārun',
          'bahasa_mandarin' => '火车',
          'fonetik_mandarin' => 'Huǒchē',
          'kategori' => 'Kendaraan',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Pesawat',
          'bahasa_inggris' => 'Airplane',
          'fonetik' => 'er-plein',
          'bahasa_arab' => 'طَائِرَةٌ',
          'fonetik_arab' => 'Ṭāʾiratun',
          'bahasa_mandarin' => '飞机',
          'fonetik_mandarin' => 'Fēijī',
          'kategori' => 'Kendaraan',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Kapal',
          'bahasa_inggris' => 'Ship',
          'fonetik' => 'syip',
          'bahasa_arab' => 'سَفِينَةٌ',
          'fonetik_arab' => 'Safīnatun',
          'bahasa_mandarin' => '船',
          'fonetik_mandarin' => 'Chuán',
          'kategori' => 'Kendaraan',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Perahu',
          'bahasa_inggris' => 'Boat',
          'fonetik' => 'bout',
          'bahasa_arab' => 'قَارِبٌ',
          'fonetik_arab' => 'Qāribun',
          'bahasa_mandarin' => '小船',
          'fonetik_mandarin' => 'Xiǎochuán',
          'kategori' => 'Kendaraan',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Helikopter',
          'bahasa_inggris' => 'Helicopter',
          'fonetik' => 'he-li-kop-ter',
          'bahasa_arab' => 'مِرْوَاحِيَّةٌ',
          'fonetik_arab' => 'Mirwāḥiyyah',
          'bahasa_mandarin' => '直升机',
          'fonetik_mandarin' => 'Zhíshēngjī',
          'kategori' => 'Kendaraan',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Taksi',
          'bahasa_inggris' => 'Taxi',
          'fonetik' => 'tek-si',
          'bahasa_arab' => 'سَيَّارَةُ أُجْرَةٍ',
          'fonetik_arab' => 'Sayyāratu Ujrah',
          'bahasa_mandarin' => '出租车',
          'fonetik_mandarin' => 'Chūzūchē',
          'kategori' => 'Kendaraan',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Ambulans',
          'bahasa_inggris' => 'Ambulance',
          'fonetik' => 'em-byu-lens',
          'bahasa_arab' => 'سَيَّارَةُ إِسْعَافٍ',
          'fonetik_arab' => 'Sayyāratu Isʿāf',
          'bahasa_mandarin' => '救护车',
          'fonetik_mandarin' => 'Jiùhùchē',
          'kategori' => 'Kendaraan',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Mobil Polisi',
          'bahasa_inggris' => 'Police car',
          'fonetik' => 'po-lis kar',
          'bahasa_arab' => 'سَيَّارَةُ شُرْطَةٍ',
          'fonetik_arab' => 'Sayyāratu Shurṭah',
          'bahasa_mandarin' => '警车',
          'fonetik_mandarin' => 'Jǐngchē',
          'kategori' => 'Kendaraan',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Mobil Pemadam',
          'bahasa_inggris' => 'Fire truck',
          'fonetik' => 'fai-er trak',
          'bahasa_arab' => 'سَيَّارَةُ إِطْفَاءٍ',
          'fonetik_arab' => 'Sayyāratu Iṭfāʾ',
          'bahasa_mandarin' => '消防车',
          'fonetik_mandarin' => 'Xiāofángchē',
          'kategori' => 'Kendaraan',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Traktor',
          'bahasa_inggris' => 'Tractor',
          'fonetik' => 'trek-ter',
          'bahasa_arab' => 'جَرَّارٌ',
          'fonetik_arab' => 'Jarrārun',
          'bahasa_mandarin' => '拖拉机',
          'fonetik_mandarin' => 'Tuōlājī',
          'kategori' => 'Kendaraan',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Sekuter',
          'bahasa_inggris' => 'Scooter',
          'fonetik' => 'sku-ter',
          'bahasa_arab' => 'سكوتر',
          'fonetik_arab' => 'Sukūtar',
          'bahasa_mandarin' => '踏板车',
          'fonetik_mandarin' => 'Tàbǎnchē',
          'kategori' => 'Kendaraan',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Van',
          'bahasa_inggris' => 'Van',
          'fonetik' => 'ven',
          'bahasa_arab' => 'شَاحِنَةٌ صَغِيرَةٌ',
          'fonetik_arab' => 'Shāḥinatun Ṣaghīrah',
          'bahasa_mandarin' => '面包车',
          'fonetik_mandarin' => 'Miànbāochē',
          'kategori' => 'Kendaraan',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Kapal Selam',
          'bahasa_inggris' => 'Submarine',
          'fonetik' => 'sab-ma-rin',
          'bahasa_arab' => 'غَوَّاصَةٌ',
          'fonetik_arab' => 'Ghawwāṣatun',
          'bahasa_mandarin' => '潜水艇',
          'fonetik_mandarin' => 'Qiánshuǐtǐng',
          'kategori' => 'Kendaraan',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Roket',
          'bahasa_inggris' => 'Rocket',
          'fonetik' => 'ro-ket',
          'bahasa_arab' => 'صَارُوخٌ',
          'fonetik_arab' => 'Ṣārūkhun',
          'bahasa_mandarin' => '火箭',
          'fonetik_mandarin' => 'Huǒjiàn',
          'kategori' => 'Kendaraan',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Balon Udara',
          'bahasa_inggris' => 'Hot air balloon',
          'fonetik' => 'hot er ba-lun',
          'bahasa_arab' => 'مُنْطَادٌ',
          'fonetik_arab' => 'Munṭādun',
          'bahasa_mandarin' => '热气球',
          'fonetik_mandarin' => 'Rèqìqiú',
          'kategori' => 'Kendaraan',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Tank',
          'bahasa_inggris' => 'Tank',
          'fonetik' => 'tengk',
          'bahasa_arab' => 'دَبَّابَةٌ',
          'fonetik_arab' => 'Dabbābatun',
          'bahasa_mandarin' => '坦克',
          'fonetik_mandarin' => 'Tǎnkè',
          'kategori' => 'Kendaraan',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Papan Luncur',
          'bahasa_inggris' => 'Skateboard',
          'fonetik' => 'skeyt-bord',
          'bahasa_arab' => 'لَوْحُ تَزَلُّجٍ',
          'fonetik_arab' => 'Lawḥu Tazalluj',
          'bahasa_mandarin' => '滑板',
          'fonetik_mandarin' => 'Huábǎn',
          'kategori' => 'Kendaraan',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Sepatu Roda',
          'bahasa_inggris' => 'Roller skates',
          'fonetik' => 'ro-ler skeyts',
          'bahasa_arab' => 'مِزْلَاجٌ',
          'fonetik_arab' => 'Mizlājún',
          'bahasa_mandarin' => '旱冰鞋',
          'fonetik_mandarin' => 'Hànbīngxié',
          'kategori' => 'Kendaraan',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Becak',
          'bahasa_inggris' => 'Pedicab',
          'fonetik' => 'pe-di-keb',
          'bahasa_arab' => 'بِيتْشَاك',
          'fonetik_arab' => 'Bītsyāk',
          'bahasa_mandarin' => '三轮车',
          'fonetik_mandarin' => 'Sānlúnchē',
          'kategori' => 'Kendaraan',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'MRT',
          'bahasa_inggris' => 'Mass Rapid Transit',
          'fonetik' => 'mes re-pid tren-sit',
          'bahasa_arab' => 'الْقِطَارُ السَّرِيْعُ',
          'fonetik_arab' => 'Al-Qiṭārus Sarīʿ',
          'bahasa_mandarin' => '捷运',
          'fonetik_mandarin' => 'Jiéyùn',
          'kategori' => 'Kendaraan',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'LRT',
          'bahasa_inggris' => 'Light Rail Transit',
          'fonetik' => 'lait reyl tren-sit',
          'bahasa_arab' => 'الْقِطَارُ الْخَفِيْفُ',
          'fonetik_arab' => 'Al-Qiṭārul Khafīf',
          'bahasa_mandarin' => '轻轨',
          'fonetik_mandarin' => 'Qīngguǐ',
          'kategori' => 'Kendaraan',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Monorel',
          'bahasa_inggris' => 'Monorail',
          'fonetik' => 'mo-no-reyl',
          'bahasa_arab' => 'قِطَارٌ أُحَادِيُّ السِّكَّةِ',
          'fonetik_arab' => 'Qiṭārun Uḥādiyus Sikkah',
          'bahasa_mandarin' => '单轨铁路',
          'fonetik_mandarin' => 'Dānguǐ tiělù',
          'kategori' => 'Kendaraan',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Mikrolet',
          'bahasa_inggris' => 'Minibus',
          'fonetik' => 'mi-ni-bas',
          'bahasa_arab' => 'حَافِلَةٌ صَغِيْرَةٌ',
          'fonetik_arab' => 'Ḥāfilatun Shaghiirah',
          'bahasa_mandarin' => '小巴',
          'fonetik_mandarin' => 'Xiǎobā',
          'kategori' => 'Kendaraan',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Bajaj',
          'bahasa_inggris' => 'Auto rickshaw',
          'fonetik' => 'o-to rik-syo',
          'bahasa_arab' => 'تُك تُك',
          'fonetik_arab' => 'Tuk Tuk',
          'bahasa_mandarin' => '嘟嘟车',
          'fonetik_mandarin' => 'Dūdūchē',
          'kategori' => 'Kendaraan',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Delman',
          'bahasa_inggris' => 'Horse-drawn carriage',
          'fonetik' => 'hors-dron ke-riej',
          'bahasa_arab' => 'عَرَبَةُ خُيُولٍ',
          'fonetik_arab' => 'ʿArabatu Khuyūlin',
          'bahasa_mandarin' => '马车',
          'fonetik_mandarin' => 'Mǎchē',
          'kategori' => 'Kendaraan',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Mobil Balap',
          'bahasa_inggris' => 'Racing car',
          'fonetik' => 'rey-sing kar',
          'bahasa_arab' => 'سَيَّارَةُ سِبَاقٍ',
          'fonetik_arab' => 'Sayyāratu Sibāq',
          'bahasa_mandarin' => '赛车',
          'fonetik_mandarin' => 'Sàichē',
          'kategori' => 'Kendaraan',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Mobil Jenazah',
          'bahasa_inggris' => 'Hearse',
          'fonetik' => 'hers',
          'bahasa_arab' => 'سَيَّارَةُ نَقْلِ الْمَوْتَى',
          'fonetik_arab' => 'Sayyāratu Naqlil Mawtā',
          'bahasa_mandarin' => '灵车',
          'fonetik_mandarin' => 'Língchē',
          'kategori' => 'Kendaraan',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Mobil Derek',
          'bahasa_inggris' => 'Tow truck',
          'fonetik' => 'tou trak',
          'bahasa_arab' => 'شَاحِنَةُ سَحْبٍ',
          'fonetik_arab' => 'Shāḥinatu Saḥbin',
          'bahasa_mandarin' => '拖车',
          'fonetik_mandarin' => 'Tuōchē',
          'kategori' => 'Kendaraan',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Mobil Sampah',
          'bahasa_inggris' => 'Garbage truck',
          'fonetik' => 'gar-beij trak',
          'bahasa_arab' => 'شَاحِنَةُ نَفَايَاتٍ',
          'fonetik_arab' => 'Shāḥinatu Nafāyātin',
          'bahasa_mandarin' => '垃圾车',
          'fonetik_mandarin' => 'Lājīchē',
          'kategori' => 'Kendaraan',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Mobil Tangki',
          'bahasa_inggris' => 'Tanker truck',
          'fonetik' => 'teng-ker trak',
          'bahasa_arab' => 'شَاحِنَةُ صِهْرِيْجٍ',
          'fonetik_arab' => 'Shāḥinatu Ṣihrījin',
          'bahasa_mandarin' => '罐车',
          'fonetik_mandarin' => 'Guànchē',
          'kategori' => 'Kendaraan',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Limo',
          'bahasa_inggris' => 'Limousine',
          'fonetik' => 'li-mu-zin',
          'bahasa_arab' => 'لِيْمُوزِين',
          'fonetik_arab' => 'Līmūzīn',
          'bahasa_mandarin' => '豪华轿车',
          'fonetik_mandarin' => 'Háohuá jiàochē',
          'kategori' => 'Kendaraan',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Buldoser',
          'bahasa_inggris' => 'Bulldozer',
          'fonetik' => 'bul-do-zer',
          'bahasa_arab' => 'جَرَّافَةٌ',
          'fonetik_arab' => 'Jarrāfatun',
          'bahasa_mandarin' => '推土机',
          'fonetik_mandarin' => 'Tuītǔjī',
          'kategori' => 'Kendaraan',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Ekskavator',
          'bahasa_inggris' => 'Excavator',
          'fonetik' => 'eks-ka-ve-ter',
          'bahasa_arab' => 'حَفَّارَةٌ',
          'fonetik_arab' => 'Ḥaffāratun',
          'bahasa_mandarin' => '挖掘机',
          'fonetik_mandarin' => 'Wājuéjī',
          'kategori' => 'Kendaraan',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Crane',
          'bahasa_inggris' => 'Crane',
          'fonetik' => 'kreyn',
          'bahasa_arab' => 'رَافِعَةٌ',
          'fonetik_arab' => 'Rāfiʿatun',
          'bahasa_mandarin' => '起重机',
          'fonetik_mandarin' => 'Qǐzhòngjī',
          'kategori' => 'Kendaraan',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Forklift',
          'bahasa_inggris' => 'Forklift',
          'fonetik' => 'fork-lift',
          'bahasa_arab' => 'رَافِعَةٌ شَوْكِيَّةٌ',
          'fonetik_arab' => 'Rāfiʿatun Syawkiyyah',
          'bahasa_mandarin' => '叉车',
          'fonetik_mandarin' => 'Chāchē',
          'kategori' => 'Kendaraan',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Truk Molen',
          'bahasa_inggris' => 'Concrete mixer',
          'fonetik' => 'kon-krit mik-ser',
          'bahasa_arab' => 'خَلَّاطَةُ خَرَسَانَةٍ',
          'fonetik_arab' => 'Khallāṭatu Kharasānah',
          'bahasa_mandarin' => '混凝土搅拌车',
          'fonetik_mandarin' => 'Hùnníngtǔ jiǎobànchē',
          'kategori' => 'Kendaraan',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Truk Jungkit',
          'bahasa_inggris' => 'Dump truck',
          'fonetik' => 'damp trak',
          'bahasa_arab' => 'شَاحِنَةُ تَفْرِيْغٍ',
          'fonetik_arab' => 'Shāḥinatu Tafrīghin',
          'bahasa_mandarin' => '自卸卡车',
          'fonetik_mandarin' => 'Zìxiè kǎchē',
          'kategori' => 'Kendaraan',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Kapal Pesiar',
          'bahasa_inggris' => 'Cruise ship',
          'fonetik' => 'kruz syip',
          'bahasa_arab' => 'سَفِينَةٌ سِيَاحِيَّةٌ',
          'fonetik_arab' => 'Safīnatun Siyāḥiyyah',
          'bahasa_mandarin' => '邮轮',
          'fonetik_mandarin' => 'Yóulún',
          'kategori' => 'Kendaraan',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Kapal Feri',
          'bahasa_inggris' => 'Ferry',
          'fonetik' => 'fe-ri',
          'bahasa_arab' => 'عَبَّارَةٌ',
          'fonetik_arab' => 'ʿAbbāratun',
          'bahasa_mandarin' => '渡轮',
          'fonetik_mandarin' => 'Dùlún',
          'kategori' => 'Kendaraan',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Kapal Tongkang',
          'bahasa_inggris' => 'Barge',
          'fonetik' => 'barj',
          'bahasa_arab' => 'صَنْدَلٌ',
          'fonetik_arab' => 'Ṣandalun',
          'bahasa_mandarin' => '驳船',
          'fonetik_mandarin' => 'Bóchuán',
          'kategori' => 'Kendaraan',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Kapal Layar',
          'bahasa_inggris' => 'Sailboat',
          'fonetik' => 'seyl-bout',
          'bahasa_arab' => 'قَارِبٌ شِرَاعِيٌّ',
          'fonetik_arab' => 'Qāribun Syirāʿiyyun',
          'bahasa_mandarin' => '帆船',
          'fonetik_mandarin' => 'Fānchuán',
          'kategori' => 'Kendaraan',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Jetski',
          'bahasa_inggris' => 'Jetski',
          'fonetik' => 'jet-ski',
          'bahasa_arab' => 'دَرَّاجَةٌ مَائِيَّةٌ',
          'fonetik_arab' => 'Darrājatun Māʾiyyah',
          'bahasa_mandarin' => '水上摩托',
          'fonetik_mandarin' => 'Shuǐshàng mótuō',
          'kategori' => 'Kendaraan',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Rakit',
          'bahasa_inggris' => 'Raft',
          'fonetik' => 'raft',
          'bahasa_arab' => 'طَوْفٌ',
          'fonetik_arab' => 'Ṭawfun',
          'bahasa_mandarin' => '筏子',
          'fonetik_mandarin' => 'Fázi',
          'kategori' => 'Kendaraan',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Pesawat Tempur',
          'bahasa_inggris' => 'Fighter jet',
          'fonetik' => 'fai-ter jet',
          'bahasa_arab' => 'طَائِرَةٌ مُقَاتِلَةٌ',
          'fonetik_arab' => 'Ṭāʾiratun Muqātilah',
          'bahasa_mandarin' => '战斗机',
          'fonetik_mandarin' => 'Zhàndòujī',
          'kategori' => 'Kendaraan',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Pesawat Kargo',
          'bahasa_inggris' => 'Cargo plane',
          'fonetik' => 'kar-go plein',
          'bahasa_arab' => 'طَائِرَةُ شَحْنٍ',
          'fonetik_arab' => 'Ṭāʾiratu Syahnin',
          'bahasa_mandarin' => '运输机',
          'fonetik_mandarin' => 'Yùnshūjī',
          'kategori' => 'Kendaraan',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Paralayang',
          'bahasa_inggris' => 'Paraglide',
          'fonetik' => 'pe-re-glaid',
          'bahasa_arab' => 'مِظَلَّةٌ هُبُوْطٍ',
          'fonetik_arab' => 'Miẓallatu Hubūṭ',
          'bahasa_mandarin' => '滑翔伞',
          'fonetik_mandarin' => 'Huáxiángsǎn',
          'kategori' => 'Kendaraan',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Gantole',
          'bahasa_inggris' => 'Hang glider',
          'fonetik' => 'heng glai-der',
          'bahasa_arab' => 'طَائِرَةٌ شِرَاعِيَّةٌّ',
          'fonetik_arab' => 'Ṭāʾiratun Syirāʿiyyah',
          'bahasa_mandarin' => '悬挂式滑翔机',
          'fonetik_mandarin' => 'Xuánguàshì huáxiángjī',
          'kategori' => 'Kendaraan',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Drone',
          'bahasa_inggris' => 'Drone',
          'fonetik' => 'droun',
          'bahasa_arab' => 'طَائِرَةٌ بِدُوْنِ طَيَّارٍ',
          'fonetik_arab' => 'Ṭāʾiratun bidūni Ṭayyār',
          'bahasa_mandarin' => '无人机',
          'fonetik_mandarin' => 'Wúrénjī',
          'kategori' => 'Kendaraan',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Pesawat Amfibi',
          'bahasa_inggris' => 'Seaplane',
          'fonetik' => 'si-plein',
          'bahasa_arab' => 'طَائِرَةٌ بَرْمَائِيَّةٌ',
          'fonetik_arab' => 'Ṭāʾiratun Barmāʾiyyah',
          'bahasa_mandarin' => '水上飞机',
          'fonetik_mandarin' => 'Shuǐshàng fēijī',
          'kategori' => 'Kendaraan',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Kereta Salju',
          'bahasa_inggris' => 'Sled',
          'fonetik' => 'sled',
          'bahasa_arab' => 'مِزْلَجَةٌ',
          'fonetik_arab' => 'Mizlajatun',
          'bahasa_mandarin' => '雪橇',
          'fonetik_mandarin' => 'Xuěqiāo',
          'kategori' => 'Kendaraan',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Mobil Salju',
          'bahasa_inggris' => 'Snowmobile',
          'fonetik' => 'snou-mo-bil',
          'bahasa_arab' => 'دَرَّاجَةُ ثَلْجٍ',
          'fonetik_arab' => 'Darrājatu Tholjin',
          'bahasa_mandarin' => '雪地摩托',
          'fonetik_mandarin' => 'Xuědì mótuō',
          'kategori' => 'Kendaraan',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Ski',
          'bahasa_inggris' => 'Ski',
          'fonetik' => 'ski',
          'bahasa_arab' => 'زَلَّاجَةٌ',
          'fonetik_arab' => 'Zallājatun',
          'bahasa_mandarin' => '滑雪板',
          'fonetik_mandarin' => 'Huáxuěbǎn',
          'kategori' => 'Kendaraan',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Snowboard',
          'bahasa_inggris' => 'Snowboard',
          'fonetik' => 'snou-bord',
          'bahasa_arab' => 'لَوْحُ التَّزَلُّجِ عَلَى الثَّلْجِ',
          'fonetik_arab' => 'Lawḥut Tazalluji ʿalā Tholj',
          'bahasa_mandarin' => '单板滑雪',
          'fonetik_mandarin' => 'Dānbǎn huáxuě',
          'kategori' => 'Kendaraan',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Kereta Gantung',
          'bahasa_inggris' => 'Cable car',
          'fonetik' => 'key-bel kar',
          'bahasa_arab' => 'عَرَبَةُ كَابِلاتٍ',
          'fonetik_arab' => 'ʿArabatu Kābilāt',
          'bahasa_mandarin' => '缆车',
          'fonetik_mandarin' => 'Lǎnchē',
          'kategori' => 'Kendaraan',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Gondola',
          'bahasa_inggris' => 'Gondola',
          'fonetik' => 'gon-do-la',
          'bahasa_arab' => 'جُنْدُوْل',
          'fonetik_arab' => 'Jundūl',
          'bahasa_mandarin' => '平底船',
          'fonetik_mandarin' => 'Píngdǐchuán',
          'kategori' => 'Kendaraan',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Kereta Kuda',
          'bahasa_inggris' => 'Horse carriage',
          'fonetik' => 'hors ke-riej',
          'bahasa_arab' => 'عَرَبَةُ خُيُولٍ',
          'fonetik_arab' => 'ʿArabatu Khuyūlin',
          'bahasa_mandarin' => '马车',
          'fonetik_mandarin' => 'Mǎchē',
          'kategori' => 'Kendaraan',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Dokar',
          'bahasa_inggris' => 'Gig',
          'fonetik' => 'gig',
          'bahasa_arab' => 'دُوْكَار',
          'fonetik_arab' => 'Dūkār',
          'bahasa_mandarin' => '两轮马车',
          'fonetik_mandarin' => 'Liǎng lún mǎchē',
          'kategori' => 'Kendaraan',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Andong',
          'bahasa_inggris' => 'Four-wheeled carriage',
          'fonetik' => 'for wild ke-riej',
          'bahasa_arab' => 'عَرَبَةٌ بِأَرْبَعِ عَجَلَاتٍ',
          'fonetik_arab' => 'ʿArabatun bi-Arbaʿi ʿAjalāt',
          'bahasa_mandarin' => '四轮马车',
          'fonetik_mandarin' => 'Sì lún mǎchē',
          'kategori' => 'Kendaraan',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Bendi',
          'bahasa_inggris' => 'Chariot',
          'fonetik' => 'ce-ri-yot',
          'bahasa_arab' => 'عَرَبَةٌ حَرْبِيَّةٌ',
          'fonetik_arab' => 'ʿArabatun Ḥarbiyyah',
          'bahasa_mandarin' => '战车',
          'fonetik_mandarin' => 'Zhànchē',
          'kategori' => 'Kendaraan',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Gerobak',
          'bahasa_inggris' => 'Cart',
          'fonetik' => 'kart',
          'bahasa_arab' => 'عَرَبَةٌ يَدَوِيَّةٌ',
          'fonetik_arab' => 'ʿArabatun Yadawiyyah',
          'bahasa_mandarin' => '手推车',
          'fonetik_mandarin' => 'Shǒutuīchē',
          'kategori' => 'Kendaraan',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Pedati',
          'bahasa_inggris' => 'Ox-cart',
          'fonetik' => 'oks kart',
          'bahasa_arab' => 'عَرَبَةٌ تَجُرُّهَا الثِّيْرَانُ',
          'fonetik_arab' => 'ʿArabatun tajurruhuts Tsīrān',
          'bahasa_mandarin' => '牛车',
          'fonetik_mandarin' => 'Niúchē',
          'kategori' => 'Kendaraan',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Sepeda Lipat',
          'bahasa_inggris' => 'Folding bike',
          'fonetik' => 'foul-ding baik',
          'bahasa_arab' => 'دَرَّاجَةٌ قَابِلَةٌ لِلطَّيِّ',
          'fonetik_arab' => 'Darrājatun Qābilatun liṭ-Ṭayy',
          'bahasa_mandarin' => '折叠自行车',
          'fonetik_mandarin' => 'Zhédié zìxíngchē',
          'kategori' => 'Kendaraan',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Otopet',
          'bahasa_inggris' => 'Push scooter',
          'fonetik' => 'pusy sku-ter',
          'bahasa_arab' => 'سكوتر يَدَوِيّ',
          'fonetik_arab' => 'Sukūtar Yadawiyy',
          'bahasa_mandarin' => '滑板车',
          'fonetik_mandarin' => 'Huábǎnchē',
          'kategori' => 'Kendaraan',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Segway',
          'bahasa_inggris' => 'Segway',
          'fonetik' => 'seg-wey',
          'bahasa_arab' => 'سِيْجْوِي',
          'fonetik_arab' => 'Sījwī',
          'bahasa_mandarin' => '赛格威',
          'fonetik_mandarin' => 'Sàigéwēi',
          'kategori' => 'Kendaraan',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Hoverboard',
          'bahasa_inggris' => 'Hoverboard',
          'fonetik' => 'ho-ver-bord',
          'bahasa_arab' => 'لَوْحٌ طَائِرٌ',
          'fonetik_arab' => 'Lawḥun Ṭāʾirun',
          'bahasa_mandarin' => '悬浮滑板',
          'fonetik_mandarin' => 'Xuánfú huábǎn',
          'kategori' => 'Kendaraan',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Unicycle',
          'bahasa_inggris' => 'Unicycle',
          'fonetik' => 'yu-ni-sai-kel',
          'bahasa_arab' => 'دَرَّاجَةٌ أُحَادِيَّةُ الْعَجَلَةِ',
          'fonetik_arab' => 'Darrājatun Uḥādiyyatul ʿAjalah',
          'bahasa_mandarin' => '单轮车',
          'fonetik_mandarin' => 'Dānlúnchē',
          'kategori' => 'Kendaraan',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Tandem',
          'bahasa_inggris' => 'Tandem bicycle',
          'fonetik' => 'ten-dem bai-si-kel',
          'bahasa_arab' => 'دَرَّاجَةٌ تَرْكِيْبِيَّةٌ',
          'fonetik_arab' => 'Darrājatun Tarkībiyyah',
          'bahasa_mandarin' => '双人自行车',
          'fonetik_mandarin' => 'Shuāngrén zìxíngchē',
          'kategori' => 'Kendaraan',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Pesawat Luar Angkasa',
          'bahasa_inggris' => 'Spacecraft',
          'fonetik' => 'speys-kraft',
          'bahasa_arab' => 'سَفِينَةُ فَضَاءٍ',
          'fonetik_arab' => 'Safīnatu Faḍāʾ',
          'bahasa_mandarin' => '宇宙飞船',
          'fonetik_mandarin' => 'Yǔzhòu fēichuán',
          'kategori' => 'Kendaraan',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Rover',
          'bahasa_inggris' => 'Lunar rover',
          'fonetik' => 'lu-ner rou-ver',
          'bahasa_arab' => 'مَرْكَبَةٌ فَضَائِيَّةٌ',
          'fonetik_arab' => 'Markabatun Faḍāʾiyyah',
          'bahasa_mandarin' => '月球车',
          'fonetik_mandarin' => 'Yuèqiúchē',
          'kategori' => 'Kendaraan',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Landing Module',
          'bahasa_inggris' => 'Landing Module',
          'fonetik' => 'len-ding mo-dyul',
          'bahasa_arab' => 'وِحْدَةُ هُبُوْطٍ',
          'fonetik_arab' => 'Wiḥdatu Hubūṭ',
          'bahasa_mandarin' => '着陆舱',
          'fonetik_mandarin' => 'Zhuólùcāng',
          'kategori' => 'Kendaraan',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Kereta Cepat',
          'bahasa_inggris' => 'Bullet train',
          'fonetik' => 'bu-let trein',
          'bahasa_arab' => 'قِطَارٌ طَلْقَةٌ',
          'fonetik_arab' => 'Qiṭārun Ṭalqah',
          'bahasa_mandarin' => '动车',
          'fonetik_mandarin' => 'Dòngchē',
          'kategori' => 'Kendaraan',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Kapal Induk',
          'bahasa_inggris' => 'Aircraft carrier',
          'fonetik' => 'er-kraft ke-ri-yer',
          'bahasa_arab' => 'حَامِلَةُ طَائِرَاتٍ',
          'fonetik_arab' => 'Ḥāmilatu Ṭāʾirāt',
          'bahasa_mandarin' => '航空母舰',
          'fonetik_mandarin' => 'Hángkōng mǔjiàn',
          'kategori' => 'Kendaraan',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Pesawat Jet',
          'bahasa_inggris' => 'Jet plane',
          'fonetik' => 'jet plein',
          'bahasa_arab' => 'طَائِرَةٌ نَفَّاثَةٌ',
          'fonetik_arab' => 'Ṭāʾiratun Naffāthah',
          'bahasa_mandarin' => '喷气式飞机',
          'fonetik_mandarin' => 'Pēnqìshì fēijī',
          'kategori' => 'Kendaraan',
          'hari' => 13,
        ),
    );
  }
}