<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Pakaian
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Baju',
          'bahasa_inggris' => 'Shirt',
          'fonetik' => 'syert',
          'bahasa_arab' => 'قَمِيصٌ',
          'fonetik_arab' => 'Qamīṣun',
          'bahasa_mandarin' => '衬衫',
          'fonetik_mandarin' => 'Chènshān',
          'kategori' => 'Pakaian',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Celana',
          'bahasa_inggris' => 'Pants',
          'fonetik' => 'pents',
          'bahasa_arab' => 'بَنْطَلُونٌ',
          'fonetik_arab' => 'Banṭalūnún',
          'bahasa_mandarin' => '裤子',
          'fonetik_mandarin' => 'Kùzi',
          'kategori' => 'Pakaian',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Sepatu',
          'bahasa_inggris' => 'Shoes',
          'fonetik' => 'syuz',
          'bahasa_arab' => 'حِذَاءٌ',
          'fonetik_arab' => 'Ḥidhāʾun',
          'bahasa_mandarin' => '鞋子',
          'fonetik_mandarin' => 'Xiézi',
          'kategori' => 'Pakaian',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Topi',
          'bahasa_inggris' => 'Hat',
          'fonetik' => 'het',
          'bahasa_arab' => 'قُبَّعَةٌ',
          'fonetik_arab' => 'Qubbaʿatun',
          'bahasa_mandarin' => '帽子',
          'fonetik_mandarin' => 'Màozi',
          'kategori' => 'Pakaian',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Kaus Kaki',
          'bahasa_inggris' => 'Socks',
          'fonetik' => 'soks',
          'bahasa_arab' => 'جَوْرَبٌ',
          'fonetik_arab' => 'Jawrabun',
          'bahasa_mandarin' => '袜子',
          'fonetik_mandarin' => 'Wàzi',
          'kategori' => 'Pakaian',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Jaket',
          'bahasa_inggris' => 'Jacket',
          'fonetik' => 'ja-ket',
          'bahasa_arab' => 'سُتْرَةٌ',
          'fonetik_arab' => 'Sutratun',
          'bahasa_mandarin' => '夹克',
          'fonetik_mandarin' => 'Jiákè',
          'kategori' => 'Pakaian',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Gaun',
          'bahasa_inggris' => 'Dress',
          'fonetik' => 'dres',
          'bahasa_arab' => 'فُسْتَانٌ',
          'fonetik_arab' => 'Fustānun',
          'bahasa_mandarin' => '连衣裙',
          'fonetik_mandarin' => 'Liányīqún',
          'kategori' => 'Pakaian',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Rok',
          'bahasa_inggris' => 'Skirt',
          'fonetik' => 'skert',
          'bahasa_arab' => 'تَنُّورَةٌ',
          'fonetik_arab' => 'Tannūratun',
          'bahasa_mandarin' => '裙子',
          'fonetik_mandarin' => 'Qúnzi',
          'kategori' => 'Pakaian',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Celana Pendek',
          'bahasa_inggris' => 'Shorts',
          'fonetik' => 'syorts',
          'bahasa_arab' => 'سِرْوَالٌ قَصِيْرٌ',
          'fonetik_arab' => 'Sirwālun Qaṣīrun',
          'bahasa_mandarin' => '短裤',
          'fonetik_mandarin' => 'Duǎnkù',
          'kategori' => 'Pakaian',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Sandal',
          'bahasa_inggris' => 'Sandals',
          'fonetik' => 'sen-dels',
          'bahasa_arab' => 'صَنْدَلٌ',
          'fonetik_arab' => 'Sandalun',
          'bahasa_mandarin' => '凉鞋',
          'fonetik_mandarin' => 'Liángxié',
          'kategori' => 'Pakaian',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Piyama',
          'bahasa_inggris' => 'Pajamas',
          'fonetik' => 'pe-ja-mas',
          'bahasa_arab' => 'مَنَامَةٌ',
          'fonetik_arab' => 'Manāmatun',
          'bahasa_mandarin' => '睡衣',
          'fonetik_mandarin' => 'Shuìyī',
          'kategori' => 'Pakaian',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Sweater',
          'bahasa_inggris' => 'Sweater',
          'fonetik' => 'swe-ter',
          'bahasa_arab' => 'سُتْرَةٌ صُوفِيَّةٌ',
          'fonetik_arab' => 'Sutratun Ṣūfīyah',
          'bahasa_mandarin' => '毛衣',
          'fonetik_mandarin' => 'Máoyī',
          'kategori' => 'Pakaian',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Mantel',
          'bahasa_inggris' => 'Coat',
          'fonetik' => 'kout',
          'bahasa_arab' => 'مِعْطَفٌ',
          'fonetik_arab' => 'Miʿṭafun',
          'bahasa_mandarin' => '外套',
          'fonetik_mandarin' => 'Wàitào',
          'kategori' => 'Pakaian',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Sarung Tangan',
          'bahasa_inggris' => 'Gloves',
          'fonetik' => 'glavz',
          'bahasa_arab' => 'قُفَّازٌ',
          'fonetik_arab' => 'Quffāzun',
          'bahasa_mandarin' => '手套',
          'fonetik_mandarin' => 'Shǒutào',
          'kategori' => 'Pakaian',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Syal',
          'bahasa_inggris' => 'Scarf',
          'fonetik' => 'skarf',
          'bahasa_arab' => 'وِشَاحٌ',
          'fonetik_arab' => 'Wishāḥun',
          'bahasa_mandarin' => '围巾',
          'fonetik_mandarin' => 'Wéijīn',
          'kategori' => 'Pakaian',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Ikat Pinggang',
          'bahasa_inggris' => 'Belt',
          'fonetik' => 'belt',
          'bahasa_arab' => 'حِزَامٌ',
          'fonetik_arab' => 'Ḥizāmun',
          'bahasa_mandarin' => '皮带',
          'fonetik_mandarin' => 'Pídài',
          'kategori' => 'Pakaian',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Sepatu Bot',
          'bahasa_inggris' => 'Boots',
          'fonetik' => 'buts',
          'bahasa_arab' => 'حِذَاءٌ طَوِيْلٌ',
          'fonetik_arab' => 'Ḥidhāʾun Ṭawīlun',
          'bahasa_mandarin' => '靴子',
          'fonetik_mandarin' => 'Xuēzi',
          'kategori' => 'Pakaian',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Kemeja',
          'bahasa_inggris' => 'T-shirt',
          'fonetik' => 'ti-syert',
          'bahasa_arab' => 'قَمِيصٌ',
          'fonetik_arab' => 'Qamīṣun',
          'bahasa_mandarin' => 'T恤',
          'fonetik_mandarin' => 'T-xù',
          'kategori' => 'Pakaian',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Rompi',
          'bahasa_inggris' => 'Vest',
          'fonetik' => 'vest',
          'bahasa_arab' => 'صَدْرِيَّةٌ',
          'fonetik_arab' => 'Ṣadriyyatun',
          'bahasa_mandarin' => '背心',
          'fonetik_mandarin' => 'Bèixīn',
          'kategori' => 'Pakaian',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Dasi',
          'bahasa_inggris' => 'Tie',
          'fonetik' => 'tai',
          'bahasa_arab' => 'رَبْطَةُ عُنُقٍ',
          'fonetik_arab' => 'Rabṭatu ʿUnuqin',
          'bahasa_mandarin' => '领带',
          'fonetik_mandarin' => 'Lǐngdài',
          'kategori' => 'Pakaian',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Jas Hujan',
          'bahasa_inggris' => 'Raincoat',
          'fonetik' => 'rein-kout',
          'bahasa_arab' => 'مِعْطَفُ الْمَطَرِ',
          'fonetik_arab' => 'Miʿṭaful Maṭari',
          'bahasa_mandarin' => '雨衣',
          'fonetik_mandarin' => 'Yǔyī',
          'kategori' => 'Pakaian',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Pakaian Renang',
          'bahasa_inggris' => 'Swimsuit',
          'fonetik' => 'swim-sut',
          'bahasa_arab' => 'ثَوْبُ السِّبَاحَةِ',
          'fonetik_arab' => 'Thawbus Sibāḥati',
          'bahasa_mandarin' => '泳衣',
          'fonetik_mandarin' => 'Yǒngyī',
          'kategori' => 'Pakaian',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Kacamata',
          'bahasa_inggris' => 'Glasses',
          'fonetik' => 'gla-ses',
          'bahasa_arab' => 'نَظَّارَةٌ',
          'fonetik_arab' => 'Naẓẓāratun',
          'bahasa_mandarin' => '眼镜',
          'fonetik_mandarin' => 'Yǎnjìng',
          'kategori' => 'Pakaian',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Dompet',
          'bahasa_inggris' => 'Wallet',
          'fonetik' => 'wo-let',
          'bahasa_arab' => 'مِحْفَظَةٌ',
          'fonetik_arab' => 'Miḥfaẓatun',
          'bahasa_mandarin' => '钱包',
          'fonetik_mandarin' => 'Qiánbāo',
          'kategori' => 'Pakaian',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Kaus Dalam',
          'bahasa_inggris' => 'Undershirt',
          'fonetik' => 'an-der-syert',
          'bahasa_arab' => 'فَانِلَّةٌ دَاخِلِيَّةٌ',
          'fonetik_arab' => 'Fānillatun Dākhiliyyah',
          'bahasa_mandarin' => '内衣',
          'fonetik_mandarin' => 'Nèiyī',
          'kategori' => 'Pakaian',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Celana Dalam',
          'bahasa_inggris' => 'Underwear',
          'fonetik' => 'an-der-wer',
          'bahasa_arab' => 'ثِيَابٌ دَاخِلِيَّةٌ',
          'fonetik_arab' => 'Thiyābun Dākhiliyyah',
          'bahasa_mandarin' => '内裤',
          'fonetik_mandarin' => 'Nèikù',
          'kategori' => 'Pakaian',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Kutang',
          'bahasa_inggris' => 'Bra',
          'fonetik' => 'bra',
          'bahasa_arab' => 'حِمَالَةُ الصَّدْرِ',
          'fonetik_arab' => 'Ḥimālatus Ṣadri',
          'bahasa_mandarin' => '胸罩',
          'fonetik_mandarin' => 'Xiōngzhào',
          'kategori' => 'Pakaian',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Kimono',
          'bahasa_inggris' => 'Kimono',
          'fonetik' => 'ki-mo-no',
          'bahasa_arab' => 'كِيمُونُو',
          'fonetik_arab' => 'Kīmūnū',
          'bahasa_mandarin' => '和服',
          'fonetik_mandarin' => 'Héfú',
          'kategori' => 'Pakaian',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Jubah Mandi',
          'bahasa_inggris' => 'Bathrobe',
          'fonetik' => 'bath-roub',
          'bahasa_arab' => 'بُرْنُسُ الْحَمَّامِ',
          'fonetik_arab' => 'Burnusul Ḥammāmi',
          'bahasa_mandarin' => '浴袍',
          'fonetik_mandarin' => 'Yùpáo',
          'kategori' => 'Pakaian',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Pakaian Tidur',
          'bahasa_inggris' => 'Nightwear',
          'fonetik' => 'nait-wer',
          'bahasa_arab' => 'مَلَابِسُ النَّوْمِ',
          'fonetik_arab' => 'Malābisun Nawmi',
          'bahasa_mandarin' => '睡衣',
          'fonetik_mandarin' => 'Shuìyī',
          'kategori' => 'Pakaian',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Jas',
          'bahasa_inggris' => 'Suit',
          'fonetik' => 'sut',
          'bahasa_arab' => 'بَدْلَةٌ',
          'fonetik_arab' => 'Badlatun',
          'bahasa_mandarin' => '西装',
          'fonetik_mandarin' => 'Xīzhuāng',
          'kategori' => 'Pakaian',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Blazer',
          'bahasa_inggris' => 'Blazer',
          'fonetik' => 'bley-zer',
          'bahasa_arab' => 'سُتْرَةٌّ',
          'fonetik_arab' => 'Sutratun',
          'bahasa_mandarin' => '休闲西装',
          'fonetik_mandarin' => 'Xiūxián xīzhuāng',
          'kategori' => 'Pakaian',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Tuxedo',
          'bahasa_inggris' => 'Tuxedo',
          'fonetik' => 'tak-si-do',
          'bahasa_arab' => 'بَدْلَةُ رَسْمِيَّةٌ',
          'fonetik_arab' => 'Badlatun Rasmiyyah',
          'bahasa_mandarin' => '燕尾服',
          'fonetik_mandarin' => 'Yànwěifú',
          'kategori' => 'Pakaian',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Kebaya',
          'bahasa_inggris' => 'Kebaya',
          'fonetik' => 'ke-ba-ya',
          'bahasa_arab' => 'كِبَايَا',
          'fonetik_arab' => 'Kibāyā',
          'bahasa_mandarin' => '卡巴雅',
          'fonetik_mandarin' => 'Kǎbāyǎ',
          'kategori' => 'Pakaian',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Batik',
          'bahasa_inggris' => 'Batik',
          'fonetik' => 'ba-tik',
          'bahasa_arab' => 'بَاتِيك',
          'fonetik_arab' => 'Bātīk',
          'bahasa_mandarin' => '蜡染',
          'fonetik_mandarin' => 'Làrǎn',
          'kategori' => 'Pakaian',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Sarung',
          'bahasa_inggris' => 'Sarong',
          'fonetik' => 'sa-rong',
          'bahasa_arab' => 'إِزَارٌ',
          'fonetik_arab' => 'Izārun',
          'bahasa_mandarin' => '围裙',
          'fonetik_mandarin' => 'Wéiqún',
          'kategori' => 'Pakaian',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Jilbab',
          'bahasa_inggris' => 'Hijab',
          'fonetik' => 'hi-jab',
          'bahasa_arab' => 'حِجَابٌ',
          'fonetik_arab' => 'Ḥijābun',
          'bahasa_mandarin' => '头巾',
          'fonetik_mandarin' => 'Tóujīn',
          'kategori' => 'Pakaian',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Cadar',
          'bahasa_inggris' => 'Veil',
          'fonetik' => 'veyl',
          'bahasa_arab' => 'نِقَابٌ',
          'fonetik_arab' => 'Niqābun',
          'bahasa_mandarin' => '面纱',
          'fonetik_mandarin' => 'Miànshā',
          'kategori' => 'Pakaian',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Peci',
          'bahasa_inggris' => 'Cap',
          'fonetik' => 'kep',
          'bahasa_arab' => 'قَلَنْسُوَةٌ',
          'fonetik_arab' => 'Qalansuwatun',
          'bahasa_mandarin' => '便帽',
          'fonetik_mandarin' => 'Biànmào',
          'kategori' => 'Pakaian',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Helm',
          'bahasa_inggris' => 'Helmet',
          'fonetik' => 'hel-met',
          'bahasa_arab' => 'خُوْذَةٌ',
          'fonetik_arab' => 'Khūdhatun',
          'bahasa_mandarin' => '头盔',
          'fonetik_mandarin' => 'Tóukuī',
          'kategori' => 'Pakaian',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Bando',
          'bahasa_inggris' => 'Headband',
          'fonetik' => 'hed-bend',
          'bahasa_arab' => 'عِصَابَةُ الرَّأْسِ',
          'fonetik_arab' => 'ʿIṣābatur Raʾsi',
          'bahasa_mandarin' => '发带',
          'fonetik_mandarin' => 'Fàdài',
          'kategori' => 'Pakaian',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Jepit Rambut',
          'bahasa_inggris' => 'Hairpin',
          'fonetik' => 'her-pin',
          'bahasa_arab' => 'دَبُّوْسُ الشَّعْرِ',
          'fonetik_arab' => 'Dabbūsus Syyʿri',
          'bahasa_mandarin' => '发夹',
          'fonetik_mandarin' => 'Fàjiā',
          'kategori' => 'Pakaian',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Kalung',
          'bahasa_inggris' => 'Necklace',
          'fonetik' => 'nek-les',
          'bahasa_arab' => 'قِلَادَةٌ',
          'fonetik_arab' => 'Qilādatun',
          'bahasa_mandarin' => '项链',
          'fonetik_mandarin' => 'Xiàngliàn',
          'kategori' => 'Pakaian',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Gelang',
          'bahasa_inggris' => 'Bracelet',
          'fonetik' => 'breis-let',
          'bahasa_arab' => 'سِوَارٌ',
          'fonetik_arab' => 'Siwārun',
          'bahasa_mandarin' => '手链',
          'fonetik_mandarin' => 'Shǒuliàn',
          'kategori' => 'Pakaian',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Cincin',
          'bahasa_inggris' => 'Ring',
          'fonetik' => 'ring',
          'bahasa_arab' => 'خَاتَمٌ',
          'fonetik_arab' => 'Khātamun',
          'bahasa_mandarin' => '戒指',
          'fonetik_mandarin' => 'Jièzhi',
          'kategori' => 'Pakaian',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Anting',
          'bahasa_inggris' => 'Earrings',
          'fonetik' => 'ir-ringz',
          'bahasa_arab' => 'قُرْطٌ',
          'fonetik_arab' => 'Qurṭun',
          'bahasa_mandarin' => '耳环',
          'fonetik_mandarin' => 'Ěrhuán',
          'kategori' => 'Pakaian',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Jam Tangan',
          'bahasa_inggris' => 'Watch',
          'fonetik' => 'wa-c',
          'bahasa_arab' => 'سَاعَةُ يَدٍ',
          'fonetik_arab' => 'Sāʿatu Yadin',
          'bahasa_mandarin' => '手表',
          'fonetik_mandarin' => 'Shǒubiǎo',
          'kategori' => 'Pakaian',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Bros',
          'bahasa_inggris' => 'Brooch',
          'fonetik' => 'brouc',
          'bahasa_arab' => 'دَبُّوْسُ زِيْنَةٍ',
          'fonetik_arab' => 'Dabbūsu Zīnatin',
          'bahasa_mandarin' => '胸针',
          'fonetik_mandarin' => 'Xiōngzhēn',
          'kategori' => 'Pakaian',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Tas',
          'bahasa_inggris' => 'Bag',
          'fonetik' => 'beg',
          'bahasa_arab' => 'حَقِيْبَةٌ',
          'fonetik_arab' => 'Ḥaqībatun',
          'bahasa_mandarin' => '包',
          'fonetik_mandarin' => 'Bāo',
          'kategori' => 'Pakaian',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Ransel',
          'bahasa_inggris' => 'Backpack',
          'fonetik' => 'bek-pek',
          'bahasa_arab' => 'حَقِيْبَةُ الظَّهْرِ',
          'fonetik_arab' => 'Ḥaqībatuẓ Ẓohri',
          'bahasa_mandarin' => '背包',
          'fonetik_mandarin' => 'Bèibāo',
          'kategori' => 'Pakaian',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Payung',
          'bahasa_inggris' => 'Umbrella',
          'fonetik' => 'am-bre-la',
          'bahasa_arab' => 'مِظَلَّةٌ',
          'fonetik_arab' => 'Miẓallatun',
          'bahasa_mandarin' => '雨伞',
          'fonetik_mandarin' => 'Yǔsǎn',
          'kategori' => 'Pakaian',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Sapu Tangan',
          'bahasa_inggris' => 'Handkerchief',
          'fonetik' => 'hen-der-cif',
          'bahasa_arab' => 'مِنْدِيْلٌ',
          'fonetik_arab' => 'Mindīlun',
          'bahasa_mandarin' => '手帕',
          'fonetik_mandarin' => 'Shǒupà',
          'kategori' => 'Pakaian',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Masker',
          'bahasa_inggris' => 'Mask',
          'fonetik' => 'mesk',
          'bahasa_arab' => 'كَمَّامَةٌ',
          'fonetik_arab' => 'Kammāmatun',
          'bahasa_mandarin' => '口罩',
          'fonetik_mandarin' => 'Kǒuzhào',
          'kategori' => 'Pakaian',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Kacamata Hitam',
          'bahasa_inggris' => 'Sunglasses',
          'fonetik' => 'san-gla-ses',
          'bahasa_arab' => 'نَظَّارَةٌ شَمْسِيَّةٌ',
          'fonetik_arab' => 'Naẓẓāratun Syamsiyyah',
          'bahasa_mandarin' => '太阳镜',
          'fonetik_mandarin' => 'Tàiyángjìng',
          'kategori' => 'Pakaian',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Seragam',
          'bahasa_inggris' => 'Uniform',
          'fonetik' => 'yu-ni-form',
          'bahasa_arab' => 'زِيٌّ رَسْمِيٌّ',
          'fonetik_arab' => 'Ziyyun Rasmiyyun',
          'bahasa_mandarin' => '制服',
          'fonetik_mandarin' => 'Zhìfú',
          'kategori' => 'Pakaian',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Apron',
          'bahasa_inggris' => 'Apron',
          'fonetik' => 'ey-pron',
          'bahasa_arab' => 'مِئْزَرٌ',
          'fonetik_arab' => 'Miʾzarun',
          'bahasa_mandarin' => '围裙',
          'fonetik_mandarin' => 'Wéiqún',
          'kategori' => 'Pakaian',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Pakaian Olahraga',
          'bahasa_inggris' => 'Sportswear',
          'fonetik' => 'sports-wer',
          'bahasa_arab' => 'مَلَابِسُ الرِّيَاضَةِ',
          'fonetik_arab' => 'Malābisur Riyāḍati',
          'bahasa_mandarin' => '运动服',
          'fonetik_mandarin' => 'Yùndòngfú',
          'kategori' => 'Pakaian',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Sepatu Olahraga',
          'bahasa_inggris' => 'Sneakers',
          'fonetik' => 'sni-kerz',
          'bahasa_arab' => 'حِذَاءٌ رِيَاضِيٌّ',
          'fonetik_arab' => 'Ḥidhāʾun Riyāḍiyyun',
          'bahasa_mandarin' => '运动鞋',
          'fonetik_mandarin' => 'Yùndòngxié',
          'kategori' => 'Pakaian',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Sepatu Hak Tinggi',
          'bahasa_inggris' => 'High heels',
          'fonetik' => 'hai hilz',
          'bahasa_arab' => 'حِذَاءٌ ذُو كَعْبٍ عَالٍ',
          'fonetik_arab' => 'Ḥidhāʾun dhū Kaʿbin ʿālin',
          'bahasa_mandarin' => '高跟鞋',
          'fonetik_mandarin' => 'Gāogēnxié',
          'kategori' => 'Pakaian',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Sepatu Teplek',
          'bahasa_inggris' => 'Flats',
          'fonetik' => 'flets',
          'bahasa_arab' => 'حِذَاءٌ مُسَطَّحٌ',
          'fonetik_arab' => 'Ḥidhāʾun Musaṭṭaḥun',
          'bahasa_mandarin' => '平底鞋',
          'fonetik_mandarin' => 'Píngdǐxié',
          'kategori' => 'Pakaian',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Kain',
          'bahasa_inggris' => 'Cloth',
          'fonetik' => 'kloth',
          'bahasa_arab' => 'قُمَاشٌ',
          'fonetik_arab' => 'Qumāshun',
          'bahasa_mandarin' => '布',
          'fonetik_mandarin' => 'Bù',
          'kategori' => 'Pakaian',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Sutra',
          'bahasa_inggris' => 'Silk',
          'fonetik' => 'silk',
          'bahasa_arab' => 'حَرِيْرٌ',
          'fonetik_arab' => 'Ḥarīrun',
          'bahasa_mandarin' => '丝绸',
          'fonetik_mandarin' => 'Sīchóu',
          'kategori' => 'Pakaian',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Wol',
          'bahasa_inggris' => 'Wool',
          'fonetik' => 'wul',
          'bahasa_arab' => 'صُوْفٌ',
          'fonetik_arab' => 'Ṣūfun',
          'bahasa_mandarin' => '羊毛',
          'fonetik_mandarin' => 'Yángmáo',
          'kategori' => 'Pakaian',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Kulit',
          'bahasa_inggris' => 'Leather',
          'fonetik' => 'le-dher',
          'bahasa_arab' => 'جِلْدٌ',
          'fonetik_arab' => 'Jildun',
          'bahasa_mandarin' => '皮革',
          'fonetik_mandarin' => 'Pígé',
          'kategori' => 'Pakaian',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Katun',
          'bahasa_inggris' => 'Cotton',
          'fonetik' => 'ko-ton',
          'bahasa_arab' => 'قُطْنٌ',
          'fonetik_arab' => 'Quṭnun',
          'bahasa_mandarin' => '棉',
          'fonetik_mandarin' => 'Mián',
          'kategori' => 'Pakaian',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Renda',
          'bahasa_inggris' => 'Lace',
          'fonetik' => 'leys',
          'bahasa_arab' => 'دَانْتِيْل',
          'fonetik_arab' => 'Dāntīl',
          'bahasa_mandarin' => '蕾丝',
          'fonetik_mandarin' => 'Lěisī',
          'kategori' => 'Pakaian',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Mukena',
          'bahasa_inggris' => 'Prayer robe',
          'fonetik' => 'preyer roub',
          'bahasa_arab' => 'ثَوْبُ الصَّلَاةِ',
          'fonetik_arab' => 'Thawbus Ṣalāti',
          'bahasa_mandarin' => '祈祷袍',
          'fonetik_mandarin' => 'Qǐdǎopáo',
          'kategori' => 'Pakaian',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Sorban',
          'bahasa_inggris' => 'Turban',
          'fonetik' => 'tur-ban',
          'bahasa_arab' => 'عِمَامَةٌ',
          'fonetik_arab' => 'ʿImāmatun',
          'bahasa_mandarin' => '头巾',
          'fonetik_mandarin' => 'Tóujīn',
          'kategori' => 'Pakaian',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Tanjak',
          'bahasa_inggris' => 'Traditional headgear',
          'fonetik' => 'tra-di-syonal hed-gir',
          'bahasa_arab' => 'غِطَاءُ الرَّأْسِ التَّقْلِيْدِيُّ',
          'fonetik_arab' => 'Ghiṭāʾur Raʾsit Taqlīdiyyu',
          'bahasa_mandarin' => '传统头饰',
          'fonetik_mandarin' => 'Chuántǒng tóushì',
          'kategori' => 'Pakaian',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Keris',
          'bahasa_inggris' => 'Kris (Dagger)',
          'fonetik' => 'kris',
          'bahasa_arab' => 'خَنْجَر تَقْلِيْدِيّ',
          'fonetik_arab' => 'Khanjar Taqlīdiyy',
          'bahasa_mandarin' => '克里斯短剑',
          'fonetik_mandarin' => 'Kèlǐsī duǎnjiàn',
          'kategori' => 'Pakaian',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Kain Ihram',
          'bahasa_inggris' => 'Ihram clothing',
          'fonetik' => 'ih-ram kloth-ing',
          'bahasa_arab' => 'مَلَابِسُ الْإِحْرَامِ',
          'fonetik_arab' => 'Malābisul Iḥrāmi',
          'bahasa_mandarin' => '戒衣',
          'fonetik_mandarin' => 'Jièyī',
          'kategori' => 'Pakaian',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Baju Kurung',
          'bahasa_inggris' => 'Baju Kurung',
          'fonetik' => 'ba-ju ku-rung',
          'bahasa_arab' => 'ثَوْب كُورُونغ',
          'fonetik_arab' => 'Thawb Kūrūng',
          'bahasa_mandarin' => '可巴雅',
          'fonetik_mandarin' => 'Kěbāyǎ',
          'kategori' => 'Pakaian',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Penutup Telinga',
          'bahasa_inggris' => 'Earmuffs',
          'fonetik' => 'ir-mafs',
          'bahasa_arab' => 'أَغْطِيَةُ الْأُذُنِ',
          'fonetik_arab' => 'Aghṭiyatul Udhu-ni',
          'bahasa_mandarin' => '耳罩',
          'fonetik_mandarin' => 'Ěrzhào',
          'kategori' => 'Pakaian',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Hodie',
          'bahasa_inggris' => 'Hoodie',
          'fonetik' => 'hu-di',
          'bahasa_arab' => 'سُتْرَةٌ بِقَلَنْسُوَةٍ',
          'fonetik_arab' => 'Sutratun bi-Qolansu-wah',
          'bahasa_mandarin' => '连帽衫',
          'fonetik_mandarin' => 'Liánmàoshān',
          'kategori' => 'Pakaian',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Legging',
          'bahasa_inggris' => 'Leggings',
          'fonetik' => 'le-gingz',
          'bahasa_arab' => 'لِبَاسٌ ضَيِّقٌ',
          'fonetik_arab' => 'Libāsun Ḍoyyiqun',
          'bahasa_mandarin' => '紧身裤',
          'fonetik_mandarin' => 'Jǐnshēnkù',
          'kategori' => 'Pakaian',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Cardigan',
          'bahasa_inggris' => 'Cardigan',
          'fonetik' => 'kar-di-gan',
          'bahasa_arab' => 'كارديغان',
          'fonetik_arab' => 'Kārdīghān',
          'bahasa_mandarin' => '轴襟毛衣',
          'fonetik_mandarin' => 'Zhóujīn máoyī',
          'kategori' => 'Pakaian',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Stocking',
          'bahasa_inggris' => 'Stockings',
          'fonetik' => 'sto-kingz',
          'bahasa_arab' => 'جَوَارِبُ طَوِيْلَةٌ',
          'fonetik_arab' => 'Jawāribu Ṭowīlah',
          'bahasa_mandarin' => '长筒袜',
          'fonetik_mandarin' => 'Chángtǒngwà',
          'kategori' => 'Pakaian',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Manset',
          'bahasa_inggris' => 'Cuff',
          'fonetik' => 'kaf',
          'bahasa_arab' => 'أَكْمَامٌ',
          'fonetik_arab' => 'Akmāmun',
          'bahasa_mandarin' => '袖口',
          'fonetik_mandarin' => 'Xiùkǒu',
          'kategori' => 'Pakaian',
          'hari' => 13,
        ),
    );
  }
}