<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Sayuran
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Wortel',
          'bahasa_inggris' => 'Carrot',
          'fonetik' => 'ke-ret',
          'bahasa_arab' => 'جَزَرٌ',
          'fonetik_arab' => 'Jazarún',
          'bahasa_mandarin' => '胡萝卜',
          'fonetik_mandarin' => 'Húluóbo',
          'kategori' => 'Sayuran',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Tomat',
          'bahasa_inggris' => 'Tomato',
          'fonetik' => 'to-mey-to',
          'bahasa_arab' => 'طَمَاطِمٌ',
          'fonetik_arab' => 'Ṭamāṭimun',
          'bahasa_mandarin' => '西红柿',
          'fonetik_mandarin' => 'Xīhóngshì',
          'kategori' => 'Sayuran',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Kentang',
          'bahasa_inggris' => 'Potato',
          'fonetik' => 'po-tey-to',
          'bahasa_arab' => 'بَطَاطِسٌ',
          'fonetik_arab' => 'Baṭāṭisun',
          'bahasa_mandarin' => '土豆',
          'fonetik_mandarin' => 'Tǔdòu',
          'kategori' => 'Sayuran',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Brokoli',
          'bahasa_inggris' => 'Broccoli',
          'fonetik' => 'bro-ko-li',
          'bahasa_arab' => 'بُرُوكُلِي',
          'fonetik_arab' => 'Burūkulī',
          'bahasa_mandarin' => '西兰花',
          'fonetik_mandarin' => 'Xīlánhuā',
          'kategori' => 'Sayuran',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Bayam',
          'bahasa_inggris' => 'Spinach',
          'fonetik' => 'spi-nac',
          'bahasa_arab' => 'سَبَانِخٌ',
          'fonetik_arab' => 'Sabānikhun',
          'bahasa_mandarin' => '菠菜',
          'fonetik_mandarin' => 'Bōcài',
          'kategori' => 'Sayuran',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Jagung',
          'bahasa_inggris' => 'Corn',
          'fonetik' => 'korn',
          'bahasa_arab' => 'ذُرَةٌ',
          'fonetik_arab' => 'Dhuratun',
          'bahasa_mandarin' => '玉米',
          'fonetik_mandarin' => 'Yùmǐ',
          'kategori' => 'Sayuran',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Bawang Merah',
          'bahasa_inggris' => 'Shallot',
          'fonetik' => 'syal-lot',
          'bahasa_arab' => 'بَصَلٌ أَحْمَرُ',
          'fonetik_arab' => 'Baṣalun Aḥmaru',
          'bahasa_mandarin' => '红葱头',
          'fonetik_mandarin' => 'Hóng cōngtóu',
          'kategori' => 'Sayuran',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Bawang Putih',
          'bahasa_inggris' => 'Garlic',
          'fonetik' => 'gar-lik',
          'bahasa_arab' => 'ثُومٌ',
          'fonetik_arab' => 'Thūmun',
          'bahasa_mandarin' => '大蒜',
          'fonetik_mandarin' => 'Dàsuàn',
          'kategori' => 'Sayuran',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Selada',
          'bahasa_inggris' => 'Lettuce',
          'fonetik' => 'le-tes',
          'bahasa_arab' => 'خَسٌّ',
          'fonetik_arab' => 'Khassun',
          'bahasa_mandarin' => '生菜',
          'fonetik_mandarin' => 'Shēngcài',
          'kategori' => 'Sayuran',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Timun',
          'bahasa_inggris' => 'Cucumber',
          'fonetik' => 'kyu-kam-ber',
          'bahasa_arab' => 'خِيَارٌ',
          'fonetik_arab' => 'Khīyārun',
          'bahasa_mandarin' => '黄瓜',
          'fonetik_mandarin' => 'Huángguā',
          'kategori' => 'Sayuran',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Paprika',
          'bahasa_inggris' => 'Bell pepper',
          'fonetik' => 'bel pe-per',
          'bahasa_arab' => 'فُلْفُلٌ حُلْوٌ',
          'fonetik_arab' => 'Fulful Ḥulw',
          'bahasa_mandarin' => '灯笼椒',
          'fonetik_mandarin' => 'Dēnglóngjiāo',
          'kategori' => 'Sayuran',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Jamur',
          'bahasa_inggris' => 'Mushroom',
          'fonetik' => 'masy-rum',
          'bahasa_arab' => 'فُطْرٌ',
          'fonetik_arab' => 'Fuṭrun',
          'bahasa_mandarin' => '蘑菇',
          'fonetik_mandarin' => 'Mógu',
          'kategori' => 'Sayuran',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Terong',
          'bahasa_inggris' => 'Eggplant',
          'fonetik' => 'eg-plent',
          'bahasa_arab' => 'بَاذِنْجَانٌ',
          'fonetik_arab' => 'Bādhinjānun',
          'bahasa_mandarin' => '茄子',
          'fonetik_mandarin' => 'Qiézi',
          'kategori' => 'Sayuran',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Labu',
          'bahasa_inggris' => 'Pumpkin',
          'fonetik' => 'pam-kin',
          'bahasa_arab' => 'قَرْعٌ',
          'fonetik_arab' => 'Qarʿun',
          'bahasa_mandarin' => '南瓜',
          'fonetik_mandarin' => 'Nánguā',
          'kategori' => 'Sayuran',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Cabai',
          'bahasa_inggris' => 'Chili',
          'fonetik' => 'ci-li',
          'bahasa_arab' => 'فُلْفُلٌ حَارٌ',
          'fonetik_arab' => 'Fulful Ḥārr',
          'bahasa_mandarin' => '辣椒',
          'fonetik_mandarin' => 'Làjiāo',
          'kategori' => 'Sayuran',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Kacang Polong',
          'bahasa_inggris' => 'Peas',
          'fonetik' => 'piz',
          'bahasa_arab' => 'بَازِلَّاءُ',
          'fonetik_arab' => 'Bāzillāʾu',
          'bahasa_mandarin' => '豌豆',
          'fonetik_mandarin' => 'Wāndòu',
          'kategori' => 'Sayuran',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Kembang Kol',
          'bahasa_inggris' => 'Cauliflower',
          'fonetik' => 'ko-li-flau-wer',
          'bahasa_arab' => 'قَرْنَبِيطٌ',
          'fonetik_arab' => 'Qarnabīṭun',
          'bahasa_mandarin' => '花椰菜',
          'fonetik_mandarin' => 'Huāyēcài',
          'kategori' => 'Sayuran',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Seledri',
          'bahasa_inggris' => 'Celery',
          'fonetik' => 'se-le-ri',
          'bahasa_arab' => 'كَرَفْسٌ',
          'fonetik_arab' => 'Karafsun',
          'bahasa_mandarin' => '芹菜',
          'fonetik_mandarin' => 'Qíncài',
          'kategori' => 'Sayuran',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Kangkung',
          'bahasa_inggris' => 'Water Spinach',
          'fonetik' => 'wo-ter spi-nac',
          'bahasa_arab' => 'سَبَانِخُ الْمَاءِ',
          'fonetik_arab' => 'Sabānikhul Māʾi',
          'bahasa_mandarin' => '空心菜',
          'fonetik_mandarin' => 'Kōngxīncài',
          'kategori' => 'Sayuran',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Sawi',
          'bahasa_inggris' => 'Mustard Greens',
          'fonetik' => 'mas-terd grinz',
          'bahasa_arab' => 'خَرْدَلٌ',
          'fonetik_arab' => 'Khardalun',
          'bahasa_mandarin' => '芥菜',
          'fonetik_mandarin' => 'Jiècài',
          'kategori' => 'Sayuran',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Kubis',
          'bahasa_inggris' => 'Cabbage',
          'fonetik' => 'ka-beij',
          'bahasa_arab' => 'كُرُنْبٌ',
          'fonetik_arab' => 'Kurunbun',
          'bahasa_mandarin' => '卷心菜',
          'fonetik_mandarin' => 'Juǎnxīncài',
          'kategori' => 'Sayuran',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Daun Bawang',
          'bahasa_inggris' => 'Scallion',
          'fonetik' => 'ska-li-yen',
          'bahasa_arab' => 'بَصَلٌ أَخْضَرُ',
          'fonetik_arab' => 'Baṣalun Akhḍaru',
          'bahasa_mandarin' => '葱',
          'fonetik_mandarin' => 'Cōng',
          'kategori' => 'Sayuran',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Daun Ketumbar',
          'bahasa_inggris' => 'Coriander',
          'fonetik' => 'ko-ri-yen-der',
          'bahasa_arab' => 'كُزْبَرَةٌ',
          'fonetik_arab' => 'Kuzbaratun',
          'bahasa_mandarin' => '香菜',
          'fonetik_mandarin' => 'Xiāngcài',
          'kategori' => 'Sayuran',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Asparagus',
          'bahasa_inggris' => 'Asparagus',
          'fonetik' => 'as-pa-ra-ges',
          'bahasa_arab' => 'هِلْيَوْنٌ',
          'fonetik_arab' => 'Hilyawnun',
          'bahasa_mandarin' => '芦笋',
          'fonetik_mandarin' => 'Lúsǔn',
          'kategori' => 'Sayuran',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Lobak',
          'bahasa_inggris' => 'Radish',
          'fonetik' => 'ra-disy',
          'bahasa_arab' => 'فُجْلٌ',
          'fonetik_arab' => 'Fujlun',
          'bahasa_mandarin' => '萝卜',
          'fonetik_mandarin' => 'Luóbo',
          'kategori' => 'Sayuran',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Ubi Jalar',
          'bahasa_inggris' => 'Sweet Potato',
          'fonetik' => 'swit po-tey-to',
          'bahasa_arab' => 'بَطَاطَا حُلْوَةٌ',
          'fonetik_arab' => 'Baṭāṭā Ḥulwah',
          'bahasa_mandarin' => '红薯',
          'fonetik_mandarin' => 'Hóngshǔ',
          'kategori' => 'Sayuran',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Singkong',
          'bahasa_inggris' => 'Cassava',
          'fonetik' => 'ka-sa-va',
          'bahasa_arab' => 'كَسَافَا',
          'fonetik_arab' => 'Kasāfā',
          'bahasa_mandarin' => '木薯',
          'fonetik_mandarin' => 'Mùshǔ',
          'kategori' => 'Sayuran',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Bit',
          'bahasa_inggris' => 'Beetroot',
          'fonetik' => 'bit-rut',
          'bahasa_arab' => 'بَنْجَرٌ',
          'fonetik_arab' => 'Banjarun',
          'bahasa_mandarin' => '甜菜',
          'fonetik_mandarin' => 'Tiáncài',
          'kategori' => 'Sayuran',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Jahe',
          'bahasa_inggris' => 'Ginger',
          'fonetik' => 'jin-jer',
          'bahasa_arab' => 'زَنْجَبِيْلٌ',
          'fonetik_arab' => 'Zanjabīlun',
          'bahasa_mandarin' => '生姜',
          'fonetik_mandarin' => 'Shēngjiāng',
          'kategori' => 'Sayuran',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Kunyit',
          'bahasa_inggris' => 'Turmeric',
          'fonetik' => 'tur-me-rik',
          'bahasa_arab' => 'كُرْكُمٌ',
          'fonetik_arab' => 'Kurkumun',
          'bahasa_mandarin' => '姜黄',
          'fonetik_mandarin' => 'Jiānghuáng',
          'kategori' => 'Sayuran',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Kacang Panjang',
          'bahasa_inggris' => 'Long Bean',
          'fonetik' => 'long bin',
          'bahasa_arab' => 'لُوبِيَا طَوِيْلَةٌ',
          'fonetik_arab' => 'Lūbiyā Ṭawīlah',
          'bahasa_mandarin' => '长豆',
          'fonetik_mandarin' => 'Chángdòu',
          'kategori' => 'Sayuran',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Buncis',
          'bahasa_inggris' => 'Green Beans',
          'fonetik' => 'grin binz',
          'bahasa_arab' => 'فَاصُوْلِيَا خَضْرَاءُ',
          'fonetik_arab' => 'Fāṣūliyā Khaḍrāʾu',
          'bahasa_mandarin' => '四季豆',
          'fonetik_mandarin' => 'Sìjìdòu',
          'kategori' => 'Sayuran',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Kedelai',
          'bahasa_inggris' => 'Soybean',
          'fonetik' => 'soy-bin',
          'bahasa_arab' => 'فُويَا',
          'fonetik_arab' => 'Fūyā',
          'bahasa_mandarin' => '大豆',
          'fonetik_mandarin' => 'Dàdòu',
          'kategori' => 'Sayuran',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Tauge',
          'bahasa_inggris' => 'Bean Sprouts',
          'fonetik' => 'bin spraut',
          'bahasa_arab' => 'نَبْتَةُ الْفَاصُوْلِيَا',
          'fonetik_arab' => 'Nabtatul Fāṣūliyā',
          'bahasa_mandarin' => '豆芽',
          'fonetik_mandarin' => 'Dòuyá',
          'kategori' => 'Sayuran',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Petai',
          'bahasa_inggris' => 'Stink Bean',
          'fonetik' => 'stingk bin',
          'bahasa_arab' => 'بِتَاي',
          'fonetik_arab' => 'Bitāy',
          'bahasa_mandarin' => '臭豆',
          'fonetik_mandarin' => 'Chòudòu',
          'kategori' => 'Sayuran',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Jengkol',
          'bahasa_inggris' => 'Jengkol',
          'fonetik' => 'jeng-kol',
          'bahasa_arab' => 'جِيْنغْكُوْل',
          'fonetik_arab' => 'Jīngkūl',
          'bahasa_mandarin' => '任豆',
          'fonetik_mandarin' => 'Rèndòu',
          'kategori' => 'Sayuran',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Pare',
          'bahasa_inggris' => 'Bitter Gourd',
          'fonetik' => 'bi-ter gord',
          'bahasa_arab' => 'الْقَرْعُ الْمُرُّ',
          'fonetik_arab' => 'Al-Qarʿul Murru',
          'bahasa_mandarin' => '苦瓜',
          'fonetik_mandarin' => 'Kǔguā',
          'kategori' => 'Sayuran',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Labu Siam',
          'bahasa_inggris' => 'Chayote',
          'fonetik' => 'ca-yo-te',
          'bahasa_arab' => 'الْقَرْعُ السِّيَامِيُّ',
          'fonetik_arab' => 'Al-Qarʿus Siyāmiyyu',
          'bahasa_mandarin' => '佛手瓜',
          'fonetik_mandarin' => 'Fóshǒuguā',
          'kategori' => 'Sayuran',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Oyong',
          'bahasa_inggris' => 'Luffa',
          'fonetik' => 'lu-fa',
          'bahasa_arab' => 'اللُّوفُ',
          'fonetik_arab' => 'Al-Lūfu',
          'bahasa_mandarin' => '丝瓜',
          'fonetik_mandarin' => 'Sīguā',
          'kategori' => 'Sayuran',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Beligo',
          'bahasa_inggris' => 'Winter Melon',
          'fonetik' => 'win-ter me-lon',
          'bahasa_arab' => 'الْبِطِّيْخُ الشِّتَوِيُّ',
          'fonetik_arab' => 'Al-Biṭṭīkhush Shītawiyyu',
          'bahasa_mandarin' => '冬瓜',
          'fonetik_mandarin' => 'Dōngguā',
          'kategori' => 'Sayuran',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Zucchini',
          'bahasa_inggris' => 'Zucchini',
          'fonetik' => 'zu-ki-ni',
          'bahasa_arab' => 'كُوسَى',
          'fonetik_arab' => 'Kūsā',
          'bahasa_mandarin' => '西葫芦',
          'fonetik_mandarin' => 'Xīhúlú',
          'kategori' => 'Sayuran',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Mentimun Jepang',
          'bahasa_inggris' => 'Kyuri',
          'fonetik' => 'kyu-ri',
          'bahasa_arab' => 'خِيَارٌ يَابَانِيٌّ',
          'fonetik_arab' => 'Khīyārun Yābāniyyun',
          'bahasa_mandarin' => '日本黄瓜',
          'fonetik_mandarin' => 'Rìběn huángguā',
          'kategori' => 'Sayuran',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Lengkuas',
          'bahasa_inggris' => 'Galangal',
          'fonetik' => 'ga-lang-gal',
          'bahasa_arab' => 'خُولَنْجَان',
          'fonetik_arab' => 'Khūlanjān',
          'bahasa_mandarin' => '高良姜',
          'fonetik_mandarin' => 'Gāoliángjiāng',
          'kategori' => 'Sayuran',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Serai',
          'bahasa_inggris' => 'Lemongrass',
          'fonetik' => 'le-mon-gres',
          'bahasa_arab' => 'عُشْبُ اللَّيْمُوْنِ',
          'fonetik_arab' => 'ʿUshbul Laymūni',
          'bahasa_mandarin' => '香茅',
          'fonetik_mandarin' => 'Xiāngmáo',
          'kategori' => 'Sayuran',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Kemangi',
          'bahasa_inggris' => 'Basil',
          'fonetik' => 'be-zil',
          'bahasa_arab' => 'رَيْحَانٌ',
          'fonetik_arab' => 'Rayḥānun',
          'bahasa_mandarin' => '罗勒',
          'fonetik_mandarin' => 'Luólè',
          'kategori' => 'Sayuran',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Peterseli',
          'bahasa_inggris' => 'Parsley',
          'fonetik' => 'par-sli',
          'bahasa_arab' => 'بَقْدُوْنِسٌ',
          'fonetik_arab' => 'Baqdūnisun',
          'bahasa_mandarin' => '欧芹',
          'fonetik_mandarin' => 'Ōuqín',
          'kategori' => 'Sayuran',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Rosemary',
          'bahasa_inggris' => 'Rosemary',
          'fonetik' => 'rouz-me-ri',
          'bahasa_arab' => 'إِكْلِيْلُ الْجَبَلِ',
          'fonetik_arab' => 'Iklīlul Jabali',
          'bahasa_mandarin' => '迷迭香',
          'fonetik_mandarin' => 'Mídiéxiāng',
          'kategori' => 'Sayuran',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Thyme',
          'bahasa_inggris' => 'Thyme',
          'fonetik' => 'taim',
          'bahasa_arab' => 'زَعْتَرٌ',
          'fonetik_arab' => 'Zaʿtarun',
          'bahasa_mandarin' => '百里香',
          'fonetik_mandarin' => 'Bǎilǐxiāng',
          'kategori' => 'Sayuran',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Rebung',
          'bahasa_inggris' => 'Bamboo Shoots',
          'fonetik' => 'bam-bu syuts',
          'bahasa_arab' => 'بَرَاعِمُ الْخَيْزُرَانِ',
          'fonetik_arab' => 'Barāʿimul Khayzurāni',
          'bahasa_mandarin' => '竹笋',
          'fonetik_mandarin' => 'Zhúsǔn',
          'kategori' => 'Sayuran',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Pakcoy',
          'bahasa_inggris' => 'Bok Choy',
          'fonetik' => 'bok-coy',
          'bahasa_arab' => 'بَاكْتْشُوي',
          'fonetik_arab' => 'Bāktsyūy',
          'bahasa_mandarin' => '白菜',
          'fonetik_mandarin' => 'Báicài',
          'kategori' => 'Sayuran',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Kailan',
          'bahasa_inggris' => 'Chinese Broccoli',
          'fonetik' => 'cai-nis bro-ko-li',
          'bahasa_arab' => 'بُرُوْكُلِي صِيْنِيٌّ',
          'fonetik_arab' => 'Burūkulī Ṣīniyyun',
          'bahasa_mandarin' => '芥兰',
          'fonetik_mandarin' => 'Jièlán',
          'kategori' => 'Sayuran',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Okra',
          'bahasa_inggris' => 'Okra',
          'fonetik' => 'ok-ra',
          'bahasa_arab' => 'بَامِيَةٌ',
          'fonetik_arab' => 'Bāmiyatun',
          'bahasa_mandarin' => '秋葵',
          'fonetik_mandarin' => 'Qiūkuí',
          'kategori' => 'Sayuran',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Adas',
          'bahasa_inggris' => 'Fennel',
          'fonetik' => 'fe-nel',
          'bahasa_arab' => 'شَمَرٌ',
          'fonetik_arab' => 'Syamarun',
          'bahasa_mandarin' => '茴香',
          'fonetik_mandarin' => 'Huíxiāng',
          'kategori' => 'Sayuran',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Labu Kuning',
          'bahasa_inggris' => 'Butternut Squash',
          'fonetik' => 'ba-ter-nat skwosy',
          'bahasa_arab' => 'قَرْع عَسَلِيّ',
          'fonetik_arab' => 'Qarʿ ʿAsaliyy',
          'bahasa_mandarin' => '胡桃南瓜',
          'fonetik_mandarin' => 'Hútáo nánguā',
          'kategori' => 'Sayuran',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Jantung Pisang',
          'bahasa_inggris' => 'Banana Blossom',
          'fonetik' => 'ba-na-na blo-sam',
          'bahasa_arab' => 'زَهْرَةُ الْمَوْزِ',
          'fonetik_arab' => 'Zahratul Mawzi',
          'bahasa_mandarin' => '香蕉花',
          'fonetik_mandarin' => 'Xiāngjiāohuā',
          'kategori' => 'Sayuran',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Kecombrang',
          'bahasa_inggris' => 'Torch Ginger',
          'fonetik' => 'torc jin-jer',
          'bahasa_arab' => 'زَنْجَبِيْلُ الشُّعْلَةِ',
          'fonetik_arab' => 'Zanjabīlush Syuʿlati',
          'bahasa_mandarin' => '火炬姜',
          'fonetik_mandarin' => 'Huǒjùjiāng',
          'kategori' => 'Sayuran',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Jamur Kuping',
          'bahasa_inggris' => 'Wood Ear Mushroom',
          'fonetik' => 'wud ir masy-rum',
          'bahasa_arab' => 'فُطْرُ أُذُنِ الْخَشَبِ',
          'fonetik_arab' => 'Fuṭru Udunil Khasyabi',
          'bahasa_mandarin' => '木耳',
          'fonetik_mandarin' => 'Mù\'ěr',
          'kategori' => 'Sayuran',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Jamur Tiram',
          'bahasa_inggris' => 'Oyster Mushroom',
          'fonetik' => 'ois-ter masy-rum',
          'bahasa_arab' => 'فُطْرُ الْمَحَارِ',
          'fonetik_arab' => 'Fuṭrul Maḥāri',
          'bahasa_mandarin' => '平菇',
          'fonetik_mandarin' => 'Pínggū',
          'kategori' => 'Sayuran',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Jamur Merang',
          'bahasa_inggris' => 'Straw Mushroom',
          'fonetik' => 'stro masy-rum',
          'bahasa_arab' => 'فُطْرُ الْقَشِّ',
          'fonetik_arab' => 'Fuṭrul Qasysyi',
          'bahasa_mandarin' => '草菇',
          'fonetik_mandarin' => 'Cǎogū',
          'kategori' => 'Sayuran',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Jamur Shiitake',
          'bahasa_inggris' => 'Shiitake Mushroom',
          'fonetik' => 'syi-ta-ke masy-rum',
          'bahasa_arab' => 'فُطْرُ الشِّيْتَاكِي',
          'fonetik_arab' => 'Fuṭrus Syītākī',
          'bahasa_mandarin' => '香菇',
          'fonetik_mandarin' => 'Xiānggū',
          'kategori' => 'Sayuran',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Cabai Hijau',
          'bahasa_inggris' => 'Green Chili',
          'fonetik' => 'grin ci-li',
          'bahasa_arab' => 'فُلْفُلٌ أَخْضَرُ',
          'fonetik_arab' => 'Fulfulun Akhḍaru',
          'bahasa_mandarin' => '青辣椒',
          'fonetik_mandarin' => 'Qīng làjiāo',
          'kategori' => 'Sayuran',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Cabai Rawit',
          'bahasa_inggris' => 'Bird Eye Chili',
          'fonetik' => 'berd ai ci-li',
          'bahasa_arab' => 'فُلْفُلٌ صَغِيْرٌ',
          'fonetik_arab' => 'Fulfulun Shaghiirun',
          'bahasa_mandarin' => '小米辣',
          'fonetik_mandarin' => 'Xiǎomǐlà',
          'kategori' => 'Sayuran',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Bawang Bombay',
          'bahasa_inggris' => 'Onion',
          'fonetik' => 'a-ni-yen',
          'bahasa_arab' => 'بَصَلٌ كَبِيْرٌ',
          'fonetik_arab' => 'Baṣalun Kabiirun',
          'bahasa_mandarin' => '圆葱',
          'fonetik_mandarin' => 'Yuáncōng',
          'kategori' => 'Sayuran',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Bawang Prei',
          'bahasa_inggris' => 'Leek',
          'fonetik' => 'lik',
          'bahasa_arab' => 'كُرَّاثٌ',
          'fonetik_arab' => 'Kurrāthun',
          'bahasa_mandarin' => '韭葱',
          'fonetik_mandarin' => 'Jiǔcōng',
          'kategori' => 'Sayuran',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Kucai',
          'bahasa_inggris' => 'Chives',
          'fonetik' => 'caivz',
          'bahasa_arab' => 'ثُومٌ مُعَمَّرٌ',
          'fonetik_arab' => 'Thūmun Muʿammarun',
          'bahasa_mandarin' => '韭菜',
          'fonetik_mandarin' => 'Jiǔcài',
          'kategori' => 'Sayuran',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Daun Sop',
          'bahasa_inggris' => 'Parsley',
          'fonetik' => 'par-sli',
          'bahasa_arab' => 'بَقْدُوْنِسٌ',
          'fonetik_arab' => 'Baqdūnisun',
          'bahasa_mandarin' => '芹菜叶',
          'fonetik_mandarin' => 'Qíncài yè',
          'kategori' => 'Sayuran',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Kecipir',
          'bahasa_inggris' => 'Winged Bean',
          'fonetik' => 'wing-d bin',
          'bahasa_arab' => 'فَاصُوْلِيَا مُجَنَّحَةٌ',
          'fonetik_arab' => 'Fāṣūliyā Mujannaḥah',
          'bahasa_mandarin' => '四棱豆',
          'fonetik_mandarin' => 'Sìléngdòu',
          'kategori' => 'Sayuran',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Kacang Merah',
          'bahasa_inggris' => 'Red Kidney Bean',
          'fonetik' => 'red kid-ni bin',
          'bahasa_arab' => 'فَاصُوْلِيَا حَمْرَاءُ',
          'fonetik_arab' => 'Fāṣūliyā Ḥamrāʾu',
          'bahasa_mandarin' => '红豆',
          'fonetik_mandarin' => 'Hóngdòu',
          'kategori' => 'Sayuran',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Kacang Tanah',
          'bahasa_inggris' => 'Peanut',
          'fonetik' => 'pi-nat',
          'bahasa_arab' => 'فُوْلٌ سُوْدَانِيٌّ',
          'fonetik_arab' => 'Fūlun Sūdāniyyun',
          'bahasa_mandarin' => '花生',
          'fonetik_mandarin' => 'Huāshēng',
          'kategori' => 'Sayuran',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Jagung Muda',
          'bahasa_inggris' => 'Baby Corn',
          'fonetik' => 'bey-bi korn',
          'bahasa_arab' => 'ذُرَةٌ صَغِيْرَةٌ',
          'fonetik_arab' => 'Dhuratun Shaghiirah',
          'bahasa_mandarin' => '玉米笋',
          'fonetik_mandarin' => 'Yùmǐsǔn',
          'kategori' => 'Sayuran',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Kentang Manis',
          'bahasa_inggris' => 'Sweet Potato',
          'fonetik' => 'swit po-tey-to',
          'bahasa_arab' => 'بَطَاطَا حُلْوَةٌ',
          'fonetik_arab' => 'Baṭāṭā Ḥulwah',
          'bahasa_mandarin' => '山芋',
          'fonetik_mandarin' => 'Shānyù',
          'kategori' => 'Sayuran',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Talas',
          'bahasa_inggris' => 'Taro',
          'fonetik' => 'ta-ro',
          'bahasa_arab' => 'قُلْقَاسٌ',
          'fonetik_arab' => 'Qulqāsun',
          'bahasa_mandarin' => '芋头',
          'fonetik_mandarin' => 'Yùtou',
          'kategori' => 'Sayuran',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Sawi Putih',
          'bahasa_inggris' => 'Napa Cabbage',
          'fonetik' => 'na-pa ka-beij',
          'bahasa_arab' => 'كُرُنْبٌ صِيْنِيٌّ',
          'fonetik_arab' => 'Kurunbun Ṣīniyyun',
          'bahasa_mandarin' => '大白菜',
          'fonetik_mandarin' => 'Dàbáicài',
          'kategori' => 'Sayuran',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Sawi Hijau',
          'bahasa_inggris' => 'Choy Sum',
          'fonetik' => 'coy sam',
          'bahasa_arab' => 'خَرْدَلٌ أَخْضَرُ',
          'fonetik_arab' => 'Khardalun Akhḍaru',
          'bahasa_mandarin' => '菜心',
          'fonetik_mandarin' => 'Càixīn',
          'kategori' => 'Sayuran',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Terong Belanda',
          'bahasa_inggris' => 'Tamarillo',
          'fonetik' => 'ta-ma-ri-yo',
          'bahasa_arab' => 'تَامَارِيْلُو',
          'fonetik_arab' => 'Tāmārīlū',
          'bahasa_mandarin' => '树番茄',
          'fonetik_mandarin' => 'Shùfānqié',
          'kategori' => 'Sayuran',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Kacang Kapri',
          'bahasa_inggris' => 'Snow Peas',
          'fonetik' => 'snou piz',
          'bahasa_arab' => 'بَازِلَّاءُ الثَّلْجِ',
          'fonetik_arab' => 'Bāzillāʾuts Tsalji',
          'bahasa_mandarin' => '荷兰豆',
          'fonetik_mandarin' => 'Hélándòu',
          'kategori' => 'Sayuran',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Daun Kelor',
          'bahasa_inggris' => 'Moringa Leaf',
          'fonetik' => 'mo-ring-ga lif',
          'bahasa_arab' => 'وَرَقُ الْمُوْرِينِجَا',
          'fonetik_arab' => 'Waraqul Mūrīnijā',
          'bahasa_mandarin' => '辣木叶',
          'fonetik_mandarin' => 'Làmùyè',
          'kategori' => 'Sayuran',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Daun Salam',
          'bahasa_inggris' => 'Bay Leaf',
          'fonetik' => 'bey lif',
          'bahasa_arab' => 'وَرَقُ الْغَارِ',
          'fonetik_arab' => 'Waraqul Ghāri',
          'bahasa_mandarin' => '月桂叶',
          'fonetik_mandarin' => 'Yuèguìyè',
          'kategori' => 'Sayuran',
          'hari' => 13,
        ),
    );
  }
}