<?php

namespace Database\Seeders\Support\Game\Blueprints;

class Warna
{
  public static function defaultWords(): array
  {
    return array(
      0 =>
        array(
          'bahasa_indonesia' => 'Merah',
          'bahasa_inggris' => 'Red',
          'fonetik' => 'red',
          'bahasa_arab' => 'أَحْمَرُ',
          'fonetik_arab' => 'Aḥmaru',
          'bahasa_mandarin' => '红色',
          'fonetik_mandarin' => 'Hóngsè',
          'kategori' => 'Warna',
          'hari' => 1,
        ),
      1 =>
        array(
          'bahasa_indonesia' => 'Biru',
          'bahasa_inggris' => 'Blue',
          'fonetik' => 'blu',
          'bahasa_arab' => 'أَزْرَقُ',
          'fonetik_arab' => 'Azraqu',
          'bahasa_mandarin' => '蓝色',
          'fonetik_mandarin' => 'Lánsè',
          'kategori' => 'Warna',
          'hari' => 1,
        ),
      2 =>
        array(
          'bahasa_indonesia' => 'Kuning',
          'bahasa_inggris' => 'Yellow',
          'fonetik' => 'ye-lo',
          'bahasa_arab' => 'أَصْفَرُ',
          'fonetik_arab' => 'Aṣfaru',
          'bahasa_mandarin' => '黄色',
          'fonetik_mandarin' => 'Huángsè',
          'kategori' => 'Warna',
          'hari' => 1,
        ),
      3 =>
        array(
          'bahasa_indonesia' => 'Hijau',
          'bahasa_inggris' => 'Green',
          'fonetik' => 'grin',
          'bahasa_arab' => 'أَخْضَرُ',
          'fonetik_arab' => 'Akhḍaru',
          'bahasa_mandarin' => '绿色',
          'fonetik_mandarin' => 'Lǜsè',
          'kategori' => 'Warna',
          'hari' => 1,
        ),
      4 =>
        array(
          'bahasa_indonesia' => 'Hitam',
          'bahasa_inggris' => 'Black',
          'fonetik' => 'blek',
          'bahasa_arab' => 'أَسْوَدُ',
          'fonetik_arab' => 'Aswadu',
          'bahasa_mandarin' => '黑色',
          'fonetik_mandarin' => 'Hēisè',
          'kategori' => 'Warna',
          'hari' => 1,
        ),
      5 =>
        array(
          'bahasa_indonesia' => 'Putih',
          'bahasa_inggris' => 'White',
          'fonetik' => 'wait',
          'bahasa_arab' => 'أَبْيَضُ',
          'fonetik_arab' => 'Abyaḍu',
          'bahasa_mandarin' => '白色',
          'fonetik_mandarin' => 'Báisè',
          'kategori' => 'Warna',
          'hari' => 1,
        ),
      6 =>
        array(
          'bahasa_indonesia' => 'Oranye',
          'bahasa_inggris' => 'Orange',
          'fonetik' => 'o-renj',
          'bahasa_arab' => 'بُرْتُقَالِيٌّ',
          'fonetik_arab' => 'Burtuqālīyun',
          'bahasa_mandarin' => '橙色',
          'fonetik_mandarin' => 'Chéngsè',
          'kategori' => 'Warna',
          'hari' => 2,
        ),
      7 =>
        array(
          'bahasa_indonesia' => 'Ungu',
          'bahasa_inggris' => 'Purple',
          'fonetik' => 'per-pel',
          'bahasa_arab' => 'بَنَفْسَجِيٌّ',
          'fonetik_arab' => 'Banafsaǧīyun',
          'bahasa_mandarin' => '紫色',
          'fonetik_mandarin' => 'Zǐsè',
          'kategori' => 'Warna',
          'hari' => 2,
        ),
      8 =>
        array(
          'bahasa_indonesia' => 'Merah Muda',
          'bahasa_inggris' => 'Pink',
          'fonetik' => 'pingk',
          'bahasa_arab' => 'وَرْدِيٌّ',
          'fonetik_arab' => 'Wardīyun',
          'bahasa_mandarin' => '粉色',
          'fonetik_mandarin' => 'Fěnsè',
          'kategori' => 'Warna',
          'hari' => 2,
        ),
      9 =>
        array(
          'bahasa_indonesia' => 'Cokelat',
          'bahasa_inggris' => 'Brown',
          'fonetik' => 'braun',
          'bahasa_arab' => 'بُنِّيٌّ',
          'fonetik_arab' => 'Bunnīyun',
          'bahasa_mandarin' => '棕色',
          'fonetik_mandarin' => 'Zōngsè',
          'kategori' => 'Warna',
          'hari' => 2,
        ),
      10 =>
        array(
          'bahasa_indonesia' => 'Abu-abu',
          'bahasa_inggris' => 'Gray',
          'fonetik' => 'grey',
          'bahasa_arab' => 'رَمَادِيٌّ',
          'fonetik_arab' => 'Ramādīyun',
          'bahasa_mandarin' => '灰色',
          'fonetik_mandarin' => 'Huīsè',
          'kategori' => 'Warna',
          'hari' => 2,
        ),
      11 =>
        array(
          'bahasa_indonesia' => 'Emas',
          'bahasa_inggris' => 'Gold',
          'fonetik' => 'gould',
          'bahasa_arab' => 'ذَهَبِيٌّ',
          'fonetik_arab' => 'Dhahabīyun',
          'bahasa_mandarin' => '金色',
          'fonetik_mandarin' => 'Jīnsè',
          'kategori' => 'Warna',
          'hari' => 2,
        ),
      12 =>
        array(
          'bahasa_indonesia' => 'Perak',
          'bahasa_inggris' => 'Silver',
          'fonetik' => 'sil-ver',
          'bahasa_arab' => 'فِضِّيٌّ',
          'fonetik_arab' => 'Fiḍḍīyun',
          'bahasa_mandarin' => '银色',
          'fonetik_mandarin' => 'Yínsè',
          'kategori' => 'Warna',
          'hari' => 3,
        ),
      13 =>
        array(
          'bahasa_indonesia' => 'Beige',
          'bahasa_inggris' => 'Beige',
          'fonetik' => 'beizh',
          'bahasa_arab' => 'بَيْجٌ',
          'fonetik_arab' => 'Bayjún',
          'bahasa_mandarin' => '米色',
          'fonetik_mandarin' => 'Mǐsè',
          'kategori' => 'Warna',
          'hari' => 3,
        ),
      14 =>
        array(
          'bahasa_indonesia' => 'Biru Laut',
          'bahasa_inggris' => 'Navy',
          'fonetik' => 'nei-vi',
          'bahasa_arab' => 'كُحْلِيٌّ',
          'fonetik_arab' => 'Kuḥlīyun',
          'bahasa_mandarin' => '海军蓝',
          'fonetik_mandarin' => 'Hǎijūnlán',
          'kategori' => 'Warna',
          'hari' => 3,
        ),
      15 =>
        array(
          'bahasa_indonesia' => 'Pirus',
          'bahasa_inggris' => 'Turquoise',
          'fonetik' => 'ter-kois',
          'bahasa_arab' => 'فَيْرُوْزِيٌّ',
          'fonetik_arab' => 'Fayrūzīyun',
          'bahasa_mandarin' => '绿松石色',
          'fonetik_mandarin' => 'Lǜsōngshísè',
          'kategori' => 'Warna',
          'hari' => 3,
        ),
      16 =>
        array(
          'bahasa_indonesia' => 'Nila',
          'bahasa_inggris' => 'Indigo',
          'fonetik' => 'in-di-go',
          'bahasa_arab' => 'نِيْلِيٌّ',
          'fonetik_arab' => 'Nīlīyun',
          'bahasa_mandarin' => '靛蓝色',
          'fonetik_mandarin' => 'Diànlánsè',
          'kategori' => 'Warna',
          'hari' => 3,
        ),
      17 =>
        array(
          'bahasa_indonesia' => 'Merah Marun',
          'bahasa_inggris' => 'Maroon',
          'fonetik' => 'ma-run',
          'bahasa_arab' => 'بُنِّيٌّ مَائِلٌ لِلْحُمْرَةِ',
          'fonetik_arab' => 'Bunnī mī’il lil-ḥumrah',
          'bahasa_mandarin' => '栗色',
          'fonetik_mandarin' => 'Lìsè',
          'kategori' => 'Warna',
          'hari' => 3,
        ),
      18 =>
        array(
          'bahasa_indonesia' => 'Putih Susu',
          'bahasa_inggris' => 'Cream',
          'fonetik' => 'krim',
          'bahasa_arab' => 'كَرِيْمِيٌّ',
          'fonetik_arab' => 'Karīmīyun',
          'bahasa_mandarin' => '乳白色',
          'fonetik_mandarin' => 'Rǔbáisè',
          'kategori' => 'Warna',
          'hari' => 4,
        ),
      19 =>
        array(
          'bahasa_indonesia' => 'Biru Muda',
          'bahasa_inggris' => 'Light Blue',
          'fonetik' => 'lait blu',
          'bahasa_arab' => 'أَزْرَقُ فَاتِحٌ',
          'fonetik_arab' => 'Azraqu Fātiḥun',
          'bahasa_mandarin' => '浅蓝色',
          'fonetik_mandarin' => 'Qiǎnlánsè',
          'kategori' => 'Warna',
          'hari' => 4,
        ),
      20 =>
        array(
          'bahasa_indonesia' => 'Hijau Muda',
          'bahasa_inggris' => 'Light Green',
          'fonetik' => 'lait grin',
          'bahasa_arab' => 'أَخْضَرُ فَاتِحٌ',
          'fonetik_arab' => 'Akhḍaru Fātiḥun',
          'bahasa_mandarin' => '浅绿色',
          'fonetik_mandarin' => 'Qiǎnlǜsè',
          'kategori' => 'Warna',
          'hari' => 4,
        ),
      21 =>
        array(
          'bahasa_indonesia' => 'Kuning Muda',
          'bahasa_inggris' => 'Light Yellow',
          'fonetik' => 'lait ye-lo',
          'bahasa_arab' => 'أَصْفَرُ فَاتِحٌ',
          'fonetik_arab' => 'Aṣfaru Fātiḥun',
          'bahasa_mandarin' => '浅黄色',
          'fonetik_mandarin' => 'Qiǎnhuángsè',
          'kategori' => 'Warna',
          'hari' => 4,
        ),
      22 =>
        array(
          'bahasa_indonesia' => 'Merah Muda Pucat',
          'bahasa_inggris' => 'Pale Pink',
          'fonetik' => 'peyl pingk',
          'bahasa_arab' => 'وَرْدِيٌّ بَاهِتٌ',
          'fonetik_arab' => 'Wardīyun Bāhitun',
          'bahasa_mandarin' => '淡粉色',
          'fonetik_mandarin' => 'Dànfěnsè',
          'kategori' => 'Warna',
          'hari' => 4,
        ),
      23 =>
        array(
          'bahasa_indonesia' => 'Abu-abu Muda',
          'bahasa_inggris' => 'Light Gray',
          'fonetik' => 'lait grey',
          'bahasa_arab' => 'رَمَادِيٌّ فَاتِحٌ',
          'fonetik_arab' => 'Ramādīyun Fātiḥun',
          'bahasa_mandarin' => '浅灰色',
          'fonetik_mandarin' => 'Qiǎnhuīsè',
          'kategori' => 'Warna',
          'hari' => 4,
        ),
      24 =>
        array(
          'bahasa_indonesia' => 'Biru Tua',
          'bahasa_inggris' => 'Dark Blue',
          'fonetik' => 'dark blu',
          'bahasa_arab' => 'أَزْرَقُ غَامِقٌ',
          'fonetik_arab' => 'Azraqu Ghāmiqun',
          'bahasa_mandarin' => '深蓝色',
          'fonetik_mandarin' => 'Shēnlánsè',
          'kategori' => 'Warna',
          'hari' => 5,
        ),
      25 =>
        array(
          'bahasa_indonesia' => 'Hijau Tua',
          'bahasa_inggris' => 'Dark Green',
          'fonetik' => 'dark grin',
          'bahasa_arab' => 'أَخْضَرُ غَامِقٌ',
          'fonetik_arab' => 'Akhḍaru Ghāmiqun',
          'bahasa_mandarin' => '深绿色',
          'fonetik_mandarin' => 'Shēnlǜsè',
          'kategori' => 'Warna',
          'hari' => 5,
        ),
      26 =>
        array(
          'bahasa_indonesia' => 'Merah Tua',
          'bahasa_inggris' => 'Dark Red',
          'fonetik' => 'dark red',
          'bahasa_arab' => 'أَحْمَرُ غَامِقٌ',
          'fonetik_arab' => 'Aḥmaru Ghāmiqun',
          'bahasa_mandarin' => '深红色',
          'fonetik_mandarin' => 'Shēnhóngsè',
          'kategori' => 'Warna',
          'hari' => 5,
        ),
      27 =>
        array(
          'bahasa_indonesia' => 'Kuning Tua',
          'bahasa_inggris' => 'Dark Yellow',
          'fonetik' => 'dark ye-lo',
          'bahasa_arab' => 'أَصْفَرُ غَامِقٌ',
          'fonetik_arab' => 'Aṣfaru Ghāmiqun',
          'bahasa_mandarin' => '深黄色',
          'fonetik_mandarin' => 'Shēnhuángsè',
          'kategori' => 'Warna',
          'hari' => 5,
        ),
      28 =>
        array(
          'bahasa_indonesia' => 'Cokelat Tua',
          'bahasa_inggris' => 'Dark Brown',
          'fonetik' => 'dark braun',
          'bahasa_arab' => 'بُنِّيٌّ غَامِقٌ',
          'fonetik_arab' => 'Bunnīyun Ghāmiqun',
          'bahasa_mandarin' => '深棕色',
          'fonetik_mandarin' => 'Shēnzōngsè',
          'kategori' => 'Warna',
          'hari' => 5,
        ),
      29 =>
        array(
          'bahasa_indonesia' => 'Abu-abu Tua',
          'bahasa_inggris' => 'Dark Gray',
          'fonetik' => 'dark grey',
          'bahasa_arab' => 'رَمَادِيٌّ غَامِقٌ',
          'fonetik_arab' => 'Ramādīyun Ghāmiqun',
          'bahasa_mandarin' => '深灰色',
          'fonetik_mandarin' => 'Shēnhuīsè',
          'kategori' => 'Warna',
          'hari' => 5,
        ),
      30 =>
        array(
          'bahasa_indonesia' => 'Hijau Zaitun',
          'bahasa_inggris' => 'Olive',
          'fonetik' => 'o-liv',
          'bahasa_arab' => 'زَيْتُوْنِيٌّ',
          'fonetik_arab' => 'Zaytūnīyun',
          'bahasa_mandarin' => '橄榄绿',
          'fonetik_mandarin' => 'Gǎnlǎnlǜ',
          'kategori' => 'Warna',
          'hari' => 6,
        ),
      31 =>
        array(
          'bahasa_indonesia' => 'Oranye Jingga',
          'bahasa_inggris' => 'Tangerine',
          'fonetik' => 'ten-je-rin',
          'bahasa_arab' => 'يُوسُفِيٌّ',
          'fonetik_arab' => 'Yūsufiyyun',
          'bahasa_mandarin' => '橘红色',
          'fonetik_mandarin' => 'Júhóngsè',
          'kategori' => 'Warna',
          'hari' => 6,
        ),
      32 =>
        array(
          'bahasa_indonesia' => 'Merah Tomat',
          'bahasa_inggris' => 'Tomato Red',
          'fonetik' => 'to-mey-to red',
          'bahasa_arab' => 'أَحْمَرُ طَمَاطِمِيٌّ',
          'fonetik_arab' => 'Aḥmaru Ṭamāṭimiyyun',
          'bahasa_mandarin' => '番茄红',
          'fonetik_mandarin' => 'Fānqiéhóng',
          'kategori' => 'Warna',
          'hari' => 6,
        ),
      33 =>
        array(
          'bahasa_indonesia' => 'Ungu Terong',
          'bahasa_inggris' => 'Eggplant Purple',
          'fonetik' => 'eg-plent per-pel',
          'bahasa_arab' => 'بَنَفْسَجِيٌّ بَاذِنْجَانِيٌّ',
          'fonetik_arab' => 'Banafsaǧīyun Bādhinjāniyyun',
          'bahasa_mandarin' => '茄紫色',
          'fonetik_mandarin' => 'Qiézǐsè',
          'kategori' => 'Warna',
          'hari' => 6,
        ),
      34 =>
        array(
          'bahasa_indonesia' => 'Kuning Lemon',
          'bahasa_inggris' => 'Lemon Yellow',
          'fonetik' => 'le-mon ye-lo',
          'bahasa_arab' => 'أَصْفَرُ لَيْمُوْنِيٌّ',
          'fonetik_arab' => 'Aṣfaru Laymūnīyun',
          'bahasa_mandarin' => '柠檬黄',
          'fonetik_mandarin' => 'Níngménghuáng',
          'kategori' => 'Warna',
          'hari' => 6,
        ),
      35 =>
        array(
          'bahasa_indonesia' => 'Hijau Daun',
          'bahasa_inggris' => 'Leaf Green',
          'fonetik' => 'lif grin',
          'bahasa_arab' => 'أَخْضَرُ وَرَقِيٌّ',
          'fonetik_arab' => 'Akhḍaru Waraqiyyun',
          'bahasa_mandarin' => '叶绿色',
          'fonetik_mandarin' => 'Yèlǜsè',
          'kategori' => 'Warna',
          'hari' => 6,
        ),
      36 =>
        array(
          'bahasa_indonesia' => 'Hijau Zamrud',
          'bahasa_inggris' => 'Emerald',
          'fonetik' => 'e-me-rald',
          'bahasa_arab' => 'زُمُرُّدِيٌّ',
          'fonetik_arab' => 'Zumurrudiyyun',
          'bahasa_mandarin' => '祖母绿',
          'fonetik_mandarin' => 'Zǔmǔlǜ',
          'kategori' => 'Warna',
          'hari' => 7,
        ),
      37 =>
        array(
          'bahasa_indonesia' => 'Biru Safir',
          'bahasa_inggris' => 'Sapphire',
          'fonetik' => 'se-fa-yer',
          'bahasa_arab' => 'يَاقُوْتِيٌّ أَزْرَقُ',
          'fonetik_arab' => 'Yāqūtiyyun Azraqu',
          'bahasa_mandarin' => '蓝宝石色',
          'fonetik_mandarin' => 'Lánbǎoshísè',
          'kategori' => 'Warna',
          'hari' => 7,
        ),
      38 =>
        array(
          'bahasa_indonesia' => 'Merah Delima',
          'bahasa_inggris' => 'Ruby',
          'fonetik' => 'ru-bi',
          'bahasa_arab' => 'يَاقُوْتِيٌّ أَحْمَرُ',
          'fonetik_arab' => 'Yāqūtiyyun Aḥmaru',
          'bahasa_mandarin' => '红宝石色',
          'fonetik_mandarin' => 'Hóngbǎoshísè',
          'kategori' => 'Warna',
          'hari' => 7,
        ),
      39 =>
        array(
          'bahasa_indonesia' => 'Tembaga',
          'bahasa_inggris' => 'Copper',
          'fonetik' => 'ko-per',
          'bahasa_arab' => 'نُحَاسِيٌّ',
          'fonetik_arab' => 'Nuḥāsiyyun',
          'bahasa_mandarin' => '铜色',
          'fonetik_mandarin' => 'Tóngsè',
          'kategori' => 'Warna',
          'hari' => 7,
        ),
      40 =>
        array(
          'bahasa_indonesia' => 'Perunggu',
          'bahasa_inggris' => 'Bronze',
          'fonetik' => 'bronz',
          'bahasa_arab' => 'بُرُوْنْزِيٌّ',
          'fonetik_arab' => 'Burūnzīyun',
          'bahasa_mandarin' => '青铜色',
          'fonetik_mandarin' => 'Qīngtóngsè',
          'kategori' => 'Warna',
          'hari' => 7,
        ),
      41 =>
        array(
          'bahasa_indonesia' => 'Berlian',
          'bahasa_inggris' => 'Diamond',
          'fonetik' => 'da-ye-mond',
          'bahasa_arab' => 'أَلْمَاسِيٌّ',
          'fonetik_arab' => 'Almāsiyyun',
          'bahasa_mandarin' => '钻石色',
          'fonetik_mandarin' => 'Zuànshísè',
          'kategori' => 'Warna',
          'hari' => 7,
        ),
      42 =>
        array(
          'bahasa_indonesia' => 'Merah Mawar',
          'bahasa_inggris' => 'Rose',
          'fonetik' => 'rouz',
          'bahasa_arab' => 'وَرْدِيٌّ',
          'fonetik_arab' => 'Wardiyyun',
          'bahasa_mandarin' => '玫瑰红',
          'fonetik_mandarin' => 'Méiguīhóng',
          'kategori' => 'Warna',
          'hari' => 8,
        ),
      43 =>
        array(
          'bahasa_indonesia' => 'Ungu Lavender',
          'bahasa_inggris' => 'Lavender',
          'fonetik' => 'le-ven-der',
          'bahasa_arab' => 'خُزَامِيٌّ',
          'fonetik_arab' => 'Khuzāmiyyun',
          'bahasa_mandarin' => '薰衣草色',
          'fonetik_mandarin' => 'Xūnyīcǎosè',
          'kategori' => 'Warna',
          'hari' => 8,
        ),
      44 =>
        array(
          'bahasa_indonesia' => 'Kuning Matahari',
          'bahasa_inggris' => 'Sunlight Yellow',
          'fonetik' => 'san-lait ye-lo',
          'bahasa_arab' => 'أَصْفَرُ شَمْسِيٌّ',
          'fonetik_arab' => 'Aṣfaru Syamsiyyun',
          'bahasa_mandarin' => '阳光黄',
          'fonetik_mandarin' => 'Yángguānghuáng',
          'kategori' => 'Warna',
          'hari' => 8,
        ),
      45 =>
        array(
          'bahasa_indonesia' => 'Hijau Mint',
          'bahasa_inggris' => 'Mint Green',
          'fonetik' => 'mint grin',
          'bahasa_arab' => 'أَخْضَرُ نَعْنَاعِيٌّ',
          'fonetik_arab' => 'Akhḍaru Naʿnāʿiyyun',
          'bahasa_mandarin' => '薄荷绿',
          'fonetik_mandarin' => 'Bòhélǜ',
          'kategori' => 'Warna',
          'hari' => 8,
        ),
      46 =>
        array(
          'bahasa_indonesia' => 'Merah Ceri',
          'bahasa_inggris' => 'Cherry Red',
          'fonetik' => 'ce-ri red',
          'bahasa_arab' => 'أَحْمَرُ كَرَزِيٌّ',
          'fonetik_arab' => 'Aḥmaru Karaziyyun',
          'bahasa_mandarin' => '樱桃红',
          'fonetik_mandarin' => 'Yīngtáohóng',
          'kategori' => 'Warna',
          'hari' => 8,
        ),
      47 =>
        array(
          'bahasa_indonesia' => 'Putih Melati',
          'bahasa_inggris' => 'Jasmine White',
          'fonetik' => 'jas-min wait',
          'bahasa_arab' => 'أَبْيَضُ اليَاسَمِيْنِ',
          'fonetik_arab' => 'Abyaḍul Yāsamīni',
          'bahasa_mandarin' => '茉莉白',
          'fonetik_mandarin' => 'Mòlìbái',
          'kategori' => 'Warna',
          'hari' => 8,
        ),
      48 =>
        array(
          'bahasa_indonesia' => 'Magenta',
          'bahasa_inggris' => 'Magenta',
          'fonetik' => 'ma-jen-ta',
          'bahasa_arab' => 'أُرْجُوَانِيٌّ',
          'fonetik_arab' => 'Urjuwāniyyun',
          'bahasa_mandarin' => '洋红色',
          'fonetik_mandarin' => 'Yánghóngsè',
          'kategori' => 'Warna',
          'hari' => 9,
        ),
      49 =>
        array(
          'bahasa_indonesia' => 'Sian',
          'bahasa_inggris' => 'Cyan',
          'fonetik' => 'sai-yen',
          'bahasa_arab' => 'سَمَاوِيٌّ',
          'fonetik_arab' => 'Samāwiyyun',
          'bahasa_mandarin' => '青色',
          'fonetik_mandarin' => 'Qīngsè',
          'kategori' => 'Warna',
          'hari' => 9,
        ),
      50 =>
        array(
          'bahasa_indonesia' => 'Teal',
          'bahasa_inggris' => 'Teal',
          'fonetik' => 'til',
          'bahasa_arab' => 'أَخْضَرُ زُرْقُمِيٌّ',
          'fonetik_arab' => 'Akhḍaru Zurqumiyyun',
          'bahasa_mandarin' => '蓝绿色',
          'fonetik_mandarin' => 'Lánlǜsè',
          'kategori' => 'Warna',
          'hari' => 9,
        ),
      51 =>
        array(
          'bahasa_indonesia' => 'Khaki',
          'bahasa_inggris' => 'Khaki',
          'fonetik' => 'ka-ki',
          'bahasa_arab' => 'خَاكِيٌّ',
          'fonetik_arab' => 'Khākiyyun',
          'bahasa_mandarin' => '卡其色',
          'fonetik_mandarin' => 'Kǎqísè',
          'kategori' => 'Warna',
          'hari' => 9,
        ),
      52 =>
        array(
          'bahasa_indonesia' => 'Peach',
          'bahasa_inggris' => 'Peach',
          'fonetik' => 'pic',
          'bahasa_arab' => 'خَوْخِيٌّ',
          'fonetik_arab' => 'Khawkhiyyun',
          'bahasa_mandarin' => '桃色',
          'fonetik_mandarin' => 'Táosè',
          'kategori' => 'Warna',
          'hari' => 9,
        ),
      53 =>
        array(
          'bahasa_indonesia' => 'Apricot',
          'bahasa_inggris' => 'Apricot',
          'fonetik' => 'ap-ri-kot',
          'bahasa_arab' => 'مِشْمِشِيٌّ',
          'fonetik_arab' => 'Mishmishiyyun',
          'bahasa_mandarin' => '杏色',
          'fonetik_mandarin' => 'Xìngsè',
          'kategori' => 'Warna',
          'hari' => 9,
        ),
      54 =>
        array(
          'bahasa_indonesia' => 'Cokelat Tanah',
          'bahasa_inggris' => 'Earthy Brown',
          'fonetik' => 'er-thi braun',
          'bahasa_arab' => 'بُنِّيٌّ تُرَابِيٌّ',
          'fonetik_arab' => 'Bunnīyun Turābiyyun',
          'bahasa_mandarin' => '大地色',
          'fonetik_mandarin' => 'Dàdìsè',
          'kategori' => 'Warna',
          'hari' => 10,
        ),
      55 =>
        array(
          'bahasa_indonesia' => 'Hijau Lumut',
          'bahasa_inggris' => 'Moss Green',
          'fonetik' => 'mos grin',
          'bahasa_arab' => 'أَخْضَرُ طُحْلُبِيٌّ',
          'fonetik_arab' => 'Akhḍaru Ṭuḥlubiyyun',
          'bahasa_mandarin' => '苔藓绿',
          'fonetik_mandarin' => 'Táoxiǎnlǜ',
          'kategori' => 'Warna',
          'hari' => 10,
        ),
      56 =>
        array(
          'bahasa_indonesia' => 'Biru Langit',
          'bahasa_inggris' => 'Sky Blue',
          'fonetik' => 'skai blu',
          'bahasa_arab' => 'أَزْرَقُ سَمَاوِيٌّ',
          'fonetik_arab' => 'Azraqu Samāwiyyun',
          'bahasa_mandarin' => '天蓝色',
          'fonetik_mandarin' => 'Tiānlánsè',
          'kategori' => 'Warna',
          'hari' => 10,
        ),
      57 =>
        array(
          'bahasa_indonesia' => 'Cokelat Kayu',
          'bahasa_inggris' => 'Wood Brown',
          'fonetik' => 'wud braun',
          'bahasa_arab' => 'بُنِّيٌّ خَشَبِيٌّ',
          'fonetik_arab' => 'Bunnīyun Khashabiyyun',
          'bahasa_mandarin' => '木色',
          'fonetik_mandarin' => 'Mùsè',
          'kategori' => 'Warna',
          'hari' => 10,
        ),
      58 =>
        array(
          'bahasa_indonesia' => 'Merah Bata',
          'bahasa_inggris' => 'Brick Red',
          'fonetik' => 'brik red',
          'bahasa_arab' => 'أَحْمَرُ مِثْلَ الْقِرْمِيْدِ',
          'fonetik_arab' => 'Aḥmaru mithlal Qirmīdi',
          'bahasa_mandarin' => '砖红色',
          'fonetik_mandarin' => 'Zhuānhóngsè',
          'kategori' => 'Warna',
          'hari' => 10,
        ),
      59 =>
        array(
          'bahasa_indonesia' => 'Pasir',
          'bahasa_inggris' => 'Sand',
          'fonetik' => 'send',
          'bahasa_arab' => 'رَمْلِيٌّ',
          'fonetik_arab' => 'Ramliyyun',
          'bahasa_mandarin' => '沙色',
          'fonetik_mandarin' => 'Shāsè',
          'kategori' => 'Warna',
          'hari' => 10,
        ),
      60 =>
        array(
          'bahasa_indonesia' => 'Kuning Neon',
          'bahasa_inggris' => 'Neon Yellow',
          'fonetik' => 'ni-on ye-lo',
          'bahasa_arab' => 'أَصْفَرُ نِيُوْن',
          'fonetik_arab' => 'Aṣfarun Niyūn',
          'bahasa_mandarin' => '霓虹黄',
          'fonetik_mandarin' => 'Níhónghuáng',
          'kategori' => 'Warna',
          'hari' => 11,
        ),
      61 =>
        array(
          'bahasa_indonesia' => 'Hijau Neon',
          'bahasa_inggris' => 'Neon Green',
          'fonetik' => 'ni-on grin',
          'bahasa_arab' => 'أَخْضَرُ نِيُوْن',
          'fonetik_arab' => 'Akhḍarun Niyūn',
          'bahasa_mandarin' => '霓虹绿',
          'fonetik_mandarin' => 'Níhónglǜ',
          'kategori' => 'Warna',
          'hari' => 11,
        ),
      62 =>
        array(
          'bahasa_indonesia' => 'Merah Menyala',
          'bahasa_inggris' => 'Bright Red',
          'fonetik' => 'brait red',
          'bahasa_arab' => 'أَحْمَرُ زَاهٍ',
          'fonetik_arab' => 'Aḥmaru Zāhin',
          'bahasa_mandarin' => '鲜红色',
          'fonetik_mandarin' => 'Xiānhóngsè',
          'kategori' => 'Warna',
          'hari' => 11,
        ),
      63 =>
        array(
          'bahasa_indonesia' => 'Biru Cerah',
          'bahasa_inggris' => 'Bright Blue',
          'fonetik' => 'brait blu',
          'bahasa_arab' => 'أَزْرَقُ زَاهٍ',
          'fonetik_arab' => 'Azraqu Zāhin',
          'bahasa_mandarin' => '亮蓝色',
          'fonetik_mandarin' => 'Liànglánsè',
          'kategori' => 'Warna',
          'hari' => 11,
        ),
      64 =>
        array(
          'bahasa_indonesia' => 'Oranye Neon',
          'bahasa_inggris' => 'Neon Orange',
          'fonetik' => 'ni-on o-renj',
          'bahasa_arab' => 'بُرْتُقَالِيٌّ نِيُوْن',
          'fonetik_arab' => 'Burtuqālīyun Niyūn',
          'bahasa_mandarin' => '霓虹橙',
          'fonetik_mandarin' => 'Níhóngchéng',
          'kategori' => 'Warna',
          'hari' => 11,
        ),
      65 =>
        array(
          'bahasa_indonesia' => 'Ungu Cerah',
          'bahasa_inggris' => 'Bright Purple',
          'fonetik' => 'brait per-pel',
          'bahasa_arab' => 'بَنَفْسَجِيٌّ زَاهٍ',
          'fonetik_arab' => 'Banafsaǧīyun Zāhin',
          'bahasa_mandarin' => '亮紫色',
          'fonetik_mandarin' => 'Liàngzǐsè',
          'kategori' => 'Warna',
          'hari' => 11,
        ),
      66 =>
        array(
          'bahasa_indonesia' => 'Arang',
          'bahasa_inggris' => 'Charcoal',
          'fonetik' => 'car-koul',
          'bahasa_arab' => 'فَحْمِيٌّ',
          'fonetik_arab' => 'Faḥmiyyun',
          'bahasa_mandarin' => '炭灰色',
          'fonetik_mandarin' => 'Tànhuīsè',
          'kategori' => 'Warna',
          'hari' => 12,
        ),
      67 =>
        array(
          'bahasa_indonesia' => 'Gading',
          'bahasa_inggris' => 'Ivory',
          'fonetik' => 'ai-vo-ri',
          'bahasa_arab' => 'عَاجِيٌّ',
          'fonetik_arab' => 'ʿĀjiyyun',
          'bahasa_mandarin' => '象牙色',
          'fonetik_mandarin' => 'Xiàngyásè',
          'kategori' => 'Warna',
          'hari' => 12,
        ),
      68 =>
        array(
          'bahasa_indonesia' => 'Sepia',
          'bahasa_inggris' => 'Sepia',
          'fonetik' => 'se-pi-ya',
          'bahasa_arab' => 'سِيْبِيَا',
          'fonetik_arab' => 'Sībiyā',
          'bahasa_mandarin' => '乌贼墨色',
          'fonetik_mandarin' => 'Wūzéimòsè',
          'kategori' => 'Warna',
          'hari' => 12,
        ),
      69 =>
        array(
          'bahasa_indonesia' => 'Oker',
          'bahasa_inggris' => 'Ochre',
          'fonetik' => 'o-ker',
          'bahasa_arab' => 'مُغْرَةٌ',
          'fonetik_arab' => 'Mughratun',
          'bahasa_mandarin' => '赭石色',
          'fonetik_mandarin' => 'Zhěshísè',
          'kategori' => 'Warna',
          'hari' => 12,
        ),
      70 =>
        array(
          'bahasa_indonesia' => 'Kuning Gading',
          'bahasa_inggris' => 'Creamy Yellow',
          'fonetik' => 'kri-mi ye-lo',
          'bahasa_arab' => 'أَصْفَرُ عَاجِيٌّ',
          'fonetik_arab' => 'Aṣfaru ʿĀjiyyun',
          'bahasa_mandarin' => '奶黄色',
          'fonetik_mandarin' => 'Nǎihuángsè',
          'kategori' => 'Warna',
          'hari' => 12,
        ),
      71 =>
        array(
          'bahasa_indonesia' => 'Abu-abu Asap',
          'bahasa_inggris' => 'Smoky Gray',
          'fonetik' => 'smo-ki grey',
          'bahasa_arab' => 'رَمَادِيٌّ دُخَانِيٌّ',
          'fonetik_arab' => 'Ramādīyun Dukhāniyyun',
          'bahasa_mandarin' => '烟灰色',
          'fonetik_mandarin' => 'Yānhuīsè',
          'kategori' => 'Warna',
          'hari' => 12,
        ),
      72 =>
        array(
          'bahasa_indonesia' => 'Merah Hati',
          'bahasa_inggris' => 'Deep Red',
          'fonetik' => 'dip red',
          'bahasa_arab' => 'أَحْمَرُ قَانٍ',
          'fonetik_arab' => 'Aḥmaru Qānin',
          'bahasa_mandarin' => '枣红色',
          'fonetik_mandarin' => 'Zǎohóngsè',
          'kategori' => 'Warna',
          'hari' => 13,
        ),
      73 =>
        array(
          'bahasa_indonesia' => 'Kuning Kunyit',
          'bahasa_inggris' => 'Saffron',
          'fonetik' => 'se-fron',
          'bahasa_arab' => 'زَعْفَرَانِيٌّ',
          'fonetik_arab' => 'Zaʿfarāniyyun',
          'bahasa_mandarin' => '藏红色',
          'fonetik_mandarin' => 'Zànghóngsè',
          'kategori' => 'Warna',
          'hari' => 13,
        ),
      74 =>
        array(
          'bahasa_indonesia' => 'Biru Toska',
          'bahasa_inggris' => 'Teal Blue',
          'fonetik' => 'til blu',
          'bahasa_arab' => 'أَزْرَقُ تُرْكُوَازِيٌّ',
          'fonetik_arab' => 'Azraqu Turkūwāziyyun',
          'bahasa_mandarin' => '青粉色',
          'fonetik_mandarin' => 'Qīng fěnsè',
          'kategori' => 'Warna',
          'hari' => 13,
        ),
      75 =>
        array(
          'bahasa_indonesia' => 'Hitam Pekat',
          'bahasa_inggris' => 'Jet Black',
          'fonetik' => 'jet blek',
          'bahasa_arab' => 'أَسْوَدُ فَاحِمٌ',
          'fonetik_arab' => 'Aswadu Fāḥimun',
          'bahasa_mandarin' => '漆黑色',
          'fonetik_mandarin' => 'Qī hēisè',
          'kategori' => 'Warna',
          'hari' => 13,
        ),
      76 =>
        array(
          'bahasa_indonesia' => 'Putih Bersih',
          'bahasa_inggris' => 'Pure White',
          'fonetik' => 'pyur wait',
          'bahasa_arab' => 'أَبْيَضُ نَاصِعٌ',
          'fonetik_arab' => 'Abyaḍu Nāṣiʿun',
          'bahasa_mandarin' => '纯白色',
          'fonetik_mandarin' => 'Chúnbáisè',
          'kategori' => 'Warna',
          'hari' => 13,
        ),
      77 =>
        array(
          'bahasa_indonesia' => 'Warna-warni',
          'bahasa_inggris' => 'Colorful',
          'fonetik' => 'ka-ler-ful',
          'bahasa_arab' => 'مُلَوَّنٌ',
          'fonetik_arab' => 'Mulawwanun',
          'bahasa_mandarin' => '彩色',
          'fonetik_mandarin' => 'Cǎisè',
          'kategori' => 'Warna',
          'hari' => 13,
        ),
    );
  }
}